//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@interface Observation.ObservationRegistrar.Extent__priv_5AE0855755CD62D4521FC18D42BC1E4B
{
    id context;
}

@end

