//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

// Global C++ functions

AIDInterface::metaClass;
AppleDeviceManagementHIDEventService::gMetaClass;
AppleDeviceManagementHIDEventService::metaClass;
AppleDeviceManagementHIDEventService::operator delete(void*, unsigned long);
AppleDeviceManagementHIDEventService::operator new(unsigned long);
AppleDeviceManagementHIDEventService::superClass;
AppleDeviceManagementHIDEventService_ktv;
AppleMultitouchHIDEventDriverV2::gMetaClass;
AppleMultitouchInputHIDEventDriver::gMetaClass;
AppleMultitouchInputHIDEventDriver::metaClass;
AppleMultitouchInputHIDEventDriver::operator delete(void*, unsigned long);
AppleMultitouchInputHIDEventDriver::operator new(unsigned long);
AppleMultitouchInputHIDEventDriver::superClass;
AppleMultitouchInputHIDEventDriver_ktv;
AppleMultitouchMouseHIDEventDriver::gMetaClass;
AppleMultitouchMouseHIDEventDriver::metaClass;
AppleMultitouchMouseHIDEventDriver::operator delete(void*, unsigned long);
AppleMultitouchMouseHIDEventDriver::operator new(unsigned long);
AppleMultitouchMouseHIDEventDriver::superClass;
AppleMultitouchMouseHIDEventDriver_ktv;
AppleMultitouchTrackpadHIDEventDriver::gMetaClass;
AppleMultitouchTrackpadHIDEventDriver::metaClass;
AppleMultitouchTrackpadHIDEventDriver::operator delete(void*, unsigned long);
AppleMultitouchTrackpadHIDEventDriver::operator new(unsigned long);
AppleMultitouchTrackpadHIDEventDriver::superClass;
AppleMultitouchTrackpadHIDEventDriver_ktv;
IOHIDEventService::gMetaClass;
IOHIDInterface::metaClass;
OSArray::metaClass;
OSBoolean::metaClass;
OSDictionary::metaClass;
OSNumber::metaClass;
OSString::metaClass;
kWakeReasonAccelString;
kWakeReasonAutoInputReportString;
kWakeReasonBatteryString;
kWakeReasonButtonString;
kWakeReasonControlDataString;
kWakeReasonCriticalErrorsString;
kWakeReasonHostString;
kWakeReasonInvalidString;
kWakeReasonKeyboardString;
kWakeReasonMessageString;
kWakeReasonPowerSwitchString;
kWakeReasonTrackpadString;
kWakeReasonUnknownString;
vtable for AppleDeviceManagementHIDEventService;
vtable for AppleDeviceManagementHIDEventService::MetaClass;
vtable for AppleMultitouchHIDEventDriverV2;
vtable for AppleMultitouchInputHIDEventDriver;
vtable for AppleMultitouchInputHIDEventDriver::MetaClass;
vtable for AppleMultitouchMouseHIDEventDriver;
vtable for AppleMultitouchMouseHIDEventDriver::MetaClass;
vtable for AppleMultitouchTrackpadHIDEventDriver;
vtable for AppleMultitouchTrackpadHIDEventDriver::MetaClass;
vtable for IOHIDEventService;
