//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class Vega10DiagLedProgrammerV2 {
public: // (access info unavailable from symbols alone)
    Vega10DiagLedProgrammerV2();
    Vega10DiagLedProgrammerV2(OSMetaClass const*);
    getMetaClass() const;
    init(ATIController*);
    programBootOk();
    programPanelDown();
    programPanelOk();
    resetLEDs();
    updateDiagnosticLEDs(AtiDiagLedProgrammer::GPU_DIAG_BOOT_STATE);
    ~Vega10DiagLedProgrammerV2();
};
