//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class Vega10DiagLedProgrammerFactory {
public: // (access info unavailable from symbols alone)
    createDiagLedProgrammer(unsigned int, ATIController*);
};
