//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleUSBAudioInterruptPipe {
public: // (access info unavailable from symbols alone)
    AppleUSBAudioInterruptPipe();
    AppleUSBAudioInterruptPipe(OSMetaClass const*);
    auto Abort();
    auto ClearPipeStall(bool);
    auto Read(IOBufferMemoryDescriptor*, IOUSBHostCompletion*);
    auto SetIdlePolicy(unsigned int);
    auto forDeviceOnInterfaceWithProperties(AppleUSBAudioDevice*, IOService*, unsigned short, unsigned char);
    auto free();
    auto getMetaClass() const;
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~AppleUSBAudioInterruptPipe();
};
