//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AUAClockMultiplierDictionary {
public: // (access info unavailable from symbols alone)
    AUAClockMultiplierDictionary();
    AUAClockMultiplierDictionary(OSMetaClass const*);
    auto getMetaClass() const;
    auto initControlsArray(unsigned char const*, unsigned char);
    auto initControlsArray(unsigned char const*, unsigned char) (.cold.1);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~AUAClockMultiplierDictionary();
};
