//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class __cxxabiv1::__pbase_type_info {
public: // (access info unavailable from symbols alone)
    can_catch(__cxxabiv1::__shim_type_info const*, void*&) const;
    ~__pbase_type_info();
};
