//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IO80211ControllerMonitor {
public: // (access info unavailable from symbols alone)
    IO80211ControllerMonitor();
    IO80211ControllerMonitor(OSMetaClass const*);
    collectAmpduChipCounterStats(apple80211_chip_stats*, IO80211LinkQualityMonitor*);
    configureReport(IOReportChannelList*, unsigned int, void*, void*);
    createHeReportersAndLegend();
    createInterfaceReportSet();
    createReportersAndLegend();
    destroyReporters();
    free();
    free()::kalloc_type_view_269;
    getAMPDUChannelID(apple80211_ampdu_stat_report*, unsigned int*);
    getBTCoexWLANLostAntenna(unsigned long long*, unsigned long long*, bool*);
    getBtPct();
    getChanCCA(apple80211_channel, long long*);
    getChanQualChannelID(ChannelQualityTypes, apple80211_channel);
    getController();
    getDriverAvailable();
    getLinkRecoveryReportChannelID(apple80211_link_recovery_action, IO80211LinkRecoveryActionState);
    getLinkRecoveryReportChannelID(apple80211_link_recovery_reason);
    getLinkRecoveryReportChannelID(apple80211_link_recovery_reason, apple80211_link_recovery_user_input);
    getLogger() const;
    getMetaClass() const;
    getRxErrorRate(unsigned int*);
    getTxErrorRate(unsigned int*);
    getTxRetransmitRate(unsigned int*);
    increaseLinkRecoveryStatsActionStateCounters(unsigned int, unsigned int);
    increaseLinkRecoveryStatsRecoveryReasonCounters(unsigned int);
    increaseLinkRecoveryStatsUserInputCounters(unsigned int, unsigned int);
    initWithControllerAndProvider(IO80211Controller*, IOService*);
    initWithControllerAndProvider(IO80211Controller*, IOService*)::kalloc_type_view_212;
    isStatValid(unsigned char*, unsigned long);
    resetIO80211ReporterHistory();
    setAMPDUstat(apple80211_stat_report*, apple80211_ampdu_stat_report*);
    setBTCoexstat(apple80211_stat_report*, apple80211_btCoex_report*);
    setBtPct(unsigned short);
    setChanCCA(apple80211_channel, int);
    setChanNoiseFloor(apple80211_channel, int);
    setChanNoiseFloorLTE(apple80211_channel, int);
    setChipCounterStats(apple80211_chip_stats*);
    setChipHeCounterStats(apple80211_he_stats*);
    setDriverAvailable(void*, unsigned long);
    setFrameStats(apple80211_frame_counters*);
    setInfraSpecificFrameStats(apple80211_infra_specific_stats*);
    setLTECoexstat(apple80211_stat_report*, apple80211_lteCoex_report*);
    setLprxStats(apple80211_power_debug_sub_info*);
    setPowerStats(apple80211_power_debug_sub_info*);
    setRxetStats(apple80211_power_debug_sub_info*);
    updateAllReports();
    updateReport(IOReportChannelList*, unsigned int, void*, void*);
    updateReportDetail();
    withControllerAndProvider(IO80211Controller*, IOService*);
    ~IO80211ControllerMonitor();
};
