//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IO80211TimerSource {
public: // (access info unavailable from symbols alone)
    IO80211TimerSource();
    IO80211TimerSource(OSMetaClass const*);
    allocWithParams(IO80211TimerSourcePriority, OSObject*, IO80211WorkQueue*, void (*)(OSObject*, IO80211TimerSource*));
    allocWithParams(OSObject*, IO80211WorkQueue*, void (*)(OSObject*, IO80211TimerSource*));
    free();
    getMetaClass() const;
    init(IO80211TimerSourcePriority, OSObject*, IO80211WorkQueue*, void (*)(OSObject*, IO80211TimerSource*));
    ~IO80211TimerSource();
};
