//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IO80211BufferPool {
public: // (access info unavailable from symbols alone)
    IO80211BufferPool();
    IO80211BufferPool(OSMetaClass const*);
    flushPool();
    free();
    getBuffer();
    getMetaClass() const;
    mapBufferPool();
    printStats(char const*) const;
    resetPool();
    returnBuffer(IO80211Buffer*);
    unmapBufferPool();
    withOptions(IO80211BufferPoolOptions*, bool);
    withOptions(IO80211BufferPoolOptions*, bool)::_os_log_fmt;
    ~IO80211BufferPool();
};
