//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOHistogramReporter {
public: // (access info unavailable from symbols alone)
    IOHistogramReporter(OSMetaClass const*);
    auto handleCreateLegend();
    auto initWith(IOService*, unsigned short, unsigned long long, OSSymbol const*, unsigned long long, int, IOHistogramSegmentConfig*);
    auto overrideBucketValues(unsigned int, unsigned long long, long long, long long, long long);
    auto tallyValue(long long);
    auto with(IOService*, unsigned short, unsigned long long, char const*, unsigned long long, int, IOHistogramSegmentConfig*);
    ~IOHistogramReporter();
};
