//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSDictionary;

@interface PS190APHardwareID
{
    _Bool _productionStatus;
    _Bool _securityMode;
    unsigned int _boardID;
    unsigned int _chipID;
    unsigned int _securityDomain;
    unsigned int _flavorField;
}

+ (id);
- (id);
- (_Bool);
- (unsigned int);
- (_Bool);
- (id);
- (unsigned int);
- (unsigned int);
- (_Bool);
- (id);
- (unsigned int);

// Remaining properties
@property(readonly) unsigned int boardID; // @synthesize boardID=_boardID;
@property(readonly) unsigned int chipID; // @synthesize chipID=_chipID;
@property(readonly) unsigned int flavorField; // @synthesize flavorField=_flavorField;
@property(readonly) NSDictionary *personalizationParameters;
@property(readonly) _Bool productionStatus; // @synthesize productionStatus=_productionStatus;
@property(readonly) unsigned int securityDomain; // @synthesize securityDomain=_securityDomain;
@property(readonly) _Bool securityMode; // @synthesize securityMode=_securityMode;

@end

