//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSString;

@interface B2PDataSessionDiscoveryEntry
{
    unsigned char _sessionID;
    NSString *_tag;
}

- (id);
- (id);
- (unsigned char);
- (void);

// Remaining properties
@property(readonly) unsigned char sessionID; // @synthesize sessionID=_sessionID;
@property(readonly) NSString *tag; // @synthesize tag=_tag;

@end

