//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSObject;
@protocol OS_dispatch_queue, OS_dispatch_semaphore, OS_os_log;

@interface HPMForceRetimerDFUModeSetter
{
    unsigned int _hpmService;
    unsigned int _hpmConnection;
    unsigned int _address;
    _Bool _enableDFUMode;
    NSObject<OS_os_log> *_log;
    unsigned int _thunderboltController;
    NSObject<OS_dispatch_queue> *_notificationQueue;
    NSObject<OS_dispatch_semaphore> *_notificationSemaphore;
    struct IONotificationPort *_notificationPort;
    unsigned int _notification;
    struct IOCFPlugInInterfaceStruct **_cfPlugInInterface;
    struct AppleHPMLibInterfaceStructV3 **_hpmInterface;
}

- (_Bool);
- (_Bool);
- (id);
- (_Bool);
- (unsigned int);
- (_Bool);
- (unsigned int);
- (id);
- (_Bool);
- (_Bool);
- (void);
- (void);
- (_Bool);
- (void);
- (const char *);

@end

