//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class ATCRTBloodhoundPacketDumper, NSObject;
@protocol OS_dispatch_queue;

@interface ThunderboltPacketDumper
{
    ATCRTBloodhoundPacketDumper *_dumper;
    NSObject<OS_dispatch_queue> *_writeQueue;
    _Bool _suppressed;
}

- (void);
- (void);
- (void);
- (void);
- (void);
- (void);
- (void);
- (void);
- (void);
- (void);
- (_Bool);
- (void);
- (void);

// Remaining properties
@property _Bool suppressed; // @synthesize suppressed=_suppressed;

@end

