//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class std::__1::__copy_move_unwrap_iters[abi:ne200100]<std::__1::__copy_impl, xpc::array::iterator, xpc::array::iterator, std::__1::insert_iterator<std::__1::set<xpc::dict, CellularUsagePolicyClient::policy_cmp_by_bundleId, std::__1::allocator<xpc {
public: // (access info unavailable from symbols alone)
    dict>>>, 0>(xpc::array::iterator, xpc::array::iterator, std::__1::insert_iterator<std::__1::set<xpc::dict, CellularUsagePolicyClient::policy_cmp_by_bundleId, std::__1::allocator<xpc::dict>>>);
};
