//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class MISSING_TYPE;

@interface Runtime.ElfImageCache
{
    MISSING_TYPE *elf32;
    MISSING_TYPE *elf64;
}

@end

