//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension Swift.Substring.UTF8View {
    distance(from: Swift.String.Index, to: Swift.String.Index) -> Swift.Int
    index(_: Swift.String.Index, offsetBy: Swift.Int) -> Swift.String.Index
    index(_: Swift.String.Index, offsetBy: Swift.Int, limitedBy: Swift.String.Index) -> Swift.Optional<Swift.String.Index>
    index(after: Swift.String.Index) -> Swift.String.Index
}
