//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class dyld4::Atlas::Image {
public: // (access info unavailable from symbols alone)
    Image(dyld4::RuntimeState*, lsl::Allocator&, lsl::SharedPtr<dyld4::Atlas::Mapper>&, dyld4::Loader const*);
    Image(lsl::Allocator&, dyld4::FileRecord&&, lsl::SharedPtr<dyld4::Atlas::Mapper>&, dyld4::Atlas::SafePointer);
    Image(lsl::Allocator&, dyld4::FileRecord&&, lsl::SharedPtr<dyld4::Atlas::Mapper>&, dyld4::Atlas::SafePointer, lsl::UUID const&);
    auto ml() const;
    auto swap(dyld4::Atlas::Image&);
    auto uuid() const;
};
