//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class lsl::OrderedSet<char const*, lsl::ConstCharStarCompare> {
public: // (access info unavailable from symbols alone)
    auto insert(char const* const&);
    auto insert(char const*&&);
};
