//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class lsl::Bitmap {
public: // (access info unavailable from symbols alone)
    Bitmap(lsl::Allocator&, unsigned long);
    auto setBit(unsigned long);
    auto setBit(unsigned long) (.cold.1);
    ~Bitmap();
};
