//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class objc_visitor::Category {
public: // (access info unavailable from symbols alone)
    getClassMethods(objc_visitor::Visitor const&) const;
    getInstanceMethods(objc_visitor::Visitor const&) const;
};
