//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class objc_visitor::MethodList {
public: // (access info unavailable from symbols alone)
    getMethod(objc_visitor::Visitor const&, unsigned int) const;
    getMethod(objc_visitor::Visitor const&, unsigned int) const (.cold.1);
    getMethod(objc_visitor::Visitor const&, unsigned int) const (.cold.2);
    numMethods() const;
    numMethods() const (.cold.1);
    usesRelativeOffsets() const;
    usesRelativeOffsets() const (.cold.1);
};
