//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class PropertyList::Bitmap {
public: // (access info unavailable from symbols alone)
    Bitmap(lsl::Allocator&, unsigned long long);
    setBit(unsigned long long);
    setBit(unsigned long long) (.cold.1);
};
