//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class TTokenGenerator {
public: // (access info unavailable from symbols alone)
    TTokenGenerator();
    auto Add(char const*);
    auto AddBinary(void const*, unsigned int);
    auto AddInt(int);
    auto AddLongLong(long long);
    auto Generate(unsigned int&);
    auto Generate(unsigned int&) (.cold.1);
    auto Generate(unsigned int&) (.cold.2);
    auto Generate(unsigned int&) (.cold.3);
    auto GetDescription();
    ~TTokenGenerator();
};
