//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class CoreStorageFamily {
public: // (access info unavailable from symbols alone)
    CoreStorageFamily();
    CoreStorageFamily(OSMetaClass const*);
    auto addVolume(CoreStorageLogical*);
    auto commitFamilyProperties(OSDictionary*, CoreStorageLogical*, tx*, bool*, bool*);
    auto copyFamilyProperties(bool);
    auto createFamily(OSDictionary*, lvf_handle*, CoreStorageGroup*);
    auto free();
    auto free()::kalloc_type_view_30;
    auto free()::kalloc_type_view_31;
    auto free()::kalloc_type_view_32;
    auto getMetaClass() const;
    auto getSBAddr() const;
    auto init();
    auto init()::kalloc_type_view_101;
    auto init()::kalloc_type_view_93;
    auto init()::kalloc_type_view_97;
    auto initWithProps(OSDictionary*);
    auto loadContext(OSData**, OSString**, unsigned int*, unsigned int*, bool*);
    auto lockEncryptionContext();
    auto lockProperties();
    auto messageLVClients();
    auto rebootNeededForNewTarget(unsigned int);
    auto removeVolume(CoreStorageLogical*);
    auto removeVolumeKeys();
    auto unlockProperties();
    auto unlockVEKs(IOService*, OSData**, OSString*);
    auto updateFamilyProperties(OSDictionary*, CoreStorageLogical*, tx*, lvg*);
    auto validateEncryptionContext(OSString*);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~CoreStorageFamily();
};
