//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class CoreStorageUserClient {
public: // (access info unavailable from symbols alone)
    CoreStorageUserClient();
    CoreStorageUserClient(OSMetaClass const*);
    clientClose();
    createLogicalVolume(IOExternalMethodArguments*);
    createLogicalVolumeShim(OSObject*, void*, IOExternalMethodArguments*);
    debugPortal(IOExternalMethodArguments*);
    debugPortalShim(OSObject*, void*, IOExternalMethodArguments*);
    destroyLogicalVolume(IOExternalMethodArguments*);
    destroyLogicalVolumeShim(OSObject*, void*, IOExternalMethodArguments*);
    externalMethod(unsigned int, IOExternalMethodArguments*, IOExternalMethodDispatch*, OSObject*, void*);
    getExtents(IOExternalMethodArguments*);
    getExtentsShim(OSObject*, void*, IOExternalMethodArguments*);
    getFamilyProperties(IOExternalMethodArguments*);
    getFamilyPropertiesShim(OSObject*, void*, IOExternalMethodArguments*);
    getGroupProperties(IOExternalMethodArguments*);
    getGroupPropertiesShim(OSObject*, void*, IOExternalMethodArguments*);
    getGroupStatistics(IOExternalMethodArguments*);
    getGroupStatisticsShim(OSObject*, void*, IOExternalMethodArguments*);
    getListOfLVGs(IOExternalMethodArguments*);
    getListOfLVGsShim(OSObject*, void*, IOExternalMethodArguments*);
    getMetaClass() const;
    getPhysicalVolumeProperties(IOExternalMethodArguments*);
    getPhysicalVolumePropertiesShim(OSObject*, void*, IOExternalMethodArguments*);
    getVolumeProperties(IOExternalMethodArguments*);
    getVolumePropertiesShim(OSObject*, void*, IOExternalMethodArguments*);
    getVolumesForGroup(IOExternalMethodArguments*);
    getVolumesForGroupShim(OSObject*, void*, IOExternalMethodArguments*);
    initWithTask(task*, void*, unsigned int);
    mapArguments(IOExternalMethodArguments*, IOMemoryMap**, void**, unsigned long*, void**, unsigned long*, bool);
    minPVResizeDelta(IOExternalMethodArguments*);
    minPVResizeDeltaShim(OSObject*, void*, IOExternalMethodArguments*);
    pinUnpinExtents(IOExternalMethodArguments*);
    pinUnpinExtentsShim(OSObject*, void*, IOExternalMethodArguments*);
    resizePhysicalVolume(IOExternalMethodArguments*);
    resizePhysicalVolumeShim(OSObject*, void*, IOExternalMethodArguments*);
    resizeVolume(IOExternalMethodArguments*);
    resizeVolumeShim(OSObject*, void*, IOExternalMethodArguments*);
    setSystemPowerState(IOExternalMethodArguments*);
    setSystemPowerStateShim(OSObject*, void*, IOExternalMethodArguments*);
    start(IOService*);
    unmapArguments(IOExternalMethodArguments*, IOMemoryMap**, void**, void**, unsigned long, bool);
    updateFamily(IOExternalMethodArguments*);
    updateFamilyShim(OSObject*, void*, IOExternalMethodArguments*);
    updateGroup(IOExternalMethodArguments*);
    updateGroupShim(OSObject*, void*, IOExternalMethodArguments*);
    updateLogicalVolume(IOExternalMethodArguments*);
    updateLogicalVolumeShim(OSObject*, void*, IOExternalMethodArguments*);
    volumeRevertReqs(IOExternalMethodArguments*);
    volumeRevertReqsShim(OSObject*, void*, IOExternalMethodArguments*);
    ~CoreStorageUserClient();
};
