//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class CoreStorage {
public: // (access info unavailable from symbols alone)
    CoreStorage();
    CoreStorage(OSMetaClass const*);
    addGroup(CoreStorageGroup*);
    addLogicalFamily(CoreStorageFamily*);
    addLogicalVolume(CoreStorageLogical*);
    addPhysicalVolume(CoreStoragePhysical*);
    createLogicalVolume(char*, unsigned long);
    debugPortal(DebugPortalArg*, unsigned long, void*, unsigned long*, bool);
    destroyLogicalVolume(char*, unsigned long);
    findGroup(CoreStoragePhysical*);
    findGroup(OSString const*);
    findGroup(char const*);
    findLogicalFamily(OSString const*);
    findLogicalVolume(OSString const*);
    findLogicalVolume(char const*);
    findPhysicalVolume(OSString const*);
    free();
    getExtents(char*, unsigned long, char*, unsigned long*);
    getFamilyProperties(char*, unsigned long, OSSerialize*, bool);
    getGroupProperties(char*, unsigned long, OSSerialize*);
    getGroupStatistics(char*, unsigned long, OSSerialize*);
    getListOfGroups(char*, unsigned long*);
    getMetaClass() const;
    getPhysicalVolumeProperties(char*, unsigned long, OSSerialize*);
    getVolumeProperties(char*, unsigned long, OSSerialize*);
    getVolumesForGroup(char*, unsigned long, char*, unsigned long*);
    init();
    minPVResizeDelta(char*, unsigned long, char*, unsigned long*);
    pinUnpinExtents(char*, unsigned long);
    removeGroup(CoreStorageGroup*);
    removeLogicalFamily(CoreStorageFamily*);
    removeLogicalVolume(CoreStorageLogical*);
    removePhysicalVolume(CoreStoragePhysical*);
    resizePhysicalVolume(char*, unsigned long);
    resizeVolume(char*, unsigned long);
    setSystemPowerState(unsigned int);
    startPhysicalVolume(IORegistryEntry*);
    updateFamily(char*, unsigned long);
    updateGroup(char*, unsigned long, char*, unsigned long*);
    updateLogicalVolume(char*, unsigned long);
    volumeRevertRequirements(char*, unsigned long, char*, unsigned long*);
    ~CoreStorage();
};
