//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOGeneralMemoryDescriptor {
public: // (access info unavailable from symbols alone)
    IOGeneralMemoryDescriptor(OSMetaClass const*);
    auto complete(unsigned int);
    auto dmaCommandOperation(unsigned int, void*, unsigned int) const;
    auto doMap(_vm_map*, unsigned long long*, unsigned int, unsigned long long, unsigned long long);
    auto doUnmap(_vm_map*, unsigned long long, unsigned long long);
    auto getPhysicalSegment(unsigned long long, unsigned long long*, unsigned int);
    auto getPreparationID();
    auto initWithOptions(void*, unsigned int, unsigned int, task*, unsigned int, IOMapper*);
    auto makeMapping(IOMemoryDescriptor*, task*, unsigned long long, unsigned int, unsigned long long, unsigned long long);
    auto prepare(unsigned int);
    auto serialize(OSSerialize*) const;
    auto setPurgeable(unsigned int, unsigned int*);
    ~IOGeneralMemoryDescriptor();
};
