//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleUSBRequestCompleter {
public: // (access info unavailable from symbols alone)
    AppleUSBRequestCompleter(OSMetaClass const*);
    auto bundlingTimeoutHandler(IOTimerEventSource*);
    auto checkForWork();
    auto completeRequestQueue(queue_entry*);
    auto completeRequestThreadCall(AppleUSBRequestCompleter::tRequestCompleteData*);
    auto completeRequestThreadCallGated(AppleUSBRequest*);
    auto completeSynchronousRequestQueueThreadCall(thread_call*);
    auto completeSynchronousRequestQueueThreadCallGated();
    auto free();
    auto init(OSObject*, IOWorkLoop*, void (*)(OSObject*, ...));
    auto onThread();
    auto onThreadGated(bool&);
    auto signalWorkAvailable();
    auto stop();
    ~AppleUSBRequestCompleter();
};
