//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleUSBRequestCompleter {
public: // (access info unavailable from symbols alone)
    AppleUSBRequestCompleter(OSMetaClass const*);
    bundlingTimeoutHandler(IOTimerEventSource*);
    checkForWork();
    completeRequestQueue(queue_entry*);
    completeRequestThreadCall(AppleUSBRequestCompleter::tRequestCompleteData*);
    completeRequestThreadCallGated(AppleUSBRequest*);
    completeSynchronousRequestQueueThreadCall(thread_call*);
    completeSynchronousRequestQueueThreadCallGated();
    free();
    init(OSObject*, IOWorkLoop*, void (*)(OSObject*, ...));
    onThread();
    onThreadGated(bool&);
    signalWorkAvailable();
    stop();
    ~AppleUSBRequestCompleter();
};
