//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleUSBHostDeviceIdler {
public: // (access info unavailable from symbols alone)
    AppleUSBHostDeviceIdler();
    AppleUSBHostDeviceIdler(OSMetaClass const*);
    auto disable();
    auto enable();
    auto free();
    auto getMetaClass() const;
    auto initWithDeviceAndWorkLoop(IOUSBHostDevice*, IOWorkLoop*);
    auto removeObject(OSMetaClassBase const*);
    auto removeObjectGated(OSMetaClassBase const*);
    auto removeObjectGated(OSMetaClassBase const*)::_os_log_fmt;
    auto setObject(OSMetaClassBase const*);
    auto setObjectGated(OSMetaClassBase const*);
    auto setObjectGated(OSMetaClassBase const*)::_os_log_fmt;
    auto tickle();
    auto timerCompletion(IOTimerEventSource*);
    auto timerCompletion(IOTimerEventSource*)::_os_log_fmt;
    auto updateIdlePolicy(unsigned int);
    auto updateIdlePolicyGated(unsigned int);
    auto withDeviceAndWorkLoop(IOUSBHostDevice*, IOWorkLoop*);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~AppleUSBHostDeviceIdler();
};
