//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOBufferMemoryDescriptor {
public: // (access info unavailable from symbols alone)
    IOBufferMemoryDescriptor(OSMetaClass const*);
    auto Dispatch(IORPC);
    auto _RESERVEDIOBufferMemoryDescriptor0();
    auto _RESERVEDIOBufferMemoryDescriptor1();
    auto _RESERVEDIOBufferMemoryDescriptor10();
    auto _RESERVEDIOBufferMemoryDescriptor11();
    auto _RESERVEDIOBufferMemoryDescriptor12();
    auto _RESERVEDIOBufferMemoryDescriptor13();
    auto _RESERVEDIOBufferMemoryDescriptor14();
    auto _RESERVEDIOBufferMemoryDescriptor15();
    auto _RESERVEDIOBufferMemoryDescriptor2();
    auto _RESERVEDIOBufferMemoryDescriptor3();
    auto _RESERVEDIOBufferMemoryDescriptor4();
    auto _RESERVEDIOBufferMemoryDescriptor5();
    auto _RESERVEDIOBufferMemoryDescriptor6();
    auto _RESERVEDIOBufferMemoryDescriptor7();
    auto _RESERVEDIOBufferMemoryDescriptor8();
    auto _RESERVEDIOBufferMemoryDescriptor9();
    auto appendBytes(void const*, unsigned long);
    auto getBytesNoCopy();
    auto getBytesNoCopy(unsigned long, unsigned long);
    auto getCapacity() const;
    auto inTaskWithPhysicalMask(task*, unsigned int, unsigned long long, unsigned long long);
    auto initWithPhysicalMask(task*, unsigned int, unsigned long long, unsigned long long, unsigned long long);
    auto setDirection(unsigned int);
    auto setLength(unsigned long);
    ~IOBufferMemoryDescriptor();
};
