//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOUSBHostDevice::MetaClass {
public: // (access info unavailable from symbols alone)
    Dispatch(IORPC);
    MetaClass();
    alloc() const;
    ~MetaClass();
};
