//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleUSBEHCIPort {
public: // (access info unavailable from symbols alone)
    AppleUSBEHCIPort();
    AppleUSBEHCIPort(OSMetaClass const*);
    enableChangeInterrupt();
    enableChangeInterrupt()::_os_log_fmt;
    enterTestMode(tEHCITestMode);
    enterTestMode(tEHCITestMode)::_os_log_fmt;
    enterTestMode(tEHCITestMode)::kalloc_type_view_217;
    enterTestMode(tEHCITestMode)::kalloc_type_view_226;
    enterTestMode(tEHCITestMode)::kalloc_type_view_232;
    enumerateDeviceComplete(IOUSBHostDevice*, int);
    free();
    getMetaClass() const;
    getPortSC() const;
    getPortSCForWriting() const;
    getPortSpeed();
    getPortStatusGated(unsigned int&);
    initWithPortSC(IODeviceMemory*, OSDictionary*);
    initWithPortSC(IODeviceMemory*, OSDictionary*)::_os_log_fmt;
    initWithPortSCandDTEntry(IODeviceMemory*, IORegistryEntry*);
    initWithPortSCandDTEntry(IODeviceMemory*, IORegistryEntry*)::_os_log_fmt;
    interruptOccurred(IOInterruptEventSource*, int);
    interruptOccurred(IOInterruptEventSource*, int)::_os_log_fmt;
    powerOff();
    powerOff()::_os_log_fmt;
    powerOn();
    powerOn()::_os_log_fmt;
    resetAndCreateDevice(unsigned int);
    resetAndCreateDevice(unsigned int)::_os_log_fmt;
    resetPort(unsigned int);
    resetPort(unsigned int)::_os_log_fmt;
    resume();
    resume()::_os_log_fmt;
    setPortSC(unsigned int) const;
    setProperties(OSObject*);
    start(IOService*);
    start(IOService*)::_os_log_fmt;
    suspend();
    suspend()::_os_log_fmt;
    testMode(tEHCITestMode);
    testMode(tEHCITestMode)::_os_log_fmt;
    testModeThreadCall(void*, void*);
    testModeThreadCall(void*, void*)::kalloc_type_view_251;
    withPortSC(IODeviceMemory*, OSDictionary*);
    withPortSCandDTEntry(IODeviceMemory*, IORegistryEntry*);
    ~AppleUSBEHCIPort();
};
