//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleUSBEHCISplitIsochronousRequestPool {
public: // (access info unavailable from symbols alone)
    AppleUSBEHCISplitIsochronousRequestPool();
    AppleUSBEHCISplitIsochronousRequestPool(OSMetaClass const*);
    auto allocateCommand();
    auto getMetaClass() const;
    auto withWorkLoopAndController(IOWorkLoop*, AppleUSBEHCI*);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~AppleUSBEHCISplitIsochronousRequestPool();
};
