//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleUSBEHCIIsochronousRequest {
public: // (access info unavailable from symbols alone)
    AppleUSBEHCIIsochronousRequest();
    AppleUSBEHCIIsochronousRequest(OSMetaClass const*);
    auto cancel();
    auto complete();
    auto complete() (.cold.1);
    auto complete()::_os_log_fmt;
    auto finish(int);
    auto finish(int)::_os_log_fmt;
    auto free();
    auto getLastFrame();
    auto getMetaClass() const;
    auto initWithControllerAndPool(AppleUSBEHCI*, AppleUSBRequestPool*);
    auto link();
    auto prepare(AppleUSBHostRequest*, AppleUSBEHCIIsochronousEndpoint*);
    auto prepare(AppleUSBHostRequest*, AppleUSBEHCIIsochronousEndpoint*)::_os_log_fmt;
    auto update();
    auto update(int);
    auto withControllerAndPool(AppleUSBEHCI*, AppleUSBRequestPool*);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~AppleUSBEHCIIsochronousRequest();
};
