//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleUSBEHCIqTDPool {
public: // (access info unavailable from symbols alone)
    AppleUSBEHCIqTDPool();
    AppleUSBEHCIqTDPool(OSMetaClass const*);
    free();
    free()::kalloc_type_view_72;
    getMetaClass() const;
    getTD();
    getTD()::kalloc_type_view_116;
    initWithOptions(unsigned int, IOMapper*);
    returnTD(AppleUSBEHCIqTD*);
    withOptions(unsigned int, IOMapper*);
    ~AppleUSBEHCIqTDPool();
};
