//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class DIDeviceRequest {
public: // (access info unavailable from symbols alone)
    create(IOLWPool<DIDeviceRequest>&, unsigned int);
    die();
    init(unsigned int);
    ~DIDeviceRequest();
};
