//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IntervalMapLRU {
public: // (access info unavailable from symbols alone)
    auto changeCacheSize(int);
    auto clearAllNodes();
    auto clearAllNodes() (.cold.1);
    auto clearAllNodes() (.cold.2);
    auto insertNode(IntervalMapLRU::Node*, bool, bool (*)(void*, unsigned long long, unsigned long), void*);
    auto insertNode(IntervalMapLRU::Node*, bool, bool (*)(void*, unsigned long long, unsigned long), void*) (.cold.1);
    auto insertNode(IntervalMapLRU::Node*, bool, bool (*)(void*, unsigned long long, unsigned long), void*) (.cold.2);
    auto insertNode(IntervalMapLRU::Node*, bool, bool (*)(void*, unsigned long long, unsigned long), void*) (.cold.3);
    auto insertNodeLocked(IntervalMapLRU::Node*, IntervalMapLRU::Node*, bool);
    auto insertNodeLocked(IntervalMapLRU::Node*, IntervalMapLRU::Node*, bool) (.cold.1);
    auto insertNodeLocked(IntervalMapLRU::Node*, IntervalMapLRU::Node*, bool) (.cold.2);
    auto insertNodeLocked(IntervalMapLRU::Node*, IntervalMapLRU::Node*, bool) (.cold.3);
    auto invalidateByLRULocked(unsigned long, IntervalMapLRU::_nodes*);
    auto invalidateByLRULocked(unsigned long, IntervalMapLRU::_nodes*) (.cold.1);
    auto invalidateRange(unsigned long long, unsigned long long);
    auto printCache() const;
    auto removeNodeLocked(IntervalMapLRU::Node*);
    auto removeNodeLocked(IntervalMapLRU::Node*) (.cold.1);
    auto removeNodeLocked(IntervalMapLRU::Node*) (.cold.2);
    auto searchForRange(unsigned long long, unsigned long long, IntervalMapLRU::NodeCompareRes*, IntervalMapLRU::NodeIterator*);
};
