//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class libkern::safe_allocation<OSSharedPtr<IOMemoryMap>, os_detail::IOKit_typed_allocator<OSSharedPtr<IOMemoryMap>, false>, os_detail::panic_trapping_policy> {
public: // (access info unavailable from symbols alone)
    auto destroy_dealloc_(OSSharedPtr<IOMemoryMap>*, unsigned long);
};
