//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension Swift.Unicode.UTF16.ForwardParser._buffer {
    getter : Swift._UIntBuffer<Swift.UInt16>
    modify : Swift._UIntBuffer<Swift.UInt16>
    modify : Swift._UIntBuffer<Swift.UInt16> with unmangled suffix ".resume.0"
    setter : Swift._UIntBuffer<Swift.UInt16>
}
