//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension Swift.Dictionary.Keys.Iterator {
    init(Swift.Dictionary<A, B>.Iterator) -> Swift.Dictionary<A, B>.Keys.Iterator
    next() -> Swift.Optional<A>
}
