//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension Swift.InstantiateKeyPathBuffer {
    pushAddressDiscriminatedFunctionPointer(_: Swift.UnsafeRawPointer, discriminator: Swift.UInt64) -> ()
    visitComputedComponent(mutating: Swift.Bool, idKind: Swift.KeyPathComputedIDKind, idResolution: Swift.KeyPathComputedIDResolution, idValueBase: Swift.UnsafeRawPointer, idValue: Swift.Int32, getter: Swift.UnsafeRawPointer, setter: Swift.Optional<Swift.UnsafeRawPointer>, arguments: Swift.Optional<Swift.KeyPathPatternComputedArguments>, externalArgs: Swift.Optional<Swift.UnsafeBufferPointer<Swift.Int32>>) -> ()
    visitStoredComponent(kind: Swift.KeyPathStructOrClass, mutable: Swift.Bool, offset: Swift.KeyPathPatternStoredOffset) -> ()
}
