//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleUSBNCMPacketQueue {
public: // (access info unavailable from symbols alone)
    AppleUSBNCMPacketQueue();
    auto reset();
    ~AppleUSBNCMPacketQueue();
};
