//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleEthernetAquantiaAqtionTEG {
public: // (access info unavailable from symbols alone)
    AppleEthernetAquantiaAqtionTEG();
    AppleEthernetAquantiaAqtionTEG(OSMetaClass const*);
    auto getMetaClass() const;
    auto init(unsigned char, OSString*, OSDictionary*);
    auto init(unsigned char, OSString*, OSDictionary*) (.cold.1);
    auto init(unsigned char, OSString*, OSDictionary*)::_os_log_fmt;
    auto scheduleNativePulse(unsigned long long, unsigned int);
    auto scheduleNativePulse(unsigned long long, unsigned int) (.cold.1);
    auto scheduleNativePulse(unsigned long long, unsigned int) (.cold.2);
    auto scheduleNativePulse(unsigned long long, unsigned int)::_os_log_fmt;
    auto schedulePulse(unsigned long long, unsigned int);
    auto schedulePulse(unsigned long long, unsigned int) (.cold.1);
    auto schedulePulse(unsigned long long, unsigned int) (.cold.2);
    auto schedulePulse(unsigned long long, unsigned int)::_os_log_fmt;
    auto start(IOService*);
    auto start(IOService*) (.cold.1);
    auto start(IOService*) (.cold.2);
    auto start(IOService*)::_os_log_fmt;
    auto stop(IOService*);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~AppleEthernetAquantiaAqtionTEG();
};
