//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension UniformTypeIdentifiers.UTTagClass {
    == infix(UniformTypeIdentifiers.UTTagClass, UniformTypeIdentifiers.UTTagClass) -> Swift.Bool
    encode(to: Swift.Encoder) throws -> ()
    hash(into: inout Swift.Hasher) -> ()
    init(from: Swift.Decoder) throws -> UniformTypeIdentifiers.UTTagClass
    init(rawValue: Swift.String) -> UniformTypeIdentifiers.UTTagClass
}
