//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class capabilities::updaterinternal {
public: // (access info unavailable from symbols alone)
    dynamicICENVMFSizeBytes();
    dynamicICENVMFSizeBytes()::ret;
    guard variable for dynamicICENVMFSizeBytes()::ret;
    guard variable for supportsAudioOverPCIe()::ret;
    supportsAudioOverPCIe();
    supportsAudioOverPCIe()::ret;
};
