//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension ARKit.UserBodyEnrollmentData.PropertyState {
    == infix(ARKit.UserBodyEnrollmentData.PropertyState, ARKit.UserBodyEnrollmentData.PropertyState) -> Swift.Bool
    hash(into: inout Swift.Hasher) -> ()
}
