//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension ARKit.ImageTrackingProvider {
    __allocating_init(referenceImages: Swift.Array<ARKit.ReferenceImage>) -> ARKit.ImageTrackingProvider
    __deallocating_deinit
    deinit
    init(referenceImages: Swift.Array<ARKit.ReferenceImage>) -> ARKit.ImageTrackingProvider
}
