//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension ARKit.SimplifiedSceneReconstructionProvider.anchorUpdates {
    getter : ARKit.AnchorUpdateSequence<ARKit.MeshAnchor>
}
