//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class com_softraid_driver_SoftRAID_PowerMonitor {
public: // (access info unavailable from symbols alone)
    BlockShutdown();
    PoweringOn();
    Sleeping();
    TimerProc(IOTimerEventSource*);
    VolumeClosed();
    com_softraid_driver_SoftRAID_PowerMonitor();
    com_softraid_driver_SoftRAID_PowerMonitor(OSMetaClass const*);
    free();
    getMetaClass() const;
    init();
    ~com_softraid_driver_SoftRAID_PowerMonitor();
};
