//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class com_softraid_driver_SoftRAID_DriverEventRecPool {
public: // (access info unavailable from symbols alone)
    AllocDriverEventRec();
    FreeDriverEventRec(DriverEventRec*);
    com_softraid_driver_SoftRAID_DriverEventRecPool();
    com_softraid_driver_SoftRAID_DriverEventRecPool(OSMetaClass const*);
    free();
    free()::kalloc_type_view_585;
    getMetaClass() const;
    init();
    init()::kalloc_type_view_558;
    ~com_softraid_driver_SoftRAID_DriverEventRecPool();
};
