//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension os.OSMetricStatisticalLevel {
    == infix(os.OSMetricStatisticalLevel, os.OSMetricStatisticalLevel) -> Swift.Bool
    hash(into: inout Swift.Hasher) -> ()
}
