//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleActuatorDeviceUserClient {
public: // (access info unavailable from symbols alone)
    AppleActuatorDeviceUserClient();
    AppleActuatorDeviceUserClient(OSMetaClass const*);
    auto changeHostClickControl(void*);
    auto clientClose();
    auto clientDied();
    auto clientMemoryForType(unsigned int, unsigned int*, IOMemoryDescriptor**);
    auto createLogQueue();
    auto enqueueLog(unsigned char*, unsigned int);
    auto free();
    auto getMetaClass() const;
    auto getReport(MTDeviceReportStruct*, MTDeviceReportStruct*, unsigned long long, unsigned long long*);
    auto getTargetAndMethodForIndex(IOService**, unsigned int);
    auto initWithTask(task*, void*, unsigned int, OSDictionary*);
    auto initWithTask(task*, void*, unsigned int, OSDictionary*)::_os_log_fmt;
    auto issueDriverRequest(MTDriverRequestStruct*, MTDriverRequestResultStruct*, unsigned long long, unsigned long long*);
    auto recacheProperties();
    auto registerNotificationPort(ipc_port*, unsigned int, unsigned int);
    auto reservedMethod();
    auto setHostClickControlRequested(void*);
    auto setReport(MTDeviceReportStruct*, MTDeviceReportStruct*, unsigned long long, unsigned long long*);
    auto setSendsLogs(void*);
    auto setWaveform(MTActuatorSetWaveformStruct*, MTActuatorSetWaveformStruct*, unsigned long long, unsigned long long*);
    auto start(IOService*);
    auto stop(IOService*);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~AppleActuatorDeviceUserClient();
};
