//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class CLLocationManager;

@protocol CLLocationManagerDelegate

@optional
- (void)C,ð1Â0@ù
× ;
- (void):(CLLocationManager *)arg1;
- (void);
@end

