//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSDate, NSError, NSUUID;

@interface RTCurrentWorkoutSnapshot
{
    _Bool _isFirstPartyWorkout;
    NSUUID *_sessionIdentifier;
    unsigned long long _activityType;
    long long _locationType;
    long long _swimmingLocationType;
    long long _sessionType;
    unsigned long long _sessionState;
    NSDate *_workoutStartDate;
    NSDate *_snapshotDate;
    NSError *_sessionError;
}

- (id);
- (long long);
- (id);
- (id);
- (_Bool);
- (id);
- (long long);
- (id);
- (void);
- (id);
- (unsigned long long);
- (id)error %@;
- (long long)n;
- (unsigned long long)Öºÿè*µÚ;

// Remaining properties
@property(readonly, nonatomic) unsigned long long activityType; // @synthesize activityType=_activityType;
@property(readonly, nonatomic) _Bool isFirstPartyWorkout; // @synthesize isFirstPartyWorkout=_isFirstPartyWorkout;
@property(readonly, nonatomic) long long locationType; // @synthesize locationType=_locationType;
@property(readonly, nonatomic) NSError *sessionError; // @synthesize sessionError=_sessionError;
@property(readonly, nonatomic) NSUUID *sessionIdentifier; // @synthesize sessionIdentifier=_sessionIdentifier;
@property(readonly, nonatomic) unsigned long long sessionState; // @synthesize sessionState=_sessionState;
@property(readonly, nonatomic) long long sessionType; // @synthesize sessionType=_sessionType;
@property(readonly, nonatomic) NSDate *snapshotDate; // @synthesize snapshotDate=_snapshotDate;
@property(readonly, nonatomic) long long swimmingLocationType; // @synthesize swimmingLocationType=_swimmingLocationType;
@property(readonly, copy, nonatomic) NSDate *workoutStartDate; // @synthesize workoutStartDate=_workoutStartDate;

@end

