//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSArray;

@interface RTDTWResult
{
    double _distance;
    NSArray *_cellIndices;
}

- (id);
- (id);
- (void);
- (double);
- (void)onPreprocessor:applyRule_largeDistanceTransitionsAreInvalid_ForTransitionAtIndex:failed to fetch visit location for identifiers %@ and %@. Passthrough. /* Error: Ran out of types for this method. */;
- (void)%@, poi category, %@, timezone, %@;

// Remaining properties
@property(retain, nonatomic) NSArray *cellIndices; // @synthesize cellIndices=_cellIndices;
@property(nonatomic) double distance; // @synthesize distance=_distance;

@end

