//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <coreroutine/RTService.h>

@class NSManagedObjectContext, NSManagedObjectModel, NSPersistentContainer, NSURL, RTDataProtectionManager, RTPlatform;

@interface RTInterimPersistenceManager : RTService
{
    RTDataProtectionManager *_dataProtectionManager;
    RTPlatform *_platform;
    NSPersistentContainer *_persistentContainer;
    NSManagedObjectModel *_managedObjectModel;
    NSManagedObjectContext *_managedObjectContext;
    NSURL *_modelsDirectory;
    NSURL *_storesDirectory;
    unsigned long long _availability;
}

+ (id);
+ (id);
+ (id);
- (void);
- (id)];
- (id);
- (void);
- (void);
- (int);
- (_Bool)System/Library/PrivateFrameworks/ProtocolBuffer.framework/Versions/A/ProtocolBuffer;
- (_Bool);
- (int);
- (id)n;
- (id);
- (void);
- (void);
- (unsigned long long);
- (void);
- (id);
- (id);
- (void);
- (id);
- (id)satisfying:bluePOITileStore /* Error: Ran out of types for this method. */;
- (void)p«äÿa+	;
- (id)³;
- (void)ÞÿG½.âX;

// Remaining properties
@property(nonatomic) unsigned long long availability; // @synthesize availability=_availability;
@property(readonly, nonatomic) RTDataProtectionManager *dataProtectionManager; // @synthesize dataProtectionManager=_dataProtectionManager;
@property(readonly, nonatomic) NSManagedObjectContext *managedObjectContext; // @synthesize managedObjectContext=_managedObjectContext;
@property(readonly, nonatomic) NSManagedObjectModel *managedObjectModel; // @synthesize managedObjectModel=_managedObjectModel;
@property(readonly, nonatomic) NSURL *modelsDirectory; // @synthesize modelsDirectory=_modelsDirectory;
@property(readonly, nonatomic) NSPersistentContainer *persistentContainer; // @synthesize persistentContainer=_persistentContainer;
@property(readonly, nonatomic) RTPlatform *platform; // @synthesize platform=_platform;
@property(readonly, nonatomic) NSURL *storesDirectory; // @synthesize storesDirectory=_storesDirectory;

@end

