//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSMutableDictionary, NSString;

@interface RTMetric
{
    _Bool _loggingEnabled;
    _Bool _submitted;
    NSMutableDictionary *_metrics;
}

+ (id);
+ (id);
+ (id)R;
+ (id);
+ (CDStruct_b8464340)ple.private.alloy.screentime.invite;
+ (id);
- (_Bool);
- (void);
- (_Bool);
- (id);
- (_Bool);
- (void);
- (void);
- (_Bool);
- (id)andler: /* Error: Ran out of types for this method. */;
- (id);
- (id)Ñ;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(nonatomic) _Bool loggingEnabled; // @synthesize loggingEnabled=_loggingEnabled;
@property(readonly, nonatomic) NSMutableDictionary *metrics; // @synthesize metrics=_metrics;
@property(nonatomic) _Bool submitted; // @synthesize submitted=_submitted;
@property(readonly) Class superclass;

@end

