//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <coreroutine/RTNotification.h>

@class NSArray;

@interface RTPlaceInferenceUpdateNotification : RTNotification
{
    NSArray *_placeInferences;
}

- (id);
- (id);
- (void);
- (id)nationAddress:networkPrefixLength: /* Error: Ran out of types for this method. */;

// Remaining properties
@property(readonly, nonatomic) NSArray *placeInferences; // @synthesize placeInferences=_placeInferences;

@end

