//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSError, RTDistanceCalculator, RTLearnedLocationOfInterest, RTLocation;

@interface RTRegionToLocationOfInterestMatchingMetrics
{
    RTDistanceCalculator *_distanceCalculator;
    RTLocation *_region;
    RTLearnedLocationOfInterest *_locationOfInterest;
    NSError *_matchingError;
    unsigned long long _numberOfMatches;
}

+ (void);
- (id);
- (id);
- (id);
- (id)7
;
- (unsigned long long)T;
- (void);
- (id)nfo;
- (id);
- (void)uleBurstNoiseFilter identifyNoiseInWindowRange:] /* Error: Ran out of types for this method. */;

// Remaining properties
@property(readonly, nonatomic) RTLearnedLocationOfInterest *locationOfInterest; // @synthesize locationOfInterest=_locationOfInterest;
@property(readonly, nonatomic) NSError *matchingError; // @synthesize matchingError=_matchingError;
@property(readonly, nonatomic) unsigned long long numberOfMatches; // @synthesize numberOfMatches=_numberOfMatches;
@property(readonly, nonatomic) RTLocation *region; // @synthesize region=_region;

@end

