//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <coreroutine/RTService.h>

@class NSDate, NSString, RTDefaultsManager, RTTripClusterProcessor, RTTripClusterProcessorOptions, RTTripClusterRecencyStore, RTTripClusterRoadTransitionsDataStore, RTTripClusterRoadTransitionsStore, RTTripClusterRouteStore, RTTripClusterScheduleStore, RTTripClusterStore, RTTripClusterWaypointDataStore, RTTripSegment, RTTripSegmentManager;

@interface RTTripClusterManager : RTService
{
    double _accumulatedDistance;
    double _accumulatedDuration;
    NSDate *_multiModalStartDate;
    NSDate *_multiModalEndDate;
    RTTripSegment *_pendingDrivingTripSegment;
    _Bool _isClusterLearningInProgress;
    _Bool _clustersUnlockedAfterStartUp;
    _Bool _isTripSegmentClusteringEnabled;
    _Bool _shouldDeferClusterProcessing;
    RTTripSegmentManager *_tripSegmentManager;
    RTDefaultsManager *_defaultsManager;
    RTTripClusterProcessorOptions *_options;
    RTTripClusterProcessor *_tripClusterProcessor;
    RTTripClusterStore *_tripClusterStore;
    RTTripClusterRouteStore *_tripClusterRouteStore;
    RTTripClusterWaypointDataStore *_tripClusterWaypointStore;
    RTTripClusterRoadTransitionsDataStore *_tripClusterRouteRoadTransitionsStore;
    RTTripClusterRecencyStore *_tripClusterRecencyStore;
    RTTripClusterScheduleStore *_tripClusterScheduleStore;
    RTTripClusterRoadTransitionsStore *_tripSegmentRoadTransitionsStore;
}

+ (long long);
- (void);
- (void);
- (id);
- (id);
- (id);
- (id);
- (id);
- (id);
- (id);
- (_Bool);
- (void);
- (void);
- (void);
- (void);
- (void);
- (void);
- (void);
- (void);
- (void);
- (void);
- (void);
- (void);
- (_Bool);
- (void);
- (void);
- (int);
- (double);
- (void);
- (_Bool);
- (_Bool);
- (id);
- (void);
- (id);
- (void);
- (void);
- (id);
- (void);
- (_Bool);
- (id);
- (_Bool);
- (_Bool);
- (void);
- (void);
- (_Bool);
- (_Bool);
- (_Bool);
- (void);
- (void);
- (id);
- (id);
- (void);
- (void);
- (id);
- (unsigned long long);
- (void);
- (int);
- (int);
- (int);
- (int);
- (void);
- (id);
- (id);
- (void);
- (void);
- (void);
- (id);
- (id);
- (id);
- (void);
- (void);
- (void);
- (void);
- (void);
- (long long);
- (long long);
- (void);
- (id);
- (id);
- (void);
- (unsigned long long);
- (unsigned long long);
- (_Bool);
- (id);
- (int);
- (_Bool);
- (void);
- (void);
- (void);
- (void);
- (void);
- (id);
- (void);
- (void);
- (id);
- (void);
- (void)sing:(id)arg1 trainReason:currentPipelineError:enableTripSegmentProcessingOnBattery:handler: /* Error: Ran out of types for this method. */;
- (id)nagerTrainIgnoreDeferral;
- (void), %@, trainResult, %@;
- (void)avedRecords, %@, deletedRecordIDs, %@, operationError, %@;

// Remaining properties
@property(readonly, nonatomic) _Bool clustersUnlockedAfterStartUp; // @synthesize clustersUnlockedAfterStartUp=_clustersUnlockedAfterStartUp;
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(retain, nonatomic) RTDefaultsManager *defaultsManager; // @synthesize defaultsManager=_defaultsManager;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) _Bool isClusterLearningInProgress; // @synthesize isClusterLearningInProgress=_isClusterLearningInProgress;
@property _Bool isTripSegmentClusteringEnabled; // @synthesize isTripSegmentClusteringEnabled=_isTripSegmentClusteringEnabled;
@property(retain, nonatomic) RTTripClusterProcessorOptions *options; // @synthesize options=_options;
@property _Bool shouldDeferClusterProcessing; // @synthesize shouldDeferClusterProcessing=_shouldDeferClusterProcessing;
@property(readonly) Class superclass;
@property(retain, nonatomic) RTTripClusterProcessor *tripClusterProcessor; // @synthesize tripClusterProcessor=_tripClusterProcessor;
@property(retain, nonatomic) RTTripClusterRecencyStore *tripClusterRecencyStore; // @synthesize tripClusterRecencyStore=_tripClusterRecencyStore;
@property(retain, nonatomic) RTTripClusterRoadTransitionsDataStore *tripClusterRouteRoadTransitionsStore; // @synthesize tripClusterRouteRoadTransitionsStore=_tripClusterRouteRoadTransitionsStore;
@property(retain, nonatomic) RTTripClusterRouteStore *tripClusterRouteStore; // @synthesize tripClusterRouteStore=_tripClusterRouteStore;
@property(retain, nonatomic) RTTripClusterScheduleStore *tripClusterScheduleStore; // @synthesize tripClusterScheduleStore=_tripClusterScheduleStore;
@property(retain, nonatomic) RTTripClusterStore *tripClusterStore; // @synthesize tripClusterStore=_tripClusterStore;
@property(retain, nonatomic) RTTripClusterWaypointDataStore *tripClusterWaypointStore; // @synthesize tripClusterWaypointStore=_tripClusterWaypointStore;
@property(retain, nonatomic) RTTripSegmentManager *tripSegmentManager; // @synthesize tripSegmentManager=_tripSegmentManager;
@property(retain, nonatomic) RTTripClusterRoadTransitionsStore *tripSegmentRoadTransitionsStore; // @synthesize tripSegmentRoadTransitionsStore=_tripSegmentRoadTransitionsStore;

@end

