//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <coreroutine/RTService.h>

@class NSMutableArray, RTPersistentTimer, RTWiFiManager;

@interface RTWiFiFootprintMonitor : RTService
{
    long long _footprintState;
    RTPersistentTimer *_scanTimer;
    NSMutableArray *_scanResults;
    RTWiFiManager *_wifiManager;
}

+ (id);
- (void);
- (void);
- (id);
- (id);
- (void);
- (void);
- (id);
- (long long);
- (void);
- (void);
- (void);
- (void);
- (long long);
- (void);
- (void);
- (void);
- (void);
- (id)EIKEv2ConfigurationDelegate>";
- (id);
- (void)Cache appInfoForPid:(id)arg1 UUID:bundleID:completionHandler:] /* Error: Ran out of types for this method. */;
- (void);
- (void);
- (void)e}@, polygon centroid, %@, error, %@;
- (void)B@b5Ð[^À=
×£pV@vËªB@BË>¸P^ÀR¸ë}v@¹ÝË}¨B@°WXp?^ÀAµmä?;

// Remaining properties
@property(nonatomic) long long footprintState; // @synthesize footprintState=_footprintState;
@property(retain, nonatomic) NSMutableArray *scanResults; // @synthesize scanResults=_scanResults;
@property(retain, nonatomic) RTPersistentTimer *scanTimer; // @synthesize scanTimer=_scanTimer;
@property(retain, nonatomic) RTWiFiManager *wifiManager; // @synthesize wifiManager=_wifiManager;

@end

