//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSHashTable, NSObject, TUCallCenter;
@protocol OS_dispatch_queue;

@interface SMEmergencyCallManager
{
    NSObject<OS_dispatch_queue> *_queue;
    NSHashTable *_observers;
    TUCallCenter *_callCenter;
}

- (void);
- (void);
- (void);
- (void);
- (void);
- (_Bool);
- (id);
- (id);
- (void);
- (id)%ld - parsing sessionInfo:%@ /* Error: Ran out of types for this method. */;
- (void);
- (void);
- (void);
- (void)n for topic %@ keyID %@ version %u;
- (id);
- (void)冹;
- (void);
- (void), %@, error, %@;
- (void)fetched nil location.;

// Remaining properties
@property(retain, nonatomic) TUCallCenter *callCenter; // @synthesize callCenter=_callCenter;
@property(retain, nonatomic) NSHashTable *observers; // @synthesize observers=_observers;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;

@end

