//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <coreroutine/RTService.h>

@class RTDefaultsManager, RTDeviceLocationPredictor, SMSessionStore, SMSuggestionsStore;

@interface SMSuggestionsMetricsManager : RTService
{
    RTDefaultsManager *_defaultsManager;
    RTDeviceLocationPredictor *_deviceLocationPredictor;
    SMSessionStore *_sessionStore;
    SMSuggestionsStore *_suggestionsStore;
}

+ (id);
- (id)!@9J;
- (void);
- (void)(8 *H;
- (void);
- (id);
- (void);
- (id);
- (void);
- (void);
- (_Bool);
- (id);
- (id);
- (long long);
- (long long);
- (long long);
- (id);
- (id);
- (id);
- (id);
- (id);
- (id);
- (id);
- (id);
- (_Bool);
- (void);
- (void);
- (void);
- (void)for %@;
- (id);
- (void)ions:(id)arg1 offset:error:inManagedObjectContext: /* Error: Ran out of types for this method. */;
- (id);

// Remaining properties
@property(retain, nonatomic) RTDefaultsManager *defaultsManager; // @synthesize defaultsManager=_defaultsManager;
@property(retain, nonatomic) RTDeviceLocationPredictor *deviceLocationPredictor; // @synthesize deviceLocationPredictor=_deviceLocationPredictor;
@property(retain, nonatomic) SMSessionStore *sessionStore; // @synthesize sessionStore=_sessionStore;
@property(retain, nonatomic) SMSuggestionsStore *suggestionsStore; // @synthesize suggestionsStore=_suggestionsStore;

@end

