//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class DXTCEncoder {
public: // (access info unavailable from symbols alone)
    DXTCEncoder(CommonData const&);
    DXTCEncoder(CommonData const&)::once_control;
    auto CompressTexels(at_texel_region_t const&, at_block_buffer_t const&, float, at_flags_t) const;
    auto CompressTexels(at_texel_region_t const&, at_block_buffer_t const&, float, at_flags_t) const::kSRGBprimaries;
    auto DebugDescription(char*, unsigned long) const;
    auto DecompressTexels(at_block_buffer_t const&, at_texel_region_t const&, at_flags_t) const;
    auto GetBlockCounts(at_size_t) const;
    auto GetBlockDimensions() const;
    auto GetBlockFeaturesStatic(at_block_format_t, at_flags_t);
    auto GetBlockSize() const;
    auto GetEncoderType() const;
    auto GetHash() const;
    auto IsCompressionMonolithic(at_flags_t) const;
    auto IsDecompressionMonolithic(at_flags_t) const;
    auto operator==(ATEncoder const&) const;
    ~DXTCEncoder();
};
