//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleBacklightMath {
public: // (access info unavailable from symbols alone)
    AppleBacklightMath();
    auto binaryLogarithm(unsigned short);
    auto binlog(unsigned short);
    auto binpow(unsigned short);
    auto countLeadingZeroes(unsigned int);
    auto extractBits16(unsigned char const*, unsigned int, unsigned int);
    auto extractBits16(unsigned char const*, unsigned int, unsigned int) (.cold.1);
    auto getBOBPWM();
    auto getBacklightAttribute(unsigned int);
    auto getBacklightAttributeLinearCorrectionTable(unsigned int);
    auto getBrightnessIndexOverride(unsigned short);
    auto getDisplayConfigOverride(unsigned short);
    auto getIndexForRawBacklightValue(unsigned short);
    auto getMaxPWMScale();
    auto getMaxUsablePWM();
    auto getMinPWMScale();
    auto getMinUsablePWM();
    auto getRawBacklightForIndexValue(unsigned short);
    auto overrideBrightnessIndex(AppleDisplayOverrideBrightnessIndexOverride const*, unsigned short, bool, unsigned short);
    auto overrideBrightnessIndexLinearCorrection(unsigned short, bool, unsigned short);
    auto overrideBrightnessIndexTable(AppleDisplayOverrideBrightnessIndexOverride const*, unsigned short, bool);
    auto powerOfTwo(int);
    auto setBOBPWM(unsigned short);
    auto setBacklightAttributes(unsigned char const*, unsigned int, unsigned int);
    auto setDimmingRatio(unsigned short);
    auto setMaxUsablePWM(unsigned short);
    auto setMinUsablePWM(unsigned short);
};
