//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class icu::number::NumberFormatter {
public: // (access info unavailable from symbols alone)
    forSkeleton(icu::UnicodeString const&, UErrorCode&);
    forSkeleton(icu::UnicodeString const&, UParseError&, UErrorCode&);
    with();
    withLocale(icu::Locale const&);
};
