//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class icu::HinduLunarCalendar {
public: // (access info unavailable from symbols alone)
    HinduLunarCalendar(icu::HinduLunarCalendar const&);
    HinduLunarCalendar(icu::Locale const&, UErrorCode&);
    HinduLunarCalendar(icu::Locale const&, int, icu::TimeZone const*, UErrorCode&);
    add(UCalendarDateFields, int, UErrorCode&);
    add(icu::Calendar::EDateFields, int, UErrorCode&);
    amod(int, int) const;
    angle(int, int, double) const;
    clone() const;
    createInterval(int, int) const;
    defaultCenturyStart() const;
    defaultCenturyStartYear() const;
    fixedFromHinduLunar(icu::HinduDate) const;
    getBegin(std::__1::pair<double, double> const&) const;
    getDynamicClassID() const;
    getEnd(std::__1::pair<double, double> const&) const;
    getFieldResolutionTable() const;
    getHinduCalZoneAstroCalc() const;
    getHinduCalendarType() const;
    getMonthOffset() const;
    getStaticClassID();
    getType() const;
    getYearOffset() const;
    gregorianNewYear(int) const;
    gregorianYearRange(int) const;
    handleComputeFields(int, UErrorCode&);
    handleComputeMonthStart(int, int, signed char, UErrorCode&) const;
    handleComputeOrdinalDay(int);
    handleGetExtendedYear(UErrorCode&);
    handleGetLimit(UCalendarDateFields, icu::Calendar::ELimitType) const;
    handleGetMonthLength(int, int, UErrorCode&) const;
    haveDefaultCentury() const;
    hinduDate(int, int, bool, int, bool) const;
    hinduDayCount(int) const;
    hinduFullmoonFromFixed(int) const;
    hinduLunarFromFixed(int) const;
    hinduLunarNewYear(int) const;
    inDaylightTime(UErrorCode&) const;
    internalGetDefaultCenturyStart() const;
    internalGetDefaultCenturyStartYear() const;
    isInRange(double, std::__1::pair<double, double> const&) const;
    isLeapMonthBetween(int, int) const;
    listRange(std::__1::vector<int, std::__1::allocator<int>> const&, std::__1::pair<int, int> const&) const;
    mod3(double, double, double) const;
    modLisp(double, double) const;
    roll(UCalendarDateFields, int, UErrorCode&);
    roll(icu::Calendar::EDateFields, int, UErrorCode&);
    setLocation(icu::Angle const&, icu::Angle const&, int, double);
    ujjainOffset() const;
    ~HinduLunarCalendar();
};
