//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class icu::Edits {
public: // (access info unavailable from symbols alone)
    auto addReplace(int, int);
    auto addUnchanged(int);
    auto append(int);
    auto copyArray(icu::Edits const&);
    auto copyErrorTo(UErrorCode&) const;
    auto growArray();
    auto mergeAndAppend(icu::Edits const&, icu::Edits const&, UErrorCode&);
    auto moveArray(icu::Edits&);
    auto operator=(icu::Edits const&);
    auto operator=(icu::Edits&&);
    auto releaseArray();
    auto reset();
    ~Edits();
};
