//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class icu::UCharsTrie::Iterator {
public: // (access info unavailable from symbols alone)
    Iterator(icu::ConstChar16Ptr, int, UErrorCode&);
    Iterator(icu::UCharsTrie const&, int, UErrorCode&);
    branchNext(char16_t const*, int, UErrorCode&);
    hasNext() const;
    next(UErrorCode&);
    reset();
    ~Iterator();
};
