//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class icu::number::impl::MutablePatternModifier {
public: // (access info unavailable from symbols alone)
    MutablePatternModifier(bool);
    auto addToChain(icu::number::impl::MicroPropsGenerator const*);
    auto apply(icu::FormattedStringBuilder&, int, int, UErrorCode&) const;
    auto containsField(icu::FormattedStringBuilder::Field) const;
    auto createConstantModifier(UErrorCode&);
    auto createImmutable(UErrorCode&);
    auto createImmutableForPlural(icu::StandardPlural::Form, UErrorCode&);
    auto getCodePointCount() const;
    auto getCurrencySymbolForUnitWidth(UErrorCode&) const;
    auto getParameters(icu::number::impl::Modifier::Parameters&) const;
    auto getPrefixLength() const;
    auto getSymbol(icu::number::impl::AffixPatternType) const;
    auto insertPrefix(icu::FormattedStringBuilder&, int, UErrorCode&);
    auto insertSuffix(icu::FormattedStringBuilder&, int, UErrorCode&);
    auto isStrong() const;
    auto needsPlurals() const;
    auto prepareAffix(bool);
    auto processQuantity(icu::number::impl::DecimalQuantity&, icu::number::impl::MicroProps&, UErrorCode&) const;
    auto setNumberProperties(icu::number::impl::Signum, icu::StandardPlural::Form);
    auto setPatternAttributes(UNumberSignDisplay, bool, bool);
    auto setPatternInfo(icu::number::impl::AffixPatternProvider const*, icu::FormattedStringBuilder::Field);
    auto setSymbols(icu::DecimalFormatSymbols const*, icu::CurrencyUnit const&, UNumberUnitWidth, icu::PluralRules const*, UErrorCode&);
    auto strictEquals(icu::number::impl::Modifier const&) const;
    auto toUnicodeString() const;
    non-virtual thunk to apply(icu::FormattedStringBuilder&, int, int, UErrorCode&) const;
    non-virtual thunk to containsField(icu::FormattedStringBuilder::Field) const;
    non-virtual thunk to getCodePointCount() const;
    non-virtual thunk to getParameters(icu::number::impl::Modifier::Parameters&) const;
    non-virtual thunk to getPrefixLength() const;
    non-virtual thunk to getSymbol(icu::number::impl::AffixPatternType) const;
    non-virtual thunk to isStrong() const;
    non-virtual thunk to strictEquals(icu::number::impl::Modifier const&) const;
};
