//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class icu::UTF16CollationIterator {
public: // (access info unavailable from symbols alone)
    UTF16CollationIterator(icu::UTF16CollationIterator const&, char16_t const*);
    auto backwardNumCodePoints(int, UErrorCode&);
    auto forwardNumCodePoints(int, UErrorCode&);
    auto foundNULTerminator();
    auto getOffset() const;
    auto handleGetTrailSurrogate();
    auto handleNextCE32(int&, UErrorCode&);
    auto nextCodePoint(UErrorCode&);
    auto operator==(icu::CollationIterator const&) const;
    auto previousCodePoint(UErrorCode&);
    auto resetToOffset(int);
    ~UTF16CollationIterator();
};
