//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AMDRadeonX6000_AmdRadeonControllerNavi10 {
public: // (access info unavailable from symbols alone)
    AMDRadeonX6000_AmdRadeonControllerNavi10();
    AMDRadeonX6000_AmdRadeonControllerNavi10(OSMetaClass const*);
    auto createControllerCoreServices();
    auto createControllerServices();
    auto free();
    auto getMetaClass() const;
    auto probe(IOService*, int*);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~AMDRadeonX6000_AmdRadeonControllerNavi10();
};
