//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AMDRadeonX6000_AmdLinkedListIterator {
public: // (access info unavailable from symbols alone)
    AMDRadeonX6000_AmdLinkedListIterator();
    AMDRadeonX6000_AmdLinkedListIterator(OSMetaClass const*);
    getMetaClass() const;
    getNext();
    init();
    ~AMDRadeonX6000_AmdLinkedListIterator();
};
