//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AMDRadeonX6000_AmdAsicInfoNavi {
public: // (access info unavailable from symbols alone)
    AMDRadeonX6000_AmdAsicInfoNavi(OSMetaClass const*);
    getCapability(AsicCapabilitySelector) const;
    getDscCapability(AGDCGPUDSCCapability_t*) const;
    getMetaClass() const;
    getTimingRange(IODisplayTimingRangeV2&) const;
    populateDeviceInfo();
    populateFbLocation();
    populateMemorySize();
    ~AMDRadeonX6000_AmdAsicInfoNavi();
};
