//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AMDRadeonX6000_AmdHdcpAuthFailInterrupt {
public: // (access info unavailable from symbols alone)
    AMDRadeonX6000_AmdHdcpAuthFailInterrupt();
    AMDRadeonX6000_AmdHdcpAuthFailInterrupt(OSMetaClass const*);
    callbackHandler(OSObject*, void*);
    deferredInterruptHandler(OSObject*, IOInterruptEventSource*, int);
    getMetaClass() const;
    handle(void*);
    initWithController(InterruptInfo*, AMDRadeonX6000_IAmdRadeonController*);
    initialize();
    isDefaultOn();
    ~AMDRadeonX6000_AmdHdcpAuthFailInterrupt();
};
