//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOAHCIDevice {
public: // (access info unavailable from symbols alone)
    IOAHCIDevice();
    IOAHCIDevice(OSMetaClass const*);
    auto CompleteRequest(OSObject*);
    auto CompleteRequest(OSObject*) (.cold.1);
    auto Create(unsigned int, unsigned int);
    auto Destroy();
    auto DisableLinkPowerManagement();
    auto EnableLinkPowerManagement();
    auto ExecuteRequest(IOSerialATARequestFIS*);
    auto FreeAHCIRequest(OSObject*);
    auto GetAHCIDataPointer();
    auto GetAHCIDataSize();
    auto GetAHCIRequest(bool);
    auto GetDevicePort();
    auto GetPortLinkPowerManagement();
    auto ReleaseTag(unsigned int);
    auto RemoveDeviceProperty(char const*);
    auto RequestTag();
    auto SetAHCIRequestCount(unsigned int);
    auto SetDeviceProperty(char const*, OSObject*);
    auto SetInitialDeviceProperties(OSDictionary*);
    auto SetRecoveryState(bool);
    auto attach(IOService*);
    auto detach(IOService*);
    auto didTerminate(IOService*, unsigned int, bool*);
    auto free();
    auto getMetaClass() const;
    auto handleClose(IOService*, unsigned int);
    auto handleOpen(IOService*, unsigned int, void*);
    auto init(OSDictionary*);
    auto matchPropertyTable(OSDictionary*, int*);
    auto message(unsigned int, IOService*, void*);
    auto start(IOService*);
    auto stop(IOService*);
    auto terminate(unsigned int);
    auto willTerminate(IOService*, unsigned int);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~IOAHCIDevice();
};
