//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOHIDUserDevice {
public: // (access info unavailable from symbols alone)
    IOHIDUserDevice();
    IOHIDUserDevice(OSMetaClass const*);
    auto free();
    auto getMetaClass() const;
    auto getReport(IOMemoryDescriptor*, IOHIDReportType, unsigned int);
    auto getReport(IOMemoryDescriptor*, IOHIDReportType, unsigned int, unsigned int, IOHIDCompletion*);
    auto handleStart(IOService*);
    auto handleStop(IOService*);
    auto initWithProperties(OSDictionary*);
    auto newCountryCodeNumber() const;
    auto newLocationIDNumber() const;
    auto newManufacturerString() const;
    auto newProductIDNumber() const;
    auto newProductString() const;
    auto newReportDescriptor(IOMemoryDescriptor**) const;
    auto newReportIntervalNumber() const;
    auto newSerialNumberString() const;
    auto newTransportString() const;
    auto newVendorIDNumber() const;
    auto newVendorIDSourceNumber() const;
    auto newVersionNumber() const;
    auto setReport(IOMemoryDescriptor*, IOHIDReportType, unsigned int);
    auto setReport(IOMemoryDescriptor*, IOHIDReportType, unsigned int, unsigned int, IOHIDCompletion*);
    auto withProperties(OSDictionary*);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~IOHIDUserDevice();
};
