//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOHIDEventServiceFastPathUserClient {
public: // (access info unavailable from symbols alone)
    IOHIDEventServiceFastPathUserClient();
    IOHIDEventServiceFastPathUserClient(OSMetaClass const*);
    _close(IOHIDEventServiceFastPathUserClient*, void*, IOExternalMethodArguments*);
    _copyEvent(IOHIDEventServiceFastPathUserClient*, void*, IOExternalMethodArguments*);
    _copyEvent(IOHIDEventServiceFastPathUserClient*, void*, IOExternalMethodArguments*)::_os_log_fmt;
    _open(IOHIDEventServiceFastPathUserClient*, void*, IOExternalMethodArguments*);
    clientClose();
    clientMemoryForType(unsigned int, unsigned int*, IOMemoryDescriptor**);
    clientMemoryForTypeGated(unsigned int*, IOMemoryDescriptor**);
    close();
    copyEvent(OSObject*, unsigned int);
    copyProperty(char const*) const;
    copyPropertyGated(char const*, OSObject**) const;
    didTerminate(IOService*, unsigned int, bool*);
    externalMethod(unsigned int, IOExternalMethodArgumentsOpaque*);
    externalMethodGated(IOHIDEventServiceFastPathUserClient::ExternalMethodGatedArguments*);
    free();
    getMetaClass() const;
    getService();
    getSharedMemorySize();
    initWithTask(task*, void*, unsigned int);
    initWithTask(task*, void*, unsigned int) (.cold.1);
    initWithTask(task*, void*, unsigned int)::_os_log_fmt;
    message(unsigned int, IOService*, void*);
    message(unsigned int, IOService*, void*)::'block-literal'::_os_log_fmt;
    message(unsigned int, IOService*, void*)::_os_log_fmt;
    open(unsigned int, OSDictionary*);
    open(unsigned int, OSDictionary*)::_os_log_fmt;
    serializeDebugState(void*, OSSerialize*);
    setProperties(OSObject*);
    setPropertiesGated(OSObject*);
    start(IOService*);
    stop(IOService*);
    ~IOHIDEventServiceFastPathUserClient();
};
