//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class libkern::intrusive_shared_ptr<IOSharedDataQueue, intrusive_osobject_retainer> {
public: // (access info unavailable from symbols alone)
    get() const &;
    intrusive_shared_ptr();
    operator->() const;
    operator=(libkern::intrusive_shared_ptr<IOSharedDataQueue, intrusive_osobject_retainer>&&);
    reset();
    reset(IOSharedDataQueue*, libkern::no_retain_t);
};
