//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class OSSharedPtr<OSSymbol const> {
public: // (access info unavailable from symbols alone)
    OSSharedPtr(std::nullptr_t);
    operator=(OSSharedPtr<OSSymbol const>&&);
    ~OSSharedPtr();
};
