//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleEFIRuntime {
public: // (access info unavailable from symbols alone)
    AppleEFIRuntime();
    AppleEFIRuntime(OSMetaClass const*);
    __OSFinalClass();
    attachCoreAnalyticsService(void*, IOService*, IONotifier*);
    callEFIRuntime(unsigned int (*)(void*, void*, void*, void*, void*, void*), void*, void*, void*, void*, void*, void*) const;
    getConfigurationTable(EFI_GUID*, void**);
    getMetaClass() const;
    getNextHighMonotonicCount(unsigned int*);
    getNextVariableName(unsigned int*, short*, EFI_GUID*) const;
    getTime(EFI_TIME*, EFI_TIME_CAPABILITIES*) const;
    getVariable(short const*, EFI_GUID const*, unsigned int*, unsigned int*, void*) const;
    getWakeupTime(unsigned char*, unsigned char*, EFI_TIME*) const;
    readSpiFlash(unsigned long long, unsigned int, unsigned int, unsigned char*);
    resetSystem(EFI_RESET_TYPE, unsigned int, unsigned int, short*);
    setTime(EFI_TIME*);
    setVariable(short const*, EFI_GUID const*, unsigned int, unsigned int, void const*);
    setWakeupTime(unsigned char, EFI_TIME*);
    start(IOService*);
    ~AppleEFIRuntime();
};
