//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class KDIFileBackingStore {
public: // (access info unavailable from symbols alone)
    KDIFileBackingStore();
    KDIFileBackingStore(OSMetaClass const*);
    auto _handleStart(IOService*);
    auto _handleStop(IOService*);
    auto flush();
    auto getMetaClass() const;
    auto getUserVnode(OSObject*, vfs_context*);
    auto init(OSDictionary*);
    auto probe(IOService*, int*);
    auto putUserVnode();
    auto readBytes(long long, unsigned long, unsigned long*, void*, bool);
    auto reportEOF(long long*);
    auto reportResizable(bool*);
    auto setEOF(long long);
    auto writeBytes(long long, unsigned long, unsigned long*, void const*, bool);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~KDIFileBackingStore();
};
