//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class std::__1::allocate_shared[abi:ne200100]<std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>, std::__1::allocator<std::__1::vector<unsigned char, std::__1 {
public: // (access info unavailable from symbols alone)
    allocator<unsigned char>>>, unsigned char const*, unsigned char const*, 0>(std::__1::allocator<std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>> const&, unsigned char const*&&, unsigned char const*&&);
};
