//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class axis::MedialAxis {
public: // (access info unavailable from symbols alone)
    auto compute_simplified_medial_axis(std::__1::shared_ptr<axis::Polygon2D>, double, double);
};
