//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class axis::SpatialPredicates {
public: // (access info unavailable from symbols alone)
    auto contains(axis::Geometry2D const&, axis::Geometry2D const&, double);
    auto covered_by(axis::Geometry2D const&, axis::Geometry2D const&, double);
    auto covers(axis::Geometry2D const&, axis::Geometry2D const&, double);
    auto crosses(axis::Geometry2D const&, axis::Geometry2D const&, double);
    auto disjoint(axis::Geometry2D const&, axis::Geometry2D const&, double);
    auto equals(axis::Geometry2D const&, axis::Geometry2D const&, double);
    auto get_de9im(axis::Geometry2D const&, axis::Geometry2D const&, double);
    auto intersects(axis::BBox2D const&, axis::BBox2D const&, double);
    auto intersects(axis::BBox2D const&, axis::Geometry2D const&, double);
    auto intersects(axis::BBox2D const&, axis::LineSeg2D const&, double);
    auto intersects(axis::Geometry2D const&, axis::BBox2D const&, double);
    auto intersects(axis::Geometry2D const&, axis::Geometry2D const&, double);
    auto intersects(axis::LineSeg2D const&, axis::BBox2D const&, double);
    auto is_self_intersecting(axis::Geometry2D const&);
    auto overlaps(axis::Geometry2D const&, axis::Geometry2D const&, double);
    auto relate(axis::Geometry2D const&, axis::Geometry2D const&, axis::DE9IM const&, double);
    auto relate(axis::Geometry2D const&, axis::Geometry2D const&, std::__1::vector<axis::DE9IM, std::__1::allocator<axis::DE9IM>> const&, double);
    auto touches(axis::Geometry2D const&, axis::Geometry2D const&, double);
    auto within(axis::Geometry2D const&, axis::Geometry2D const&, double);
};
