//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class std::bad_array_new_length {
public: // (access info unavailable from symbols alone)
    bad_array_new_length();
    ~bad_array_new_length();
};
