//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension SwiftTLSLibrary.ImportedPSK {
    __derived_struct_equals(SwiftTLSLibrary.ImportedPSK, SwiftTLSLibrary.ImportedPSK) -> Swift.Bool
    init(importedIdentity: SwiftTLSLibrary.ImportedIdentity, ipskx: CryptoKit.SymmetricKey) -> SwiftTLSLibrary.ImportedPSK
}
