//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension SwiftTLSLibrary.ServerHandshakeState {
    receivedClientFinished(_: SwiftTLSLibrary.FinishedMessage, bytes: SwiftTLSLibrary.ByteBuffer) throws(SwiftTLSLibrary.TLSError) -> SwiftTLSLibrary.PartialHandshakeResult
    receivedClientHello(_: SwiftTLSLibrary.ClientHello, bytes: SwiftTLSLibrary.ByteBuffer) throws(SwiftTLSLibrary.TLSError) -> Swift.Optional<SwiftTLSLibrary.PartialHandshakeResult>
    sendingServerCertificate() throws(SwiftTLSLibrary.TLSError) -> SwiftTLSLibrary.PartialHandshakeResult
    sendingServerCertificateVerify() throws(SwiftTLSLibrary.TLSError) -> SwiftTLSLibrary.PartialHandshakeResult
    sendingServerEncryptedExtensions(SwiftTLSLibrary.EncryptedExtensions) throws(SwiftTLSLibrary.TLSError) -> SwiftTLSLibrary.PartialHandshakeResult
    sendingServerFinished() throws(SwiftTLSLibrary.TLSError) -> SwiftTLSLibrary.PartialHandshakeResult
    sendingServerHello(inout SwiftTLSLibrary.ServerHello) throws(SwiftTLSLibrary.TLSError) -> SwiftTLSLibrary.PartialHandshakeResult
}
