//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleTDMControlLUN {
public: // (access info unavailable from symbols alone)
    AppleTDMControlLUN();
    AppleTDMControlLUN(OSMetaClass const*);
    auto BatteryStatusTimerCallback(IOTimerEventSource*);
    auto ConnectedViaUSB();
    auto DisableBatteryStatusPolling();
    auto EnableBatteryStatusPolling();
    auto GetAndSetPowerRequirement();
    auto GetBatteryStatus(unsigned char*, unsigned char);
    auto GetEVPDINQUIRYData(IOMemoryDescriptor*, unsigned char, unsigned short);
    auto GetInitialPowerState();
    auto GetNumberOfPowerStateTransitions();
    auto HandleCheckPowerState();
    auto HandlePowerChange();
    auto HandlePowerChange() (.cold.1);
    auto InitializePowerManagement(IOService*);
    auto MessageAppleTDMType00Objects(unsigned int, void*);
    auto ReconditionTarget();
    auto SendControlRequest(unsigned short, unsigned char, unsigned char);
    auto SendTargetReconditionCommand(unsigned char, unsigned char);
    auto SetProvisionedPower(unsigned int);
    auto SetupBatteryStatusPolling();
    auto StartDeviceSupport();
    auto TicklePowerManager();
    auto free();
    auto getMetaClass() const;
    auto setProperties(OSObject*);
    auto start(IOService*);
    auto willTerminate(IOService*, unsigned int);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~AppleTDMControlLUN();
};
