//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleTDMAKSCommand {
public: // (access info unavailable from symbols alone)
    AppleTDMAKSCommand();
    AppleTDMAKSCommand(OSMetaClass const*);
    auto Create(IOService*, unsigned short);
    auto getMetaClass() const;
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~AppleTDMAKSCommand();
};
