//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension Runtime.X86_64Context.framePointer {
    getter : Swift.UInt64
    modify : Swift.UInt64
    modify : Swift.UInt64 with unmangled suffix ".resume.0"
    setter : Swift.UInt64
}
