//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleUSBXHCIRequestPool {
public: // (access info unavailable from symbols alone)
    AppleUSBXHCIRequestPool();
    AppleUSBXHCIRequestPool(OSMetaClass const*);
    auto allocateCommand();
    auto free();
    auto getMetaClass() const;
    auto initWithWorkLoopAndController(IOWorkLoop*, AppleUSBXHCI*);
    auto withWorkLoopAndController(IOWorkLoop*, AppleUSBXHCI*);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~AppleUSBXHCIRequestPool();
};
