//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AtiAppleMcilServices {
public: // (access info unavailable from symbols alone)
    AtiAppleMcilServices(PP_Instance*, void*);
    AtiAppleMcilServices(PP_Instance*, void*)::PPLIB_IRI_REGISTERY_NAME;
    allocateMemory(void*, _MCIL_MEMBLOCK_INFO*);
    assertInterrupt(void*, _MCIL_IRQ_ASSERT_INTERRUPT_INFO*);
    callPPLibIri(_IRI_CALL_INPUT*, _IRI_CALL_OUTPUT*);
    copyMemory(void*, _MCIL_COPYMEM_INFO*);
    debugPrint(unsigned int, char const*, ...);
    delayInMicroseconds(void*, unsigned int);
    dummyCallBack();
    eRecordErrorMessage(void*, _MCIL_ERECORD_ERROR_MESSAGE_INFO*);
    eRecordSystemAccess(void*, _MCIL_ERECORD_SYSTEM_ACCESS_INFO*);
    executeBiosTable(void*, _MCIL_BIOSTABLE_INFO*);
    fillServiceCallbacks(void*, _MCIL_SERVICE_CALLBACKS*);
    getCallbacks();
    getPPLibIri();
    getPciConfigData(void*, _MCIL_PCICONFIG_DATA*);
    getRegistryKey(void*, _MCIL_REGISTRY_INFO*);
    gpuPowerControl(void*, void*);
    modifyRegister(void*, _MCIL_MODIFYREGISTER_INFO*);
    notifyEvent(void*, _MCIL_NOTIFYMODECHANGE_INFO*);
    obtainIri(void*, _MCIL_IRI_OBTAIN_INPUT*, _MCIL_IRI_OBTAIN_OUTPUT*);
    obtainIri(void*, _MCIL_IRI_OBTAIN_INPUT*, _MCIL_IRI_OBTAIN_OUTPUT*)::CAIL_IRI_REGISTERY_NAME;
    obtainIri(void*, _MCIL_IRI_OBTAIN_INPUT*, _MCIL_IRI_OBTAIN_OUTPUT*)::IRI_STR;
    queryPPLibIri(unsigned int, void*, unsigned int);
    querySystemInfo(void*, _MCIL_SYSTEM_INFO*);
    queryTableRevision(void*, _MCIL_BIOSTABLE_INFO*);
    readRomImage(void*, _MCIL_DATA_INFO*);
    releaseIri(void*, _IRI_RELEASE_INPUT*);
    releaseMemory(void*, _MCIL_MEMBLOCK_INFO*);
    setMessageCode(void*, _MCIL_MESSAGE_INFO*);
    setPciConfigData(void*, _MCIL_PCICONFIG_DATA*);
    setRegistryKey(void*, _MCIL_REGISTRY_INFO*);
    sleepInMilliseconds(void*, unsigned int);
    syncExecution(void*, _MCIL_SYNEXECUTION_INFO*);
    systemTimestamp(void*, _MCIL_SYSTEMTIMESTAMP_INFO*);
    systemTimestamp(void*, _MCIL_SYSTEMTIMESTAMP_INFO*)::OUTPUT_TIME_FORMAT_MASK;
    waitFor(void*, _MCIL_WAITFOR_INFO*);
    waitForGUIIdle(void*);
    waitForMCIdle(void*);
    zeroMemory(void*, _MCIL_ZEROMEM_INFO*);
};
