//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleVTD {
public: // (access info unavailable from symbols alone)
    AppleVTD();
    AppleVTD(OSMetaClass const*);
    addMemoryRange(unsigned long long, unsigned long long);
    addMemoryRange(unsigned long long, unsigned long long)::'block-literal'::_os_log_fmt;
    adjustDevice(IOService*);
    adjustDevice(IOService*)::_os_log_fmt;
    callPlatformFunction(OSSymbol const*, bool, void*, void*, void*, void*);
    checkFree(vtd_space*, unsigned int);
    contextInvalidate(unsigned short);
    contextInvalidate(unsigned short) (.cold.1);
    deviceMapperActivate(AppleVTDDeviceMapper*, unsigned int);
    deviceMapperActivate(AppleVTDDeviceMapper*, unsigned int)::_os_log_fmt;
    free();
    free()::kalloc_type_view_855;
    getMetaClass() const;
    getPageSize() const;
    handleFault(IOInterruptEventSource*, int);
    handleInterrupt(IOInterruptEventSource*, int);
    init(IOWorkLoop*, OSData const*);
    init(IOWorkLoop*, OSData const*)::_os_log_fmt;
    initHardware(IOService*);
    initHardware(IOService*) (.cold.1);
    initHardware(IOService*) (.cold.2);
    initHardware(IOService*)::_os_log_fmt;
    initHardware(IOService*)::kalloc_type_view_1502;
    install(IOWorkLoop*, unsigned int, IOService*, OSData const*, IOPCIMessagedInterruptController*);
    install(IOWorkLoop*, unsigned int, IOService*, OSData const*, IOPCIMessagedInterruptController*)::_os_log_fmt;
    installInterrupts();
    interruptInvalidate(unsigned short, unsigned short);
    interruptInvalidate(unsigned short, unsigned short) (.cold.1);
    iovmInsert(unsigned int, unsigned long long, unsigned long long, unsigned long long, unsigned long long);
    iovmMapMemory(IOMemoryDescriptor*, unsigned long long, unsigned long long, unsigned int, IODMAMapSpecification const*, IODMACommand*, IODMAMapPageList const*, unsigned long long*, unsigned long long*);
    iovmUnmapMemory(IOMemoryDescriptor*, IODMACommand*, unsigned long long, unsigned long long);
    mapToPhysicalAddress(unsigned long long);
    newContextPage(unsigned int);
    newContextPage(unsigned int) (.cold.1);
    relocateDevice(IOService*, bool);
    removeDevice(IOService*);
    reserveRanges(vtd_space*, bool);
    reserveRanges(vtd_space*, bool)::_os_log_fmt;
    spaceInsert(vtd_space*, unsigned int, unsigned long long, unsigned long long, unsigned long long, unsigned long long);
    spaceMapMemory(vtd_space*, IOMemoryDescriptor*, unsigned long long, unsigned long long, unsigned int, IODMAMapSpecification const*, IODMACommand*, IODMAMapPageList const*, unsigned long long*, unsigned long long*);
    spaceMapToPhysicalAddress(vtd_space*, unsigned long long);
    spaceUnmapMemory(vtd_space*, IOMemoryDescriptor*, IODMACommand*, unsigned long long, unsigned long long);
    spaceUnmapMemory(vtd_space*, IOMemoryDescriptor*, IODMACommand*, unsigned long long, unsigned long long) (.cold.1);
    space_alloc(vtd_space*, unsigned int, unsigned int, unsigned int, IODMAMapSpecification const*, upl_page_info const*);
    space_alloc(vtd_space*, unsigned int, unsigned int, unsigned int, IODMAMapSpecification const*, upl_page_info const*)::_os_log_fmt;
    space_alloc_fixed(vtd_space*, unsigned int, unsigned int, bool);
    space_create(unsigned int, unsigned int, unsigned int);
    space_create(unsigned int, unsigned int, unsigned int) (.cold.1);
    space_create(unsigned int, unsigned int, unsigned int) (.cold.2);
    space_create(unsigned int, unsigned int, unsigned int)::_os_log_fmt;
    space_create(unsigned int, unsigned int, unsigned int)::kalloc_type_view_960;
    space_destroy(vtd_space*);
    space_destroy(vtd_space*)::kalloc_type_view_936;
    space_free(vtd_space*, unsigned int, unsigned int);
    timer(OSObject*, IOTimerEventSource*);
    ~AppleVTD();
};
