//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleNVMeRequestTimer {
public: // (access info unavailable from symbols alone)
    AppleNVMeRequestTimer();
    AppleNVMeRequestTimer(OSMetaClass const*);
    auto CompareDeadlines(unsigned long long, unsigned long long);
    auto CreateTimerEventSource(OSObject*, void (*)(OSObject*, IOTimerEventSource*), unsigned int);
    auto CreateTimerEventSource(OSObject*, void (*)(OSObject*, IOTimerEventSource*), unsigned int) (.cold.1);
    auto CreateTimerEventSource(OSObject*, void (*)(OSObject*, IOTimerEventSource*), unsigned int) (.cold.2);
    auto DisableRequestTimer();
    auto EnableRequestTimer(bool);
    auto EnableRequestTimer(bool) (.cold.1);
    auto EnableRequestTimer(bool) (.cold.2);
    auto ExtendDeadline(AppleNVMeRequest*, unsigned int);
    auto GetTimeoutValue();
    auto Init(OSObject*, void (*)(OSObject*, IOTimerEventSource*), unsigned int);
    auto SetRequestDeadline(AppleNVMeRequest*);
    auto SetRequestDeadline(AppleNVMeRequest*) (.cold.1);
    auto SetTimeoutValue(unsigned int);
    auto free();
    auto getMetaClass() const;
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~AppleNVMeRequestTimer();
};
