//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IODiskImageBlockStorageDeviceInKernel {
public: // (access info unavailable from symbols alone)
    IODiskImageBlockStorageDeviceInKernel();
    IODiskImageBlockStorageDeviceInKernel(OSMetaClass const*);
    attach(IOService*);
    getMetaClass() const;
    ~IODiskImageBlockStorageDeviceInKernel();
};
