//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class KDIDiskImage {
public: // (access info unavailable from symbols alone)
    KDIDiskImage(OSMetaClass const*);
    _handleAttach(IOService*);
    _handleDetach(IOService*);
    _handleStart(IOService*);
    checksumsMatch(HDIChecksumStruct*, HDIChecksumStruct*);
    enableCache(bool);
    flush();
    getBackingStore();
    getMetaClass() const;
    init(OSDictionary*);
    readSectorChunk(long long, long long*, long long*, void**, bool);
    readSectors(long long, long long, long long*, void*, bool);
    reportRemovable(bool*);
    reportSectorCount(long long*);
    reportStoredChecksum(HDIChecksumStruct*);
    reportWriteProtection(bool*);
    setUnmatchable(bool);
    writeSectors(long long, long long, long long*, void const*, bool);
    ~KDIDiskImage();
};
