//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension Metal {
    MTLCopyAllDevicesWithObserver(handler: (__C.MTLDevice, __C.MTLDeviceNotificationName) -> ()) -> (devices: Swift.Array<__C.MTLDevice>, observer: __C.NSObject)
    MTLIOCreateCompressionContext(Swift.String, __C.MTLIOCompressionMethod, Swift.Int) -> Swift.Optional<Swift.UnsafeMutableRawPointer>
}
