//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@protocol NSObject
- (id)B;
- (unsigned long long)@?32;
- (_Bool)@;
- (unsigned long long)Acknowledgement;
- (_Bool)socialHighlightCacheTimeoutInterval;
- (_Bool);
- (_Bool);
- (struct _NSZone *)kMDItemCopyright;

// Remaining properties
@property(readonly) unsigned long long hash;
@end

