//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension _RegexParser.Diagnostic.Behavior {
    == infix(_RegexParser.Diagnostic.Behavior, _RegexParser.Diagnostic.Behavior) -> Swift.Bool
    hash(into: inout Swift.Hasher) -> ()
}
