//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class hashtable<char const*, pair<char const*, char const*>, &hash_str(char const* const&), str_equal_to, _extract_first<pair<char const*, char const*>, char const*>> {
public: // (access info unavailable from symbols alone)
    auto clear();
    auto find(char const* const&);
    auto find_or_insert(char const* const&);
    auto grow(unsigned long);
    auto insert_internal(pair<char const*, char const*> const&, unsigned long);
    ~hashtable();
};
