//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class ioreq_ent {
public: // (access info unavailable from symbols alone)
    auto clip(ioreq_ent const*, ioreq_ent**, ioreq_ent**, ioreq_ent**, ioreq_ent**, ioreq_ent*);
    auto merge(ioreq_ent const*);
    auto mergeable(ioreq_ent const*, bool*) const;
    auto print(char const*) const;
};
