//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class space_allocator {
public: // (access info unavailable from symbols alone)
    auto add_extent_for_trim(phy_ext_addr, unsigned long long);
    auto add_space(unsigned int, tx*, unsigned long long, unsigned long long, int, vector<pv_reservation>*);
    auto alloc_blks(vector<pv_reservation>&, tx*, unsigned int*, unsigned long long*, unsigned long long*, backref_info const*, int);
    auto alloc_blks_contig_high_int(pv_node*, unsigned long long, unsigned long long&, unsigned long long&, int);
    auto alloc_blks_contig_int(pv_node*, unsigned long long, unsigned long long, unsigned long long*, unsigned long long*, int);
    auto alloc_blks_contig_low_int(pv_node*, unsigned long long, unsigned long long&, unsigned long long&, unsigned long long, int);
    auto alloc_blks_largest(unsigned int, tx*, unsigned long long*, unsigned long long*, backref_info const*, int);
    auto alloc_blks_mod_len(unsigned int, tx*, unsigned long long, unsigned long long, unsigned int*, unsigned long long*, unsigned long long*, backref_info const*, int);
    auto alloc_blks_offset(unsigned int, tx*, unsigned long long, unsigned long long, backref_info const*, int);
    auto alloc_blks_offset_int(pv_node*, unsigned long long*, unsigned long long, int);
    auto alloc_blks_pv_mod_len(unsigned int, tx*, unsigned long long, unsigned long long, unsigned long long*, unsigned long long*, backref_info const*, int);
    auto alloc_blks_pv_mod_len_int(unsigned int, tx*, unsigned long long, unsigned long long, unsigned long long*, unsigned long long*, backref_info const*, int);
    auto alloc_blks_pv_nextfree(unsigned int, unsigned long long, unsigned long long, unsigned long long*, unsigned long long*);
    auto alloc_blks_pv_zoned(unsigned int, tx*, unsigned long long, unsigned long long, unsigned long long*, unsigned long long*, backref_info const*, int);
    auto alloc_blks_pv_zoned(unsigned int, tx*, unsigned long long, unsigned long long, unsigned long long*, unsigned long long*, backref_info const*, int)::map_rehash_funcs;
    auto alloc_blks_zoned(unsigned int, tx*, unsigned long long, unsigned long long, unsigned int*, unsigned long long*, unsigned long long*, backref_info const*, int);
    auto alloc_blks_zoned_any(unsigned int, tx*, unsigned long long, unsigned long long, unsigned int*, unsigned long long*, unsigned long long*, backref_info const*, int);
    auto commit_blks(unsigned int, tx*, unsigned long long, unsigned long long, bool, backref_info const*);
    auto commit_blks_int(pv_node*, tx*, unsigned long long, unsigned long long, bool, backref_info const*);
    auto create_chunk(unsigned int, unsigned int);
    auto create_chunk_int(pv_node*, unsigned int);
    auto create_pv(unsigned int);
    auto create_pvg(unsigned int);
    auto destroy_chunk(unsigned int, unsigned int);
    auto destroy_pv(unsigned int);
    auto destroy_pvg(unsigned int);
    auto free_blks(unsigned int, tx*, unsigned long long, unsigned long long, vector<pv_reservation>*, int);
    auto free_ext_list(vector<phy_ext> const&, tx*);
    auto freeze_extents(unsigned int, unsigned long long, unsigned long long);
    auto frozen_query(unsigned int, unsigned long long*, unsigned long long*);
    auto get_pv(unsigned int);
    auto get_pv_backref_tree(unsigned int);
    auto get_pv_freespace(unsigned int, unsigned int);
    auto get_pvg(unsigned int);
    auto grow_space(pv_node*, tx*, unsigned long long);
    auto insert_pvge(unsigned int, unsigned int);
    auto is_free_ext(unsigned int, unsigned long long, unsigned long long, bool*);
    auto iterate_free_space(unsigned int, int (*)(pv_node*, chunk_node*, fe_node*, void*), void*, int);
    auto iterate_free_space_int(pv_node*, unsigned long long, int (*)(pv_node*, chunk_node*, fe_node*, void*), void*, int);
    auto iterate_free_space_reverse(unsigned int, int (*)(pv_node*, chunk_node*, fe_node*, void*), void*, int);
    auto list_free_ext(unsigned long);
    auto load_flog(unsigned int, unsigned int);
    auto load_flog_int(pv_node*, chunk_node*, bool*);
    auto notify_cpdk_alg(unsigned int, unsigned long long, unsigned long long, bool);
    auto populate();
    auto remove_extent_for_trim(phy_ext_addr, unsigned long long);
    auto remove_pvge(unsigned int, unsigned int);
    auto reserve_blks(unsigned int, unsigned long long, vector<pv_reservation>&);
    auto reserve_blks_pv(unsigned int, unsigned long long, vector<pv_reservation>&);
    auto resize_space(unsigned int, tx*, unsigned long long);
    auto rollback_blks(vector<pv_reservation>&);
    auto send_trims_down();
    auto shrink_space(pv_node*, tx*, unsigned long long);
    auto special_extents(unsigned int, unsigned long long, unsigned long long);
    auto special_query(unsigned int, unsigned long long*, unsigned long long*);
    auto teardown();
    auto trims_to_issue();
    auto unfreeze_extents(unsigned int);
    space_allocator(lvg*);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~space_allocator();
};
