//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class vector<cpdk_data_move_req> {
public: // (access info unavailable from symbols alone)
    auto push_back(cpdk_data_move_req const&);
    auto reserve(unsigned long);
    auto resize(unsigned long, cpdk_data_move_req const&);
    ~vector();
};
