//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class vector<pv_chunk_summary_ent> {
public: // (access info unavailable from symbols alone)
    auto push_back(pv_chunk_summary_ent const&);
    auto reserve(unsigned long);
    ~vector();
};
