//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class vector<caller_info> {
public: // (access info unavailable from symbols alone)
    push_back(caller_info const&);
    reserve(unsigned long);
};
