//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AMDRadeonX6000_AMDAccelDevice {
public: // (access info unavailable from symbols alone)
    AMDRadeonX6000_AMDAccelDevice();
    AMDRadeonX6000_AMDAccelDevice(OSMetaClass const*);
    deviceStart();
    deviceStop();
    getCpuGpuTimes(sAMD_CPU_GPU_TIMES*);
    getHardwareInfo(_sAMD_GET_HW_INFO_VALUES*);
    getMetaClass() const;
    getTargetAndMethodForIndex(IOService**, unsigned int);
    ~AMDRadeonX6000_AMDAccelDevice();
};
