//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AMDRadeonX6000_AMDPM4HWChannel {
public: // (access info unavailable from symbols alone)
    AMDRadeonX6000_AMDPM4HWChannel(OSMetaClass const*);
    auto allocateMemoryResources();
    auto attachUserQueue(AMDRadeonX6000_AMDUserQueue*);
    auto detachUserQueue(AMDRadeonX6000_AMDUserQueue*);
    auto free();
    auto getChannelProgressStatus(bool&);
    auto getMetaClass() const;
    auto getOneDwordNOPCommand();
    auto getRing() const;
    auto gfxResetWithEOP(CailHwEngineQueue*);
    auto infiniteWaitOnPowerUp();
    auto init(int, AMDRadeonX6000_IAMDHWInterface*, AMDRadeonX6000_IAMDHWEngine*, AMDRadeonX6000_IAMDHWRing*, char const*);
    auto performClearState();
    auto prepareAndFlushResetEOPFence();
    auto submitCommandBuffer(AMD_SUBMIT_COMMAND_BUFFER_INFO*);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~AMDRadeonX6000_AMDPM4HWChannel();
};
