//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOAccelContextList::Iterator {
public: // (access info unavailable from symbols alone)
    Iterator(IOAccelContextList&);
    auto getNextContext();
};
