//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleEffaceableNOR {
public: // (access info unavailable from symbols alone)
    AppleEffaceableNOR();
    AppleEffaceableNOR(OSMetaClass const*);
    auto eraseRegionNor(unsigned int, unsigned int);
    auto getMetaClass() const;
    auto getPageSizeNor();
    auto getRegionCountNor();
    auto getRegionSizeNor(unsigned int);
    auto nor();
    auto readRegionNor(unsigned int, void*, unsigned int, unsigned int);
    auto setupDeviceContract();
    auto setupNorContract();
    auto start(IOService*);
    auto writeRegionNor(unsigned int, void const*, unsigned int, unsigned int);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~AppleEffaceableNOR();
};
