//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOImageLoaderImageDictionary {
public: // (access info unavailable from symbols alone)
    IOImageLoaderImageDictionary();
    IOImageLoaderImageDictionary(OSMetaClass const*);
    auto countAttributesWith(IOImageLoaderImageDictionary*, char const*, char const*);
    auto doAllImagesHaveAttributeOfObjectType(IOImageLoaderImageDictionary*, char const*, OSMetaClass const*, bool (*)(OSString const*, char const*, OSObject const*, OSMetaClass const*, void*, void*, void*, void*), void*, void*, void*, void*);
    auto doAllImagesHaveAttributes(IOImageLoaderImageDictionary*);
    auto doAllImagesHaveUniqueAttribute(IOImageLoaderImageDictionary*, char const*);
    auto doAttributesExist(IOImageLoaderImageDictionary*, OSString*);
    auto doAttributesExist(IOImageLoaderImageDictionary*, char const*);
    auto getAttribute(OSDictionary*, OSString const*);
    auto getAttribute(OSDictionary*, char const*);
    auto getAttributes(IOImageLoaderImageDictionary*, OSString const*);
    auto getAttributes(IOImageLoaderImageDictionary*, char const*);
    auto getAttributesFromUniqueAttribute(IOImageLoaderImageDictionary*, OSString const*);
    auto getAttributesFromUniqueAttribute(IOImageLoaderImageDictionary*, char const*);
    auto getImageFromUniqueAttribute(IOImageLoaderImageDictionary*, char const*, OSString const*);
    auto getImageFromUniqueAttribute(IOImageLoaderImageDictionary*, char const*, char const*);
    auto getImageFromUniqueImagetype(IOImageLoaderImageDictionary*, OSString const*);
    auto getImageFromUniqueImagetype(IOImageLoaderImageDictionary*, char const*);
    auto getMetaClass() const;
    auto isAttributeOfType(OSDictionary*, OSString*, OSMetaClass const*);
    auto isAttributeOfType(OSDictionary*, char const*, OSMetaClass const*);
    auto isAttributeUnique(IOImageLoaderImageDictionary*, char const*, OSString const*);
    auto isAttributeUnique(IOImageLoaderImageDictionary*, char const*, char const*);
    auto isImageRequired(IOImageLoaderImageDictionary*, OSString const*);
    auto isImageRequired(IOImageLoaderImageDictionary*, char const*);
    auto isObjectOfType(OSObject*, OSMetaClass const*);
    auto iterateImages(IOImageLoaderImageDictionary*, char const*, OSMetaClass const*, bool (*)(OSString const*, char const*, OSObject const*, OSMetaClass const*, void*, void*, void*, void*), void*, void*, void*, void*);
    auto setAttributeWithBoolean(OSDictionary*, OSString const*, OSBoolean const*);
    auto setAttributeWithBoolean(OSDictionary*, OSString const*, bool);
    auto setAttributeWithBoolean(OSDictionary*, char const*, OSBoolean const*);
    auto setAttributeWithBoolean(OSDictionary*, char const*, bool);
    auto setAttributeWithNumber(OSDictionary*, OSString const*, OSNumber const*);
    auto setAttributeWithNumber(OSDictionary*, OSString const*, unsigned long long);
    auto setAttributeWithNumber(OSDictionary*, char const*, OSNumber const*);
    auto setAttributeWithNumber(OSDictionary*, char const*, unsigned long long);
    auto setAttributeWithObject(OSDictionary*, OSString const*, OSObject const*);
    auto setAttributeWithObject(OSDictionary*, char const*, OSObject const*);
    auto setAttributeWithString(OSDictionary*, OSString const*, OSString const*);
    auto setAttributeWithString(OSDictionary*, OSString const*, char const*);
    auto setAttributeWithString(OSDictionary*, char const*, OSString const*);
    auto setAttributeWithString(OSDictionary*, char const*, char const*);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~IOImageLoaderImageDictionary();
};
