//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface DockBarScrollWheelEventHandler : NSObject
{
}

- (unsigned long long)_scrollDirectionBasedOnOrientation:(id)arg1;
- (void)handleScrollWheelEvent:(id)arg1 type:(unsigned int)arg2;
- (id)initWithConnection:(unsigned int)arg1;

@end

