//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@interface DockFloatAnimatedProperty : NSObject <NSCopying>
{
    _Bool _active;
    float _from;
    float _now;
    float _to;
    unsigned long long _easingFunction;
    double _start;
    double _duration;
}

- (float)interpolate:(double)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

