//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "ECTextLayer.h"

@interface ECItemListLabelLayer : ECTextLayer
{
}

- (id)initWithScaleFactor:(float)arg1;

@end

