//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class ECEvent;

@protocol ECKeyboardNavigating <NSObject>
- (_Bool)navigate:(long long)arg1 withEvent:(ECEvent *)arg2;

@optional
@property(nonatomic) unsigned long long selectedIndex;
// Preceding property had unknown attributes: ?
// Original attribute string: TQ,?,N

@end

