//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <QuartzCore/CALayer.h>

@class NSString;

@interface ECMaterialLayer : CALayer
{
    NSString *_groupName;
    unsigned char _materialStyle;
    unsigned long long _material;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned char materialStyle; // @synthesize materialStyle=_materialStyle;
@property(nonatomic) unsigned long long material; // @synthesize material=_material;
- (void)layoutSublayers;
- (id)initWithMaterial:(unsigned long long)arg1 groupName:(id)arg2 style:(unsigned char)arg3;

@end

