//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSSet, NSString;

@interface ECScreenTimeController : NSObject
{
    id policyChangedCompletion;
    id stateChangedCompletion;
    id policyMonitor;
    id policiesByApplication;
    id assignmentTimer;
    void applications;
    _Bool isEnabled;
}

+ (struct CGImage *)restrictedImageFor:(float)arg1;
+ (id)queue;
- (void).cxx_destruct;
- (id)init;
- (_Bool)isApplicationRestrictedWithBundleID:(id)arg1;
- (id)initWithPolicyChangedCompletion:(CDUnknownBlockType)arg1 stateChangedCompletion:(CDUnknownBlockType)arg2;
@property(nonatomic) _Bool isEnabled; // @synthesize isEnabled;
@property(nonatomic, readonly) NSSet *restrictedApplications;
@property(nonatomic, copy) NSArray *applications;
@property(nonatomic, readonly) NSString *debugDescription;

@end

