//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <QuartzCore/CALayer.h>

#import "NSCopying-Protocol.h"

@class ECStatusLabelDescription;

@interface ECStatusLabelLayer : CALayer <NSCopying>
{
    ECStatusLabelDescription *_labelDescription;
    struct CGRect _normalizedFrame;
    struct CGRect _backgroundNormalizedFrame;
    struct CGRect _lastLayoutFrame;
    double _size;
    float _scaleFactor;
    _Bool _hidden;
    CALayer *_imageLayer;
    CALayer *_backgroundLayer;
    CALayer *_shadowLayer;
    CALayer *_secondShadowLayer;
    _Bool _rightToLeft;
}

+ (void)initialize;
- (void).cxx_destruct;
@property(nonatomic) _Bool rightToLeft; // @synthesize rightToLeft=_rightToLeft;
@property(nonatomic) float scaleFactor; // @synthesize scaleFactor=_scaleFactor;
@property(retain, nonatomic) ECStatusLabelDescription *labelDescription; // @synthesize labelDescription=_labelDescription;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)_renderBadgeImage;
- (void)_createLayers;
- (void)updateBadgeColor;
- (void)layoutForFrame:(struct CGRect)arg1;
- (id)initWithMaxSize:(double)arg1 scaleFactor:(float)arg2 rightToLeft:(_Bool)arg3;

@end

