//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class LPSpringboard;
@protocol OS_xpc_object;

@interface LPSpringboardConnection : NSObject
{
    NSObject<OS_xpc_object> *_connection;
    LPSpringboard *_springboard;
}

- (void).cxx_destruct;
- (void)_getApplicationList:(id)arg1;
- (void)_acceptConnection:(id)arg1;
- (void)_setupListener;
- (void)activate;
- (void)dealloc;
- (id)initWithSpringboard:(id)arg1;

@end

