//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol SessionConsoleMonitor;

@protocol SessionConsoleObserver <NSObject>
- (void)sessionConsoleDidDisconnect:(id <SessionConsoleMonitor>)arg1;
- (void)sessionConsoleDidConnect:(id <SessionConsoleMonitor>)arg1;
@end

