//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleEffaceableStorage {
public: // (access info unavailable from symbols alone)
    AppleEffaceableStorage(OSMetaClass const*);
    auto calcSHA1Sys(void const*, unsigned int, void*);
    auto callPlatformFunction(OSSymbol const*, bool, void*, void*, void*, void*);
    auto cmpMemSys(void const*, void const*, unsigned int);
    auto crc32Sys(unsigned int, void const*, unsigned int);
    auto device();
    auto efReturn(int);
    auto effaceLocker(unsigned int, bool);
    auto effaceLockerGated(unsigned int, bool);
    auto formatStorage();
    auto formatStorageGated();
    auto generateNonce(void*);
    auto generateNonceGated(void*);
    auto getBytes(void*, unsigned long long, unsigned long long);
    auto getBytesGated(void*, unsigned long long, unsigned long long);
    auto getCapacity();
    auto getLocker(unsigned int, void*, unsigned long long*, bool);
    auto getLockerGated(unsigned int, void*, unsigned long long*, bool);
    auto getMetaClass() const;
    auto getWorkLoop() const;
    auto ioReturn(_EffaceableReturn);
    auto isFormatted();
    auto logf(void*, char const*, ...);
    auto logk(void*, char const*, ...);
    auto moveMemSys(void*, void const*, unsigned int);
    auto panicSys(char const*);
    auto readRandomSys(void*, unsigned int);
    auto registerService(unsigned int);
    auto setBytes(void const*, unsigned long long, unsigned long long);
    auto setBytesGated(void*, unsigned long long, unsigned long long);
    auto setLocker(unsigned int, void const*, unsigned long long, bool);
    auto setLockerGated(unsigned int, void const*, unsigned long long, bool);
    auto setLockerWithID(unsigned int, void const*, unsigned long long, unsigned int, bool);
    auto setLockerWithIDGated(_setLockerWithID*);
    auto setMemSys(void*, unsigned char, unsigned int);
    auto setPropertySys(char const*, unsigned int);
    auto setupSystemContract();
    auto spaceForLocker(unsigned int, unsigned long long*);
    auto spaceForLockerGated(unsigned int, unsigned long long*);
    auto start(IOService*);
    auto storage();
    auto system();
    auto vlogfSys(char const*, __va_list_tag*);
    auto wipeStorage();
    auto wipeStorageGated(void*);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~AppleEffaceableStorage();
};
