//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension _RegexParser.CaptureList.Builder.OptionalNesting {
    init(canNest: Swift.Bool) -> _RegexParser.CaptureList.Builder.OptionalNesting
}
