//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension _StringProcessing.DSLTree.Node {
    (_canOnlyMatchAtStartImpl in _30D2A4D3B4368AC4FFB7B1F49A4BE7F0)(inout _StringProcessing.MatchingOptions) -> Swift.Optional<Swift.Bool>
    appending(_StringProcessing.DSLTree.Node) -> _StringProcessing.DSLTree.Node
    appendingAlternationCase(_StringProcessing.DSLTree.Node) -> _StringProcessing.DSLTree.Node
    getNamedCaptures() -> Swift.Array<Swift.String>
}
