//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOFireWirePowerManager {
public: // (access info unavailable from symbols alone)
    IOFireWirePowerManager();
    IOFireWirePowerManager(OSMetaClass const*);
    _RESERVEDIOFireWirePowerManager0();
    _RESERVEDIOFireWirePowerManager1();
    _RESERVEDIOFireWirePowerManager2();
    _RESERVEDIOFireWirePowerManager3();
    _RESERVEDIOFireWirePowerManager4();
    _RESERVEDIOFireWirePowerManager5();
    _RESERVEDIOFireWirePowerManager6();
    _RESERVEDIOFireWirePowerManager7();
    _RESERVEDIOFireWirePowerManager8();
    _RESERVEDIOFireWirePowerManager9();
    allocateDeciwatts(unsigned int);
    createWithController(IOFireWireController*);
    deallocateDeciwatts(unsigned int);
    getMetaClass() const;
    initWithController(IOFireWireController*);
    setMaximumDeciwatts(unsigned int);
    ~IOFireWirePowerManager();
};
