//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOFWIsochChannel {
public: // (access info unavailable from symbols alone)
    IOFWIsochChannel();
    IOFWIsochChannel(OSMetaClass const*);
    _RESERVEDIOFWIsochChannel0();
    _RESERVEDIOFWIsochChannel1();
    _RESERVEDIOFWIsochChannel2();
    _RESERVEDIOFWIsochChannel3();
    addListener(IOFWIsochPort*);
    allocateChannel();
    allocateChannelBegin(IOFWSpeed, unsigned long long, unsigned int*);
    checkMemoryInRange(IOMemoryDescriptor*);
    free();
    getMetaClass() const;
    handleBusReset();
    handleBusReset()::kalloc_type_view_957;
    init(IOFireWireController*, bool, unsigned int, IOFWSpeed, int (*)(void*, IOFWIsochChannel*, unsigned int), void*);
    reallocBandwidth(unsigned int);
    releaseChannel();
    releaseChannelComplete();
    setTalker(IOFWIsochPort*);
    start();
    stop();
    threadFunc(void*);
    threadFunc(void*)::kalloc_type_view_996;
    updateBandwidth(bool);
    ~IOFWIsochChannel();
};
