//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOFWReceiveDCL {
public: // (access info unavailable from symbols alone)
    IOFWReceiveDCL(OSMetaClass const*);
    auto debug();
    auto getMetaClass() const;
    auto importUserDCL(unsigned char*, unsigned long long&, IOMemoryMap*, OSArray const*);
    auto initWithParams(OSSet*, unsigned char, unsigned int, IOVirtualRange*);
    auto setWaitControl(bool);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~IOFWReceiveDCL();
};
