//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOFWUserPhysicalAddressSpace {
public: // (access info unavailable from symbols alone)
    IOFWUserPhysicalAddressSpace();
    IOFWUserPhysicalAddressSpace(OSMetaClass const*);
    auto exporterCleanup(OSObject const*);
    auto free();
    auto getMetaClass() const;
    auto getSegmentCount(unsigned int*);
    auto getSegments(unsigned int*, IOFireWireLib::FWPhysicalSegment32*);
    auto initWithDesc(IOFireWireBus*, IOMemoryDescriptor*);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~IOFWUserPhysicalAddressSpace();
};
