//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOTimeSyncIntervalFilter128 {
public: // (access info unavailable from symbols alone)
    IOTimeSyncIntervalFilter128(OSMetaClass const*);
    auto _RESERVEDIOTimeSyncIntervalFilter1280();
    auto _RESERVEDIOTimeSyncIntervalFilter1281();
    auto _RESERVEDIOTimeSyncIntervalFilter12810();
    auto _RESERVEDIOTimeSyncIntervalFilter12811();
    auto _RESERVEDIOTimeSyncIntervalFilter12812();
    auto _RESERVEDIOTimeSyncIntervalFilter12813();
    auto _RESERVEDIOTimeSyncIntervalFilter12814();
    auto _RESERVEDIOTimeSyncIntervalFilter12815();
    auto _RESERVEDIOTimeSyncIntervalFilter1282();
    auto _RESERVEDIOTimeSyncIntervalFilter1283();
    auto _RESERVEDIOTimeSyncIntervalFilter1284();
    auto _RESERVEDIOTimeSyncIntervalFilter1285();
    auto _RESERVEDIOTimeSyncIntervalFilter1286();
    auto _RESERVEDIOTimeSyncIntervalFilter1287();
    auto _RESERVEDIOTimeSyncIntervalFilter1288();
    auto _RESERVEDIOTimeSyncIntervalFilter1289();
    auto filterCount(unsigned int);
    auto free();
    auto free()::kalloc_type_view_416;
    auto getMetaClass() const;
    auto getMultiIntervalTime(unsigned int);
    auto initFilter(unsigned long long, unsigned int);
    auto initFilter(unsigned long long, unsigned int)::kalloc_type_view_394;
    auto newTimePosition(IOTS_U128, unsigned int*);
    auto reInitialiseFilter(unsigned long long, unsigned int, unsigned int*);
    auto reInitialiseFilter(unsigned long long, unsigned int, unsigned int*)::kalloc_type_view_461;
    auto reInitialiseFilter(unsigned long long, unsigned int, unsigned int*)::kalloc_type_view_467;
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~IOTimeSyncIntervalFilter128();
};
