//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class TSNBSDStackInterface {
public: // (access info unavailable from symbols alone)
    TSNBSDStackInterface();
    TSNBSDStackInterface(OSMetaClass const*);
    auto filterReceivedEvent(kev_msg const*);
    auto filterReceivedEvent(kev_msg const*)::_os_log_fmt;
    auto getMetaClass() const;
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~TSNBSDStackInterface();
};
