//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class TSNInterface::MetaClass {
public: // (access info unavailable from symbols alone)
    MetaClass();
    alloc() const;
    ~MetaClass();
};
