//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleVirtIOSoundControlTransaction {
public: // (access info unavailable from symbols alone)
    AppleVirtIOSoundControlTransaction();
    auto copyResults(void*, unsigned int);
    auto copyResults(void*, unsigned int) (.cold.1);
    auto free();
    auto getMemoryDescriptorAtIndex(unsigned int);
    auto getMemoryDescriptorCount();
    auto getMetaClass() const;
    auto getStreamId() const;
    auto getStreamLifecycleState() const;
    auto initWithRequest(IOMemoryDescriptor*, IOMemoryDescriptor*);
    auto withChannelMapInfoTransaction(unsigned int, unsigned int);
    auto withJackInfoTransaction(unsigned int, unsigned int);
    auto withPcmInfoTransaction(unsigned int, unsigned int);
    auto withPcmPrepareTransaction(unsigned int);
    auto withPcmReleaseTransaction(unsigned int);
    auto withPcmSetParametersTransaction(unsigned int, virtio_snd_pcm_set_params*);
    auto withPcmStartTransaction(unsigned int);
    auto withPcmStopTransaction(unsigned int);
    auto withRequest(IOMemoryDescriptor*, IOMemoryDescriptor*);
    ~AppleVirtIOSoundControlTransaction();
};
