//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleVirtIOBalloonMemory {
public: // (access info unavailable from symbols alone)
    AppleVirtIOBalloonMemory();
    auto free();
    auto getDescriptors() const;
    auto getMetaClass() const;
    auto getNumPages() const;
    auto initWithPageCount(unsigned int);
    auto merge(AppleVirtIOBalloonMemory*);
    auto split(AppleVirtIOBalloonMemory*&, unsigned int);
    void * operator new(unsigned long);
    ~AppleVirtIOBalloonMemory();
};
