//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class libkern {
public: // (access info unavailable from symbols alone)
    bool operator!=<OSData, intrusive_osobject_retainer>(libkern::intrusive_shared_ptr<OSData, intrusive_osobject_retainer> const&, std::nullptr_t);
    bool operator==<IORSMReceiveQueueEntry, intrusive_osobject_retainer>(libkern::intrusive_shared_ptr<IORSMReceiveQueueEntry, intrusive_osobject_retainer> const&, std::nullptr_t);
};
