//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOBootNDRV {
public: // (access info unavailable from symbols alone)
    IOBootNDRV();
    IOBootNDRV(OSMetaClass const*);
    auto doControl(unsigned int, void*);
    auto doDriverIO(unsigned int, void*, unsigned int, unsigned int);
    auto doStatus(unsigned int, void*);
    auto driverName();
    auto free();
    auto fromRegistryEntry(IORegistryEntry*);
    auto getMetaClass() const;
    auto getSymbol(char const*, unsigned long long*);
    auto getUInt32Property(IORegistryEntry*, char const*, unsigned int*);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~IOBootNDRV();
};
