//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class lsl::Vector<dyld4::RuntimeState::RegisteredDOF> {
public: // (access info unavailable from symbols alone)
    erase(dyld4::RuntimeState::RegisteredDOF*, dyld4::RuntimeState::RegisteredDOF*);
    reserve(unsigned long long);
    reserveExact(unsigned long long);
};
