//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class mach_o::Universal {
public: // (access info unavailable from symbols alone)
    archNames(char*) const;
    bestSlice(mach_o::GradedArchitectures const&, bool, mach_o::Universal::Slice&) const;
    forEachSlice(void (mach_o::Architecture, unsigned long long, unsigned long long, unsigned char, bool&) block_pointer) const;
    isUniversal(std::__1::span<unsigned char const, 18446744073709551615ul>);
    valid(unsigned long long) const;
    validSlice(mach_o::Architecture, unsigned long long, unsigned long long) const;
};
