//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class std::__1::__lower_bound_bisecting[abi:nqn210106]<std::__1::_ClassicAlgPolicy, char const**, char [4], std::__1::__identity, lsl {
public: // (access info unavailable from symbols alone)
    char const** ConstCharStarCompare>(char const**, char const (&) [4], std::__1::iterator_traits<char const**>::difference_type, lsl::ConstCharStarCompare&, std::__1::__identity&);
};
