//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOFWAddressSpace {
public: // (access info unavailable from symbols alone)
    activate();
    deactivate();
    doLock(unsigned short, IOFWSpeed&, FWAddressStruct, unsigned int, unsigned int const*, unsigned int&, unsigned int*, unsigned int, void*);
    init(IOFireWireBus*);
};
