//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IGAccelSurface {
public: // (access info unavailable from symbols alone)
    IGAccelSurface();
    IGAccelSurface(OSMetaClass const*);
    canTmpAlloc(unsigned int);
    copyBufferDMA(int, int, int, int, unsigned int, unsigned int, IOAccelEvent*, IOAccelResource2*, unsigned long long, IOAccelSysMemory*, unsigned long long, unsigned long long, unsigned int, unsigned int);
    copyFromBuffer(int, int, int, int, unsigned int, unsigned int, IOAccelEvent*, IOAccelResource2*, IOAccelSysMemory*, unsigned int, unsigned long long, unsigned int);
    copyFromBuffer(int, int, int, int, unsigned int, unsigned int, IOAccelEvent*, IOAccelResource2*, unsigned int, IOAccelSysMemory*, unsigned int, unsigned long long, unsigned int);
    copyToBuffer(int, int, int, int, unsigned int, unsigned int, IOAccelEvent*, IOAccelResource2*, IOAccelSysMemory*, unsigned int, unsigned long long, unsigned int);
    getDirtyBufferBitsFromPrivateModeBits(unsigned long long);
    getMetaClass() const;
    setBuffer(unsigned int, bool, unsigned char*, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, bool, bool, bool, unsigned short, unsigned short);
    setData(unsigned int, unsigned int&, unsigned int&, unsigned int&, unsigned int&, unsigned int&, unsigned int, unsigned int, bool, bool, bool, unsigned short, unsigned short);
    shapeSurface(unsigned int, unsigned short, unsigned short);
    submitSwapCopy(IOAccelEvent*, IOAccelResource2*, IOAccelResource2*);
    surfaceStart();
    surfaceStop();
    ~IGAccelSurface();
};
