//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IGHardwareRingBufferBlit {
public: // (access info unavailable from symbols alone)
    IGHardwareRingBufferBlit();
    IGHardwareRingBufferBlit(OSMetaClass const*);
    getMetaClass() const;
    init(IGHardwareContext*);
    waitForSemaphore(unsigned int, unsigned int);
    ~IGHardwareRingBufferBlit();
};
