//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOMemoryDescriptor {
public: // (access info unavailable from symbols alone)
    Dispatch(IORPC);
    _RESERVEDIOMemoryDescriptor1();
    _RESERVEDIOMemoryDescriptor10();
    _RESERVEDIOMemoryDescriptor11();
    _RESERVEDIOMemoryDescriptor12();
    _RESERVEDIOMemoryDescriptor13();
    _RESERVEDIOMemoryDescriptor14();
    _RESERVEDIOMemoryDescriptor15();
    _RESERVEDIOMemoryDescriptor2();
    _RESERVEDIOMemoryDescriptor3();
    _RESERVEDIOMemoryDescriptor4();
    _RESERVEDIOMemoryDescriptor5();
    _RESERVEDIOMemoryDescriptor6();
    _RESERVEDIOMemoryDescriptor7();
    _RESERVEDIOMemoryDescriptor8();
    _RESERVEDIOMemoryDescriptor9();
    addMapping(IOMemoryMap*);
    createMappingInTask(task*, unsigned long long, unsigned int, unsigned long long, unsigned long long);
    dmaCommandOperation(unsigned int, void*, unsigned int) const;
    doMap(_vm_map*, unsigned long long*, unsigned int, unsigned long long, unsigned long long);
    doUnmap(_vm_map*, unsigned long long, unsigned long long);
    getDirection() const;
    getLength() const;
    getPhysicalAddress();
    getTag();
    initWithOptions(void*, unsigned int, unsigned int, task*, unsigned int, IOMapper*);
    map(unsigned int);
    performOperation(unsigned int, unsigned long long, unsigned long long);
    readBytes(unsigned long long, void*, unsigned long long);
    removeMapping(IOMemoryMap*);
    setMapping(task*, unsigned long long, unsigned int);
    setTag(unsigned int);
    withAddressRange(unsigned long long, unsigned long long, unsigned int, task*);
    withPhysicalAddress(unsigned long long, unsigned long long, unsigned int);
    writeBytes(unsigned long long, void const*, unsigned long long);
};
