//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class SurfaceStateCommon {
public: // (access info unavailable from symbols alone)
    Generate(depth_resolve_params_t const*, SurfaceUsage);
    SetLevelLayer(SurfaceUsage, unsigned int, unsigned int);
};
