//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AMDRadeonX5000_AMDUVD7v2HWEngine {
public: // (access info unavailable from symbols alone)
    AMDRadeonX5000_AMDUVD7v2HWEngine();
    AMDRadeonX5000_AMDUVD7v2HWEngine(OSMetaClass const*);
    allocateHWChannels();
    allocateHWRings();
    commitUVDFWMsg(_SML_UVD_MSG*, unsigned long long, unsigned long long, unsigned long long);
    dumpEngineHangState(bool);
    free();
    getMetaClass() const;
    init(AMDRadeonX5000_IAMDHWInterface*, _eAMD_HW_ENGINE_TYPE);
    initHardware();
    isIdle();
    releaseHardware();
    ~AMDRadeonX5000_AMDUVD7v2HWEngine();
};
