//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AMDRadeonX5000_AMDAccelChannel {
public: // (access info unavailable from symbols alone)
    AMDRadeonX5000_AMDAccelChannel();
    AMDRadeonX5000_AMDAccelChannel(OSMetaClass const*);
    auto addToBarrier(IOAccelEvent*);
    auto checkForTimestamp(unsigned int);
    auto containsEntriesFromSubmitter(IOAccelTask*);
    auto create(AMDRadeonX5000_AMDGraphicsAccelerator*, AMDRadeonX5000_IAMDHWChannel*, unsigned int, char const*, SS_PRIORITY);
    auto disableKTrace();
    auto enableKTrace();
    auto free();
    auto getBlockedChannelInfo();
    auto getFirstPendingEntry();
    auto getHardwareDiagnosisReport(unsigned int*);
    auto getMetaClass() const;
    auto init(AMDRadeonX5000_AMDGraphicsAccelerator*, AMDRadeonX5000_IAMDHWChannel*, unsigned int, char const*, SS_PRIORITY);
    auto initBarrierData();
    auto replayBuffers(IOAccelTask*);
    auto resetHardwareAndReplay();
    auto submitBuffer(IOAccelCommandDescriptor*);
    auto submitCommands(IOAccelCommandDescriptor*);
    auto submitDPT();
    auto triage(char**, unsigned long long*);
    auto waitForRingBufferSpace();
    auto waitForTimestamp(unsigned int);
    auto writeBlockedChannelDiag(char**, unsigned long long*);
    auto writeDiagnosisReport(char*&, unsigned int&);
    auto writePendingCommandInfoDiagnosisReport(char*&, unsigned int&, AMD_COMMAND_BUFFER*, IOAccelTask*);
    auto writeWaitInfoDiagnosisReport(char*&, unsigned int&, sAMDAccelRingEntry*);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~AMDRadeonX5000_AMDAccelChannel();
};
