//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AMDRadeonX5000_AMDGFX9AlignManager {
public: // (access info unavailable from symbols alone)
    AMDRadeonX5000_AMDGFX9AlignManager();
    AMDRadeonX5000_AMDGFX9AlignManager(OSMetaClass const*);
    getAddrFormat(unsigned int);
    getAddrResourceType(unsigned int);
    getAddrSwizzleMode(unsigned int);
    getFormat(_AddrFormat);
    getMetaClass() const;
    getResourceType(_AddrResourceType);
    getSwizzleMode(_AddrSwizzleMode);
    ~AMDRadeonX5000_AMDGFX9AlignManager();
};
