//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOAccelDisplayPipePreCSCLinearizationVID {
public: // (access info unavailable from symbols alone)
    getConfigurationID() const;
    getFormat() const;
    getMaximumValue() const;
    getMinimumValue() const;
    getPlane() const;
    getSize() const;
    getType() const;
};
