//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOAccel2DContext2 {
public: // (access info unavailable from symbols alone)
    IOAccel2DContext2(OSMetaClass const*);
    auto _RESERVEDIOAccel2DContext0();
    auto _RESERVEDIOAccel2DContext1();
    auto _RESERVEDIOAccel2DContext2();
    auto _RESERVEDIOAccel2DContext3();
    auto _RESERVEDIOAccel2DContext4();
    auto _RESERVEDIOAccel2DContext5();
    auto allowsExclusiveMode() const;
    auto getSurfaceReqBits() const;
    auto getTargetAndMethodForIndex(IOService**, unsigned int);
    ~IOAccel2DContext2();
};
