//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleGFXHDA8086_38C8Controller {
public: // (access info unavailable from symbols alone)
    AppleGFXHDA8086_38C8Controller();
    AppleGFXHDA8086_38C8Controller(OSMetaClass const*);
    auto framebufferEventGate(void*, IOFramebuffer*, int, void*);
    auto getMetaClass() const;
    auto probeAndInitDisplayCodec();
    auto probeAudioLink();
    auto systemWillShutdown(unsigned int);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~AppleGFXHDA8086_38C8Controller();
};
