//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOGFXHDAStream {
public: // (access info unavailable from symbols alone)
    IOGFXHDAStream();
    IOGFXHDAStream(OSMetaClass const*);
    auto activateStream(unsigned int, unsigned int, bool);
    auto clearStreamNumber();
    auto deactivateStream(unsigned int);
    auto getBitsPerSample() const;
    auto getCASampleFormat() const;
    auto getControlData() const;
    auto getCyclicBufferMemory();
    auto getDMABlockSize() const;
    auto getDataFormat() const;
    auto getDescriptorFormat(unsigned int) const;
    auto getLinkChannelCount() const;
    auto getLinkPositionInBuffer();
    auto getMetaClass() const;
    auto getSampleRate() const;
    auto getStreamDirection() const;
    auto getStreamNumber() const;
    auto getSynchronizationGroup() const;
    auto initWithController(AppleGFXHDAController*, void*);
    auto registerStreamInterrupt(void*, void (*)(void*, void*, bool, unsigned long long*), void*, unsigned int);
    auto setBitsPerSample(unsigned int);
    auto setCASampleFormat(unsigned int);
    auto setDMABlockSize(unsigned int);
    auto setDataFormat(unsigned int);
    auto setLinkChannelCount(unsigned int);
    auto setSampleRate(unsigned int, bool);
    auto setStreamDirection(unsigned int);
    auto setStreamNumber(int);
    auto setSynchronizationGroup(unsigned int);
    auto startDMAEngine(unsigned int);
    auto stopDMAEngine(unsigned int);
    auto unregisterStreamInterrupt();
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~IOGFXHDAStream();
};
