//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension Dispatch {
    (toInt64Clamped in _517CC70A4F407F19FAF53AD6F07743FB)(Swift.Double) -> Swift.Int64
    + infix(Dispatch.DispatchTime, Dispatch.DispatchTimeInterval) -> Dispatch.DispatchTime
    + infix(Dispatch.DispatchTime, Swift.Double) -> Dispatch.DispatchTime
    + infix(Dispatch.DispatchWallTime, Dispatch.DispatchTimeInterval) -> Dispatch.DispatchWallTime
    + infix(Dispatch.DispatchWallTime, Swift.Double) -> Dispatch.DispatchWallTime
    - infix(Dispatch.DispatchTime, Dispatch.DispatchTimeInterval) -> Dispatch.DispatchTime
    - infix(Dispatch.DispatchTime, Swift.Double) -> Dispatch.DispatchTime
    - infix(Dispatch.DispatchWallTime, Dispatch.DispatchTimeInterval) -> Dispatch.DispatchWallTime
    - infix(Dispatch.DispatchWallTime, Swift.Double) -> Dispatch.DispatchWallTime
    _dispatchPreconditionTest(Dispatch.DispatchPredicate) -> Swift.Bool
    dispatchPrecondition(condition: @autoclosure () -> Dispatch.DispatchPredicate) -> ()
    dispatch_after(Swift.UInt64, __C.OS_dispatch_queue, () -> ()) -> ()
    dispatch_apply(Swift.Int, __C.OS_dispatch_queue, (Swift.Int) -> ()) -> ()
    dispatch_assert_queue(__C.OS_dispatch_queue) -> ()
    dispatch_assert_queue_barrier(__C.OS_dispatch_queue) -> ()
    dispatch_assert_queue_not(__C.OS_dispatch_queue) -> ()
    dispatch_async(__C.OS_dispatch_queue, () -> ()) -> ()
    dispatch_barrier_async(__C.OS_dispatch_queue, () -> ()) -> ()
    dispatch_barrier_sync(__C.OS_dispatch_queue, () -> ()) -> ()
    dispatch_data_apply(__C.OS_dispatch_data, (__C.OS_dispatch_data, Swift.Int, Swift.UnsafeRawPointer, Swift.Int) -> Swift.Bool) -> Swift.Bool
    dispatch_data_copy_region(__C.OS_dispatch_data, Swift.Int, Swift.UnsafeMutablePointer<Swift.Int>) -> __C.OS_dispatch_data
    dispatch_data_create(Swift.UnsafeRawPointer, Swift.Int, Swift.Optional<__C.OS_dispatch_queue>, Swift.Optional<() -> ()>) -> __C.OS_dispatch_data
    dispatch_data_create_concat(__C.OS_dispatch_data, __C.OS_dispatch_data) -> __C.OS_dispatch_data
    dispatch_data_create_map(__C.OS_dispatch_data, Swift.Optional<Swift.UnsafeMutablePointer<Swift.Optional<Swift.UnsafeRawPointer>>>, Swift.Optional<Swift.UnsafeMutablePointer<Swift.Int>>) -> __C.OS_dispatch_data
    dispatch_data_create_subrange(__C.OS_dispatch_data, Swift.Int, Swift.Int) -> __C.OS_dispatch_data
    dispatch_data_get_size(__C.OS_dispatch_data) -> Swift.Int
    dispatch_get_global_queue(Swift.Int, Swift.UInt) -> __C.OS_dispatch_queue
    dispatch_get_main_queue() -> __C.OS_dispatch_queue
    dispatch_get_specific(Swift.UnsafeRawPointer) -> Swift.Optional<Swift.UnsafeMutableRawPointer>
    dispatch_group_async(__C.OS_dispatch_group, __C.OS_dispatch_queue, () -> ()) -> ()
    dispatch_group_notify(__C.OS_dispatch_group, __C.OS_dispatch_queue, () -> ()) -> ()
    dispatch_group_wait(__C.OS_dispatch_group, Swift.UInt64) -> Swift.Int
    dispatch_io_close(__C.OS_dispatch_io, Swift.UInt) -> ()
    dispatch_io_create(Swift.UInt, Swift.Int32, __C.OS_dispatch_queue, (Swift.Int32) -> ()) -> __C.OS_dispatch_io
    dispatch_io_create_with_io(Swift.UInt, __C.OS_dispatch_io, __C.OS_dispatch_queue, (Swift.Int32) -> ()) -> __C.OS_dispatch_io
    dispatch_io_create_with_path(Swift.UInt, Swift.UnsafePointer<Swift.Int8>, Swift.Int32, Swift.UInt16, __C.OS_dispatch_queue, (Swift.Int32) -> ()) -> __C.OS_dispatch_io
    dispatch_io_set_interval(__C.OS_dispatch_io, Swift.UInt64, Swift.UInt) -> ()
    dispatch_queue_attr_make_initially_inactive(Swift.Optional<__C.OS_dispatch_queue_attr>) -> __C.OS_dispatch_queue_attr
    dispatch_queue_attr_make_with_autorelease_frequency(Swift.Optional<__C.OS_dispatch_queue_attr>, __C.dispatch_autorelease_frequency_t) -> __C.OS_dispatch_queue_attr
    dispatch_queue_attr_make_with_qos_class(Swift.Optional<__C.OS_dispatch_queue_attr>, __C.qos_class_t, Swift.Int32) -> __C.OS_dispatch_queue_attr
    dispatch_queue_create(Swift.Optional<Swift.UnsafePointer<Swift.Int8>>, Swift.Optional<__C.OS_dispatch_queue_attr>) -> __C.OS_dispatch_queue
    dispatch_queue_create_with_target(Swift.Optional<Swift.UnsafePointer<Swift.Int8>>, Swift.Optional<__C.OS_dispatch_queue_attr>, Swift.Optional<__C.OS_dispatch_queue>) -> __C.OS_dispatch_queue
    dispatch_queue_get_label(Swift.Optional<__C.OS_dispatch_queue>) -> Swift.UnsafePointer<Swift.Int8>
    dispatch_queue_get_qos_class(__C.OS_dispatch_queue, Swift.Optional<Swift.UnsafeMutablePointer<Swift.Int32>>) -> __C.qos_class_t
    dispatch_queue_get_specific(__C.OS_dispatch_queue, Swift.UnsafeRawPointer) -> Swift.Optional<Swift.UnsafeMutableRawPointer>
    dispatch_queue_set_specific(__C.OS_dispatch_queue, Swift.UnsafeRawPointer, Swift.Optional<Swift.UnsafeMutableRawPointer>, Swift.Optional<@convention(c) (Swift.Optional<Swift.UnsafeMutableRawPointer>) -> ()>) -> ()
    dispatch_read(Swift.Int32, Swift.Int, __C.OS_dispatch_queue, (__C.OS_dispatch_data, Swift.Int32) -> ()) -> ()
    dispatch_semaphore_signal(__C.OS_dispatch_semaphore) -> Swift.Int
    dispatch_semaphore_wait(__C.OS_dispatch_semaphore, Swift.UInt64) -> Swift.Int
    dispatch_source_cancel(__C.OS_dispatch_source) -> ()
    dispatch_source_create(Swift.OpaquePointer, Swift.UInt, Swift.UInt, Swift.Optional<__C.OS_dispatch_queue>) -> __C.OS_dispatch_source
    dispatch_source_get_data(__C.OS_dispatch_source) -> Swift.UInt
    dispatch_source_get_handle(__C.OS_dispatch_source) -> Swift.UInt
    dispatch_source_get_mask(__C.OS_dispatch_source) -> Swift.UInt
    dispatch_source_merge_data(__C.OS_dispatch_source, Swift.UInt) -> ()
    dispatch_source_set_cancel_handler(__C.OS_dispatch_source, Swift.Optional<() -> ()>) -> ()
    dispatch_source_set_event_handler(__C.OS_dispatch_source, Swift.Optional<() -> ()>) -> ()
    dispatch_source_set_registration_handler(__C.OS_dispatch_source, Swift.Optional<() -> ()>) -> ()
    dispatch_source_set_timer(__C.OS_dispatch_source, Swift.UInt64, Swift.UInt64, Swift.UInt64) -> ()
    dispatch_source_testcancel(__C.OS_dispatch_source) -> Swift.Int
    dispatch_time(Swift.UInt64, Swift.Int64) -> Swift.UInt64
    dispatch_walltime(Swift.Optional<Swift.UnsafePointer<__C.timespec>>, Swift.Int64) -> Swift.UInt64
}
