//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleKeyStoreHelper {
public: // (access info unavailable from symbols alone)
    copyPackedItem(OSData*, unsigned int);
    dataFromInput(IOExternalMethodArguments*);
    dataToOutput(OSData*, IOExternalMethodArguments*);
    getVerifiedItemCount(OSData*);
    get_dt_entry(char const*, char const*, unsigned int*);
    get_dt_entry(char const*, char const*, unsigned int*) (.cold.1);
    get_dt_entry(char const*, char const*, unsigned int*) (.cold.2);
    secretFromInput(unsigned long long, unsigned long long);
};
