//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleParavirtDisplayMachine {
public: // (access info unavailable from symbols alone)
    AppleParavirtDisplayMachine();
    AppleParavirtDisplayMachine(OSMetaClass const*);
    displayModeDidChange();
    displayModeWillChange();
    free();
    getMetaClass() const;
    init(IOGraphicsAccelerator2*);
    signalDisplays(unsigned int);
    signalDisplays(unsigned int) (.cold.1);
    signalDisplays(unsigned int)::_os_log_fmt;
    start(IOPCIDevice*);
    stop();
    ~AppleParavirtDisplayMachine();
};
