//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleParavirtKernelTask {
public: // (access info unavailable from symbols alone)
    AppleParavirtKernelTask();
    AppleParavirtKernelTask(OSMetaClass const*);
    defineHostTask();
    defineHostTask()::_os_log_fmt;
    getMetaClass() const;
    setResourceHeap();
    setResourceHeap()::_os_log_fmt;
    ~AppleParavirtKernelTask();
};
