//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOAccelSysMemory {
public: // (access info unavailable from symbols alone)
    IOAccelSysMemory(OSMetaClass const*);
    auto _RESERVEDIOAccelSysMemory0();
    auto _RESERVEDIOAccelSysMemory1();
    auto _RESERVEDIOAccelSysMemory2();
    auto _RESERVEDIOAccelSysMemory3();
    auto _RESERVEDIOAccelSysMemory4();
    auto _RESERVEDIOAccelSysMemory5();
    auto complete();
    auto decrement_wire_count();
    auto free();
    auto getDirtySize() const;
    auto getPhysicalSegment(unsigned long long, unsigned long long*);
    auto getResidentSize() const;
    auto getTag();
    auto increment_wire_count();
    auto init(IOGraphicsAccelerator2*);
    auto lockForCPUAccess(task*, unsigned int);
    auto matchForReuse(void*, unsigned long long);
    auto orphanIt();
    auto setPurgeable(unsigned int, unsigned int*);
    auto setTag(unsigned int);
    auto unlockForCPUAccess(task*);
    auto unorphanIt(IOAccelShared2*);
    auto unwire();
    auto wire();
    auto withMemoryDescriptor(IOGraphicsAccelerator2*, IOAccelResource2*, IOMemoryDescriptor*);
    auto withOptions(IOGraphicsAccelerator2*, task*, IOAccelShared2*, IOAccelResource2*, unsigned int, unsigned long long);
    ~IOAccelSysMemory();
};
