//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSString;

@protocol NSObject
- (Class)(v;
- (id)@;
- (unsigned long long);
- (oneway void);
- (id)`;

@optional
- (NSString *)H	;

// Remaining properties
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

