//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class __gnu_cxx::__pool<false> {
public: // (access info unavailable from symbols alone)
    _M_destroy();
    _M_initialize();
    _M_reclaim_block(char*, unsigned long);
    _M_reserve_block(unsigned long, unsigned long);
};
