//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class std::__copy_streambufs<char, std {
public: // (access info unavailable from symbols alone)
    long char_traits<char>>(std::basic_streambuf<char, std::char_traits<char>>*, std::basic_streambuf<char, std::char_traits<char>>*);
};
