//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class std::__copy_streambufs_eof<wchar_t, std {
public: // (access info unavailable from symbols alone)
    long char_traits<wchar_t>>(std::basic_streambuf<wchar_t, std::char_traits<wchar_t>>*, std::basic_streambuf<wchar_t, std::char_traits<wchar_t>>*, bool&);
};
