//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

// Global C++ functions

AudioAUUC::gMetaClass;
AudioAUUC::metaClass;
AudioAUUC::superClass;
AudioAUUCDriver::gMetaClass;
AudioAUUCDriver::metaClass;
AudioAUUCDriver::superClass;
AudioAUUCDriver_ktv;
AudioAUUC_ktv;
IOAudioEngine::metaClass;
IOService::gMetaClass;
IOUserClient::gMetaClass;
OSNumber::metaClass;
vtable for AudioAUUC;
vtable for AudioAUUC::MetaClass;
vtable for AudioAUUCDriver;
vtable for AudioAUUCDriver::MetaClass;
vtable for IOService;
vtable for IOUserClient;
