//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AIDReporterState::Channel {
public: // (access info unavailable from symbols alone)
    addChannel(IOStateReporter*, AIDReporterState::FieldReporters*, unsigned int, unsigned long long*);
    addChannel(IOStateReporter*, AIDReporterState::FieldReporters*, unsigned int, unsigned long long*) (.cold.1);
    addChannel(IOStateReporter*, AIDReporterState::FieldReporters*, unsigned int, unsigned long long*) (.cold.2);
    addChannel(IOStateReporter*, AIDReporterState::FieldReporters*, unsigned int, unsigned long long*) (.cold.3);
    addChannel(IOStateReporter*, AIDReporterState::FieldReporters*, unsigned int, unsigned long long*) (.cold.4);
    addChannel(IOStateReporter*, AIDReporterState::FieldReporters*, unsigned int, unsigned long long*) (.cold.5);
    addChannel(IOStateReporter*, AIDReporterState::FieldReporters*, unsigned int, unsigned long long*) (.cold.6);
    addChannel(IOStateReporter*, AIDReporterState::FieldReporters*, unsigned int, unsigned long long*) (.cold.7);
    addChannel(IOStateReporter*, AIDReporterState::FieldReporters*, unsigned int, unsigned long long*) (.cold.8);
    init(AIDReporterState*, OSDictionary*);
    init(AIDReporterState*, OSDictionary*) (.cold.1);
    init(AIDReporterState*, OSDictionary*) (.cold.2);
    init(AIDReporterState*, OSDictionary*) (.cold.3);
    init(AIDReporterState*, OSDictionary*) (.cold.4);
    init(AIDReporterState*, OSDictionary*) (.cold.5);
    init(AIDReporterState*, OSDictionary*) (.cold.6);
    init(AIDReporterState*, OSDictionary*) (.cold.7);
    init(AIDReporterState*, OSDictionary*) (.cold.8);
    stateNameToStateId(char const*);
    updateReportWithData(IOStateReporter*, AIDReporterState::FieldReporters*, unsigned long long, unsigned long long, OSData const*);
    updateReportWithData(IOStateReporter*, AIDReporterState::FieldReporters*, unsigned long long, unsigned long long, OSData const*) (.cold.1);
    updateReportWithData(IOStateReporter*, AIDReporterState::FieldReporters*, unsigned long long, unsigned long long, OSData const*) (.cold.2);
    updateReportWithData(IOStateReporter*, AIDReporterState::FieldReporters*, unsigned long long, unsigned long long, OSData const*) (.cold.3);
    updateReportWithData(IOStateReporter*, AIDReporterState::FieldReporters*, unsigned long long, unsigned long long, OSData const*) (.cold.4);
    updateReportWithData(IOStateReporter*, AIDReporterState::FieldReporters*, unsigned long long, unsigned long long, OSData const*) (.cold.5);
    updateReportWithData(IOStateReporter*, AIDReporterState::FieldReporters*, unsigned long long, unsigned long long, OSData const*) (.cold.6);
    updateReportWithData(IOStateReporter*, AIDReporterState::FieldReporters*, unsigned long long, unsigned long long, OSData const*) (.cold.7);
};
