//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOSkywalkTxSubmissionQueue {
public: // (access info unavailable from symbols alone)
    IOSkywalkTxSubmissionQueue();
    IOSkywalkTxSubmissionQueue(OSMetaClass const*);
    _RESERVEDIOSkywalkTxSubmissionQueue0();
    _RESERVEDIOSkywalkTxSubmissionQueue1();
    _RESERVEDIOSkywalkTxSubmissionQueue10();
    _RESERVEDIOSkywalkTxSubmissionQueue2();
    _RESERVEDIOSkywalkTxSubmissionQueue3();
    _RESERVEDIOSkywalkTxSubmissionQueue4();
    _RESERVEDIOSkywalkTxSubmissionQueue5();
    _RESERVEDIOSkywalkTxSubmissionQueue6();
    _RESERVEDIOSkywalkTxSubmissionQueue7();
    _RESERVEDIOSkywalkTxSubmissionQueue8();
    _RESERVEDIOSkywalkTxSubmissionQueue9();
    addReporters(IOService*, OSSet*);
    adjustPacketCounters();
    checkForWork();
    disable();
    enable();
    finalize();
    free();
    free()::kalloc_type_view_190;
    free()::kalloc_type_view_193;
    getEffectiveCapacity(unsigned int);
    getMetaClass() const;
    getPacketCount() const;
    getPacketListForKPipe();
    getPacketListForNetworking(unsigned int, unsigned int, bool);
    getReportChannelValue(unsigned long long);
    initWithPool(IOSkywalkPacketBufferPool*, unsigned int, unsigned int, unsigned int, OSObject*, unsigned int (*)(OSObject*, IOSkywalkTxSubmissionQueue*, unsigned int*), unsigned int (*)(OSObject*, IOSkywalkTxSubmissionQueue*, IOSkywalkPacket* const*, unsigned int, void*), void*, unsigned int);
    initWithPool(IOSkywalkPacketBufferPool*, unsigned int, unsigned int, unsigned int, OSObject*, unsigned int (*)(OSObject*, IOSkywalkTxSubmissionQueue*, unsigned int*), unsigned int (*)(OSObject*, IOSkywalkTxSubmissionQueue*, IOSkywalkPacket* const*, unsigned int, void*), void*, unsigned int)::kalloc_type_view_131;
    initWithPool(IOSkywalkPacketBufferPool*, unsigned int, unsigned int, unsigned int, OSObject*, unsigned int (*)(OSObject*, IOSkywalkTxSubmissionQueue*, unsigned int*), unsigned int (*)(OSObject*, IOSkywalkTxSubmissionQueue*, IOSkywalkPacket* const*, unsigned int, void*), void*, unsigned int)::kalloc_type_view_155;
    initialize(void*);
    legacyDequeue();
    listDequeue();
    packetCompletion(IOSkywalkPacket*, IOSkywalkPacketQueue*, unsigned int);
    packetCompletion(unsigned int, unsigned int, bool);
    packetSubmission(bool);
    packetSubmission(unsigned long long*, unsigned int*, unsigned int*);
    packetSubmissionForKPipe(bool);
    performCommand(unsigned int, void*, unsigned long);
    purgePackets();
    purgePackets() (.cold.1);
    refillTxRingForKPipe(unsigned int);
    refillTxRingForKPipe(unsigned int, bool);
    refillTxRingForNetworking(unsigned int, unsigned int, bool);
    requestDequeue(void*, unsigned int);
    sendNotification(unsigned int);
    setNICObservedCount(unsigned int);
    synchronize(unsigned int);
    synchronize(unsigned int) (.cold.1);
    withPool(IOSkywalkPacketBufferPool*, unsigned int, unsigned int, OSObject*, unsigned int (*)(OSObject*, IOSkywalkTxSubmissionQueue*, IOSkywalkPacket* const*, unsigned int, void*), void*, unsigned int);
    withPool(IOSkywalkPacketBufferPool*, unsigned int, unsigned int, OSObject*, unsigned int (*)(OSObject*, IOSkywalkTxSubmissionQueue*, unsigned int*), unsigned int (*)(OSObject*, IOSkywalkTxSubmissionQueue*, IOSkywalkPacket* const*, unsigned int, void*), void*, unsigned int, unsigned int);
    withPool(IOSkywalkPacketBufferPool*, unsigned int, unsigned int, OSObject*, unsigned int (*)(OSObject*, IOSkywalkTxSubmissionQueue*, unsigned int*), unsigned int (*)(OSObject*, IOSkywalkTxSubmissionQueue*, IOSkywalkPacket**, unsigned int, void*), void*, unsigned int, unsigned int);
    ~IOSkywalkTxSubmissionQueue();
};
