//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOSkywalkNetworkNotificationHelper {
public: // (access info unavailable from symbols alone)
    IOSkywalkNetworkNotificationHelper();
    IOSkywalkNetworkNotificationHelper(OSMetaClass const*);
    createNotificationToken(IOSkywalkNetworkPacket const*, IOSkywalkNetworkInterface const*, unsigned int*);
    free();
    getMetaClass() const;
    initWithParams(IOSkywalkNetworkNotificationHelper::_IOSkywalkNetworkNotificationHelperParams const&);
    notifyWithToken(unsigned int, IOSkywalkNetworkNotificationStatus);
    withParams(IOSkywalkNetworkNotificationHelper::_IOSkywalkNetworkNotificationHelperParams const&);
    ~IOSkywalkNetworkNotificationHelper();
};
