//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOHDIXHDDriveOutKernelUserClient {
public: // (access info unavailable from symbols alone)
    IOHDIXHDDriveOutKernelUserClient();
    IOHDIXHDDriveOutKernelUserClient(OSMetaClass const*);
    auto activateDrive();
    auto clientClose();
    auto free();
    auto getMetaClass() const;
    auto getRequest64(HDIRequestOOL64 const*, HDIRequestOOL64*);
    auto getTargetAndMethodForIndex(IOService**, unsigned int);
    auto initWithTask(task*, void*, unsigned int);
    auto processReply64(HDIReplyOOL64 const*);
    auto registerClientBuffer64(HDIRequestOOL64 const*);
    auto start(IOService*);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~IOHDIXHDDriveOutKernelUserClient();
};
