//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOBufferMemoryDescriptor {
public: // (access info unavailable from symbols alone)
    inTaskWithOptions(task*, unsigned int, unsigned long, unsigned long);
    inTaskWithPhysicalMask(task*, unsigned int, unsigned long long, unsigned long long);
};
