//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class SCSIParallelWorkLoop {
public: // (access info unavailable from symbols alone)
    Create(char const*);
    InitWithLockGroupName(char const*);
    SCSIParallelWorkLoop();
    SCSIParallelWorkLoop(OSMetaClass const*);
    free();
    getMetaClass() const;
    ~SCSIParallelWorkLoop();
};
