//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class MeCab::Param::get<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1 {
public: // (access info unavailable from symbols alone)
    allocator<char>>>(char const*) const;
};
