//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class MeCab::Tokenizer<mecab_learner_node_t, mecab_learner_path_t> {
public: // (access info unavailable from symbols alone)
    Tokenizer();
    addUnknownNodes<false>(MeCab::CharInfo&, char const*, char const*, char const*, MeCab::Allocator<mecab_learner_node_t, mecab_learner_path_t>*, MeCab::Lattice*, mecab_learner_node_t*&) const;
    close();
    lookup<false>(char const*, char const*, MeCab::Allocator<mecab_learner_node_t, mecab_learner_path_t>*, MeCab::Lattice*) const;
    open(MeCab::Param const&);
    ~Tokenizer();
};
