//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSString;

@interface NFRunScriptParametersInternal
{
    _Bool _checkAIDAllowList;
}

+ (_Bool);
- (_Bool);
- (void);
- (void);
- (void);
- (void);
- (void)�C;
- (void);
- (void);
- (_Bool);
- (_Bool);
- (_Bool);
- (_Bool);
- (_Bool);
- (id);
- (void);
- (id);
- (id)!;
- (void)initWithExtensionBundleIdentifier:(id)arg1 kind: /* Error: Ran out of types for this method. */;
- (void);

// Remaining properties
@property(retain, nonatomic) NSString *seid; // @synthesize seid=_seid;

@end

