//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class std::basic_iostream<char, std::char_traits<char>> {
public: // (access info unavailable from symbols alone)
    basic_iostream();
    basic_iostream(std::basic_streambuf<char, std::char_traits<char>>*);
    ~basic_iostream();
};
