//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension _RegexParser.AST.Quantification {
    == infix(_RegexParser.AST.Quantification, _RegexParser.AST.Quantification) -> Swift.Bool
    hash(into: inout Swift.Hasher) -> ()
    init(_: _RegexParser.Source.Located<_RegexParser.AST.Quantification.Amount>, _: _RegexParser.Source.Located<_RegexParser.AST.Quantification.Kind>, _: _RegexParser.AST.Node, _: _RegexParser.Source.Location, trivia: Swift.Array<_RegexParser.AST.Trivia>) -> _RegexParser.AST.Quantification
}
