//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IODataQueue {
public: // (access info unavailable from symbols alone)
    IODataQueue();
    IODataQueue(OSMetaClass const*);
    auto enqueue(void*, unsigned int);
    auto free();
    auto getMemoryDescriptor();
    auto getMetaClass() const;
    auto initWithCapacity(unsigned int);
    auto initWithEntries(unsigned int, unsigned int);
    auto sendDataAvailableNotification();
    auto setNotificationPort(ipc_port*);
    auto withCapacity(unsigned int);
    auto withEntries(unsigned int, unsigned int);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~IODataQueue();
};
