//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOKitDiagnostics {
public: // (access info unavailable from symbols alone)
    IOKitDiagnostics();
    IOKitDiagnostics(OSMetaClass const*);
    auto diagnostics();
    auto getMetaClass() const;
    auto serialize(OSSerialize*) const;
    auto updateOffset(OSDictionary*, unsigned long long, char const*);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~IOKitDiagnostics();
};
