//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOPMPowerSource {
public: // (access info unavailable from symbols alone)
    IOPMPowerSource();
    IOPMPowerSource(OSMetaClass const*);
    auto adapterInfo();
    auto amperage();
    auto atCriticalLevel();
    auto atWarnLevel();
    auto batteryInstalled();
    auto capacityPercentRemaining();
    auto currentCapacity();
    auto cycleCount();
    auto errorCondition();
    auto externalChargeCapable();
    auto externalConnected();
    auto free();
    auto getMetaClass() const;
    auto getPSProperty(OSSymbol const*);
    auto init();
    auto isCharging();
    auto legacyIOBatteryInfo();
    auto location();
    auto manufacturer();
    auto maxCapacity();
    auto model();
    auto powerSource();
    auto serial();
    auto setAdapterInfo(int);
    auto setAmperage(int);
    auto setAtCriticalLevel(bool);
    auto setAtWarnLevel(bool);
    auto setBatteryInstalled(bool);
    auto setCurrentCapacity(unsigned int);
    auto setCycleCount(unsigned int);
    auto setErrorCondition(OSSymbol*);
    auto setExternalChargeCapable(bool);
    auto setExternalConnected(bool);
    auto setIsCharging(bool);
    auto setLegacyIOBatteryInfo(OSDictionary*);
    auto setLocation(int);
    auto setManufacturer(OSSymbol*);
    auto setMaxCapacity(unsigned int);
    auto setModel(OSSymbol*);
    auto setPSProperty(OSSymbol const*, OSObject*);
    auto setSerial(OSSymbol*);
    auto setTimeRemaining(int);
    auto setVoltage(unsigned int);
    auto timeRemaining();
    auto updateStatus();
    auto voltage();
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~IOPMPowerSource();
};
