//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOStateNotificationListener {
public: // (access info unavailable from symbols alone)
    IOStateNotificationListener();
    IOStateNotificationListener(OSMetaClass const*);
    free();
    getMetaClass() const;
    init();
    ~IOStateNotificationListener();
};
