//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOUserUserClient {
public: // (access info unavailable from symbols alone)
    IOUserUserClient();
    IOUserUserClient(OSMetaClass const*);
    clientClose();
    clientMemoryForType(unsigned int, unsigned int*, IOMemoryDescriptor**);
    eventlinkConfigurationTrap(void*, void*, void*, void*, void*, void*);
    externalMethod(unsigned int, IOExternalMethodArguments*, IOExternalMethodDispatch*, OSObject*, void*);
    free();
    getMetaClass() const;
    getTargetAndTrapForIndex(IOService**, unsigned int);
    init(OSDictionary*);
    setProperties(OSObject*);
    setTask(task*);
    stop(IOService*);
    workgroupConfigurationTrap(void*, void*, void*, void*, void*, void*);
    ~IOUserUserClient();
};
