//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class OSKextSavedMutableSegment {
public: // (access info unavailable from symbols alone)
    OSKextSavedMutableSegment();
    OSKextSavedMutableSegment(OSMetaClass const*);
    auto free();
    auto getMetaClass() const;
    auto getVMAddr() const;
    auto getVMSize() const;
    auto initWithSegment(segment_command_64*);
    auto restoreContents(segment_command_64*);
    auto withSegment(segment_command_64*);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~OSKextSavedMutableSegment();
};
