//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class OSMetaClass {
public: // (access info unavailable from symbols alone)
    OSMetaClass(char const*, OSMetaClass const*, unsigned int);
    OSMetaClass(char const*, OSMetaClass const*, unsigned int, zone**, char const*, zone_create_flags_t);
    _RESERVEDOSMetaClass0();
    _RESERVEDOSMetaClass1();
    _RESERVEDOSMetaClass2();
    _RESERVEDOSMetaClass3();
    _RESERVEDOSMetaClass4();
    _RESERVEDOSMetaClass5();
    _RESERVEDOSMetaClass6();
    _RESERVEDOSMetaClass7();
    addInstance(OSObject const*, bool) const;
    allocClassWithName(OSString const*);
    allocClassWithName(OSSymbol const*);
    allocClassWithName(char const*);
    applyToInstances(OSOrderedSet*, bool (*)(OSObject const*, void*), void*);
    applyToInstances(bool (*)(OSObject const*, void*), void*) const;
    applyToInstancesOfClassName(OSSymbol const*, bool (*)(OSObject const*, void*), void*);
    checkMetaCast(OSMetaClassBase const*) const;
    checkMetaCastWithName(OSString const*, OSMetaClassBase const*);
    checkMetaCastWithName(OSSymbol const*, OSMetaClassBase const*);
    checkMetaCastWithName(char const*, OSMetaClassBase const*);
    checkModLoad(void*);
    considerUnloads();
    copyMetaClassWithName(OSSymbol const*);
    getClassDictionary();
    getClassName() const;
    getClassNameSymbol() const;
    getClassSize() const;
    getInstanceCount() const;
    getKext() const;
    getKmodName() const;
    getMetaClass() const;
    getMetaClassWithName(OSSymbol const*);
    getRetainCount() const;
    getSuperClass() const;
    instanceConstructed() const;
    instanceDestructed() const;
    logError(int);
    modHasInstance(char const*);
    postModLoad(void*);
    preModLoad(char const*);
    printInstanceCounts();
    release() const;
    release(int) const;
    releaseMetaClass() const;
    removeClasses(OSCollection*);
    removeInstance(OSObject const*, bool) const;
    reportModInstances(char const*);
    reservedCalled(int) const;
    retain() const;
    serialize(OSSerialize*) const;
    serializeClassDictionary(OSDictionary*);
    taggedRelease(void const*) const;
    taggedRelease(void const*, int) const;
    taggedRetain(void const*) const;
    ~OSMetaClass();
};
