//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class OSUserMetaClass {
public: // (access info unavailable from symbols alone)
    Dispatch(IORPC);
    OSUserMetaClass();
    OSUserMetaClass(OSMetaClass const*);
    free();
    getMetaClass() const;
    ~OSUserMetaClass();
};
