//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AMDRadeonX6810_AMDRadeonHWLibsX6810 {
public: // (access info unavailable from symbols alone)
    AMDRadeonX6810_AMDRadeonHWLibsX6810();
    AMDRadeonX6810_AMDRadeonHWLibsX6810(OSMetaClass const*);
    auto getMetaClass() const;
    auto populateFirmwareDirectory();
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~AMDRadeonX6810_AMDRadeonHWLibsX6810();
};
