//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSString;

__attribute__((visibility("hidden")))
@interface ProductionSRSensorWriterProvider
{
    _Bool _isBundleIdentifierEligible;
    _Bool _isValidSRSensorWriterPresent;
    _Bool _isMonitoring;
}

- (_Bool);
- (_Bool);
- (id);
- (_Bool);
- (_Bool);
- (_Bool);

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) _Bool isBundleIdentifierEligible; // @synthesize isBundleIdentifierEligible=_isBundleIdentifierEligible;
@property(readonly, nonatomic) _Bool isMonitoring; // @synthesize isMonitoring=_isMonitoring;
@property(readonly, nonatomic) _Bool isValidSRSensorWriterPresent; // @synthesize isValidSRSensorWriterPresent=_isValidSRSensorWriterPresent;
@property(readonly) Class superclass;

@end

