//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

// Global C++ functions

IOBDBlockStorageDevice::gMetaClass;
IOBDBlockStorageDevice::metaClass;
IOBDBlockStorageDevice::superClass;
IOBDBlockStorageDevice_ktv;
IOBDBlockStorageDriver::gMetaClass;
IOBDBlockStorageDriver::metaClass;
IOBDBlockStorageDriver::superClass;
IOBDBlockStorageDriver_ktv;
IOBDMedia::gMetaClass;
IOBDMedia::metaClass;
IOBDMedia::superClass;
IOBDMediaBSDClient::gMetaClass;
IOBDMediaBSDClient::metaClass;
IOBDMediaBSDClient::superClass;
IOBDMediaBSDClient_ktv;
IOBDMedia_ktv;
IODVDBlockStorageDevice::gMetaClass;
IODVDBlockStorageDriver::gMetaClass;
IOMedia::gMetaClass;
IOMediaBSDClient::gMetaClass;
auto DKIOC_PREPARE_BUFFER(unsigned long long, unsigned int, unsigned int, proc*);
vtable for IOBDBlockStorageDevice;
vtable for IOBDBlockStorageDevice::MetaClass;
vtable for IOBDBlockStorageDriver;
vtable for IOBDBlockStorageDriver::MetaClass;
vtable for IOBDMedia;
vtable for IOBDMedia::MetaClass;
vtable for IOBDMediaBSDClient;
vtable for IOBDMediaBSDClient::MetaClass;
vtable for IOBlockStorageDriver;
vtable for IODVDBlockStorageDevice;
vtable for IODVDBlockStorageDriver;
vtable for IOMedia;
vtable for IOMediaBSDClient;
vtable for IOService;
