//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension AppIntents.ParameterSummaryString.StringInterpolation {
    appendLiteral(Swift.String) -> ()
    init(literalCapacity: Swift.Int, interpolationCount: Swift.Int) -> AppIntents.ParameterSummaryString<A>.StringInterpolation
}
