//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension AppIntents._AssistantIntent.Phrase {
    init(stringInterpolation: AppIntents._AssistantIntent.Phrase<A>.StringInterpolation) -> AppIntents._AssistantIntent.Phrase<A>
    init(stringLiteral: Swift.String) -> AppIntents._AssistantIntent.Phrase<A>
}
