//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, NSURL, UTType;

@protocol NSOpenSavePanelDelegate <NSObject>

@optional
- (void)panel:(id)arg1 didSelectType:(UTType *)arg2;
- (NSString *)panel:(id)arg1 displayNameForType:(UTType *)arg2;
- (void)panelSelectionDidChange:(id)arg1;
- (void)panel:(id)arg1 willExpand:(_Bool)arg2;
- (NSString *)panel:(id)arg1 userEnteredFilename:(NSString *)arg2 confirmed:(_Bool)arg3;
- (void)panel:(id)arg1 didChangeToDirectoryURL:(NSURL *)arg2;
- (_Bool)panel:(id)arg1 validateURL:(NSURL *)arg2 error:(id *)arg3;
- (_Bool)panel:(id)arg1 shouldEnableURL:(NSURL *)arg2;
@end

