//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSView, NSWindow, TAirDropProgressController;

@protocol TAirDropProgressControllerDelegate <NSObject>
- (NSView *)airDropProgressPopoverHostViewForNode:(const struct TFENode *)arg1 outFrameInView:(struct CGRect *)arg2;
- (NSWindow *)airDropProgressPopoverHostWindow;
- (void)hideAirDropInlineProgressForNode:(const struct TFENode *)arg1;
- (void)showAirDropInlineProgressForNode:(const struct TFENode *)arg1 progressController:(TAirDropProgressController *)arg2;
@end

