//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "TCoalescingNodeObserverProtocol-Protocol.h"

@class NSMutableArray, NSString;

@interface TAirDropProgressControllerRegistry : NSObject <TCoalescingNodeObserverProtocol>
{
    NSMutableArray *_controllers;
    struct vector<TNSWeakPtr<NSObject<TAirDropProgressControllerDelegate>>, std::allocator<TNSWeakPtr<NSObject<TAirDropProgressControllerDelegate>>>> _weakDelegates;
    struct shared_ptr<TCoalescingNodeObserverCocoaBridge> _nodeObserver;
    _Bool _isUserInAirDrop;
    TNSWeakPtr_6693ddb8 _updateControllersToken;
    struct TNotificationCenterObserver _userEnteredOrExitedAirDropObserver;
    struct TNotificationCenterObserver _airDropAvailableStateChangedObserver;
}

+ (void)removeAllControllers;
+ (void)removeController:(id)arg1;
+ (_Bool)isPopoverShown;
+ (id)findControllerForNode:(const struct TFENode *)arg1;
+ (id)controllerForNode:(const struct TFENode *)arg1;
+ (void)enumerateDelegates:(const void *)arg1;
+ (void)unregisterProgressControllerDelegate:(id)arg1;
+ (void)registerProgressControllerDelegate:(id)arg1;
+ (void)tearDownIfNeeded;
+ (id)getOrCreateRegistry;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)findControllerForNodeLocked:(const struct TFENode *)arg1;
- (void)coalescingNodeObserver:(void *)arg1 nodesAdded:(const void *)arg2 toObservedNode:(const struct TFENode *)arg3;
- (void)airDropAvailabilityChanged:(id)arg1;
- (void)userEnteredOrExitedAirDrop:(id)arg1;
- (void)setIsUserInAirDrop:(_Bool)arg1;
- (void)updateControllers;
- (void)callUpdateControllersAfterDelay;
- (void)aboutToTearDown;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

