//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TTableViewController.h"

@interface TBackupVolumeTableViewController : TTableViewController
{
    struct TFENodeVector _excludeNodes;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)setExcludeNodes:(const void *)arg1;
- (void)volumeNameChanged:(const struct TFENode *)arg1;
- (void)backupStoreDeleted:(const struct TFENode *)arg1;
- (void)backupStoreAdded:(const struct TFENode *)arg1;
- (void)refresh;
- (void)handleDoubleClick:(id)arg1;
- (void)tableViewSelectionDidChange:(id)arg1;
- (void)setView:(id)arg1;
- (void)configureView;

@end

