//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSSplitViewItemAccessoryViewController.h>

#import "FPUIActionViewControllerDelegate-Protocol.h"
#import "NSPopoverDelegate-Protocol.h"
#import "TCoalescingNodeObserverProtocol-Protocol.h"
#import "TMarkTornDown-Protocol.h"

@class FINode, ICQInAppMessage, NSButton, NSLayoutConstraint, NSString, NSTextField, TImageView, TPopover, _SWCollaborationDetailViewController;

@interface TBannerViewController : NSSplitViewItemAccessoryViewController <FPUIActionViewControllerDelegate, TMarkTornDown, TCoalescingNodeObserverProtocol, NSPopoverDelegate>
{
    struct shared_ptr<TCoalescingNodeObserverCocoaBridge> _nodeObserver;
    struct TFENode _observedNode;
    struct TNotificationCenterObserver _finderPrefsChangedObserver;
    NSButton *_secondButton;
    TImageView *_symbolView;
    NSTextField *_textField;
    NSButton *_primaryButton;
    ICQInAppMessage *_icqMessage;
    NSLayoutConstraint *_textToSecondaryButtonConstraint;
    NSLayoutConstraint *_textToPrimaryButtonConstraint;
    NSString *_secondButtonTitle;
    _Bool _isButtonEnabled;
    _Bool _isSecondaryButtonEnabled;
    _Bool _isTornDown;
    int _type;
    NSString *_text;
    NSString *_buttonTitle;
    TPopover *_popover;
    _SWCollaborationDetailViewController *_collaborationDetailController;
    FINode *_collaborationNode;
}

- (id).cxx_construct;
- (void).cxx_destruct;
@property(retain, nonatomic) FINode *collaborationNode; // @synthesize collaborationNode=_collaborationNode;
@property(retain, nonatomic) _SWCollaborationDetailViewController *collaborationDetailController; // @synthesize collaborationDetailController=_collaborationDetailController;
@property(nonatomic) int type; // @synthesize type=_type;
@property(retain, nonatomic) TPopover *popover; // @synthesize popover=_popover;
@property(copy, nonatomic) NSString *buttonTitle; // @synthesize buttonTitle=_buttonTitle;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
@property(getter=isTornDown) _Bool tornDown; // @synthesize tornDown=_isTornDown;
@property(nonatomic, getter=isSecondaryButtonEnabled) _Bool secondaryButtonEnabled; // @synthesize secondaryButtonEnabled=_isSecondaryButtonEnabled;
@property(nonatomic, getter=isButtonEnabled) _Bool buttonEnabled; // @synthesize buttonEnabled=_isButtonEnabled;
- (id)nibBundle;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithNibName:(id)arg1;
- (void)actionControllerDidFinishAction:(id)arg1 error:(id)arg2;
- (void)coalescingNodeObserver:(void *)arg1 nodesChanged:(const void *)arg2 inObservedNode:(const struct TFENode *)arg3;
- (void)coalescingNodeObserver:(void *)arg1 openSyncCompleted:(const struct TFENode *)arg2;
- (void)coalescingNodeObserver:(void *)arg1 nodesDeleted:(const void *)arg2 fromObservedNode:(const struct TFENode *)arg3;
- (void)coalescingNodeObserver:(void *)arg1 nodesAdded:(const void *)arg2 toObservedNode:(const struct TFENode *)arg3;
- (void)populationChangedInContainerNode:(const struct TFENode *)arg1;
- (void)stopObservingTargetNode;
- (void)startObservingTargetNode;
- (void)launchItemsPermissionsRepairForSync;
- (void)presentAuthenticationUI;
- (void)restartFileProviderObservers;
- (void)burn;
- (_Bool)buttonEnabledStateForBurnFolder;
- (struct TString)textForBurnFolder;
- (void)emptyTrash;
- (struct TString)buttonTitleForTrashFolder;
- (_Bool)buttonEnabledStateForTrashFolder;
- (void)updateBannerState;
- (struct TString)domainBannerName;
- (void)popoverDidClose:(id)arg1;
- (void)showCollaborationPopoverOrManageSharedFolder:(id)arg1;
- (void)preheatCollaborationDetailController;
- (void)secondaryButtonPressed:(id)arg1;
- (void)buttonPressed:(id)arg1;
- (void)setRepresentedObject:(id)arg1;
- (struct TFENode)representedNode;
@property(copy, nonatomic) NSString *secondButtonTitle;
- (void)updateDynamicConstraints;
- (void)setupDynamicConstraints;
- (void)viewDidLoad;
- (void)dealloc;
- (void)aboutToTearDown;
- (id)initICQMessage:(id)arg1;
- (id)initWithBannerType:(int)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

