//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TUpdateLayerView.h"

#import "NSSpringLoadingDestination-Protocol.h"
#import "TDesktopIconViewDelegate-Protocol.h"
#import "TMarkTornDown-Protocol.h"
#import "TShrinkToFitDelegateProtocol-Protocol.h"
#import "TTrackingAreaOwnerProtocol-Protocol.h"

@class NSObject, NSString, TBrowserViewDataSource, TDesktopBandSelectionController, TDesktopGridLayoutController, TDesktopIconSpatialDataController, TDesktopIconView, TDesktopInlinePreviewController, TDesktopSelectionController, TDesktopViewPileItem, TRenameOperation, TShrinkToFitController;
@protocol TDesktopViewDelegate;

@interface TDesktopView : TUpdateLayerView <TShrinkToFitDelegateProtocol, TTrackingAreaOwnerProtocol, NSSpringLoadingDestination, TMarkTornDown, TDesktopIconViewDelegate>
{
    struct TNSWeakPtr<TBrowserViewDataSource> _dataSource;
    struct TNSWeakPtr<TDesktopSelectionController> _selectionController;
    struct TNSWeakPtr<TDesktopGridLayoutController> _gridLayoutController;
    struct TNSWeakPtr<TDesktopIconSpatialDataController> _spatialDataController;
    struct TNSWeakPtr<TDesktopBandSelectionController> _bandSelectionController;
    struct TNSWeakPtr<TDesktopInlinePreviewController> _inlinePreviewController;
    TShrinkToFitController *_stfController;
    struct TFENode _nodeBeingEdited;
    TUpdateLayerView *_bandSelectionView;
    TDesktopIconView *_anchoredDesktopIconView;
    struct TNSWeakPtr<NSObject<TDesktopViewDelegate>> _weakDelegate;
    int _delegateRespondsTo;
    struct TFENode _pendingNodeToEdit;
    TRenameOperation *_pendingRenameOp;
    _Bool _pendingNewFolderAnimation;
    unordered_set_f685e29b _pendingNodesToAnimate;
    struct TKeyValueObserver _inlinePreviewEnabledStateObserver;
    struct TKeyValueBinder _globalBandSelectionFrameBinder;
    struct unordered_map<TFENode, TDesktopViewItem *, std::hash<TFENode>, std::equal_to<TFENode>, std::allocator<std::pair<const TFENode, TDesktopViewItem *>>> _nodeToDVItemInViewMap;
    struct unordered_map<TDesktopIconView *, TDesktopViewItem *__weak, std::hash<TDesktopIconView *>, std::equal_to<TDesktopIconView *>, std::allocator<std::pair<TDesktopIconView *const, TDesktopViewItem *__weak>>> _desktopIconViewToDVItemMap;
    unsigned long long _layoutIsSuspendedCount;
    _Bool _isTornDown;
    _Bool _keepArranged;
    _Bool _snapToGrid;
    _Bool _togglePileInProgress;
    TDesktopViewPileItem *_pileDVItemBeingSkimmed;
}

- (id).cxx_construct;
- (void).cxx_destruct;
@property(retain, nonatomic) TDesktopViewPileItem *pileDVItemBeingSkimmed; // @synthesize pileDVItemBeingSkimmed=_pileDVItemBeingSkimmed;
@property _Bool togglePileInProgress; // @synthesize togglePileInProgress=_togglePileInProgress;
@property(nonatomic) _Bool snapToGrid; // @synthesize snapToGrid=_snapToGrid;
@property(nonatomic) _Bool keepArranged; // @synthesize keepArranged=_keepArranged;
@property(getter=isTornDown) _Bool tornDown; // @synthesize tornDown=_isTornDown;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)dataSourceChanged:(const void *)arg1;
- (void)updateInlineProgressForIconView:(id)arg1 node:(const struct TFENode *)arg2;
- (void)finishRemovingDesktopViewItem:(id)arg1;
- (void)hideDesktopIcon:(id)arg1 dvItem:(id)arg2 wasDeleted:(_Bool)arg3;
- (void)showDesktopIcon:(id)arg1 dvItem:(id)arg2 animate:(_Bool)arg3;
- (void)removeDesktopIcon:(id)arg1 dvItem:(id)arg2 wasDeleted:(_Bool)arg3;
- (void)addDesktopIcon:(id)arg1 forDVItem:(id)arg2;
- (id)createDesktopIconViewForNode:(const struct TFENode *)arg1 localAnchorPoint:(const struct CGPoint *)arg2 hidden:(_Bool)arg3;
- (id)createDesktopViewItem:(id)arg1 desktopIconView:(id)arg2;
- (void)removeDesktopIconsWithPredicate:(const void *)arg1 wasDeleted:(_Bool)arg2 animated:(_Bool)arg3;
- (void)removeDesktopIcons:(id)arg1 wasDeleted:(_Bool)arg2 animated:(_Bool)arg3;
- (void)removeAllDesktopIcons:(_Bool)arg1 animated:(_Bool)arg2;
- (void)layout_addRemoveAndMoveIconViews:(_Bool)arg1:(_Bool)arg2;
- (void)layout_removeAllIconViews:(_Bool)arg1;
- (void)_layout;
- (void)layout;
@property(nonatomic) _Bool layoutIsSuspended;
- (void)markLayoutDirty;
- (void)accessibilityGetNodes:(void *)arg1 forUIElements:(id)arg2;
- (id)accessibilitySelectedChildrenAttributeValue;
- (id)accessibilityAttributeValue:(id)arg1;
- (id)accessibilityAttributeNames;
- (_Bool)accessibilityIsIgnored;
- (struct CGPoint)convertPointToDesktop:(const struct CGPoint *)arg1;
- (struct CGRect)convertRectToDesktop:(const struct CGRect *)arg1;
- (struct CGPoint)convertPointFromDesktop:(const struct CGPoint *)arg1;
- (struct CGRect)convertRectFromDesktop:(const struct CGRect *)arg1;
- (void)groupAsFolderUndoAnimateNodes:(const void *)arg1 withDesktopAnchorPoints:(const void *)arg2 outOfFolder:(const struct TFENode *)arg3 atDesktopAnchorPoint:(const struct CGPoint *)arg4;
- (void)groupAsFolderAnimateNodes:(const void *)arg1 withDesktopAnchorPoints:(const void *)arg2 intoFolderItem:(id)arg3 atDesktopAnchorPoint:(const struct CGPoint *)arg4;
- (_Bool)inlinePreviewIsVisible:(_Bool)arg1 forNode:(const struct TFENode *)arg2;
- (void)inlinePreviewEnabledStateChanged:(id)arg1;
- (void)configureAnchoredDesktopIconViewForNode:(const struct TFENode *)arg1;
- (struct CGRect)anchoredDesktopIconViewFlippedFrame;
- (struct CGRect)anchoredDesktopIconViewFrame;
- (id)anchoredDesktopIconViewPriv;
- (void)bringNodeToFront:(const struct TFENode *)arg1;
- (id)popoverAnchorViewForNode:(const struct TFENode *)arg1;
- (unsigned long long)desktopIconCount;
- (id)desktopItemInViewForNode:(const struct TFENode *)arg1;
- (id)desktopItemForNode:(const struct TFENode *)arg1;
- (id)desktopViewItemForNode:(const struct TFENode *)arg1;
- (id)desktopIconForNode:(const struct TFENode *)arg1;
- (struct TFENode)nodeForDesktopIconView:(id)arg1;
- (void)preflightSnapToGridAnimation:(const void *)arg1 withDesktopAnchorPoints:(const void *)arg2;
- (void)finishPlaceholderIconAnimation:(const void *)arg1;
- (void)preflightPlaceholderIconAnimation:(const void *)arg1 withDesktopAnchorPoints:(const void *)arg2 hidden:(_Bool)arg3;
- (id)addPlaceholderDesktopIcon:(id)arg1 atDesktopAnchorPoint:(const struct CGPoint *)arg2 hidden:(_Bool)arg3;
- (void)desktopIcon:(id)arg1 createHiddenAnimationIfNeeded:(_Bool)arg2;
- (void)iconOrTitleFramesChanged:(id)arg1 newIconFrame:(const struct CGRect *)arg2 newTitleFrame:(const struct CGRect *)arg3;
@property(nonatomic, getter=isSubtitleEnabled) _Bool subtitleEnabled;
@property(nonatomic, getter=isTitleOnBottom) _Bool titleOnBottom;
@property(nonatomic) double gridSpacing;
@property(nonatomic) unsigned long long textSize;
@property(nonatomic) unsigned long long iconSize;
- (int)editingSelectionType;
- (void)shrinkToFitTextViewAboutToClose;
- (void)shrinkToFitTextViewEditingComplete:(id)arg1;
- (_Bool)shrinkToFitTextViewAboutToOpen;
- (tuple_218402bb)pendingNodeToEditHasAppeared;
- (_Bool)stopEditing:(_Bool)arg1;
- (_Bool)startEditingNodeNowOrLater:(const struct TFENode *)arg1 runNewFolderAnimation:(_Bool)arg2 renameOp:(id)arg3;
- (_Bool)startEditingWithNode:(const struct TFENode *)arg1 runNewFolderAnimation:(_Bool)arg2 renameOp:(id)arg3 afterDelay:(_Bool)arg4;
- (struct TFENodeVector)nodesInView;
- (void)getNodes:(void *)arg1 inLocalFrame:(const struct CGRect *)arg2 boundsCheckOnly:(_Bool)arg3;
- (struct TFENode)nodeAtPoint:(const struct CGPoint *)arg1;
- (id)desktopIconAtPoint:(const struct CGPoint *)arg1;
- (id)hitTestInDesktopIconViewIcon:(const struct CGPoint *)arg1;
- (id)hitTestInDesktopIconViewText:(const struct CGPoint *)arg1;
- (id)hitTestInDesktopIconViewIconOrText:(const struct CGPoint *)arg1;
- (id)_hitTest:(const struct CGPoint *)arg1 desktopIconHitTest:(const void *)arg2;
- (id)inputContext;
- (_Bool)canBecomeKeyView;
- (_Bool)acceptsFirstResponder;
- (_Bool)acceptsFirstMouse:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)finishDropAnimation:(const void *)arg1 groupNodes:(const void *)arg2;
- (void)startDropAnimation:(const void *)arg1;
- (void)preflightDropAnimation:(const void *)arg1 withDesktopAnchorPoints:(const void *)arg2 andGroupNodes:(const void *)arg3;
- (id)dragFlockingImageComponentsForNode:(const struct TFENode *)arg1;
- (id)_dragFlockingImageComponentsForDesktopIcon:(id)arg1;
- (unsigned long long)springLoadingUpdated:(id)arg1;
- (void)springLoadingHighlightChanged:(id)arg1;
- (void)springLoadingActivated:(_Bool)arg1 draggingInfo:(id)arg2;
- (_Bool)wantsPeriodicDraggingUpdates;
- (void)concludeDragOperation:(id)arg1;
- (_Bool)performDragOperation:(id)arg1;
- (_Bool)prepareForDragOperation:(id)arg1;
- (void)updateDraggingItemsForDrag:(id)arg1;
- (void)draggingEnded:(id)arg1;
- (void)draggingExited:(id)arg1;
- (unsigned long long)draggingUpdated:(id)arg1;
- (unsigned long long)draggingEntered:(id)arg1;
@property struct CGRect globalBandSelectionFrame;
@property(nonatomic) __weak NSObject<TDesktopViewDelegate> *delegate;
@property(nonatomic) __weak TDesktopInlinePreviewController *inlinePreviewController;
@property(nonatomic) __weak TDesktopBandSelectionController *bandSelectionController;
@property(nonatomic) __weak TDesktopIconSpatialDataController *spatialDataController;
@property(nonatomic) __weak TDesktopGridLayoutController *gridLayoutController;
@property(nonatomic) __weak TDesktopSelectionController *selectionController;
@property(nonatomic) __weak TBrowserViewDataSource *dataSource;
- (struct IconSpatialData)spatialDataFromViewSpatialData:(const struct IconSpatialData *)arg1;
- (_Bool)setNode:(const struct TFENode *)arg1 hidden:(_Bool)arg2;
- (_Bool)isNode:(const struct TFENode *)arg1 hidden:(_Bool *)arg2;
- (_Bool)containsNode:(const struct TFENode *)arg1;
- (void)setFrameSize:(struct CGSize)arg1;
- (struct CGRect)iconFrameForNode:(const struct TFENode *)arg1;
- (struct CGRect)frameForNode:(const struct TFENode *)arg1;
- (struct CGPoint)anchorPointForNode:(const struct TFENode *)arg1;
- (void)stopTrackingDesktopIconForPileSkimming:(id)arg1;
- (void)startTrackingDesktopIconForPileSkimming:(id)arg1;
- (void)displayConfigurationChanged;
- (_Bool)updateAnchoredGridCellFrame;
- (struct TFENode)target;
- (struct CGPoint)invalidLocalAnchorPoint;
- (void)aboutToTearDown;
- (void)initCommon;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

