//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "TMTargetCachePrimable-Protocol.h"

@class NSString;

@interface TFinderBackupCacheInfo : NSObject <TMTargetCachePrimable>
{
    struct TFENode _iCloudAggregateNode;
}

- (id).cxx_construct;
- (void).cxx_destruct;
@property struct TFENode iCloudAggregateNode; // @synthesize iCloudAggregateNode=_iCloudAggregateNode;
- (void)primeForBackup:(id)arg1 targetCache:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

