//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSImage;

@protocol TImageAttachmentContainer <NSObject>
- (_Bool)setImageAttachment:(NSImage *)arg1 toolTip:(const void *)arg2;
@end

