//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TBaseInfoWindowViewController.h"

#import "CAAnimationDelegate-Protocol.h"

@class NSBox, NSLayoutConstraint, NSString;

@interface TInfoWindowViewController : TBaseInfoWindowViewController <CAAnimationDelegate>
{
    NSBox *_separator;
    NSLayoutConstraint *_separatorGapConstraint;
    NSLayoutConstraint *_disclosedHeightConstraint;
    _Bool _expanded;
    _Bool _prefExpanded;
    _Bool _isToggleInProgress;
}

+ (void)_expandAllAsync:(id)arg1 expanded:(_Bool)arg2;
- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool isToggleInProgress; // @synthesize isToggleInProgress=_isToggleInProgress;
@property(nonatomic) _Bool expanded; // @synthesize expanded=_expanded;
- (void)nodeMDAttributeChanged:(const struct TFENode *)arg1 attributes:(id)arg2 isDisplayAttributes:(_Bool)arg3;
- (void)nodesGoingAway:(const void *)arg1;
- (void)bulkNodesDeleted:(const void *)arg1;
- (void)bulkNodesChanged:(const void *)arg1;
@property(nonatomic) _Bool prefExpanded; // @synthesize prefExpanded=_prefExpanded;
- (id)expandedPrefKey;
- (_Bool)expandedDefaultValue;
- (double)disclosedHeight;
- (void)setTargetNodes:(const void *)arg1;
- (void)_setExpandedPriv:(_Bool)arg1;
- (void)updateExpandedConstraints:(_Bool)arg1 animated:(_Bool)arg2;
- (unsigned int)scriptingID;
- (void)setSubviewsHidden:(_Bool)arg1;
- (void)postToggle;
- (void)preToggle;
@property(nonatomic) _Bool separatorHidden;
- (void)configureView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

