//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class TMTargetCache;
@protocol TMMountableBackupProtocol;

@protocol TMTargetCachePrimable <NSObject>
- (void)primeForBackup:(id <TMMountableBackupProtocol>)arg1 targetCache:(TMTargetCache *)arg2;
@end

