//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSPathControlDelegate-Protocol.h"

@class NSEvent, NSImage, NSPathComponentCell, TPathControl;
@protocol NSDraggingInfo;

@protocol TPathControlDelegate <NSPathControlDelegate>
- (const struct TFENode *)nodeForCell:(NSPathComponentCell *)arg1;
- (void)pathBar:(TPathControl *)arg1 dragImage:(NSImage *)arg2 offset:(struct CGSize)arg3 event:(NSEvent *)arg4;
- (void)pathBar:(TPathControl *)arg1 draggingEnded:(id <NSDraggingInfo>)arg2;
- (void)pathBar:(TPathControl *)arg1 draggingExited:(id <NSDraggingInfo>)arg2;
- (unsigned long long)pathBar:(TPathControl *)arg1 draggingEntered:(id <NSDraggingInfo>)arg2;
@end

