//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "IPropertyNumberApplicator.h"

@interface TPrivsIgnoreOwnershipCheckboxApplicator : IPropertyNumberApplicator
{
}

- (int)applyValue:(id)arg1 toNodes:(const void *)arg2;

@end

