//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TSizePropertyExtractor.h"

@interface TPropertyLogicalSizeExtractor : TSizePropertyExtractor
{
}

+ (id)extractor;

@end

