//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSProgressIndicator.h>

@interface TProgressIndicator : NSProgressIndicator
{
    _Bool _animateWhenIndeterminate;
}

@property(nonatomic) _Bool animateWhenIndeterminate; // @synthesize animateWhenIndeterminate=_animateWhenIndeterminate;
- (void)viewDidMoveToWindow;
- (void)setIndeterminate:(_Bool)arg1;
- (void)initCommon;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

