//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TPropertyButtonController.h"

@class NSLayoutConstraint, TUpdateLayerView;

@interface TPropertyOpenUsingCambriaController : TPropertyButtonController
{
    NSLayoutConstraint *_leadingConstraint;
    TUpdateLayerView *_wrapperView;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) TUpdateLayerView *wrapperView; // @synthesize wrapperView=_wrapperView;
@property(nonatomic) double leadingConstraintConstant;
- (void)initCommon;

@end

