//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ViewBridge/NSPreviewTargetController.h>

@interface TSavePanelTargetController : NSPreviewTargetController
{
}

+ (_Bool)allowInstantiationOnBehalfOf:(CDStruct_4c969caf)arg1;
+ (id)windowWithFrame:(struct CGRect)arg1 styleMask:(unsigned long long)arg2;
+ (Class)windowClass;
+ (id)hostControllerInterface;
+ (id)targetControllerInterface;
- (void)targetDidCompleteBootstrap;
- (id)exportedObject;

@end

