//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@class NSImage, NSString, NSTrackingArea, TMouseOverButton;

@interface TSidebarItemCell : NSTableCellView
{
    struct TFENode _node;
    _Bool _selected;
    _Bool _isEditing;
    _Bool _enabled;
    TMouseOverButton *_button;
    function_12bc7359 _iconGetter;
    NSTrackingArea *_trackingArea;
    struct function<void (TSidebarItemCell *, bool)> _fTrackingCallback;
    struct vector<TNotificationCenterObserver, std::allocator<TNotificationCenterObserver>> _observers;
    _Bool _drawingDragImage;
    int _stateID;
}

+ (void)drawSidebarIcon:(id)arg1 inRect:(struct CGRect)arg2 inContext:(struct CGContext *)arg3 highlighted:(_Bool)arg4;
+ (const struct TFENode *)nodeForItem:(id)arg1;
+ (struct CGRect)roughActionButtonRectForCell:(const struct CGRect *)arg1;
+ (_Bool)prefersTrackingUntilMouseUp;
+ (id)makeSidebarItemCellForView:(id)arg1;
- (id).cxx_construct;
- (void).cxx_destruct;
@property(nonatomic) _Bool drawingDragImage; // @synthesize drawingDragImage=_drawingDragImage;
@property(nonatomic) int stateID; // @synthesize stateID=_stateID;
@property(retain, nonatomic) TMouseOverButton *button; // @synthesize button=_button;
@property(nonatomic) _Bool isEditing; // @synthesize isEditing=_isEditing;
@property(nonatomic) _Bool selected; // @synthesize selected=_selected;
- (void)updateLayer;
- (void)viewWillDraw;
- (void)layoutDetails;
- (struct CGRect)_textFieldFrame;
- (double)textFieldFirstBaselineOffsetFromTop;
@property(readonly, nonatomic) NSImage *image;
@property(nonatomic, getter=isEnabled) _Bool enabled;
- (void)setStringValue:(const void *)arg1;
- (struct CGRect)imageRectForBounds:(struct CGRect)arg1;
- (struct CGRect)titleRectForBounds:(struct CGRect)arg1;
- (double)imageSize;
- (_Bool)isHighlighted;
- (void)accessibilityPerformAction:(id)arg1;
- (id)accessibilityActionDescription:(id)arg1;
- (id)accessibilityActionNames;
- (_Bool)accessibilityIsAttributeSettable:(id)arg1;
- (id)accessibilityAttributeValue:(id)arg1;
- (id)accessibilityAttributeNames;
- (void)displayRectIgnoringOpacity:(struct CGRect)arg1 inContext:(id)arg2;
- (double)optimalWidthForHeight:(double)arg1;
@property(readonly, nonatomic) NSString *name;
- (_Bool)isZone;
- (id)description;
- (id)dataForIdentifier:(id)arg1;
- (void)finishMakingWithNode:(const struct TFENode *)arg1 iconGetter:(function_12bc7359)arg2;
- (void)setRowSizeStyle:(long long)arg1;
- (void)updateNameAndIcon;
- (void)updateActionButtonAXTitle:(const void *)arg1;
- (void)setActionButtonStateFor:(int)arg1 action:(const void *)arg2 buttonStateTransitions:(const void *)arg3;
- (void)addActionButtonIfNeeded;
- (_Bool)isButtonRolledOver;
- (void)windowDidBecomeKey;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)addTrackingCallback:(const void *)arg1;
- (void)prepareForReuse;
- (void)aboutToTearDown;
- (id)initWithFrame:(struct CGRect)arg1;

@end

