//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TUpdateLayerView.h"

#import "NSAccessibilityElement-Protocol.h"

@class NSString;

@interface TStatusBar : TUpdateLayerView <NSAccessibilityElement>
{
}

- (_Bool)isAccessibilityElement;
- (id)accessibilityValueDescription;
- (_Bool)acceptsFirstMouse:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)setFrameSize:(struct CGSize)arg1;
- (_Bool)preservesContentDuringLiveResize;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

