//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol TTypeSelectDelegate <NSObject>
- (void)typeSelectNode:(const struct TFENode *)arg1;
- (unsigned long long)typeSelectGetSelectedNodes:(void *)arg1;
- (struct TFENodeVector)typeSelectCandidateNodes;

@optional
- (_Bool)nodeIsDimmed:(const struct TFENode *)arg1;
@end

