//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@protocol TUpdateLayoutControllerSuspenderProtocol
@property(nonatomic) _Bool isUpdateLayoutControllerDirty;
@property(nonatomic) _Bool isUpdateLayoutControllerSuspended;
- (void)updateLayoutController;
@end

