//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TTextField.h"

@class NSString;

@interface TWherePathTextField : TTextField
{
    NSString *_valueForPasteboard;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *valueForPasteboard; // @synthesize valueForPasteboard=_valueForPasteboard;
- (id)textView:(id)arg1 menu:(id)arg2 forEvent:(id)arg3 atIndex:(unsigned long long)arg4;

@end

