//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension Foundation._bridgeNSErrorToError<A where A: Foundation {
    _ObjectiveCBridgeableError>(_: __C.NSError, out: Swift.UnsafeMutablePointer<A>) -> Swift.Bool
}
