//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension Swift.DiscontiguousSlice.subscript {
    getter : (Swift.DiscontiguousSlice<A>.Index) -> A.Element
    getter : (Swift.Range<Swift.DiscontiguousSlice<A>.Index>) -> Swift.DiscontiguousSlice<A>
    read : (Swift.DiscontiguousSlice<A>.Index) -> A.Element
    read : (Swift.DiscontiguousSlice<A>.Index) -> A.Element with unmangled suffix ".resume.0"
}
