//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension Swift.UInt16.SIMD8Storage._value {
    getter : Builtin.Vec8xInt16
    modify : Builtin.Vec8xInt16
    modify : Builtin.Vec8xInt16 with unmangled suffix ".resume.0"
    setter : Builtin.Vec8xInt16
}
