//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension Swift.AnyBidirectionalCollection.subscript {
    getter : (Swift.AnyIndex) -> A
    getter : (Swift.Range<Swift.AnyIndex>) -> Swift.AnyBidirectionalCollection<A>
    read : (Swift.AnyIndex) -> A
    read : (Swift.AnyIndex) -> A with unmangled suffix ".resume.0"
}
