//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/Swift.__SwiftNativeNSArrayWithContiguousStorage.h>

@interface Swift.__SwiftDeferredNSArray : Swift.__SwiftNativeNSArrayWithContiguousStorage
{
    id _heapBufferBridged_DoNotUse;
    id _nativeStorage;
}

- (long long);

// Remaining properties
@property(nonatomic, readonly) long long count;

@end

