//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension Swift.LazyMapSequence {
    init(_base: A, transform: (A.Element) -> B) -> Swift.LazyMapSequence<A, B>
    makeIterator() -> Swift.LazyMapSequence<A, B>.Iterator
    map<A>((B) -> A1) -> Swift.LazyMapSequence<A, A1>
}
