//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension Swift.AnyRandomAccessCollection.init<A where A == A1.Element, A1: Swift {
    RandomAccessCollection>(A1) -> Swift.AnyRandomAccessCollection<A>
}
