//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension Swift.InstantiateKeyPathBuffer {
    pushAddressDiscriminatedFunctionPointer(_: Swift.UnsafeRawPointer, discriminator: Swift.UInt64) -> ()
    visitStoredComponent(kind: Swift.KeyPathStructOrClass, mutable: Swift.Bool, offset: Swift.KeyPathPatternStoredOffset) -> ()
}
