//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension Swift._getErrorEmbeddedNSErrorIndirect<A where A: Swift {
    Error>(Swift.UnsafePointer<A>) -> Swift.Optional<Swift.AnyObject>
}
