//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension Swift.ComputedArgumentWitnessesPtr.equals {
    getter : @convention(thin) (Swift.UnsafeRawPointer, Swift.UnsafeRawPointer, Swift.Int) -> Swift.Bool
}
