//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension Swift._findNextRun<A where A: Swift {
    RandomAccessCollection>(in: A, from: A.Index, by: (A.Element, A.Element) throws -> Swift.Bool) throws -> (end: A.Index, descending: Swift.Bool)
}
