//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOTimerEventSource {
public: // (access info unavailable from symbols alone)
    IOTimerEventSource(OSMetaClass const*);
    _RESERVEDIOTimerEventSource3();
    _RESERVEDIOTimerEventSource4();
    _RESERVEDIOTimerEventSource5();
    _RESERVEDIOTimerEventSource6();
    _RESERVEDIOTimerEventSource7();
    cancelTimeout();
    checkForWork();
    disable();
    enable();
    init(OSObject*, void (*)(OSObject*, IOTimerEventSource*));
    init(unsigned int, OSObject*, void (*)(OSObject*, IOTimerEventSource*));
    setTimeout(unsigned int, unsigned int);
    setTimeout(unsigned int, unsigned long long, unsigned long long);
    setTimeout(unsigned long long);
    setTimeoutFunc();
    setTimeoutMS(unsigned int);
    setTimeoutTicks(unsigned int);
    setTimeoutUS(unsigned int);
    setWorkLoop(IOWorkLoop*);
    timerEventSource(OSObject*, void (*)(OSObject*, IOTimerEventSource*));
    wakeAtTime(unsigned int, unsigned int);
    wakeAtTime(unsigned int, unsigned long long, unsigned long long);
    wakeAtTime(unsigned long long);
    wakeAtTimeMS(unsigned int);
    wakeAtTimeTicks(unsigned int);
    wakeAtTimeUS(unsigned int);
    ~IOTimerEventSource();
};
