//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOSCSIProtocolServices {
public: // (access info unavailable from symbols alone)
    AbortCommand(OSObject*);
    AbortTask(unsigned char, unsigned long long);
    AbortTaskSet(unsigned char);
    ClearACA(unsigned char);
    ClearTaskSet(unsigned char);
    CreateSCSITargetDevice();
    ExecuteCommand(OSObject*);
    HandleAbortTask(unsigned char, unsigned long long);
    HandleAbortTaskSet(unsigned char);
    HandleCheckPowerState();
    HandleClearACA(unsigned char);
    HandleClearTaskSet(unsigned char);
    LogicalUnitReset(unsigned char);
    SendNotification_VerifyDeviceState();
    TargetReset();
    TicklePowerManager();
    _RESERVEDIOSCSIProtocolServices10();
    _RESERVEDIOSCSIProtocolServices11();
    _RESERVEDIOSCSIProtocolServices12();
    _RESERVEDIOSCSIProtocolServices13();
    _RESERVEDIOSCSIProtocolServices14();
    _RESERVEDIOSCSIProtocolServices15();
    _RESERVEDIOSCSIProtocolServices16();
    _RESERVEDIOSCSIProtocolServices8();
    _RESERVEDIOSCSIProtocolServices9();
};
