//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class pxrInternal__aapl__pxrReserved__::UsdSkelInbetweenShape {
public: // (access info unavailable from symbols alone)
    UsdSkelInbetweenShape(pxrInternal__aapl__pxrReserved__::UsdAttribute const&);
    auto CreateNormalOffsetsAttr(pxrInternal__aapl__pxrReserved__::VtValue const&) const;
    auto GetNormalOffsets(pxrInternal__aapl__pxrReserved__::VtArray<pxrInternal__aapl__pxrReserved__::GfVec3f>*) const;
    auto GetNormalOffsetsAttr() const;
    auto GetOffsets(pxrInternal__aapl__pxrReserved__::VtArray<pxrInternal__aapl__pxrReserved__::GfVec3f>*) const;
    auto GetWeight(float*) const;
    auto HasAuthoredWeight() const;
    auto IsInbetween(pxrInternal__aapl__pxrReserved__::UsdAttribute const&);
    auto SetNormalOffsets(pxrInternal__aapl__pxrReserved__::VtArray<pxrInternal__aapl__pxrReserved__::GfVec3f> const&) const;
    auto SetOffsets(pxrInternal__aapl__pxrReserved__::VtArray<pxrInternal__aapl__pxrReserved__::GfVec3f> const&) const;
    auto SetWeight(float) const;
    auto _Create(pxrInternal__aapl__pxrReserved__::UsdPrim const&, pxrInternal__aapl__pxrReserved__::TfToken const&);
    auto _GetNamespacePrefix();
    auto _GetNormalOffsetsAttr(bool) const;
    auto _IsNamespaced(pxrInternal__aapl__pxrReserved__::TfToken const&);
    auto _IsValidInbetweenName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool);
    auto _MakeNamespaced(pxrInternal__aapl__pxrReserved__::TfToken const&, bool);
    auto operator==(pxrInternal__aapl__pxrReserved__::UsdSkelInbetweenShape const&) const;
};
