//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class com_apple_filesystems_lifs {
public: // (access info unavailable from symbols alone)
    auto free();
    auto getMetaClass() const;
    auto init(OSDictionary*);
    auto probe(IOService*, int*);
    auto start(IOService*);
    auto stop(IOService*);
    auto stop(IOService*) (.cold.1);
    ~com_apple_filesystems_lifs();
};
