//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IGHardwarePerProcessPageTable64::expandLevel<IGHardwarePerProcessPageTable64 {
public: // (access info unavailable from symbols alone)
    bool LevelEntry<9ul, GTTPageMapLevel4Entry>, void>(IGHardwarePerProcessPageTable64::LevelEntry<9ul, GTTPageMapLevel4Entry>&, unsigned long long, unsigned long long, void*, unsigned long long, unsigned long);
};
