//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IGHardwareGuCWorkQueue {
public: // (access info unavailable from symbols alone)
    IGHardwareGuCWorkQueue();
    IGHardwareGuCWorkQueue(OSMetaClass const*);
    addItem(unsigned int, IGHwCsType, unsigned int, KM_SCHED_WORK_QUEUE_ITEM_REC&);
    addItem(unsigned int, IGHwCsType, unsigned int, KM_SCHED_WORK_QUEUE_ITEM_REC&) (.cold.1);
    allocItem(bool*);
    calculateFreeSpace();
    debugDump();
    flush();
    free();
    getMetaClass() const;
    initWithAccelerator(IOGraphicsAccelerator2*, unsigned int, UK_SCHED_PROCESS_DESCRIPTOR_REC*);
    isEmpty();
    lockQueue();
    unlockQueue();
    withOptions(IOGraphicsAccelerator2*, unsigned int, UK_SCHED_PROCESS_DESCRIPTOR_REC*);
    ~IGHardwareGuCWorkQueue();
};
