//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IGHardwarePerProcessPageTable32 {
public: // (access info unavailable from symbols alone)
    IGHardwarePerProcessPageTable32();
    IGHardwarePerProcessPageTable32(OSMetaClass const*);
    auto describeDriverAllocations(IOAccelAllocationInfo*, int);
    auto expand(GTTVirtualAddress32);
    auto free();
    auto getMetaClass() const;
    auto getPageTableRootPhysicalAddress(unsigned long long*);
    auto hwPageWalk(GTTVirtualAddress32) const;
    auto initWithOptions(IntelAccelerator*, IGAccelTask*);
    auto mapRange(IGAddressRange const&, unsigned long long, unsigned long long);
    auto mapRangeDummy(IGAddressRange const&, unsigned long long);
    auto mapRangeRotated(IGAddressRangeRotatedPageIterator&, IGPhysicalSegmentIterator&, unsigned long long);
    auto read(unsigned long long, unsigned long long&, unsigned long long&) const;
    auto remapRange(IGAddressRange const&, unsigned long long, unsigned long long);
    auto unmapRange(IGAddressRange const&);
    auto validateMapping(GTTVirtualAddress32, unsigned long long);
    auto withOptions(IntelAccelerator*, IGAccelTask*);
    bool allocateDescriptorTable<IGHardwarePerProcessPageTable32::LevelEntry<9ul, GTTPageTableEntry>>(IGHardwarePerProcessPageTable32::LevelEntry<9ul, GTTPageTableEntry>&);
    bool commitLevel<IGHardwarePerProcessPageTable32::LevelEntry<9ul, GTTPageDirectoryEntry>, void>(IGPagePool::PageDescriptor const*, void*, unsigned long long, unsigned long);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~IGHardwarePerProcessPageTable32();
};
