//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOAccelTask {
public: // (access info unavailable from symbols alone)
    IOAccelTask(OSMetaClass const*);
    _RESERVEDIOAccelTask0();
    _RESERVEDIOAccelTask1();
    _RESERVEDIOAccelTask2();
    _RESERVEDIOAccelTask3();
    _RESERVEDIOAccelTask4();
    _RESERVEDIOAccelTask5();
    allocate(IOAccelMemoryMap const*);
    deallocate(IOAccelMemoryMap const*, unsigned long long);
    freeAllGPUMappings();
    freeAllSysMemoryMappings();
    freeAllVidMemoryMappings();
    freeToAllocGPUAddress(IOAccelMemoryMap*);
    freeWaitToAllocGPUAddress(IOAccelMemoryMap*, bool);
    getProcessIDAndName(char*, int) const;
    init(IOGraphicsAccelerator2*, unsigned int, IORangeAllocator**);
    reserve(unsigned int, unsigned long long, unsigned long long);
    ~IOAccelTask();
};
