//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOBufferCopyEventSource {
public: // (access info unavailable from symbols alone)
    IOBufferCopyEventSource();
    IOBufferCopyEventSource(OSMetaClass const*);
    auto _processCompletionQueue();
    auto _processCompletionQueue() (.cold.1);
    auto _processCompletionQueue() (.cold.2);
    auto addSubmissionQueue(IOBufferCopySubmissionQueue*);
    auto checkCompletionPending();
    auto checkForWork();
    auto complete(IOBufferCopyDMACommand*);
    auto flushMemoryQueue(void*);
    auto free();
    auto getInterruptIndex() const;
    auto getMemoryQueue() const;
    auto getMetaClass() const;
    auto initWithOwner(OSObject*, unsigned short, int, IOBufferCopyEngine*);
    auto isAvailable() const;
    auto notifyMemoryQueue(void*);
    auto prepare(void*, IOMemoryDescriptor*, unsigned int);
    auto processCompletions();
    auto removeSubmissionQueue(IOBufferCopySubmissionQueue*);
    auto setMemoryQueueProperty(void*, unsigned int, unsigned long long);
    auto shutdown();
    auto withOwner(OSObject*, unsigned short, int, IOBufferCopyEngine*);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~IOBufferCopyEventSource();
};
