//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOBufferCopyEngineUserClientState {
public: // (access info unavailable from symbols alone)
    IOBufferCopyEngineUserClientState();
    IOBufferCopyEngineUserClientState(OSMetaClass const*);
    asyncCleanupThunk(void*, void*);
    cleanup();
    cleanup() (.cold.1);
    doAsyncCleanup();
    free();
    getMetaClass() const;
    initWithWorkloop(IOWorkLoop*);
    queueForName(OSSymbol const*) const;
    submissionCompleted(IOBufferCopySubmissionQueue*);
    withWorkLoop(IOWorkLoop*);
    ~IOBufferCopyEngineUserClientState();
};
