//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

// Global C++ functions

BridgeAudioCommunicationQueue::gMetaClass;
BridgeAudioCommunicationQueue::metaClass;
BridgeAudioCommunicationQueue::superClass;
BridgeAudioCommunicationQueue_ktv;
BridgeAudioCommunicationService::gMetaClass;
BridgeAudioCommunicationService::metaClass;
BridgeAudioCommunicationService::superClass;
BridgeAudioCommunicationService_ktv;
BridgeAudioCommunicationTransport::gMetaClass;
BridgeAudioCommunicationTransport::metaClass;
BridgeAudioCommunicationTransport::superClass;
BridgeAudioCommunicationTransport_ktv;
BridgeAudioCommunicationUserClient::gMetaClass;
BridgeAudioCommunicationUserClient::metaClass;
BridgeAudioCommunicationUserClient::superClass;
BridgeAudioCommunicationUserClient_ktv;
BridgeAudioTransportBCESubmissionQueue::gMetaClass;
BridgeAudioTransportBCESubmissionQueue::metaClass;
BridgeAudioTransportBCESubmissionQueue::superClass;
BridgeAudioTransportBCESubmissionQueue_ktv;
BridgeAudioTransportIOBCE::gMetaClass;
BridgeAudioTransportIOBCE::metaClass;
BridgeAudioTransportIOBCE::superClass;
BridgeAudioTransportIOBCE_ktv;
IOBufferCopySubmissionQueue::gMetaClass;
IOService::gMetaClass;
IOUserClient::gMetaClass;
OSObject::gMetaClass;
OSSymbol::metaClass;
vtable for BridgeAudioCommunicationQueue;
vtable for BridgeAudioCommunicationQueue::MetaClass;
vtable for BridgeAudioCommunicationService;
vtable for BridgeAudioCommunicationService::MetaClass;
vtable for BridgeAudioCommunicationTransport;
vtable for BridgeAudioCommunicationTransport::MetaClass;
vtable for BridgeAudioCommunicationUserClient;
vtable for BridgeAudioCommunicationUserClient::MetaClass;
vtable for BridgeAudioTransportBCESubmissionQueue;
vtable for BridgeAudioTransportBCESubmissionQueue::MetaClass;
vtable for BridgeAudioTransportIOBCE;
vtable for BridgeAudioTransportIOBCE::MetaClass;
vtable for IOBufferCopySubmissionQueue;
vtable for IOService;
vtable for IOUserClient;
vtable for OSObject;
