//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

// Global C++ functions

AppleBCM5701Placeholder::gMetaClass;
AppleBCM5701Placeholder::metaClass;
AppleBCM5701Placeholder::operator delete(void*, unsigned long);
AppleBCM5701Placeholder::operator new(unsigned long);
AppleBCM5701Placeholder::superClass;
AppleBCM5701Placeholder_ktv;
BCM5701Enet::gMetaClass;
BCM5701EnetClock::gMetaClass;
BCM5701EnetClock_ktv;
BCM5701Enet_ktv;
BCM5701UserClient::gMetaClass;
BCM5701UserClient::metaClass;
BCM5701UserClient::operator delete(void*, unsigned long);
BCM5701UserClient::operator new(unsigned long);
BCM5701UserClient::sMethods;
BCM5701UserClient::superClass;
BCM5701UserClient_ktv;
GenerateMacAddress(IOEthernetAddress*);
GetBoolean(OSDictionary*, char const*, bool*);
GetNumber(OSDictionary*, char const*, unsigned int*);
GetNumber8(OSDictionary*, char const*, unsigned char*);
IOACPIPlatformDevice::metaClass;
IODMACommand::metaClass;
IOEthernetController::gMetaClass;
IOPCIDevice::metaClass;
IOTimeSyncNanosecondSnapshotService::gMetaClass;
IOUserClient::gMetaClass;
OSBoolean::metaClass;
OSData::metaClass;
OSDictionary::metaClass;
OSNumber::metaClass;
OSString::metaClass;
OSUnserializeXML(char const*, OSString**);
add_to_symList(dnsSymList**, unsigned char*, unsigned char*);
add_to_symList(dnsSymList**, unsigned char*, unsigned char*)::kalloc_type_view_1455;
debug_rx_iso_callbackA();
dnsCopyString(unsigned char**, unsigned char*, unsigned char**, unsigned char*, dnsSymList*);
dnsMatch(unsigned char*, unsigned char*, unsigned char*, unsigned char*);
free_symList(dnsSymList**)::kalloc_type_view_1476;
getPacketDetails(__mbuf*, char*, int);
rr_type_to_name(unsigned short)::buffer;
vtable for AppleBCM5701Placeholder;
vtable for AppleBCM5701Placeholder::MetaClass;
vtable for BCM5701Enet;
vtable for BCM5701Enet::MetaClass;
vtable for BCM5701EnetClock;
vtable for BCM5701EnetClock::MetaClass;
vtable for BCM5701UserClient;
vtable for BCM5701UserClient::MetaClass;
vtable for IOEthernetController;
vtable for IOTimeSyncNanosecondSnapshotService;
vtable for IOUserClient;
