//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleBCM5701Placeholder {
public: // (access info unavailable from symbols alone)
    AppleBCM5701Placeholder();
    AppleBCM5701Placeholder(OSMetaClass const*);
    free();
    getFeatures() const;
    getHardwareAddress(IOEthernetAddress*);
    getMaxPacketSize(unsigned int*) const;
    getMetaClass() const;
    handleStart(IOService*);
    handleStart(IOService*)::zerosAddr;
    publishToNetworkStack();
    publishToNetworkStack()::mediumTable;
    selectMedium(IONetworkMedium const*);
    setMaxPacketSize(unsigned int);
    start(IOService*);
    stop(IOService*);
    ~AppleBCM5701Placeholder();
};
