//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleAHCIDiskPolledInterface {
public: // (access info unavailable from symbols alone)
    AppleAHCIDiskPolledInterface();
    AppleAHCIDiskPolledInterface(OSMetaClass const*);
    CreateWithDriver(AppleAHCIDiskDriver*);
    InitWithDriver(AppleAHCIDiskDriver*);
    checkForWork();
    close(unsigned int);
    getMetaClass() const;
    open(unsigned int, IOMemoryDescriptor*);
    probe(IOService*);
    startIO(unsigned int, unsigned int, unsigned long long, unsigned long long, IOPolledCompletion);
    ~AppleAHCIDiskPolledInterface();
};
