//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class GEONavigationListener;

@protocol GEONavigationListenerDelegate

@optional
- (void);
- (void)4;
- (void);
- (void)setStorageGuid:(GEONavigationListener *)arg1;
@end

