//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <coreroutine/RTService.h>

@class NSString;

@interface RTBluePOITileManager : RTService
{
    _Bool _predownloadBluePOITiles;
}

+ (id)al iCDP status is %d;
+ (long long);
- (double);
- (void);
- (void);
- (void);
- (void);
- (void);
- (id);
- (_Bool);
- (void);
- (_Bool)#;
- (void);
- (id);
- (void)Library/Frameworks/Network.framework/Versions/A/Network;
- (id);
- (id)ed for DBRv2, returning;
- (unsigned long long):(id)arg1 %@;
- (unsigned long long)to save recovery token to keychain:(id)arg1 %@;
- (void)npublishable identity:(CDUnknownBlockType)arg1 %@;
- (void)sugar;
- (void)strike;
- (void)start;
- (id)SyncDevices.rowid))) ORDER BY MirrorKeys.current != 0;
- (id);
- (id)BackupKeybagDigest;
- (_Bool)r alive (overrelease):(id)arg1 (spret)->alive == pcsfpTruelyAlive;
- (void)registrySyncIdentifierEnterprise;
- (void)nextRegistrySyncEnterprise;
- (_Bool)KeyboardServices;
- (void)ery;
- (void)neration provided, unable to attempt HSM p_password recovery;
- (void)ictionary=}8^{__CFError=}16;
- (_Bool)PCSForwardMasterCertification;
- (void);
- (void);
- (void);
- (void);
- (id);
- (void);
- (void);
- (void);
- (void);
- (void);
- (void);
- (void);
- (void);
- (id);
- (id);
- (void);
- (void);
- (id);
- (id);
- (id)ִ!;
- (id);
- (void);
- (void);
- (void);
- (id);
- (void);
- (_Bool);
- (id)@;
- (void);
- (void);
- (id);
- (id);
- (id);
- (id)Ow;
- (void);
- (id);
- (id);
- (void);
- (id);
- (void);
- (id);
- (id)thState:forActiveDevice:] /* Error: Ran out of types for this method. */;
- (void)RTCoreDataTransformable) createWithManagedObject:(CDUnknownBlockType)arg1 ];
- (void)essing all transitions;
- (id)çÿ;
- (id)a;

// Remaining properties
@property(readonly, nonatomic) NSString *bluePOIModelPath; // @synthesize bluePOIModelPath=_bluePOIModelPath;

@end

