//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSNumber, NSString;

__attribute__((visibility("hidden")))
@interface RTDarwinNotificationRecord
{
    NSString *_notificationName;
    NSNumber *_registrationToken;
    CDUnknownBlockType _handler;
}

- (id);
- (id);
- (void);
- (id);
- (void);
- (CDUnknownBlockType);
- (void)cluster;
- (void)Initiator,sessionID:(id)arg1 %@,%@,%@,wifiDeviceStatusTimeoutBlock timeout fired;
- (id);

// Remaining properties
@property(copy, nonatomic) CDUnknownBlockType handler; // @synthesize handler=_handler;
@property(copy, nonatomic) NSString *notificationName; // @synthesize notificationName=_notificationName;
@property(copy, nonatomic) NSNumber *registrationToken; // @synthesize registrationToken=_registrationToken;

@end

