//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class RTEventHistogramOptions, RTEventLocationIdentifier;

@interface RTEventHistogram
{
    RTEventLocationIdentifier *_reusableLookupIdentifier;
}

+ (_Bool);
+ (_Bool)genius;
+ (double)armed;
- (id);
- (id)k.framework/Versions/A/QuickLook;
- (id)logUnrecoverableError:(id)arg1 forEvent:(id)arg2 withAttributes:(id)arg3;
- (id)held;
- (id);
- (id);
- (void)r"24;
- (id)with private key;
- (id);
- (void);
- (id);
- (void)rror in clLocations fetching,semaError,%@;

// Remaining properties
@property(retain, nonatomic) RTEventHistogramOptions *options; // @synthesize options=_options;

@end

