//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class RTContact;

@interface RTFavoritesEntry
{
    RTContact *_contact;
}

- (id)_metadata;
- (id)candidatePairToken %@, linkID:%@, baseRequestTimeStampInMS:%u, requestTimeStampAndRTTs count:%lu, requestTimeStampAndRTTs:%@ ... /* Error: Ran out of types for this method. */;
- (id);
- (id);
- (void)imum prediction window %fs;

// Remaining properties
@property(readonly, nonatomic) RTContact *contact; // @synthesize contact=_contact;

@end

