//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <coreroutine/RTService.h>

@interface RTFingerprintManager : RTService
{
    _Bool _available;
}

+ (long long);
+ (id);
- (id);
- (void);
- (void);
- (void);
- (void);
- (void);
- (void);
- (id);
- (void);
- (void);
- (void);
- (void);
- (void);
- (id)needPassword;
- (id);
- (_Bool);
- (void);
- (void);
- (unsigned long long)nto keychain:%d /* Error: Ran out of types for this method. */;
- (unsigned long long)ot available:%d /* Error: Ran out of types for this method. */;
- (void)tadata key hashes to DBR record;
- (id);
- (void);
- (void);
- (void);
- (void);
- (unsigned long long)4;
- (void);
- (id);
- (id);
- (void)!(Ð!ÐAùA,Ð1Â0@ù
× ;
- (id)nager) _submitMetricScoreBoardOnDate:submissionHandler:] /* Error: Ran out of types for this method. */;
- (id)];
- (void)ns;
- (void)on requester, %@;
- (void)[h], unc Res %{sensitive}f [h], stop Trans %{sensitive}f [h], unc Res %f [h], primaryStopDate, %@, num Of Trans %{sensitive}d, dailyDens %{sensitive}f, weeklyDens %{sensitive}f;
- (_Bool)import mirroring request, %@;
- (void);
- (void)#;

// Remaining properties
@property(nonatomic) _Bool available; // @synthesize available=_available;

@end

