//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSDate;

@interface RTFMCScoreBoard
{
    _Bool _engaged;
}

- (int);
- (void);
- (void);
- (void);
- (void);
- (void);
- (void);
- (int);
- (void);
- (id);
- (int)Primary record is terminal, re-enroll is required;
- (int)record has %@ attempts remaining;
- (void)wood;
- (int);
- (_Bool)GMA journal_mode=WAL;;
- (int)TEGER, digest TEXT);;
- (void);
- (void);
- (void);
- (void);
- (void);
- (void);
- (_Bool);
- (id);
- (id);
- (void);
- (void)fetchLookbackWindowStartDateWithLocation:(int)arg1 handler: /* Error: Ran out of types for this method. */;
- (int)ords:%{sensitive}lf, %{sensitive}lf /* Error: Ran out of types for this method. */;
- (void)rigger in notification, returning.;

// Remaining properties
@property(retain, nonatomic) NSDate *creationDate; // @synthesize creationDate=_creationDate;

@end

