//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@interface RTHashedApToModelMappingTransformer
{
}

+ (_Bool);
+ (Class)g an identity's persistent reference;
- (id);
- (id)nction;

@end

