//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSArray, NSDateInterval;

@interface RTLearnedPlaceTypeInferenceEnumerationOptions
{
    unsigned long long _batchSize;
    _Bool _sortByCreationDate;
    _Bool _ascending;
    unsigned long long _fetchLimit;
    unsigned long long _offset;
    NSDateInterval *_dateInterval;
    NSArray *_filteredToPlaceTypes;
    NSArray *_filteredToLearnedPlaceIdentifiers;
    NSArray *_filteredToIdentifiers;
    NSArray *_filteredToSessionIds;
}

+ (_Bool)ecute retro-registration.;
- (_Bool);
- (id);
- (id);
- (id);
- (id);
- (id);
- (id);
- (void);
- (Class);
- (id);
- (id)j';
- (void);
- (id);
- (id)thod;
- (_Bool);
- (id);
- (unsigned long long)16@0:8 /* Error: Ran out of types for this method. */;
- (unsigned long long)eTripClusterTable:reply: /* Error: Ran out of types for this method. */;
- (unsigned long long)arPlay:preventAutomaticRemoval:expirationDate:userInfo:handler: /* Error: Ran out of types for this method. */;

// Remaining properties
@property(readonly, nonatomic) _Bool ascending; // @synthesize ascending=_ascending;
@property(readonly, nonatomic) NSDateInterval *dateInterval; // @synthesize dateInterval=_dateInterval;
@property(readonly, nonatomic) unsigned long long fetchLimit; // @synthesize fetchLimit=_fetchLimit;
@property(readonly, nonatomic) NSArray *filteredToIdentifiers; // @synthesize filteredToIdentifiers=_filteredToIdentifiers;
@property(readonly, nonatomic) NSArray *filteredToLearnedPlaceIdentifiers; // @synthesize filteredToLearnedPlaceIdentifiers=_filteredToLearnedPlaceIdentifiers;
@property(readonly, nonatomic) NSArray *filteredToPlaceTypes; // @synthesize filteredToPlaceTypes=_filteredToPlaceTypes;
@property(readonly, nonatomic) NSArray *filteredToSessionIds; // @synthesize filteredToSessionIds=_filteredToSessionIds;
@property(readonly, nonatomic) unsigned long long offset; // @synthesize offset=_offset;
@property(readonly, nonatomic) _Bool sortByCreationDate; // @synthesize sortByCreationDate=_sortByCreationDate;

@end

