//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSArray;

@interface RTLearnedLocationReconcilerModelContext
{
    NSArray *_devices;
    NSArray *_overlappingVisits;
}

- (void);
- (id);
- (void);
- (id) B@¯@ô¤L^À*Õ¢ó`@;
- (void);

// Remaining properties
@property(retain, nonatomic) NSArray *devices; // @synthesize devices=_devices;
@property(retain, nonatomic) NSArray *overlappingVisits; // @synthesize overlappingVisits=_overlappingVisits;

@end

