//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@interface RTLearnedPlaceTypeInferenceEnumerationOptions
{
    unsigned long long _batchSize;
}

+ (_Bool);
- (_Bool);
- (id);
- (id)e}}^{_PCSPublicIdentityData}^{_PCSPublicIdentityData}^{_PCSPublicIdentityData}^{_PCSPublicIdentityData}^{_PCSIdentityData}^{_PCSIdentityData}^{__CFArray}Ii{?=BBBBBBB}I}16@0:(unsigned long long)arg1 8;
- (id)V_queryMissingKeys;
- (id)yEscrowKeysAll;
- (id)mt=},V_queryEscrowKey;
- (id)mt=},V_markMirrorKey;
- (id);
- (id);
- (id)to bind to %s, errno:%d /* Error: Ran out of types for this method. */;
- (id);
- (_Bool);
- (void);
- (id);
- (Class);
- (unsigned long long)setNumOfDataPts: /* Error: Ran out of types for this method. */;
- (void)panionLink, onDeviceLost, id, %@, name, %@, model, %@;
- (unsigned long long)cated SPI, %@;
- (unsigned long long)Õë;

// Remaining properties
@property(readonly, nonatomic) unsigned long long fetchLimit; // @synthesize fetchLimit=_fetchLimit;

@end

