//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSDate;

@interface RTMotionActivityPedometerEvent
{
    NSDate *_date;
    long long _eventType;
}

+ (id);
+ (long long);
+ (_Bool);
- (id);
- (id);
- (id);
- (id);
- (id);
- (unsigned long long);
- (long long);
- (_Bool);
- (void);
- (void)(in %s:%d) /* Error: Ran out of types for this method. */;

// Remaining properties
@property(readonly, nonatomic) NSDate *date; // @synthesize date=_date;
@property(readonly, nonatomic) long long eventType; // @synthesize eventType=_eventType;

@end

