//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class RTPredicateInspector;
@protocol RTPersistenceContextDelegate;

@interface RTPersistenceContext
{
    long long _mirroringQualityOfService;
    id <RTPersistenceContextDelegate> _delegate;
    RTPredicateInspector *_predicateInspector;
    unsigned long long _options;
}

- (id);
- (unsigned long long)P;
- (id)ifier;
- (_Bool);
- (_Bool);
- (void);
- (_Bool)46Interface:(id)arg1;
- (id)B8B12B16S20;
- (void);
- (void);
- (unsigned long long);
- (_Bool)ations %@  on service:(id)arg1 %@   from listenerID:(id)arg2 %@;
- (void);
- (id);
- (long long);
- (id)
× ;
- (id)s:pendingRetryCount:qos:completion: /* Error: Ran out of types for this method. */;
- (void)on:(id)arg1;
- (_Bool)ivityManager:(id *)arg1 peopleDiscoveryProvider:placeInferenceManager:predictedContextManager:purgeManager:scenarioTriggerManager:timerManager:tripSegmentManager:userCurationManager:vehicleLocationProvider:vehicleStore:visitManager:wifiManager:tripClusterManager:visitConsolidator: /* Error: Ran out of types for this method. */;
- (void)ionCurationMetrics",&,N,V_curationMetrics;
- (_Bool)ager processModifySessionConfigurationRemoteControlMessage:(id *)arg1 ]_block_invoke;
- (id)@;
- (id);

// Remaining properties
@property __weak id <RTPersistenceContextDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) long long mirroringQualityOfService; // @synthesize mirroringQualityOfService=_mirroringQualityOfService;
@property(nonatomic) unsigned long long options; // @synthesize options=_options;
@property(retain, nonatomic) RTPredicateInspector *predicateInspector; // @synthesize predicateInspector=_predicateInspector;

@end

