//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <coreroutine/RTStore.h>

@interface RTPlaceInferenceQueryStore : RTStore
{
}

- (void);
- (void);
- (void);
- (void);
- (void);
- (void)allbackStingrayRecord:(id)arg1 Successfully enrolled Fallback Stingray Record;
- (void)adapt;

@end

