//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <coreroutine/RTMetric.h>

@class NSString, RTRelabeler;

@interface RTRelabelerMetrics : RTMetric
{
    RTRelabeler *_relabeler;
}

+ (id);
+ (id);
+ (id);
+ (id);
+ (id);
+ (id);
+ (CDStruct_b8464340);
- (_Bool);
- (void);
- (void);
- (void);
- (void);
- (void);
- (void);
- (void);
- (id);
- (id);
- (double);
- (id);
- (id);
- (id);
- (double);
- (void);
- (void)%s, gps location received, %{sensitive}@;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) RTRelabeler *relabeler; // @synthesize relabeler=_relabeler;
@property(readonly) Class superclass;

@end

