//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSMutableArray, RTLocationManager, RTSignalGeneratorOptions;

@interface RTSignalGenerator
{
    RTSignalGeneratorOptions *_signalGeneratorOptions;
    RTLocationManager *_locationManager;
    unsigned long long _totalVisitLocationsGeneratedCount;
    unsigned long long _totalTransitionLocationsGeneratedCount;
    NSMutableArray *_generatedLocations;
}

+ (double);
+ (id);
+ (double);
+ (double);
+ (void);
+ (struct CLLocationCoordinate2D);
+ (id);
+ (id);
+ (struct CLLocationCoordinate2D);
+ (double);
+ (double);
+ (double);
+ (double);
+ (id);
- (id);
- (id);
- (id);
- (void);
- (id);
- (unsigned long long);
- (id);
- (id);
- (id);
- (id);
- (id);
- (id);
- (void)@;

// Remaining properties
@property(retain) NSMutableArray *generatedLocations; // @synthesize generatedLocations=_generatedLocations;

@end

