//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@interface RTStoredSettledStateTransitionEnumerationOptions
{
    _Bool _ascending;
}

- (id);
- (id);
- (id)nkID:%hhd; delegatedLinkID:%hhd /* Error: Ran out of types for this method. */;
- (_Bool);
- (void);
- (id);
- (unsigned long long)upperBoundEtaForDepartureDate:defaultsManager:mapsExpectedTravelTime:crowFliesExpectedTravelTime:etaScaleFactor: /* Error: Ran out of types for this method. */;
- (void)option:%lu /* Error: Ran out of types for this method. */;

// Remaining properties
@property(readonly, nonatomic) _Bool ascending; // @synthesize ascending=_ascending;

@end

