//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSDate, NSString, RTMapItem, RTStateDepictionOneState, RTStateModelLocation;
@protocol GEOMapItem;

@interface RTStateDepiction
{
    long long _numOfDataPts;
    RTStateDepictionOneState *_clusterState;
}

+ (double);
+ (_Bool);
+ (long long)edForNotifications;
- (double);
- (void);
- (double);
- (id);
- (id);
- (id);
- (id);
- (id);
- (id);
- (id);
- (void);
- (id);
- (void);
- (id);
- (void);
- (_Bool);
- (long long);
- (double);
- (void);
- (void);
- (_Bool);
- (id);
- (void);
- (double);
- (void);
- (void);
- (void);
- (id);
- (void);
- (id);
- (id);
- (unsigned long long)0@ù
× ;
- (void)Â0@ù
× ;
- (unsigned long long)ùñB,Ð1Â0@ù
× ;
- (void)|Gù1C,ð1Â0@ù
× ;
- (void);
- (void)ator:(id)arg1 error: /* Error: Ran out of types for this method. */;
- (void)bucketed;
- (id)with_uninterrupted_WiFi_connection_bucketed:is_iPhone:is_iPad:is_Watch: /* Error: Ran out of types for this method. */;
- (id)cationsOfInterestFromLocation:(double)arg1 startDate:timeInterval:handler: /* Error: Ran out of types for this method. */;
- (id)ateValidForSendingEndSessionMessage: /* Error: Ran out of types for this method. */;
- (id)foreDriveMax;
- (void)yStyling;
- (void), 8!Ü"T#Ø&ÜÌ¦H§,« À;
- (long long)À%;
- (id);
- (unsigned long long)orTimeSettled:overDuration:] /* Error: Ran out of types for this method. */;
- (void)%@;
- (id)rVisitIdentifier no visit identifier provided, returning.;
- (id)p session monitor, cache managers, and session manager;
- (void)îÿ=&;

// Remaining properties
@property(retain, nonatomic) RTStateDepictionOneState *clusterState; // @synthesize clusterState=_clusterState;
@property(copy, nonatomic) NSString *customLabel;
@property(retain, nonatomic) id <GEOMapItem> geoMapItem;
@property(retain, nonatomic) NSDate *geocodeDate;
@property(retain, nonatomic) RTStateModelLocation *location;
@property(retain, nonatomic) RTMapItem *mapItem;
@property(nonatomic) unsigned long long mapItemSource;
@property(nonatomic) long long numOfDataPts; // @synthesize numOfDataPts=_numOfDataPts;
@property(nonatomic) long long type;
@property(nonatomic) unsigned long long typeSource;

@end

