//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@interface RTTripSegmentFeatures
{
    int _tripSequenceNumber;
}

- (int);
- (id);
- (void);
- (void);
- (void);
- (id);
- (unsigned long long)receive;
- (id);
- (long long);
- (id).;
- (void);
- (void);
- (void)es not exceed required minimum interval, %.2f;

// Remaining properties
@property(nonatomic) unsigned long long transitionIndex; // @synthesize transitionIndex=_transitionIndex;

@end

