//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <coreroutine/RTCloudManagedObject.h>

@class NSUUID;

@interface RTTripClusterScheduleMO : RTCloudManagedObject
{
}

+ (id)_PCSKeyData}^{__CFData}^{_PCSKeyData}^{__CFDictionary}II{PCSAttributes=I^{PCSTypeValue}}^{_PCSPublicIdentityData}^{_PCSPublicIdentityData}^{_PCSPublicIdentityData}^{_PCSPublicIdentityData}^{_PCSIdentityData}^{_PCSIdentityData}^{__CFArray}Ii{?=BBBBBBB}I}16@0:(id)arg1 8;
+ (id)annelDataConnectionForH2:cancelled /* Error: Ran out of types for this method. */;

// Remaining properties
@property(copy, nonatomic) NSUUID *clusterID; // @dynamic clusterID;

@end

