//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSString, NSURL;

@interface RTUserNotificationAction
{
    NSString *_actionIdentifier;
    NSString *_title;
    NSURL *_url;
    NSString *_iconWithSystemImageName;
    CDUnknownBlockType _handler;
}

- (id);
- (id);
- (id)ion;
- (id);
- (void);
- (id);
- (id)nProvider;
- (id);
- (CDUnknownBlockType)y to process an out of order message given it's eligible;

// Remaining properties
@property(readonly, copy, nonatomic) NSString *actionIdentifier; // @synthesize actionIdentifier=_actionIdentifier;
@property(readonly, copy, nonatomic) CDUnknownBlockType handler; // @synthesize handler=_handler;
@property(readonly, copy, nonatomic) NSString *iconWithSystemImageName; // @synthesize iconWithSystemImageName=_iconWithSystemImageName;
@property(readonly, copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, copy, nonatomic) NSURL *url; // @synthesize url=_url;

@end

