//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSNumber;

@interface RTWiFiAccessPointMO
{
}

+ (id)setPrimarySerializedEscrowRecord:(id)arg1;
+ (id)onnection;

// Remaining properties
@property(copy, nonatomic) NSNumber *age; // @dynamic age;

@end

