//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSString;

__attribute__((visibility("hidden")))
@interface SMIDSMessageWaitingForAck
{
    NSString *_identifier;
}

- (void);
- (void);
- (long long);
- (id);
- (id)U;
- (void);
- (void);
- (id);
- (id);
- (id);
- (void);
- (CDUnknownBlockType)setCurrentSessionDeactivationCriteria: /* Error: Ran out of types for this method. */;
- (void)gnalEnvironmentType <= kCLClientSignalEnvFoliage;
- (void)ro routes/locations fetched from table4,clusterId,%@;

// Remaining properties
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;

@end

