//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class CLLocation;

@interface SMLocationEvent
{
    CLLocation *_location;
}

- (id);
- (double)+ԡ;
- (id)computeIntersectionOverUnionUsingBoundingBoxBetweenLocations:locationsCount:otherLocations:otherLocationsCount:error: /* Error: Ran out of types for this method. */;
- (void)ssed,%d,numTSPFailed,%d;

// Remaining properties
@property(readonly, nonatomic) CLLocation *location; // @synthesize location=_location;

@end

