//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleUSBXHCIRequestPool {
public: // (access info unavailable from symbols alone)
    AppleUSBXHCIRequestPool(OSMetaClass const*);
    auto free();
    auto initWithWorkLoopAndController(IOWorkLoop*, AppleUSBXHCI*);
    ~AppleUSBXHCIRequestPool();
};
