//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class std::__1::unique_ptr<void ctu::SharedSynchronizable<ctu::iokit::IOPortUSBCController>::execute_wrapped<ctu::iokit::IOPortUSBCController {
public: // (access info unavailable from symbols alone)
    setupUSBProtocols()::$_0>(ctu::iokit::IOPortUSBCController::setupUSBProtocols()::$_0&&) const::'lambda'(), std::__1::default_delete<void ctu::SharedSynchronizable<ctu::iokit::IOPortUSBCController>::execute_wrapped<ctu::iokit::IOPortUSBCController::setupUSBProtocols()::$_0>(ctu::iokit::IOPortUSBCController::setupUSBProtocols()::$_0&&) const::'lambda'()>>::~unique_ptr[abi:ne200100]();
};
