//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AMDRadeonX6000_AMDRadeonHWServicesAbstract {
public: // (access info unavailable from symbols alone)
    AMDRadeonX6000_AMDRadeonHWServicesAbstract(OSMetaClass const*);
    attach(IOService*);
    createPowerPlayInterface(PowerPlayCallbacks*);
    detach(IOService*);
    findPlugIn();
    free();
    getCail();
    getMetaClass() const;
    getTtl();
    populateDeviceInfo(AMDRadeonX6000_AMDRadeonHWServicesAbstract::DeviceInfo*);
    probe(IOService*, int*);
    readProjectName();
    readProjectName()::EFI_PROJECT_NAME_PROPERTY;
    start(IOService*);
    stop(IOService*);
    ~AMDRadeonX6000_AMDRadeonHWServicesAbstract();
};
