//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class morphun::analysis::Tokenizer {
public: // (access info unavailable from symbols alone)
    Tokenizer();
    Tokenizer(morphun::analysis::util::AttributeFactory*);
    auto close();
    auto correctOffset(int);
    auto reset();
    auto setReader(UText*);
    ~Tokenizer();
};
