//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOThunderboltString {
public: // (access info unavailable from symbols alone)
    IOThunderboltString();
    IOThunderboltString(OSMetaClass const*);
    auto getMetaClass() const;
    auto withCString(char const*);
    auto withCStringNoCopy(char const*);
    auto withString(OSString const*);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~IOThunderboltString();
};
