//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOThunderboltIECSCommand {
public: // (access info unavailable from symbols alone)
    IOThunderboltIECSCommand();
    IOThunderboltIECSCommand(OSMetaClass const*);
    auto _RESERVEDIOThunderboltIECSCommand0();
    auto _RESERVEDIOThunderboltIECSCommand1();
    auto _RESERVEDIOThunderboltIECSCommand10();
    auto _RESERVEDIOThunderboltIECSCommand11();
    auto _RESERVEDIOThunderboltIECSCommand12();
    auto _RESERVEDIOThunderboltIECSCommand13();
    auto _RESERVEDIOThunderboltIECSCommand14();
    auto _RESERVEDIOThunderboltIECSCommand15();
    auto _RESERVEDIOThunderboltIECSCommand2();
    auto _RESERVEDIOThunderboltIECSCommand3();
    auto _RESERVEDIOThunderboltIECSCommand4();
    auto _RESERVEDIOThunderboltIECSCommand5();
    auto _RESERVEDIOThunderboltIECSCommand6();
    auto _RESERVEDIOThunderboltIECSCommand7();
    auto _RESERVEDIOThunderboltIECSCommand8();
    auto _RESERVEDIOThunderboltIECSCommand9();
    auto complete(int);
    auto complete(int)::_os_log_fmt;
    auto createResources();
    auto destroyResources();
    auto free();
    auto free()::_os_log_fmt;
    auto getActualReadLength();
    auto getAddress();
    auto getBus();
    auto getCommandType();
    auto getCompletion();
    auto getDataDescriptor();
    auto getDevice();
    auto getFlags();
    auto getLength();
    auto getMetaClass() const;
    auto initWithController(IOThunderboltController*);
    auto initWithController(IOThunderboltController*)::_os_log_fmt;
    auto isInProgress();
    auto setActualReadLength(unsigned int);
    auto setAddress(unsigned char);
    auto setBus(unsigned int);
    auto setCommandType(unsigned char);
    auto setCompletion(IOThunderboltIECSCommand::Completion);
    auto setDataDescriptor(IOMemoryDescriptor*);
    auto setDevice(unsigned int);
    auto setFlags(unsigned int);
    auto setInProgress(bool);
    auto setLength(unsigned long long);
    auto setSynchronous(bool);
    auto sleepSynchronous();
    auto withController(IOThunderboltController*);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~IOThunderboltIECSCommand();
};
