//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOThunderboltConfigPollQuadletCommand {
public: // (access info unavailable from symbols alone)
    IOThunderboltConfigPollQuadletCommand();
    IOThunderboltConfigPollQuadletCommand(OSMetaClass const*);
    auto _RESERVEDIOThunderboltConfigPollQuadletCommand0();
    auto _RESERVEDIOThunderboltConfigPollQuadletCommand1();
    auto _RESERVEDIOThunderboltConfigPollQuadletCommand10();
    auto _RESERVEDIOThunderboltConfigPollQuadletCommand11();
    auto _RESERVEDIOThunderboltConfigPollQuadletCommand12();
    auto _RESERVEDIOThunderboltConfigPollQuadletCommand13();
    auto _RESERVEDIOThunderboltConfigPollQuadletCommand14();
    auto _RESERVEDIOThunderboltConfigPollQuadletCommand15();
    auto _RESERVEDIOThunderboltConfigPollQuadletCommand2();
    auto _RESERVEDIOThunderboltConfigPollQuadletCommand3();
    auto _RESERVEDIOThunderboltConfigPollQuadletCommand4();
    auto _RESERVEDIOThunderboltConfigPollQuadletCommand5();
    auto _RESERVEDIOThunderboltConfigPollQuadletCommand6();
    auto _RESERVEDIOThunderboltConfigPollQuadletCommand7();
    auto _RESERVEDIOThunderboltConfigPollQuadletCommand8();
    auto _RESERVEDIOThunderboltConfigPollQuadletCommand9();
    auto createResources();
    auto createResources()::_os_log_fmt;
    auto destroyResources();
    auto free();
    auto free()::_os_log_fmt;
    auto getConfigSpace();
    auto getMask();
    auto getMetaClass() const;
    auto getOffset();
    auto getPollCount();
    auto getPollInterval();
    auto getPort();
    auto getReadData();
    auto getValue();
    auto initWithController(IOThunderboltController*);
    auto initWithController(IOThunderboltController*)::_os_log_fmt;
    auto processConfigReadResults(void*, int, IOThunderboltConfigCommand*);
    auto processConfigReadResults(void*, int, IOThunderboltConfigCommand*)::_os_log_fmt;
    auto setConfigSpace(unsigned int);
    auto setMask(unsigned int);
    auto setOffset(unsigned int);
    auto setPollCount(unsigned int);
    auto setPollInterval(unsigned long long);
    auto setPort(unsigned int);
    auto setValue(unsigned int);
    auto submit();
    auto submit()::_os_log_fmt;
    auto submitNextConfigRead();
    auto submitNextConfigRead()::_os_log_fmt;
    auto timerCommandCallback(void*, int, IOThunderboltTimerCommand*);
    auto timerCommandCallback(void*, int, IOThunderboltTimerCommand*)::_os_log_fmt;
    auto withController(IOThunderboltController*);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~IOThunderboltConfigPollQuadletCommand();
};
