//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOThunderboltDeficitCommandQueue {
public: // (access info unavailable from symbols alone)
    IOThunderboltDeficitCommandQueue();
    IOThunderboltDeficitCommandQueue(OSMetaClass const*);
    auto _RESERVEDIOThunderboltDeficitCommandQueue0();
    auto _RESERVEDIOThunderboltDeficitCommandQueue1();
    auto _RESERVEDIOThunderboltDeficitCommandQueue2();
    auto _RESERVEDIOThunderboltDeficitCommandQueue3();
    auto _RESERVEDIOThunderboltDeficitCommandQueue4();
    auto free();
    auto getDeficit();
    auto getMetaClass() const;
    auto getQuantum();
    auto initWithWorkLoop(IOWorkLoop*);
    auto setDeficit(long long);
    auto setQuantum(long long);
    auto withWorkLoop(IOWorkLoop*);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~IOThunderboltDeficitCommandQueue();
};
