//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOThunderboltArray {
public: // (access info unavailable from symbols alone)
    IOThunderboltArray();
    IOThunderboltArray(OSMetaClass const*);
    auto getMetaClass() const;
    auto withArray(OSArray const*, unsigned int);
    auto withCapacity(unsigned int);
    auto withObjects(OSObject const**, unsigned int, unsigned int);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~IOThunderboltArray();
};
