//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOThunderboltSwitchDelegate {
public: // (access info unavailable from symbols alone)
    IOThunderboltSwitchDelegate();
    IOThunderboltSwitchDelegate(OSMetaClass const*);
    _RESERVEDIOThunderboltSwitchDelegate0();
    _RESERVEDIOThunderboltSwitchDelegate1();
    _RESERVEDIOThunderboltSwitchDelegate2();
    _RESERVEDIOThunderboltSwitchDelegate3();
    _RESERVEDIOThunderboltSwitchDelegate4();
    _RESERVEDIOThunderboltSwitchDelegate5();
    _RESERVEDIOThunderboltSwitchDelegate6();
    _RESERVEDIOThunderboltSwitchDelegate7();
    configureSpecialMode(unsigned int);
    controllerWillPowerDown();
    enterSpecialMode(unsigned int);
    exitSpecialMode(unsigned int);
    getControllerRID();
    getMetaClass() const;
    getRootDROM();
    getRouteString();
    getSwitch();
    identifyHWRevision();
    initWithControllerAndSwitch(IOThunderboltController*, IOThunderboltSwitch*);
    invalidateClientsOnPort(IOThunderboltPort*, bool);
    isLinkUp(IOThunderboltPort*, bool*);
    lateSleepPhase3();
    overrideDeviceHeader(unsigned int*);
    overrideDevicesConnectedState(bool*, bool);
    overrideIsPortDisabled(unsigned char, bool);
    overrideMinimumRequiredTMUMode(unsigned int);
    overridePortHeader(unsigned char, unsigned int*);
    overrideSupportedCLxStates(unsigned int, IOThunderboltPort*);
    overrideTRMPolicyPortFromPort(IOThunderboltPort*, IOThunderboltPort*);
    portSupportsDeviceScan(IOThunderboltPort*, bool);
    postConfigureRouter();
    preConfigureRouter();
    processXDomainLinkPreload();
    publishAdapterData();
    publishSocketIDs();
    restoreSleepState();
    saveSleepState();
    setupSpecialModes();
    updateCableParameters();
    updateWakeEnables();
    ~IOThunderboltSwitchDelegate();
};
