//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOThunderboltXDLocalPropertiesCache {
public: // (access info unavailable from symbols alone)
    IOThunderboltXDLocalPropertiesCache();
    IOThunderboltXDLocalPropertiesCache(OSMetaClass const*);
    _RESERVEDIOThunderboltXDLocalPropertiesCache0();
    _RESERVEDIOThunderboltXDLocalPropertiesCache1();
    _RESERVEDIOThunderboltXDLocalPropertiesCache10();
    _RESERVEDIOThunderboltXDLocalPropertiesCache11();
    _RESERVEDIOThunderboltXDLocalPropertiesCache12();
    _RESERVEDIOThunderboltXDLocalPropertiesCache13();
    _RESERVEDIOThunderboltXDLocalPropertiesCache14();
    _RESERVEDIOThunderboltXDLocalPropertiesCache15();
    _RESERVEDIOThunderboltXDLocalPropertiesCache2();
    _RESERVEDIOThunderboltXDLocalPropertiesCache3();
    _RESERVEDIOThunderboltXDLocalPropertiesCache4();
    _RESERVEDIOThunderboltXDLocalPropertiesCache5();
    _RESERVEDIOThunderboltXDLocalPropertiesCache6();
    _RESERVEDIOThunderboltXDLocalPropertiesCache7();
    _RESERVEDIOThunderboltXDLocalPropertiesCache8();
    _RESERVEDIOThunderboltXDLocalPropertiesCache9();
    addDictionaryToWorkQueue(OSDictionary*, OSNumber*, OSArray*);
    addDictionaryToWorkQueue(OSDictionary*, OSNumber*, OSArray*)::_os_log_fmt;
    addItemToWorkQueue(unsigned short, OSString*, OSObject*, OSNumber*, OSArray*);
    addItemToWorkQueue(unsigned short, OSString*, OSObject*, OSNumber*, OSArray*)::_os_log_fmt;
    encodeDictionary(OSDictionary*);
    encodeDictionary(OSDictionary*) (.cold.1);
    encodeDictionary(OSDictionary*) (.cold.2);
    encodeDictionary(OSDictionary*) (.cold.3);
    encodeDictionary(OSDictionary*) (.cold.4);
    encodeDictionary(OSDictionary*)::_os_log_fmt;
    free();
    free()::_os_log_fmt;
    getMetaClass() const;
    initWithLocalNode(IOThunderboltLocalNode*);
    initWithLocalNode(IOThunderboltLocalNode*)::_os_log_fmt;
    publish(IOThunderboltXDDirectory*);
    publish(IOThunderboltXDDirectory*)::_os_log_fmt;
    withLocalNode(IOThunderboltLocalNode*);
    ~IOThunderboltXDLocalPropertiesCache();
};
