//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOThunderboltXDPropertiesEntry {
public: // (access info unavailable from symbols alone)
    IOThunderboltXDPropertiesEntry();
    IOThunderboltXDPropertiesEntry(OSMetaClass const*);
    auto _RESERVEDIOThunderboltXDPropertiesEntry0();
    auto _RESERVEDIOThunderboltXDPropertiesEntry1();
    auto _RESERVEDIOThunderboltXDPropertiesEntry10();
    auto _RESERVEDIOThunderboltXDPropertiesEntry11();
    auto _RESERVEDIOThunderboltXDPropertiesEntry12();
    auto _RESERVEDIOThunderboltXDPropertiesEntry13();
    auto _RESERVEDIOThunderboltXDPropertiesEntry14();
    auto _RESERVEDIOThunderboltXDPropertiesEntry15();
    auto _RESERVEDIOThunderboltXDPropertiesEntry2();
    auto _RESERVEDIOThunderboltXDPropertiesEntry3();
    auto _RESERVEDIOThunderboltXDPropertiesEntry4();
    auto _RESERVEDIOThunderboltXDPropertiesEntry5();
    auto _RESERVEDIOThunderboltXDPropertiesEntry6();
    auto _RESERVEDIOThunderboltXDPropertiesEntry7();
    auto _RESERVEDIOThunderboltXDPropertiesEntry8();
    auto _RESERVEDIOThunderboltXDPropertiesEntry9();
    auto createIDString();
    auto createKeyString();
    auto createTypeString();
    auto free();
    auto free()::_os_log_fmt;
    auto getCache();
    auto getDataBytes();
    auto getDataOffsetInQuads();
    auto getEntryBytes();
    auto getEntryOffsetInQuads();
    auto getKey();
    auto getMetaClass() const;
    auto getSizeInQuads();
    auto getType();
    auto initResources();
    auto initWithCache(IOThunderboltXDPropertiesCache*, unsigned int);
    auto initWithCache(IOThunderboltXDPropertiesCache*, unsigned int)::_os_log_fmt;
    auto readEntry();
    auto setSizeInQuads(unsigned int);
    auto withCache(IOThunderboltXDPropertiesCache*, unsigned int);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~IOThunderboltXDPropertiesEntry();
};
