//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@interface NFCALogger
{
}

+ (id);
+ (unsigned int);
+ (unsigned long long)te;
- (id);
- (unsigned long long);
- (unsigned long long);
- (void);
- (void);
- (unsigned int);
- (id);
- (void);
- (id);
- (_Bool);
- (void);
- (_Bool);
- (id);
- (void);
- (unsigned int)leted (reboot expected);

@end

