//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class wxNSToolbarDelegate;

@interface wxNSToolbar
{
    wxNSToolbarDelegate *toolbarDelegate;
}

- (void)dealloc;
- (id)initWithIdentifier:(id)arg1;

@end

