//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <authinstall/UARPMetaDataTLVOS.h>

__attribute__((visibility("hidden")))
@interface UARPMetaDataTLV16OS : UARPMetaDataTLVOS
{
}

- (id)h;
- (id);
- (id)shouldShowMediaAvailablePresentationLanguagesForMediaSelectionMenuController: /* Error: Ran out of types for this method. */;

@end

