//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

// Global C++ functions

AppleUSBHostMergeProperties::gMetaClass;
AppleUSBMergeNub::gMetaClass;
AppleUSBMergeNub::metaClass;
AppleUSBMergeNub::superClass;
AppleUSBMergeNub_ktv;
vtable for AppleUSBMergeNub;
vtable for AppleUSBMergeNub::MetaClass;
