//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOReportLegend {
public: // (access info unavailable from symbols alone)
    auto addReporterLegend(IOReporter*, char const*, char const*);
    auto getLegend();
    auto with(OSArray*);
};
