//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleBCMWLANPCIeTransmitFlowRing {
public: // (access info unavailable from symbols alone)
    auto checkForWork();
    auto copyDestinationAddress(unsigned char*);
    auto copySourceAddress(unsigned char*);
    auto dumpRingState(char const*, char*, unsigned int, unsigned int, unsigned int);
    auto enable();
    auto free();
    auto free()::kalloc_type_view_153;
    auto getAc();
    auto getCounter();
    auto getIfFlags();
    auto getIfIndx();
    auto getIntVector();
    auto getMetaClass() const;
    auto getPriority();
    auto getReason();
    auto getResourceID();
    auto getState();
    auto getTc();
    auto getTid();
    auto initWithOwnerAndFillAction(OSObject*, unsigned int (*)(OSObject*, AppleBCMWLANByteRing*, void*, unsigned int), void (*)(OSObject*, AppleBCMWLANByteRing*, int, void*), TransmitFlowRingInfo&, CCLogStream*);
    auto initWithOwnerAndFillAction(OSObject*, unsigned int (*)(OSObject*, AppleBCMWLANByteRing*, void*, unsigned int), void (*)(OSObject*, AppleBCMWLANByteRing*, int, void*), TransmitFlowRingInfo&, CCLogStream*)::kalloc_type_view_101;
    auto logRing(char const*, unsigned int);
    auto printRingState(char const*);
    auto requestRingFill(unsigned int, bool);
    auto setReason(unsigned short);
    auto setResourceID(short);
    auto setState(TransmitFlowState);
    auto withOptions(OSObject*, unsigned int (*)(OSObject*, AppleBCMWLANByteRing*, void*, unsigned int), void (*)(OSObject*, AppleBCMWLANByteRing*, int, void*), TransmitFlowRingInfo&, CCLogStream*);
    ~AppleBCMWLANPCIeTransmitFlowRing();
};
