//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleBCMWLANPCIeSubmissionRing {
public: // (access info unavailable from symbols alone)
    checkForWork();
    commit();
    dumpRingState(char const*, char*, unsigned int, unsigned int, unsigned int);
    free();
    free()::kalloc_type_view_215;
    getBuffer();
    getBufferSize();
    getBusAddress(BCOMPCIeRingBusAddr volatile&);
    getCounter();
    getIndices(unsigned int*, unsigned int*);
    getMetaClass() const;
    getPhaseBit();
    getReadIndex();
    getRingID();
    getRingType();
    getWriteIndex();
    initWithOwnerAndOptions(OSObject*, unsigned int (*)(OSObject*, AppleBCMWLANByteRing*, void*, unsigned int), void (*)(OSObject*, AppleBCMWLANByteRing*, int, void*), PCIeRingCreationInfo&, CCLogStream*);
    initWithOwnerAndOptions(OSObject*, unsigned int (*)(OSObject*, AppleBCMWLANByteRing*, void*, unsigned int), void (*)(OSObject*, AppleBCMWLANByteRing*, int, void*), PCIeRingCreationInfo&, CCLogStream*)::kalloc_type_view_100;
    logRing(char const*, unsigned int);
    printRingState(char const*);
    requestRingFill(unsigned int, bool);
    signalWorkRecheck();
    withOptions(OSObject*, unsigned int (*)(OSObject*, AppleBCMWLANByteRing*, void*, unsigned int), void (*)(OSObject*, AppleBCMWLANByteRing*, int, void*), PCIeRingCreationInfo&, CCLogStream*);
    ~AppleBCMWLANPCIeSubmissionRing();
};
