//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleEmbeddedBluetoothProximity {
public: // (access info unavailable from symbols alone)
    AppleEmbeddedBluetoothProximity();
    AppleEmbeddedBluetoothProximity(OSMetaClass const*);
    auto dispatchProximityEvent(unsigned long long, unsigned char);
    auto free();
    auto getMetaClass() const;
    auto handleInterruptReport(unsigned long long, IOMemoryDescriptor*, IOHIDReportType, unsigned int);
    auto handleInterruptReport(unsigned long long, IOMemoryDescriptor*, IOHIDReportType, unsigned int)::_os_log_fmt;
    auto init(OSDictionary*);
    auto setProperties(OSObject*);
    auto setProperties(OSObject*)::_os_log_fmt;
    auto setProximityState(unsigned char);
    auto start(IOService*);
    auto start(IOService*)::_os_log_fmt;
    auto stop(IOService*);
    auto stop(IOService*)::_os_log_fmt;
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~AppleEmbeddedBluetoothProximity();
};
