//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class axis::DynamicIndexImpl::find_nearest_neighbors_worker<axis {
public: // (access info unavailable from symbols alone)
    guard variable for std::__1::pair<std::__1::set<axis::DynamicIndexHandle*, std::__1::less<axis::DynamicIndexHandle*>, std::__1::allocator<axis::DynamicIndexHandle*>>, double> Geometry2D>(axis::Geometry2D const&, double) const::acc;
    guard variable for std::__1::pair<std::__1::set<axis::DynamicIndexHandle*, std::__1::less<axis::DynamicIndexHandle*>, std::__1::allocator<axis::DynamicIndexHandle*>>, double> LineSeg2D>(axis::LineSeg2D const&, double) const::acc;
    guard variable for std::__1::pair<std::__1::set<axis::DynamicIndexHandle*, std::__1::less<axis::DynamicIndexHandle*>, std::__1::allocator<axis::DynamicIndexHandle*>>, double> Point2D>(axis::Point2D const&, double) const::acc;
    guard variable for std::__1::pair<std::__1::set<axis::DynamicIndexHandle*, std::__1::less<axis::DynamicIndexHandle*>, std::__1::allocator<axis::DynamicIndexHandle*>>, double> PointData2D>(axis::PointData2D const&, double) const::acc;
    std::__1::pair<std::__1::set<axis::DynamicIndexHandle*, std::__1::less<axis::DynamicIndexHandle*>, std::__1::allocator<axis::DynamicIndexHandle*>>, double> Geometry2D>(axis::Geometry2D const&, double) const::acc;
    std::__1::pair<std::__1::set<axis::DynamicIndexHandle*, std::__1::less<axis::DynamicIndexHandle*>, std::__1::allocator<axis::DynamicIndexHandle*>>, double> LineSeg2D>(axis::LineSeg2D const&, double) const::acc;
    std::__1::pair<std::__1::set<axis::DynamicIndexHandle*, std::__1::less<axis::DynamicIndexHandle*>, std::__1::allocator<axis::DynamicIndexHandle*>>, double> Point2D>(axis::Point2D const&, double) const::acc;
    std::__1::pair<std::__1::set<axis::DynamicIndexHandle*, std::__1::less<axis::DynamicIndexHandle*>, std::__1::allocator<axis::DynamicIndexHandle*>>, double> PointData2D>(axis::PointData2D const&, double) const::acc;
};
