//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class axis::AffineTransformation {
public: // (access info unavailable from symbols alone)
    AffineTransformation();
    AffineTransformation(axis::AffineTransformation const&);
    AffineTransformation(double, double, double, double, double, double);
    compose(axis::AffineTransformation const&) const;
    from_identity();
    from_reflection(axis::BaseVector2D<double> const&);
    from_reflection(double, double);
    from_rotation(double);
    from_rotation(double, double, double);
    from_scale(double);
    from_scale(double, double);
    from_translation(axis::BaseVector2D<double> const&);
    from_translation(double, double);
    get(axis::PointData2D const&) const;
    make(axis::PointData2D&) const;
    operator*(axis::AffineTransformation const&) const;
    operator*(axis::PointData2D const&) const;
    operator=(axis::AffineTransformation const&);
};
