//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class terra::Angle3D {
public: // (access info unavailable from symbols alone)
    compare_line_line(terra::PointData3D const&, terra::PointData3D const&, terra::PointData3D const&, double const&);
    compare_line_line(terra::PointData3D const&, terra::PointData3D const&, terra::PointData3D const&, terra::PointData3D const&, terra::PointData3D const&, terra::PointData3D const&);
    compare_plane_line(terra::PointData3D const&, terra::PointData3D const&, terra::PointData3D const&, terra::PointData3D const&, terra::PointData3D const&, double const&);
    compare_plane_line(terra::PointData3D const&, terra::PointData3D const&, terra::PointData3D const&, terra::PointData3D const&, terra::PointData3D const&, terra::PointData3D const&, terra::PointData3D const&, terra::PointData3D const&, terra::PointData3D const&, terra::PointData3D const&);
    compare_plane_plane(terra::PointData3D const&, terra::PointData3D const&, terra::PointData3D const&, terra::PointData3D const&, terra::PointData3D const&, terra::PointData3D const&, double const&);
    compare_plane_plane(terra::PointData3D const&, terra::PointData3D const&, terra::PointData3D const&, terra::PointData3D const&, terra::PointData3D const&, terra::PointData3D const&, terra::PointData3D const&, terra::PointData3D const&, terra::PointData3D const&, terra::PointData3D const&, terra::PointData3D const&, terra::PointData3D const&);
    compute_line_line(terra::PointData3D const&, terra::PointData3D const&, terra::PointData3D const&);
    compute_plane_line(terra::PointData3D const&, terra::PointData3D const&, terra::PointData3D const&, terra::PointData3D const&, terra::PointData3D const&);
    compute_plane_plane(terra::PointData3D const&, terra::PointData3D const&, terra::PointData3D const&, terra::PointData3D const&, terra::PointData3D const&, terra::PointData3D const&);
};
