//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

// Global C++ functions

AppleACPIACAdapter::gMetaClass;
AppleACPIACAdapter::metaClass;
AppleACPIACAdapter::operator delete(void*, unsigned long);
AppleACPIACAdapter::operator new(unsigned long);
AppleACPIACAdapter::superClass;
AppleACPIACAdapter_ktv;
AppleACPIButton::gMetaClass;
AppleACPIButton::metaClass;
AppleACPIButton::operator delete(void*, unsigned long);
AppleACPIButton::operator new(unsigned long);
AppleACPIButton::superClass;
AppleACPIButton_ktv;
AppleACPILid::gMetaClass;
AppleACPILid::metaClass;
AppleACPILid::operator delete(void*, unsigned long);
AppleACPILid::operator new(unsigned long);
AppleACPILid::superClass;
AppleACPILid_ktv;
IOACPIPlatformDevice::metaClass;
IOHIDEventService::gMetaClass;
IOService::gMetaClass;
IOService::metaClass;
OSData::metaClass;
OSNumber::metaClass;
OSString::metaClass;
vtable for AppleACPIACAdapter;
vtable for AppleACPIACAdapter::MetaClass;
vtable for AppleACPIButton;
vtable for AppleACPIButton::MetaClass;
vtable for AppleACPILid;
vtable for AppleACPILid::MetaClass;
vtable for IOHIDEventService;
vtable for IOService;
