//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension ARKit.GeometryElement.Primitive {
    == infix(ARKit.GeometryElement.Primitive, ARKit.GeometryElement.Primitive) -> Swift.Bool
    hash(into: inout Swift.Hasher) -> ()
}
