//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension ARKit.MeshAnchor.MeshClassification {
    init(rawValue: Swift.Int) -> Swift.Optional<ARKit.MeshAnchor.MeshClassification>
}
