//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension ARKit.HeadsetFitCoachingProvider.coachingUpdates {
    getter : ARKit.HeadsetFitCoachingProvider.HeadsetFitCoachingUpdates
}
