//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension ARKit.NutrinoBodySkeleton.JointName.allCases {
    getter : Swift.Array<ARKit.NutrinoBodySkeleton.JointName>
}
