//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@interface ARKit.ImageTrackingProvider
{
    id _cImageTrackingProvider;
    id _cImageTrackingConfiguration;
    id anchorUpdateIterators;
    id anchorQueue;
    id referenceImages;
}

@end

