//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class qmi::RandomMessageReporter {
public: // (access info unavailable from symbols alone)
    reportMismatch(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&);
    reportParseUnderrun();
    reportTlvMissing(unsigned char);
    reportTlvParseFailure(unsigned char);
    verifyMessageId(unsigned short, unsigned short);
    verifyTlvId(unsigned char, unsigned char);
    ~RandomMessageReporter();
};
