//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOUserEthernetInterface {
public: // (access info unavailable from symbols alone)
    IOUserEthernetInterface();
    IOUserEthernetInterface(OSMetaClass const*);
    __OSFinalClass();
    attachToDataLinkLayer(unsigned int, void*);
    detachFromDataLinkLayer(unsigned int, void*);
    getMetaClass() const;
    getNamePrefix() const;
    init(IONetworkController*);
    registerService(unsigned int);
    ~IOUserEthernetInterface();
};
