//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class MPIFrame {
public: // (access info unavailable from symbols alone)
    MPIFrame();
    MPIFrame(OSMetaClass const*);
    auto WithParameters(unsigned long long, unsigned long long, unsigned int, unsigned int);
    auto getMetaClass() const;
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~MPIFrame();
};
