//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class amber::XPCDaemonClient {
public: // (access info unavailable from symbols alone)
    XPCDaemonClient(std::__1::basic_string_view<char, std::__1::char_traits<char>>);
    auto connect(amber::URL const&, amber::ConstMemoryView, unsigned long long, unsigned int, unsigned long long);
    auto processGetCapabilities(amber::XPCSession*, amber::URL const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>&);
    non-virtual thunk to ~XPCDaemonClient();
    ~XPCDaemonClient();
};
