//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension CoreAudio.AudioHardwareDevice {
    __allocating_init(id: Swift.UInt32) -> CoreAudio.AudioHardwareDevice
    __deallocating_deinit
    deinit
    init(id: Swift.UInt32) -> CoreAudio.AudioHardwareDevice
    nearestStartTime(atTime: __C.AudioTimeStamp, withFlags: Swift.UInt32) throws -> __C.AudioTimeStamp
    setBufferFrameSize(Swift.Int) throws -> ()
    setClock(CoreAudio.AudioHardwareClock) throws -> ()
    setIOCycleUsage(Swift.Float) throws -> ()
    setIsProcessInputMuted(Swift.Bool) throws -> ()
    setIsProcessOutputMuted(Swift.Bool) throws -> ()
    setPreferredInputChannelsForStereo(Swift.Array<Swift.UInt32>) throws -> ()
    setPreferredOutputChannelsForStereo(Swift.Array<Swift.UInt32>) throws -> ()
    start(IOProcID: Swift.Optional<@convention(c) (Swift.UInt32, Swift.UnsafePointer<__C.AudioTimeStamp>, Swift.UnsafePointer<__C.AudioBufferList>, Swift.UnsafePointer<__C.AudioTimeStamp>, Swift.UnsafeMutablePointer<__C.AudioBufferList>, Swift.UnsafePointer<__C.AudioTimeStamp>, Swift.Optional<Swift.UnsafeMutableRawPointer>) -> Swift.Int32>) throws -> ()
    start(at: __C.AudioTimeStamp, flags: Swift.UInt32, IOProcID: Swift.Optional<@convention(c) (Swift.UInt32, Swift.UnsafePointer<__C.AudioTimeStamp>, Swift.UnsafePointer<__C.AudioBufferList>, Swift.UnsafePointer<__C.AudioTimeStamp>, Swift.UnsafeMutablePointer<__C.AudioBufferList>, Swift.UnsafePointer<__C.AudioTimeStamp>, Swift.Optional<Swift.UnsafeMutableRawPointer>) -> Swift.Int32>) throws -> Swift.Optional<__C.AudioTimeStamp>
    stop(IOProcID: Swift.Optional<@convention(c) (Swift.UInt32, Swift.UnsafePointer<__C.AudioTimeStamp>, Swift.UnsafePointer<__C.AudioBufferList>, Swift.UnsafePointer<__C.AudioTimeStamp>, Swift.UnsafeMutablePointer<__C.AudioBufferList>, Swift.UnsafePointer<__C.AudioTimeStamp>, Swift.Optional<Swift.UnsafeMutableRawPointer>) -> Swift.Int32>) throws -> ()
    toggleHogMode() throws -> Swift.Int32
    translateTime(__C.AudioTimeStamp) throws -> __C.AudioTimeStamp
}
