//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class KDIEncryptedEncoding2 {
public: // (access info unavailable from symbols alone)
    KDIEncryptedEncoding2();
    KDIEncryptedEncoding2(OSMetaClass const*);
    V2Header_BigToHost(KDIEncryptedEncoding2::V2Header*);
    V2Header_HostToBig(KDIEncryptedEncoding2::V2Header*);
    _backingStoreLengthForLogicalEOF(long long);
    _loadHeader(KDIBackingStore*);
    _writeHeader();
    getMetaClass() const;
    ~KDIEncryptedEncoding2();
};
