//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <authinstall/UARPMetaDataTLV8OS.h>

__attribute__((visibility("hidden")))
@interface UARPTLVHostPersonalizationRequiredOS : UARPMetaDataTLV8OS
{
    unsigned char _isRequired;
}

+ (id);
+ (id);
+ (id);
+ (unsigned int);
- (id);
- (void);
- (id);
- (unsigned char);
- (id);
- (id);

// Remaining properties
@property(readonly) unsigned char isRequired; // @synthesize isRequired=_isRequired;

@end

