//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class ACIPCBTControlClass {
public: // (access info unavailable from symbols alone)
    ACIPCBTControlClass();
    clearEventNotificationPort();
    clearEventNotificationPort() (.cold.1);
    clearEventNotificationPort() (.cold.2);
    clearNotificationPort();
    close();
    close_nl();
    deregisterEventNotification(dispatch_group_s*);
    deregisterEventNotification_nl(dispatch_group_s*);
    deregisterEventNotification_nl(dispatch_group_s*) (.cold.1);
    generalInterestCallback(void*, unsigned int, unsigned int, void*);
    getLastKnownBootStage(unsigned int*);
    getLogInternalBufferSize(unsigned int*);
    loggerTune(unsigned int, unsigned int, void*, void*);
    open(__CFRunLoop*);
    open(dispatch_queue_s*);
    open_nl(__CFRunLoop*, dispatch_queue_s*);
    open_nl(__CFRunLoop*, dispatch_queue_s*) (.cold.1);
    readLogsAsync(void*, unsigned int, bool, void (*)(void*, int, void*), void*);
    registerEventNotification(__CFRunLoop*, ACIPCControlEvent*);
    registerEventNotification(dispatch_queue_s*, ACIPCControlEvent*);
    registerEventNotification_nl(__CFRunLoop*, dispatch_queue_s*, ACIPCControlEvent*);
    registerEventNotification_nl(__CFRunLoop*, dispatch_queue_s*, ACIPCControlEvent*) (.cold.1);
    setEventNotificationPort();
    setEventNotificationPort() (.cold.1);
    setNotificationPort();
    setNotificationPort() (.cold.1);
    start();
    stop();
    waitforService();
    ~ACIPCBTControlClass();
};
