//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppleTconUARPUpdater/UARPMetaData.h>

@class NSMutableArray, NSMutableData;

@interface UARPMetaDataPersonalizationFTABPayload : UARPMetaData
{
    NSMutableArray *_tlvsMutable;
    NSMutableData *_tlvDataMutable;
}

- (id);
- (id);
- (id);
- (id);
- (id);
- (id);
- (id);
- (id);
- (id);
- (_Bool);
- (id);
- (id);
- (id);
- (id);
- (id);
- (void);

@end

