//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class std::__1::__function::__value_func<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> (unsigned long long, unsigned long long)> {
public: // (access info unavailable from symbols alone)
    auto operator()[abi:nqn210106](unsigned long long&&, unsigned long long&&) const;
};
