//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class bssl::SSL_HANDSHAKE {
public: // (access info unavailable from symbols alone)
    SSL_HANDSHAKE(ssl_st*);
    auto GetClientHello(bssl::SSLMessage*, ssl_early_callback_ctx*);
    ~SSL_HANDSHAKE();
};
