//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class bssl::SSLBuffer {
public: // (access info unavailable from symbols alone)
    auto Clear();
    auto DidWrite(unsigned long);
    auto DiscardConsumed();
    auto EnsureCap(unsigned long, unsigned long);
    ~SSLBuffer();
};
