//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class bssl::New<bssl::CERT, bssl {
public: // (access info unavailable from symbols alone)
    SSL_X509_METHOD const* const&>(bssl::SSL_X509_METHOD const* const&);
    SSL_X509_METHOD const*&>(bssl::SSL_X509_METHOD const*&);
};
