//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class std::__1::unique_ptr<err_save_state_st, bssl::internal::Deleter> {
public: // (access info unavailable from symbols alone)
    reset[abi:ne200100](err_save_state_st*);
};
