//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@interface nwswifttls.STLSRecordHandler
{
    id recordHandler;
    id logString;
}

- (void);
- (_Bool);
- (id);
- (id);
- (id);
- (id);
- (id)C;
- (id);
- (_Bool);
- (id);
- (id);
- (unsigned int);
- (long long);
- (id);
- (_Bool);
- (long long);
- (_Bool);
- (unsigned int);
- (id);
- (long long);
- (void);
- (_Bool);
- (void);
- (int);
- (void);
- (id);
- (void);

@end

