//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension SwiftTLSLibrary.Extension.PAKE.PAKEServerHello {
    __derived_struct_equals(SwiftTLSLibrary.Extension.PAKE.PAKEServerHello, SwiftTLSLibrary.Extension.PAKE.PAKEServerHello) -> Swift.Bool
    hash(into: inout Swift.Hasher) -> ()
    init(serverShare: SwiftTLSLibrary.Extension.PAKE.PAKEShare) -> SwiftTLSLibrary.Extension.PAKE.PAKEServerHello
}
