//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension Swift {
    ELEMENT_TYPE_OF_SET_VIOLATES_HASHABLE_REQUIREMENTS(Any.Type) -> Swift.Never
    KEY_TYPE_OF_DICTIONARY_VIOLATES_HASHABLE_REQUIREMENTS(Any.Type) -> Swift.Never
    _bridgeAnyObjectToAny(Swift.Optional<Swift.AnyObject>) -> Any
    _bridgeAnythingNonVerbatimToObjectiveC<A>(__owned A) -> Swift.AnyObject
    _bridgeAnythingToObjectiveC<A>(A) -> Swift.AnyObject
    _minimumMergeRunLength(Swift.Int) -> Swift.Int
    _stdlib_isOSVersionAtLeastOrVariantVersionAtLeast(Builtin.Word, Builtin.Word, Builtin.Word, Builtin.Word, Builtin.Word, Builtin.Word) -> Builtin.Int1
    _stringCompareWithSmolCheck(_: Swift._StringGuts, _: Swift._StringGuts, expecting: Swift._StringComparisonResult) -> Swift.Bool
}
