//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension SwiftTLSLibrary.HandshakeState.ClientHelloState {
    sendingClientHello(originalState: SwiftTLSLibrary.HandshakeState.IdleState, clientHello: inout SwiftTLSLibrary.ClientHello, sessionToResume: Swift.Optional<SwiftTLSLibrary.SessionTicket>, epsks: Swift.Array<SwiftTLSLibrary.GeneralEPSK>, useRawEPSKs: Swift.Bool, ephemeralKeyShare: Swift.Optional<SwiftTLSLibrary.GeneratedEphemeralPrivateKey>, currentTime: Foundation.Date) throws(SwiftTLSLibrary.TLSError) -> (state: SwiftTLSLibrary.HandshakeState.ClientHelloState, clientHelloBytes: SwiftTLSLibrary.ByteBuffer)
}
