//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension SwiftTLSLibrary.ServerHandshakeStateMachine.Configuration {
    init(serverName: Swift.Optional<Swift.String>, signingKey: Swift.Optional<CryptoKit.P256.Signing.PrivateKey>, quicTransportParameters: Swift.Optional<SwiftTLSLibrary.ByteBuffer>, alpn: Swift.Optional<Swift.Array<Swift.String>>, enableEarlyData: Swift.Bool, transportIsQUIC: Swift.Bool, useRawEPSKs: Swift.Bool) -> SwiftTLSLibrary.ServerHandshakeStateMachine.Configuration
}
