//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension SwiftTLSLibrary.ExtensionType.quicTransportParameters {
    getter : SwiftTLSLibrary.ExtensionType
    unsafeMutableAddressor : SwiftTLSLibrary.ExtensionType
}
