//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension SwiftTLSLibrary.ServerHandshakeState.NegotiatedParams {
    init(negotiatedGroup: SwiftTLSLibrary.NamedGroup, negotiatedSignatureAlgorithm: SwiftTLSLibrary.SignatureScheme, negotiatedCertificateType: SwiftTLSLibrary.CertificateType) -> SwiftTLSLibrary.ServerHandshakeState.NegotiatedParams
}
