//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension Swift.UnsafeMutableRawBufferPointer.withMemoryRebound<A, B, C where B: Swift.Error, A: ~Swift.Copyable, C: ~Swift {
    Copyable>(to: A.Type, _: (Swift.UnsafeMutableBufferPointer<A>) throws(B) -> C) throws(B) -> C
}
