//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOAccelGPURestartReport {
public: // (access info unavailable from symbols alone)
    IOAccelGPURestartReport();
    IOAccelGPURestartReport(OSMetaClass const*);
    auto getMetaClass() const;
    auto newUserClient(task*, void*, unsigned int, IOUserClient**);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~IOAccelGPURestartReport();
};
