//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOGPUChannel {
public: // (access info unavailable from symbols alone)
    IOGPUChannel(OSMetaClass const*);
    auto free();
    auto getChannelLabel() const;
    auto getMetaClass() const;
    auto hasStampIndexInEvent(IOGPUEvent const*) const;
    auto incrementStamp();
    auto init(IOGPU*, int);
    auto isIdle() const;
    auto mergeEventExcluding(IOGPUEvent*, IOGPUEvent*);
    auto setEventStamp(IOGPUEvent*);
    auto setStampIndex(int);
    auto updateChannelStampIndex(IOGPUDevice*);
    auto writeEventBarrierCommand(IOGPUEventQueue*, IOGPUEvent*, vendevtBarrierRec*);
    auto writeStampCommand(IOGPUEventQueue*, vendevtCommandRec*);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~IOGPUChannel();
};
