//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOGPUMTLLateEvalEvent {
public: // (access info unavailable from symbols alone)
    IOGPUMTLLateEvalEvent();
    IOGPUMTLLateEvalEvent(OSMetaClass const*);
    auto free();
    auto getMetaClass() const;
    auto getSubmittedValue();
    auto initWithAccelerator(IOGPU*);
    auto signalSubmitted(unsigned long long);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~IOGPUMTLLateEvalEvent();
};
