//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOGPUMTLEvent {
public: // (access info unavailable from symbols alone)
    IOGPUMTLEvent();
    IOGPUMTLEvent(OSMetaClass const*);
    auto clean_ring();
    auto clean_ring() (.cold.1);
    auto copySubmitted(unsigned long long, IOGPUEvent*, unsigned long long, unsigned long long, unsigned long long);
    auto free();
    auto getMetaClass() const;
    auto initWithAccelerator(IOGPU*, unsigned long long);
    auto scrubEvents();
    auto signalSubmitted(IOGPUEvent const*, unsigned long long);
    auto withAccelerator(IOGPU*, unsigned long long);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~IOGPUMTLEvent();
};
