//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOSurface {
public: // (access info unavailable from symbols alone)
    clientRetain();
    copyValue(char const*, unsigned int*) const;
    createFence(unsigned int, unsigned int);
    deviceCacheForAccelerator(void*, unsigned int, unsigned int);
    getAllocSize() const;
    getClientAlignedOffset() const;
    getHeight() const;
    getLockSeed() const;
    getMemoryDescriptor() const;
    getPixelFormat() const;
    getPlaneCount() const;
    getPlaneOffset(unsigned int) const;
    getProtectionOptions() const;
    getSurfaceID() const;
    getUnlockSeed() const;
    getWidth() const;
    isGPUGlobalRO() const;
    setIsAllocated(bool);
    setLayoutFromDescriptor(IOSurfaceDescriptor const*);
    setMemoryDescriptor(IOMemoryDescriptor*);
    setValue(char const*, OSMetaClassBase const*, unsigned int*);
};
