//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class KDIObject {
public: // (access info unavailable from symbols alone)
    _handleClose(IOService*, unsigned int);
    _handleOpen(IOService*, unsigned int, void*);
    _handleStop(IOService*);
    attach(IOService*);
    detach(IOService*);
    free();
    handleClose(IOService*, unsigned int);
    handleOpen(IOService*, unsigned int, void*);
    message(unsigned int, IOService*, void*);
    start(IOService*);
    stop(IOService*);
};
