//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AMDSupport {
public: // (access info unavailable from symbols alone)
    AMDSupport();
    AMDSupport(OSMetaClass const*);
    attach(IOService*);
    detach(IOService*);
    getMetaClass() const;
    probe(IOService*, int*);
    start(IOService*);
    ~AMDSupport();
};
