//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AtiAtomFirmwareInterface {
public: // (access info unavailable from symbols alone)
    AtiAtomFirmwareInterface(OSMetaClass const*);
    auto createAtomParser(BiosParserServices*, unsigned char*, DCE_Version);
    auto executeBiosCommandTable(unsigned int, void*, unsigned int);
    auto free();
    auto getBiosCommandTableInformation(CmdTableInfo*);
    auto getCrystalFreqInKHz();
    auto getDefaultDisplayEngineClockInKHz();
    auto getDefaultEngineClockInKHz();
    auto getDefaultMemoryClockInKHz();
    auto getDentistVcoFreqInKHz();
    auto getExternalClockForDpInKHz();
    auto getImage(unsigned int, unsigned int);
    auto getMetaClass() const;
    auto init(BiosParserServices*, unsigned char*, DCE_Version);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~AtiAtomFirmwareInterface();
};
