//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AtiAsicInfoReader {
public: // (access info unavailable from symbols alone)
    AtiAsicInfoReader(OSMetaClass const*);
    auto createAsicInfoReader(AtiAsicInfoReader::InitInfo&);
    auto getMetaClass() const;
    auto init(AtiAsicInfoReader::InitInfo&);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~AtiAsicInfoReader();
};
