//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class ATIDigitalConnection {
public: // (access info unavailable from symbols alone)
    ATIDigitalConnection(OSMetaClass const*);
    getMetaClass() const;
    getName();
    init(ATIController*, ActiveConnectorInfo*, ATIPanel*);
    isAnalog();
    isCRT();
    isDigital();
    isDualLinkTiming(AtiDetailedTimingInformation const*);
    isTV();
    populateHdcpInfo();
    ~ATIDigitalConnection();
};
