//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AtiEncoderControl_V1_V4 {
public: // (access info unavailable from symbols alone)
    AtiEncoderControl_V1_V4();
    AtiEncoderControl_V1_V4(OSMetaClass const*);
    encoderControl(ActiveConnectorInfo const*, AtiAtomEncoderAction);
    encoderDpObfuscation(ActiveConnectorInfo const*, AtiAtomDpObfMode);
    getMetaClass() const;
    stringifyDpLinkRate(unsigned int);
    translateLinkClockForEncoderConfig(unsigned int);
    ~AtiEncoderControl_V1_V4();
};
