//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AtiEncoderControlInterface_V2 {
public: // (access info unavailable from symbols alone)
    AtiEncoderControlInterface_V2(OSMetaClass const*);
    createEncoderControl(AtiVBiosHelper*);
    getMetaClass() const;
    ~AtiEncoderControlInterface_V2();
};
