//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AtiEncoderControl_V1_5 {
public: // (access info unavailable from symbols alone)
    AtiEncoderControl_V1_5();
    AtiEncoderControl_V1_5(OSMetaClass const*);
    encoderControl(ActiveConnectorInfo const*, AtiAtomEncoderAction);
    encoderDpObfuscation(ActiveConnectorInfo const*, AtiAtomDpObfMode);
    getMetaClass() const;
    populateDpObfuscationParameters(ActiveConnectorInfo const*, dp_obfuscation_set_parameters_v1_5*, AtiAtomDpObfMode);
    populateGeneralParameters(ActiveConnectorInfo const*, dig_encoder_generic_cmd_parameters_v1_5*, AtiAtomEncoderAction);
    populateStreamSetupParameters(ActiveConnectorInfo const*, dig_encoder_stream_setup_parameters_v1_5*);
    stringifyBitsPerColor(unsigned short);
    stringifyDpObfuscationMode(unsigned short);
    translateLinkBitsToBitsPerColor(unsigned int);
    ~AtiEncoderControl_V1_5();
};
