//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AtiSelectCrtcSourceInterface_V2 {
public: // (access info unavailable from symbols alone)
    AtiSelectCrtcSourceInterface_V2(OSMetaClass const*);
    auto createSelectCrtcSource(AtiVBiosHelper*);
    auto getMetaClass() const;
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~AtiSelectCrtcSourceInterface_V2();
};
