//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class GammaTable {
public: // (access info unavailable from symbols alone)
    GammaTable();
    GammaTable(OSMetaClass const*);
    convertColorBits(IOColorEntry&, unsigned char, unsigned char);
    convertColorBits(unsigned short, unsigned char, unsigned char);
    copyTable(GammaTable*);
    doGammaCorrection(IOColorEntry*, unsigned short, unsigned short);
    doGammaCorrection(IOColorEntry*, unsigned short, unsigned short, unsigned short);
    doGammaCorrectionForComponent(unsigned short, unsigned short, GammaTable::Color);
    encodeCLUTEntry2PixelColor(unsigned short, IOPixelInformation const&, bool);
    fillWithColor(unsigned int);
    getChannelCount();
    getColor(GammaTable::Color, unsigned short);
    getColorBits();
    getColorBytes();
    getColorDataWithPointer(unsigned char*, unsigned short, unsigned short);
    getEntry(unsigned short);
    getMetaClass() const;
    getSize();
    init(unsigned short, unsigned short, unsigned short);
    initTable(unsigned short, unsigned short, unsigned short);
    refresh(GammaTable*);
    refresh(_AMD_PIPE_GAMMA_TABLE*);
    refresh(unsigned short, unsigned short, unsigned short, void*);
    reset(unsigned short, unsigned short, unsigned short);
    reset(unsigned short, unsigned short, unsigned short)::BLACK_ENTRY;
    setColor(GammaTable::Color, unsigned short, unsigned short);
    setEntry(unsigned short, IOColorEntry const&);
    setEntry(unsigned short, IOColorEntry const&, unsigned char);
    setHWMatchStatus(bool);
    setInternals(unsigned short, unsigned short, unsigned short);
    setLinearRamp();
    ~GammaTable();
};
