//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class VI_CHDCP {
public: // (access info unavailable from symbols alone)
    VI_CHDCP();
    VI_CHDCP(OSMetaClass const*);
    getMetaClass() const;
    ~VI_CHDCP();
};
