//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOFireWireAVCTargetSpace {
public: // (access info unavailable from symbols alone)
    IOFireWireAVCTargetSpace();
    IOFireWireAVCTargetSpace(OSMetaClass const*);
    auto _RESERVEDIOFireWireAVCTargetSpace0();
    auto _RESERVEDIOFireWireAVCTargetSpace1();
    auto _RESERVEDIOFireWireAVCTargetSpace2();
    auto _RESERVEDIOFireWireAVCTargetSpace3();
    auto activateWithUserClient(IOFireWireAVCProtocolUserClient*);
    auto addSubunit(IOFireWireAVCProtocolUserClient*, void (*)(AVCSubunitInfo const*, IOFWAVCSubunitPlugMessages, IOFWAVCPlugTypes, unsigned int, unsigned int, unsigned int, unsigned short), unsigned long long*, unsigned int, unsigned int, unsigned int, unsigned long long, unsigned long long, unsigned int*);
    auto canConnectDestPlug(unsigned int, IOFWAVCPlugTypes, unsigned int*);
    auto connectTargetPlugs(IOFireWireAVCProtocolUserClient*, _AVCConnectTargetPlugsInParams*, _AVCConnectTargetPlugsOutParams*);
    auto deactivateWithUserClient(IOFireWireAVCProtocolUserClient*);
    auto disconnectTargetPlugs(IOFireWireAVCProtocolUserClient*, unsigned int, IOFWAVCPlugTypes, unsigned int, unsigned int, IOFWAVCPlugTypes, unsigned int);
    auto doWrite(unsigned short, IOFWSpeed&, FWAddressStruct, unsigned int, void const*, void*);
    auto findAVCRequestHandler(IOFireWireAVCProtocolUserClient*, unsigned int, unsigned short, IOFWSpeed, unsigned int, char const*, unsigned int);
    auto getAVCTargetSpace(IOFireWireController*);
    auto getMetaClass() const;
    auto getSubunitInfo(unsigned int);
    auto getSubunitPlugSignalFormat(IOFireWireAVCProtocolUserClient*, unsigned int, IOFWAVCPlugTypes, unsigned int, unsigned int*);
    auto getTargetPlugConnection(IOFireWireAVCProtocolUserClient*, _AVCGetTargetPlugConnectionInParams*, _AVCGetTargetPlugConnectionOutParams*);
    auto handleConnectCommand(unsigned short, unsigned int, char const*, unsigned int);
    auto handleConnectionsCommand(unsigned short, unsigned int, char const*, unsigned int);
    auto handleDisconnectCommand(unsigned short, unsigned int, char const*, unsigned int);
    auto handleInputPlugSignalFormatCommand(unsigned short, unsigned int, char const*, unsigned int);
    auto handleOutputPlugSignalFormatCommand(unsigned short, unsigned int, char const*, unsigned int);
    auto handlePlugInfoCommand(unsigned short, unsigned int, char const*, unsigned int);
    auto handlePowerCommand(unsigned short, unsigned int, char const*, unsigned int);
    auto handleSignalSourceCommand(unsigned short, unsigned int, char const*, unsigned int);
    auto handleSubUnitInfoCommand(unsigned short, unsigned int, char const*, unsigned int);
    auto handleUnitInfoCommand(unsigned short, unsigned int, char const*, unsigned int);
    auto init(IOFireWireController*);
    auto installAVCCommandHandler(IOFireWireAVCProtocolUserClient*, void (*)(AVCCommandHandlerInfo const*, unsigned int, unsigned short, void const*, unsigned int, IOFWSpeed&, unsigned int), unsigned long long*, unsigned int, unsigned int, unsigned long long, unsigned long long);
    auto pcrModified(IOFWAVCPlugTypes, unsigned int, unsigned int);
    auto publishAVCUnitDirectory();
    auto setSubunitPlugSignalFormat(IOFireWireAVCProtocolUserClient*, unsigned int, IOFWAVCPlugTypes, unsigned int, unsigned int);
    auto subUnitOfTypeCount(unsigned int);
    auto targetSendAVCResponse(unsigned int, unsigned short, IOBufferMemoryDescriptor*, unsigned int);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~IOFireWireAVCTargetSpace();
};
