//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AtiBandwidthManager {
public: // (access info unavailable from symbols alone)
    auto setPerformanceWatermarks(unsigned char);
    auto setSafeWatermarks(unsigned char);
};
