//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleThunderboltIPTransmitCommand {
public: // (access info unavailable from symbols alone)
    AppleThunderboltIPTransmitCommand();
    AppleThunderboltIPTransmitCommand(OSMetaClass const*);
    BuildHeadersPacket(AppleThunderboltIPPacketHeaderAggregated*, unsigned int);
    BuildHeadersPacket(AppleThunderboltIPPacketHeaderAggregated*, unsigned int) (.cold.1);
    BuildHeadersPacket(AppleThunderboltIPPacketHeaderAggregated*, unsigned int)::_os_log_fmt;
    BuildPacket(unsigned int, unsigned short, unsigned short, unsigned int, __mbuf*, unsigned int);
    BuildPacket(unsigned int, unsigned short, unsigned short, unsigned int, __mbuf*, unsigned int)::_os_log_fmt;
    addMemoryDescriptorMultiple(IOMemoryDescriptor**, unsigned int, unsigned long long);
    copyDataFromMbuf(__mbuf*, unsigned long long);
    free();
    getMetaClass() const;
    initWithController(IOThunderboltController*, unsigned long long);
    initWithControllerAndQueue(IOThunderboltController*, IOThunderboltTransmitQueue*);
    initWithControllerAndQueue(IOThunderboltController*, IOThunderboltTransmitQueue*)::_os_log_fmt;
    initWithControllerAndQueueAllocateDesc(IOThunderboltController*, IOThunderboltTransmitQueue*, unsigned long long);
    initWithControllerAndQueueAllocateDesc(IOThunderboltController*, IOThunderboltTransmitQueue*, unsigned long long)::_os_log_fmt;
    withController(IOThunderboltController*, unsigned long long);
    withControllerAndQueue(IOThunderboltController*, IOThunderboltTransmitQueue*, bool, unsigned long long);
    ~AppleThunderboltIPTransmitCommand();
};
