//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSArray, NSData, NSObject, NSString;
@protocol OS_os_log;

@interface PS190FirmwareFile
{
    NSObject<OS_os_log> *_log;
    NSData *_personalizedBundleData;
    unsigned char _checksum;
    struct PS190RawAppFirmwareVersion _version;
    unsigned int _imemSize;
    unsigned int _dmemSize;
    NSData *_bundleData;
    NSArray *_blocks;
    const char *_img4Object;
    const char *_imemImage;
    const char *_dmemImage;
}

- (_Bool);
- (void);
- (_Bool);
- (void);
- (const char *);
- (unsigned int);
- (const char *);
- (id);
- (id);
- (id);
- (unsigned int);
- (const char *);
- (unsigned int);
- (void);
- (id);
- (struct PS190RawAppFirmwareVersion);
- (unsigned char);
- (id);
- (id);
- (id);
- (id);
- (void);

// Remaining properties
@property(readonly) NSArray *blocks; // @synthesize blocks=_blocks;
@property(readonly) NSData *bundleData; // @synthesize bundleData=_bundleData;
@property(readonly) unsigned char checksum; // @synthesize checksum=_checksum;
@property(readonly) const char *dmemImage; // @synthesize dmemImage=_dmemImage;
@property(readonly) unsigned int dmemSize; // @synthesize dmemSize=_dmemSize;
@property(readonly) NSString *dumpBlocksString;
@property(readonly) NSString *dumpString;
@property(readonly) const char *imemImage; // @synthesize imemImage=_imemImage;
@property(readonly) unsigned int imemSize; // @synthesize imemSize=_imemSize;
@property(readonly) const char *img4Object; // @synthesize img4Object=_img4Object;
@property(readonly) struct PS190RawAppFirmwareVersion version; // @synthesize version=_version;
@property(readonly) NSString *versionString;

@end

