//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC9App_Store19ShelfCollectionView.h"

@class MISSING_TYPE;

@interface _TtC9App_Store24CompLayoutCollectionView : _TtC9App_Store19ShelfCollectionView
{
    MISSING_TYPE *orthogonalPageGridProvider;
    MISSING_TYPE *compLayoutCollectionViewDelegate;
    MISSING_TYPE *scrollObserverTokensSectionMap;
}

- (void).cxx_destruct;
- (void)scrollToItemsAtIndexPaths:(id)arg1 scrollPosition:(unsigned long long)arg2;
- (void)layout;
- (void)viewWillStartLiveResize;
- (void)willRemoveSubview:(id)arg1;
- (void)addSubview:(id)arg1;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

