//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@interface _TtC9App_Store26CarouselOverlayChevronView
{
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)jet_traitCollectionDidChange:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

