//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class MISSING_TYPE;

@interface _TtC9App_StoreP33_15915090B807FB87A3CED81F0E4D28B310TextLayout
{
    MISSING_TYPE *textStack;
}

@end

