//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSCollectionViewDataSource-Protocol.h"

@class MISSING_TYPE;

@interface App_Store.UpdatesCollectionViewDataSource <NSCollectionViewDataSource>
{
    MISSING_TYPE *presenter;
}

- (void).cxx_destruct;
- (id)init;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 itemForRepresentedObjectAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;

@end

