//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleMultitouchEventDriverV2Wrapper {
public: // (access info unavailable from symbols alone)
    AppleMultitouchEventDriverV2Wrapper();
    AppleMultitouchEventDriverV2Wrapper(OSMetaClass const*);
    dispatchKeyboardEvent(unsigned long long, unsigned int, unsigned int, unsigned int, unsigned int);
    dispatchRelativePointerEvent(unsigned long long, int, int, unsigned int, unsigned int);
    dispatchScrollWheelEvent(unsigned long long, int, int, int, unsigned int);
    free();
    getMetaClass() const;
    init();
    setSystemProperties(OSDictionary*);
    withEventDriverV2(AppleMultitouchHIDEventDriverV2*);
    wrappedObject();
    ~AppleMultitouchEventDriverV2Wrapper();
};
