//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@interface (extension in AVFoundation):__C.AVAssetWriterInput.TaggedPixelBufferGroupReceiver
{
    id writer;
    id input;
    id taggedPixelBufferGroupAdaptor;
    id $__lazy_storage_$_mutablePixelBufferPool;
}

@end

