//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension CoreVideo.CVReadOnlyPixelBuffer {
    init(unsafeBuffer: __owned __C.CVBufferRef) -> CoreVideo.CVReadOnlyPixelBuffer
}
