//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleConvergedIPCBTIDevice {
public: // (access info unavailable from symbols alone)
    AppleConvergedIPCBTIDevice();
    AppleConvergedIPCBTIDevice(OSMetaClass const*);
    auto attach(IOService*);
    auto clearDMATransfer(IODMACommand**);
    auto createSetupDevice();
    auto createSetupInterface();
    auto createWithInfo();
    auto detach(IOService*);
    auto didTerminate(IOService*, unsigned int, bool*);
    auto errorCallback(void*, acipcErrorType, void*, void*);
    auto errorFunction(acipcErrorType, void*, void*);
    auto excludePatchFromMMIOCoredump();
    auto finishImageCommand(IODMACommand**);
    auto forceDoorbellFlush();
    auto free();
    auto getACIPCDevice() const;
    auto getDMATransferPhysicalAddress(IODMACommand*, unsigned long long*);
    auto getMapper() const;
    auto getMetaClass() const;
    auto initWithInfo();
    auto isMMIOCoreDumpAllowed();
    auto prepareDMATransfer(IOMemoryDescriptor*, IODMACommand**);
    auto prepareForMMIOCoredump();
    auto prepareImageCommand(IOMemoryDescriptor*, AppleConvergedIPCIODirection, IODMACommand**);
    auto resetAllowed();
    auto start(IOService*);
    auto start(IOService*) (.cold.1);
    auto start(IOService*) (.cold.2);
    auto stop(IOService*);
    auto stop(IOService*) (.cold.1);
    auto terminate(unsigned int);
    auto terminateInterface();
    auto willTerminate(IOService*, unsigned int);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~AppleConvergedIPCBTIDevice();
};
