//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class ASIC_INFO__BAFFIN {
public: // (access info unavailable from symbols alone)
    ASIC_INFO__BAFFIN();
    ASIC_INFO__BAFFIN(OSMetaClass const*);
    auto getMetaClass() const;
    auto populateDeviceInfo();
    auto populateFbLocation();
    auto populateMemoryConfig();
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~ASIC_INFO__BAFFIN();
};
