//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class ATIConnector {
public: // (access info unavailable from symbols alone)
    cacheHpdSenseState(bool);
    getActiveConnection(unsigned char);
    getActiveConnectionFor(unsigned char);
    getActiveDpcd();
    getActiveEdid(unsigned char);
    getAssignedDriverIndex(unsigned char);
    getAuxUtil();
    getCachedHpdSenseState();
    getConnectedConnectionFor(unsigned char);
    getConnectedConnectionNumber();
    getConnectedDpcd();
    getConnectionFlags();
    getConnectorId();
    getCurrentActiveInfoStructureForCrtc(unsigned char);
    getCurrentActiveInfoStructureForDev(unsigned char);
    getDigIndex();
    getDpServices(unsigned char);
    getHdcpProxy();
    getHotPlugId();
    getPanel();
    getSenseId();
    getTransmitterLink();
    getTransmitterNumber();
    hasConnections(unsigned int);
    hasFeatures(unsigned long long);
    initWithData(unsigned char, AuxChannelProxy*, ConnectorInfo const*, ATIController*);
    initializeConnections();
    isConnected(unsigned char);
    isOnline();
    linkTrainingFailed();
    populateGoldenSettings();
    resetCacheHpdSenseState();
};
