//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AtiGpuWrangler {
public: // (access info unavailable from symbols alone)
    AtiGpuWrangler(OSMetaClass const*);
    auto attach(IOService*);
    auto callPlatformFunction(OSSymbol const*, bool, void*, void*, void*, void*);
    auto detach(IOService*);
    auto probe(IOService*, int*);
    auto start(IOService*);
    auto stop(IOService*);
    auto vendor_doDeviceAttribute(unsigned int, unsigned long*, unsigned long, unsigned long*, unsigned long*, IOExternalMethodArguments*);
    ~AtiGpuWrangler();
};
