//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class BaffinSDmaTrapInterrupt {
public: // (access info unavailable from symbols alone)
    BaffinSDmaTrapInterrupt();
    BaffinSDmaTrapInterrupt(OSMetaClass const*);
    getMetaClass() const;
    handle(void*);
    initR6xx(unsigned char, bool, ATIController*);
    initR6xx(unsigned char, bool, ATIController*)::STR_NAME;
    initR6xx(unsigned char, bool, ATIController*)::table_size;
    ~BaffinSDmaTrapInterrupt();
};
