//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class BaffinInterruptFactory {
public: // (access info unavailable from symbols alone)
    auto createHwInterruptHelper(InterruptInfo const&, ATIController*);
    auto createInterrupt(InterruptInfo const&, ATIController*);
    auto createSwInterruptHelper(InterruptInfo const&, ATIController*);
};
