//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class BaffinVerticalSyncInterrupt {
public: // (access info unavailable from symbols alone)
    BaffinVerticalSyncInterrupt();
    BaffinVerticalSyncInterrupt(OSMetaClass const*);
    getAcknowledgeRegValue();
    getMetaClass() const;
    handle(void*);
    initR6xx(unsigned char, bool, ATIController*);
    initialize();
    ~BaffinVerticalSyncInterrupt();
};
