//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class BaffinThermalAlertInterrupt {
public: // (access info unavailable from symbols alone)
    BaffinThermalAlertInterrupt();
    BaffinThermalAlertInterrupt(OSMetaClass const*);
    auto getMetaClass() const;
    auto initR6xx(unsigned char, bool, ATIController*);
    auto initialize();
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~BaffinThermalAlertInterrupt();
};
