//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOThunderboltNHIReceiveRing {
public: // (access info unavailable from symbols alone)
    IOThunderboltNHIReceiveRing(OSMetaClass const*);
    _RESERVEDIOThunderboltNHIReceiveRing0();
    _RESERVEDIOThunderboltNHIReceiveRing1();
    _RESERVEDIOThunderboltNHIReceiveRing10();
    _RESERVEDIOThunderboltNHIReceiveRing11();
    _RESERVEDIOThunderboltNHIReceiveRing12();
    _RESERVEDIOThunderboltNHIReceiveRing13();
    _RESERVEDIOThunderboltNHIReceiveRing14();
    _RESERVEDIOThunderboltNHIReceiveRing15();
    _RESERVEDIOThunderboltNHIReceiveRing16();
    _RESERVEDIOThunderboltNHIReceiveRing17();
    _RESERVEDIOThunderboltNHIReceiveRing18();
    _RESERVEDIOThunderboltNHIReceiveRing19();
    _RESERVEDIOThunderboltNHIReceiveRing2();
    _RESERVEDIOThunderboltNHIReceiveRing20();
    _RESERVEDIOThunderboltNHIReceiveRing21();
    _RESERVEDIOThunderboltNHIReceiveRing22();
    _RESERVEDIOThunderboltNHIReceiveRing23();
    _RESERVEDIOThunderboltNHIReceiveRing24();
    _RESERVEDIOThunderboltNHIReceiveRing25();
    _RESERVEDIOThunderboltNHIReceiveRing26();
    _RESERVEDIOThunderboltNHIReceiveRing27();
    _RESERVEDIOThunderboltNHIReceiveRing28();
    _RESERVEDIOThunderboltNHIReceiveRing29();
    _RESERVEDIOThunderboltNHIReceiveRing3();
    _RESERVEDIOThunderboltNHIReceiveRing30();
    _RESERVEDIOThunderboltNHIReceiveRing31();
    _RESERVEDIOThunderboltNHIReceiveRing4();
    _RESERVEDIOThunderboltNHIReceiveRing5();
    _RESERVEDIOThunderboltNHIReceiveRing6();
    _RESERVEDIOThunderboltNHIReceiveRing7();
    _RESERVEDIOThunderboltNHIReceiveRing8();
    _RESERVEDIOThunderboltNHIReceiveRing9();
    completeCommand(IOThunderboltReceiveCommand*);
    copyDescriptorMemory();
    copyDeviceMemory();
    getOwner();
    requestMoreWork();
    setCommandStatus(IOThunderboltReceiveCommand*, int);
    setOwner(IOThunderboltReceiveQueue*);
    setReceivedLength(IOThunderboltReceiveCommand*, unsigned long long);
    ~IOThunderboltNHIReceiveRing();
};
