//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOThunderboltArray {
public: // (access info unavailable from symbols alone)
    auto withCapacity(unsigned int);
};
