//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOAccelChannel2 {
public: // (access info unavailable from symbols alone)
    IOAccelChannel2(OSMetaClass const*);
    _RESERVEDIOAccelChannel2();
    _RESERVEDIOAccelChannel3();
    _RESERVEDIOAccelChannel4();
    _RESERVEDIOAccelChannel5();
    free();
    getChannelLabel() const;
    getMetaClass() const;
    incrementStamp();
    init(IOGraphicsAccelerator2*, int);
    mergeEventExcluding(IOAccelEvent*, IOAccelEvent*);
    setEventStamp(IOAccelEvent*);
    setStampIndex(int);
    submitterDestroyed(IOAccelSubmitter2*);
    triage(char**, unsigned long long*);
    willSubmitCommands(unsigned long long);
    writeEventBarrierCommand(IOAccelEventQueue*, IOAccelEvent*, vendevtBarrierRec*);
    writeStampCommand(IOAccelEventQueue*, vendevtCommandRec*);
    ~IOAccelChannel2();
};
