//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOAccelTaskList {
public: // (access info unavailable from symbols alone)
    addTask(IOAccelTask*);
    getCount() const;
    init();
    removeTask(IOAccelTask*);
    removeTask(IOAccelTask*)::_os_log_fmt;
};
