//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOAccelSharedList {
public: // (access info unavailable from symbols alone)
    addShared(IOAccelShared2*);
    getCount() const;
    init();
    removeShared(IOAccelShared2*);
    removeShared(IOAccelShared2*)::_os_log_fmt;
};
