//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOAccelDisplayPipeGammaTable2 {
public: // (access info unavailable from symbols alone)
    IOAccelDisplayPipeGammaTable2();
    IOAccelDisplayPipeGammaTable2(OSMetaClass const*);
    free();
    getMetaClass() const;
    getTableCount() const;
    getTableEntry(unsigned int, float*, float*, float*) const;
    getTableMaxValue() const;
    getTableMinValue() const;
    init(IOAccelDisplayPipeGammaTableData*);
    init(IOAccelDisplayPipeGammaTableData*) (.cold.1);
    withGammaTableData(IOAccelDisplayPipeGammaTableData*);
    ~IOAccelDisplayPipeGammaTable2();
};
