//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOAccelDevice2 {
public: // (access info unavailable from symbols alone)
    IOAccelDevice2();
    IOAccelDevice2(OSMetaClass const*);
    _RESERVEDIOAccelDevice0();
    _RESERVEDIOAccelDevice1();
    _RESERVEDIOAccelDevice2();
    _RESERVEDIOAccelDevice3();
    _RESERVEDIOAccelDevice4();
    _RESERVEDIOAccelDevice5();
    add_orphaned_mappings(OSSet*);
    clientClose();
    detach_device();
    deviceStart();
    deviceStop();
    didTerminate(IOService*, unsigned int, bool*);
    externalMethod(unsigned int, IOExternalMethodArguments*, IOExternalMethodDispatch*, OSObject*, void*);
    free();
    getMetaClass() const;
    getTargetAndMethodForIndex(IOService**, unsigned int);
    get_config(IOAccelDeviceConfigData*);
    get_current_trace_filter(IOAccelDeviceTraceFilterData*);
    get_device_info(IOAccelDeviceInfoReturnData*);
    get_event_machine(IOAccelDeviceEventMachineData*);
    get_name(char*);
    get_next_gid_group(IOAccelDeviceGIDGroupData*);
    get_next_global_object_id(IOAccelDeviceGlobalObjectIDData*);
    get_surface_info(unsigned int, IOAccelDeviceSurfaceData*);
    get_surface_info(unsigned int, IOAccelDeviceSurfaceData*)::_os_log_fmt;
    init(OSDictionary*, task*);
    orphanClientMappings(OSSet*);
    requestTerminate(IOService*, unsigned int);
    set_api_property(IOAccelDeviceAPIProperty*);
    set_stereo(unsigned int, unsigned int);
    start(IOService*);
    stop(IOService*);
    stopLocked();
    ~IOAccelDevice2();
};
