//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOAccelLegacyDisplayMachine {
public: // (access info unavailable from symbols alone)
    IOAccelLegacyDisplayMachine(OSMetaClass const*);
    auto audit_freed_resource(IOAccelResource2*);
    auto destroyScanoutResource(unsigned int, unsigned int, IOFramebuffer*, IOAccelResource2*);
    auto disableFlipInterrupt(unsigned int);
    auto display_mode_did_change(unsigned int);
    auto display_mode_did_change(unsigned int) (.cold.1);
    auto display_mode_will_change(unsigned int);
    auto display_mode_will_change(unsigned int)::_os_log_fmt;
    auto enableFlipInterrupt(unsigned int);
    auto find_primary_display_pipe(IOAccelLegacyDisplayPipe*);
    auto found_framebuffer(IOFramebuffer*);
    auto found_framebuffer(IOFramebuffer*) (.cold.1);
    auto framebuffer_did_power_on(unsigned int);
    auto framebuffer_will_power_off(unsigned int);
    auto getDisplayResource(unsigned int, unsigned int) const;
    auto getFramebufferPixelBytes(unsigned int) const;
    auto getFramebufferStereoMode(unsigned int) const;
    auto getFullScreenSurface(unsigned int) const;
    auto getLegacyDisplayPipe(unsigned int) const;
    auto getMetaClass() const;
    auto getScanoutHeight(unsigned int) const;
    auto getScanoutResource(unsigned int, unsigned int) const;
    auto getScanoutSurface(unsigned int) const;
    auto getScanoutWidth(unsigned int) const;
    auto getWindowServerFullScreenAssemblySurface(unsigned int) const;
    auto initScanoutResource(unsigned int, unsigned int, IOFramebuffer*, IOAccelResource2*);
    auto isCurrentFramebufferModeAcceleratorBacked(unsigned int);
    auto isFramebufferHardwareMirrorOfFramebuffer(unsigned int, unsigned int);
    auto is_framebuffer_safe_for_exclusive(unsigned int) const;
    auto needsSecondaryFramebufferResources();
    auto resetFullScreen(IOAccelEvent*, unsigned int, IOAccelResource2*, IOAccelResource2*);
    auto resetScanout(IOAccelEvent*, unsigned int, IOAccelResource2*, IOAccelResource2*);
    auto reset_fullscreen(unsigned int, bool);
    auto reset_scanout(unsigned int);
    auto setStereo(unsigned int, IOAccelStereoMode);
    auto setupFullScreen(unsigned int, IOAccelResource2*, IOAccelResource2*);
    auto setupScanout(unsigned int, IOAccelResource2*, IOAccelResource2*);
    auto setup_fullscreen(IOAccelLegacySurface*);
    auto setup_scanout(IOAccelLegacySurface*);
    auto start(IOPCIDevice*);
    auto stop();
    auto submitFlipBuffer(IOAccelEvent*, unsigned int, unsigned int, IOAccelResource2*, IOAccelResource2*);
    auto submitScanoutFlipBuffer(IOAccelEvent*, unsigned int, unsigned int, IOAccelResource2*, IOAccelResource2*);
    auto submit_flip(IOAccelEvent*, unsigned int, unsigned int);
    auto submit_scanout_flip(IOAccelEvent*, unsigned int, unsigned int);
    auto surface_will_stop(IOAccelLegacySurface*);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~IOAccelLegacyDisplayMachine();
};
