//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOAccelOrphanedVidMemoryPool {
public: // (access info unavailable from symbols alone)
    freeWaitToPrepareMap(IOAccelMemoryMap*, bool);
    freeWaitToPrepareMemory(IOAccelMemory*, bool);
};
