//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AMDRadeonX5000_AMDRadeonHWLibsMIXED {
public: // (access info unavailable from symbols alone)
    AMDRadeonX5000_AMDRadeonHWLibsMIXED(OSMetaClass const*);
    callPlatformFunction(OSSymbol const*, bool, void*, void*, void*, void*);
    callPlatformFunction(char const*, bool, void*, void*, void*, void*);
    callPlatformFunction(char const*, bool, void*, void*, void*, void*)::CAIL_INTERFACE_KEY;
    callPlatformFunction(char const*, bool, void*, void*, void*, void*)::TTL_INTERFACE_KEY;
    createCailInterface(IOPCIDevice*);
    createTtlInterface(IOPCIDevice*);
    free();
    getMetaClass() const;
    start(IOService*);
    stop(IOService*);
    ~AMDRadeonX5000_AMDRadeonHWLibsMIXED();
};
