//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleThunderboltPCIDownAdapter {
public: // (access info unavailable from symbols alone)
    AppleThunderboltPCIDownAdapter();
    AppleThunderboltPCIDownAdapter(OSMetaClass const*);
    auto activate(AppleThunderboltPCIDownAdapter*);
    auto activateSetLegacyProperty();
    auto addActivationWaiter(AppleThunderboltPCIUpAdapter*);
    auto callActivationWaiters();
    auto createResources();
    auto deactivate();
    auto deactivateRemoveLegacyProperty();
    auto destroyResources();
    auto earlyWake();
    auto finalize(unsigned int);
    auto findPCIChildFromDeviceFunction(IOPCIDevice*, unsigned char, unsigned char);
    auto finishActivation();
    auto finishPCICorrelation();
    auto free();
    auto getMetaClass() const;
    auto getPCICapabilityOffset();
    auto init();
    auto isActivated();
    auto lateSleep();
    auto needsEarlyWake();
    auto pathIsEnabled(bool);
    auto removeActivationWaiter(AppleThunderboltPCIUpAdapter*);
    auto setPCICapabilityOffset(unsigned int);
    auto setThunderboltClient(AppleThunderboltPCIUpAdapter*);
    auto setupBootArgs();
    auto setupPCICorrelationFromPCIDevice(IOPCIDevice*);
    auto setupPCICorrelationPathFromAdapter(AppleThunderboltPCIDownAdapter*);
    auto setupRootPCICorrelationPath();
    auto shouldWaitForLinkActive();
    auto start(IOService*);
    auto upstreamPCIDeviceNotification(void*, IOService*, IONotifier*);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~AppleThunderboltPCIDownAdapter();
};
