//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class CACFNumber {
public: // (access info unavailable from symbols alone)
    auto GetFixed32() const;
    auto GetFixed64() const;
    auto PrintToLog(__CFNumber const*, unsigned int);
    ~CACFNumber();
};
