//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class XPC_Dictionary {
public: // (access info unavailable from symbols alone)
    GetArray(char const*, XPC_Array&) const;
    GetDictionary(char const*, XPC_Dictionary&) const;
    ~XPC_Dictionary();
};
