//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOAVBAVTPL2ReceiveQueueIdentifier {
public: // (access info unavailable from symbols alone)
    IOAVBAVTPL2ReceiveQueueIdentifier();
    IOAVBAVTPL2ReceiveQueueIdentifier(OSMetaClass const*);
    canDecodePacket(IOEthernetController::IOEthernetAVBPacket const*);
    getMetaClass() const;
    streamIdentifierForPacket(IOEthernetController::IOEthernetAVBPacket const*);
    ~IOAVBAVTPL2ReceiveQueueIdentifier();
};
