//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@interface (null) (NSMutableDataObjcTypeSerialization)
+ (id);
+ (id);
+ (id);
+ (id);
- (void);
- (void);
- (void);
- (void);
- (void);
- (void);
- (void);
- (_Bool);
- (_Bool);
- (_Bool);
- (_Bool);
- (void);
- (void);
- (void);
- (Class);
- (void);
- (id);
- (void);
- (void *);
- (void)utputFormatting;
- (id)Âõ(\Âõ(\Âõ(\V-²ï§ÆK7A;
- (void);
- (_Bool)E;
- (void);
@end

