//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@interface (null) (NSPort)
+ (id);
+ (id)rn;
+ (id)ÿW4õÜ9;
- (_Bool);
- (_Bool);
- (void);
- (id);
- (Class);
- (void);
- (unsigned long long);
- (void);
- (_Bool);
- (id);
- (id);
- (Class);
- (void);
- (id);
- (id)¸;
- (unsigned int)class name for class;
- (void)b@0@@ "  ;
- (id)ÒÒÓÔÕÖÖÖÖÖÖÖ×ØÙÚÛÜÜÜÝÝÞßàáááâããäååæææççèèèèèééêëëììííîîïïððððððððñòóôôõö÷øøùúúúûüüýýýýþþÿ;
- (void):(id)arg1;
- (void)µ¥;
@end

