//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

__attribute__((visibility("hidden")))
@interface _NSCallStackArray
{
    void **_frames;
    unsigned long long _cnt;
    unsigned long long _ignore;
    char **_pcstrs;
    _Bool _wantSyms;
}

- (unsigned long long);
- (id);
- (id);
- (id);
- (void);
- (unsigned long long);

@end

