//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

__attribute__((visibility("hidden")))
@interface _NSInlineData
{
    unsigned short _length;
}

- (id);
- (id);
- (id);
- (id);
- (unsigned long long);
- (const void *)wrap;
- (_Bool)ÿ;
- (_Bool);

@end

