//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSArray, NSString;

@interface NSMetadataQueryResultGroup
{
    id _private[9];
    unsigned long long _private2[1];
    void *_reserved;
}

- (id);
- (id);
- (id);
- (void);
- (void);
- (id);
- (id);
- (void);
- (unsigned long long);
- (id)­­­®®¯¯¯¯¯°±±±±²²³´µ¶·····¸¹¹¹¹¹¹¹¹¹ººº»¼½½½¾¾¿¿¿ÀÀÁÂÂÃÄÅÅÆÆÆÇÇÈÈÈÉÉÊÊÊÊËËÌÌÍÍÎÏÏÐÐÐÐÑÒÒÒÓÓÓÔÔÔÔÕÕÖÖ××ØØØÙÚÚÛÛÜÝÞÞßßààáâãäääääååååææææçèééêëëëìììììíîîïððñòóóóôôôôõõõõõöö÷÷÷øøùùùùùùúûüüýþÿ;

// Remaining properties
@property(readonly, copy) NSString *attribute;
@property(readonly) unsigned long long resultCount;
@property(readonly, copy) NSArray *results;
@property(readonly, copy) NSArray *subgroups;
@property(readonly, retain) id value;

@end

