//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

__attribute__((visibility("hidden")))
@interface NSMutableStringProxy
{
}

- (void);
- (void);
- (void);
- (_Bool);
- (void)ring"40;
- (void)@36;

@end

