//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleHPMIECS {
public: // (access info unavailable from symbols alone)
    AppleHPMIECS();
    AppleHPMIECS(OSMetaClass const*);
    finalize(unsigned int);
    free();
    getMetaClass() const;
    hpmIECSRead(unsigned long long, unsigned int, IOMemoryDescriptor*, unsigned long long*, unsigned int);
    hpmIECSWrite(unsigned long long, unsigned int, IOMemoryDescriptor*, unsigned long long, unsigned int);
    poweredStart();
    publishHPMDevices();
    setInUse(bool);
    setRouteString(unsigned long long);
    start(IOService*);
    ~AppleHPMIECS();
};
