//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleIntelHDCP {
public: // (access info unavailable from symbols alone)
    AppleIntelHDCP(OSMetaClass const*);
    getMetaClass() const;
    getRxHDCPVersion(AppleIntelDisplayPath*);
    ~AppleIntelHDCP();
};
