//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class std::__1::unordered_map<unsigned long, std::__1::variant<HVF::Shape, HVF::Composite>, std::__1::hash<unsigned long>, std::__1::equal_to<unsigned long>, std::__1::allocator<std::__1::pair<unsigned long const, std::__1::variant<HVF::Shape, HVF::Composite>>>> {
public: // (access info unavailable from symbols alone)
    unordered_map(std::__1::unordered_map<unsigned long, std::__1::variant<HVF::Shape, HVF::Composite>, std::__1::hash<unsigned long>, std::__1::equal_to<unsigned long>, std::__1::allocator<std::__1::pair<unsigned long const, std::__1::variant<HVF::Shape, HVF::Composite>>>> const&);
};
