//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleBCMWLANJoinAdapter {
public: // (access info unavailable from symbols alone)
    abortFirmwareJoinSync(bool);
    addInstantHSAppleDeviceIE(bool, unsigned char);
    adjustMfp(apple80211AssocCandidates*, unsigned int&);
    clearWepKeysSync();
    collectImmediateFaultDataCallback(CCFaultReport*);
    completeFaultReportCallback(CCFaultReport const*);
    configure6GDefaultUnAssocDwell();
    configureSupplicantTimeOut(unsigned int);
    copyJoinTimeoutBlob(unsigned char*, unsigned long);
    createAdhocNetwork(apple80211_network_data*);
    custom6GUnAssocDwell(unsigned int);
    customUnAssocDwell(unsigned int);
    disableICVErrorEventsAsync();
    enableICVErrorEvents();
    enableMrsno(bool);
    enableSupplicantEvents();
    free();
    free()::kalloc_type_view_117;
    freeResources();
    getAssocRSNXE(unsigned char*, unsigned long long&) const;
    getAssociatedRSNXE();
    getAssociatedRSNXEAsyncCallback(CommandID&, int, CommandRxPayload&, void*);
    getBSSInfoAsync();
    getBSSInfoAsyncCallback(CommandID&, int, CommandRxPayload&, void*);
    getMetaClass() const;
    handleAssoc(wl_event_msg_t*);
    handleAssoc(wl_event_msg_t*)::_os_log_fmt;
    handleAuth(wl_event_msg_t*);
    handleAuth(wl_event_msg_t*)::_os_log_fmt;
    handleBeaconProtectionAsyncCallBack(CommandID&, int, CommandRxPayload&, void*);
    handleCustom6GUnAssocDwellAsyncCallBack(CommandID&, int, CommandRxPayload&, void*);
    handleCustomUnAssocDwellAsyncCallBack(CommandID&, int, CommandRxPayload&, void*);
    handleICVErrorEvent(wl_event_msg_t*);
    handleSetSSID(wl_event_msg_t*);
    handleSetSSID(wl_event_msg_t*)::_os_log_fmt;
    handleSupplicantEvent(wl_event_msg_t*);
    handleSupplicantEvent(wl_event_msg_t*)::_os_log_fmt;
    handleSupplicantTimeoutConfigAsyncCallBack(CommandID&, int, CommandRxPayload&, void*);
    induceFaultCallback(int, char const*);
    initWithDriver(AppleBCMWLANCore*, int (*)(OSObject*, JoinFirmwareEvent, void*), OSObject*);
    initWithDriver(AppleBCMWLANCore*, int (*)(OSObject*, JoinFirmwareEvent, void*), OSObject*)::kalloc_type_view_1117;
    performJoin(apple80211AssocCandidates*);
    prepareFRCallback(CCFaultReport const*);
    programKeyAsync(wl_wsec_key&);
    programKeyAsyncCallback(CommandID&, int, CommandRxPayload&, void*);
    programKeySync(wl_wsec_key&);
    programPMK(wsec_pmk&);
    sendConnectComplete();
    setAssocBip(unsigned int);
    setAssocRSNIE(unsigned char const*, unsigned long long);
    setAssocRSNIEAsyncCallback(CommandID&, int, CommandRxPayload&, void*);
    setAssocRSNXE(unsigned char const*, unsigned long long);
    setAssocWsecInfo(unsigned short, unsigned int, bool, unsigned int, bool);
    setBeaconProtectionParams(char const*, unsigned short, void*, unsigned short, int);
    setCustomAssocIE(unsigned char*, unsigned long long);
    setCustomAssocIEAsyncCallback(CommandID&, int, CommandRxPayload&, void*);
    setKey(apple80211_key*, bool, unsigned char*, unsigned short);
    setWsecInfoCallback(CommandID&, int, CommandRxPayload&, void*);
    triggerCC(triggerCC*);
    triggerCC(triggerCC*)::_os_log_fmt;
    withDriver(AppleBCMWLANCore*, int (*)(OSObject*, JoinFirmwareEvent, void*), OSObject*);
    ~AppleBCMWLANJoinAdapter();
};
