//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleBCMWLANByteRing {
public: // (access info unavailable from symbols alone)
    AppleBCMWLANByteRing(OSMetaClass const*);
    auto free();
    auto free()::kalloc_type_view_65;
    auto getLogger() const;
    auto getMetaClass() const;
    auto initWithOwnerAndAction(OSObject*, void (*)(OSObject*, ...));
    auto initWithOwnerAndAction(OSObject*, void (*)(OSObject*, ...))::kalloc_type_view_38;
    auto setLogger(CCLogStream*);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~AppleBCMWLANByteRing();
};
