//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleBCMWLANApFeatureConfig {
public: // (access info unavailable from symbols alone)
    free();
    free()::kalloc_type_view_72;
    getMetaClass() const;
    handleLimitedAggregation();
    initWithDriver(AppleBCMWLANCore*)::kalloc_type_view_83;
    sendBeaconMitigationParams(apple80211_bcn_mute_config&);
    ~AppleBCMWLANApFeatureConfig();
};
