//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleBCMWLANBssManager {
public: // (access info unavailable from symbols alone)
    free();
    free()::kalloc_type_view_75;
    getMetaClass() const;
    initWithDriver(AppleBCMWLANCore*)::kalloc_type_view_84;
    setCurrentBSS(AppleBCMWLANBSSBeacon*);
    setCurrentBSS(AppleBCMWLANBSSBeacon*)::logCC;
    withOptions(AppleBCMWLANCore*);
    ~AppleBCMWLANBssManager();
};
