//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleBCMWLANBSSBeacon {
public: // (access info unavailable from symbols alone)
    fromWLBSSInfo(wl_bss_info*, AppleChannelSpec_t, unsigned long long, CCLogStream*, CommonFaultReporter*);
    getBeaconMsgFromWLBSSInfo(BeaconMetaData&, unsigned char*, wl_bss_info*, AppleChannelSpec_t, unsigned long long);
    getBeaconMsgFromWLBSSInfo(BeaconMetaData&, unsigned char*, wl_bss_info*, AppleChannelSpec_t, unsigned long long)::_os_log_fmt;
    getMetaClass() const;
    setBeaconData(wl_bss_info*, AppleChannelSpec_t, unsigned long long)::_os_log_fmt;
    ~AppleBCMWLANBSSBeacon();
};
