//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleBCMWLANItemRing {
public: // (access info unavailable from symbols alone)
    AppleBCMWLANItemRing(OSMetaClass const*);
    auto CallErrorAction(int, void*);
    auto free();
    auto free()::kalloc_type_view_70;
    auto getIndices(unsigned int*, unsigned int*);
    auto getItemCount() const;
    auto getItemSize() const;
    auto getMMIORecorder();
    auto getMetaClass() const;
    auto getReadOffset();
    auto getReadableByteCount();
    auto getReadableItemCount();
    auto getReadableItemCount(unsigned int, unsigned int);
    auto getReadableItemCountContinuous(unsigned int, unsigned int);
    auto getWritableByteCount();
    auto getWritableItemCount();
    auto getWritableItemCount(unsigned int, unsigned int);
    auto getWritableItemCountContinuous(unsigned int, unsigned int);
    auto getWriteOffset();
    auto hexDumpRing();
    auto initWithOwnerAndActions(OSObject*, void (*)(OSObject*, ...), void (*)(OSObject*, AppleBCMWLANByteRing*, int, void*));
    auto initWithOwnerAndActions(OSObject*, void (*)(OSObject*, ...), void (*)(OSObject*, AppleBCMWLANByteRing*, int, void*))::kalloc_type_view_48;
    auto logRing(char const*, unsigned int);
    auto setItemCount(unsigned int);
    auto setItemSize(unsigned int);
    auto setMMIORecorder(AppleBCMWLANPCIeMMIOHistory*);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~AppleBCMWLANItemRing();
};
