//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleBCMWLANBonjourOffload {
public: // (access info unavailable from symbols alone)
    free();
    free()::kalloc_type_view_193;
    freeResources();
    getMetaClass() const;
    initWithDriver(AppleBCMWLANCore*)::kalloc_type_view_124;
    initWithDriver(AppleBCMWLANCore*)::kalloc_type_view_181;
    mDNSOffloadAddSymList(dnsSymList**, unsigned char*, unsigned char*);
    mDNSOffloadAddSymList(dnsSymList**, unsigned char*, unsigned char*)::kalloc_type_view_1696;
    mDNSOffloadConfigureKeepAlives();
    mDNSOffloadDnsCopyString(unsigned char**, unsigned char*, unsigned char**, unsigned char*, dnsSymList*);
    mDNSOffloadDnsMatch(unsigned char*, unsigned char*, unsigned char*, unsigned char*);
    mDNSOffloadDownloadConfig();
    mDNSOffloadEnable(bool);
    mDNSOffloadEnableAsyncCallBack(CommandID&, int, CommandRxPayload&, void*);
    mDNSOffloadFlatAppend(void*, unsigned int);
    mDNSOffloadFlatRRAppend(void*, dnsSymList**, unsigned char*);
    mDNSOffloadFlatSubtypesAppend(void*, dnsSymList**, unsigned char*);
    mDNSOffloadFlattenGetNonEmptyRRTxtCount();
    mDNSOffloadFlattenGetRRCount(int);
    mDNSOffloadFreeSymList(dnsSymList**)::kalloc_type_view_1718;
    mDNSOffloadGetKeepAlivePorts();
    mDNSOffloadGetNicProxyLimits(nicproxy_limits_info_s&);
    mDNSOffloadHasActivePorts(unsigned int&, unsigned int*, unsigned int*, unsigned int*, unsigned int*);
    mDNSOffloadHwConfigNicProxyData(nicproxy_info_s*);
    mDNSOffloadPublishOffloadCapability(AppleBCMWLANCore*, bool);
    mDNSOffloadReleaseHandoff();
    withDriver(AppleBCMWLANCore*);
    ~AppleBCMWLANBonjourOffload();
};
