//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class OSMetaClass {
public: // (access info unavailable from symbols alone)
    OSMetaClass(char const*, OSMetaClass const*, unsigned int);
    auto _RESERVEDOSMetaClass0();
    auto _RESERVEDOSMetaClass1();
    auto _RESERVEDOSMetaClass2();
    auto _RESERVEDOSMetaClass3();
    auto _RESERVEDOSMetaClass4();
    auto _RESERVEDOSMetaClass5();
    auto _RESERVEDOSMetaClass6();
    auto _RESERVEDOSMetaClass7();
    auto allocClassWithName(char const*);
    auto getMetaClass() const;
    auto getRetainCount() const;
    auto instanceConstructed() const;
    auto release() const;
    auto release(int) const;
    auto retain() const;
    auto serialize(OSSerialize*) const;
    auto taggedRelease(void const*) const;
    auto taggedRelease(void const*, int) const;
    auto taggedRetain(void const*) const;
    ~OSMetaClass();
};
