//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IORTC {
public: // (access info unavailable from symbols alone)
    IORTC(OSMetaClass const*);
    _RESERVEDIORTC0();
    _RESERVEDIORTC1();
    _RESERVEDIORTC2();
    _RESERVEDIORTC3();
    _RESERVEDIORTC4();
    _RESERVEDIORTC5();
    _RESERVEDIORTC6();
    _RESERVEDIORTC7();
    getMonotonicClockAndTimestamp(unsigned long long*, unsigned long long*);
    getMonotonicClockOffset(long long*);
    setMonotonicClockOffset(long long);
    ~IORTC();
};
