//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@interface (null) (Integer)
+ (id);
+ (id);
+ (id);
+ (id);
+ (id);
+ (id);
+ (id);
+ (id);
- (unsigned long long);
- (unsigned int);
- (unsigned int);
- (unsigned short);
- (id);
- (int);
- (int);
- (unsigned long long);
- (_Bool);
- (id);
- (id);
- (id);
- (id);
- (id);
- (unsigned char);
- (_Bool);
- (_Bool);
- (long long);
@end

