//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class MISSING_TYPE;

@interface AppletTranslationLibrary.ExpressMode
{
    MISSING_TYPE *modulesRequiringSlowPath;
    MISSING_TYPE *reservedTCIs;
    MISSING_TYPE *internalBuild;
    MISSING_TYPE *userDefaults;
}

+ (_Bool);
+ (id);
+ (id);
+ (_Bool);
+ (_Bool);
- (void);
- (id);

@end

