//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface CalypsoReaderContext
{
    NSMutableDictionary *_files;
}

+ (id);
+ (id);
+ (id);
- (id);
- (void);
- (id)B;
- (void);
- (void);

// Remaining properties
@property(retain, nonatomic) NSMutableDictionary *files; // @synthesize files=_files;

@end

