//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSData, NSMutableArray, NSNumber;

__attribute__((visibility("hidden")))
@interface DreamworksReaderContext
{
    NSData *_filePurseInfo;
    NSMutableArray *_filePurse;
    NSMutableArray *_fileTrans;
    NSNumber *_balance;
    NSNumber *_filePurseMaxRecCount;
}

+ (id);
- (void);
- (void);
- (void);
- (void);
- (id);
- (id);
- (id);
- (id);
- (id);
- (id);
- (id);
- (id);
- (void);
- (id);
- (void);
- (void);

// Remaining properties
@property(retain, nonatomic) NSNumber *balance; // @synthesize balance=_balance;
@property(retain, nonatomic) NSMutableArray *filePurse; // @synthesize filePurse=_filePurse;
@property(retain, nonatomic) NSData *filePurseInfo; // @synthesize filePurseInfo=_filePurseInfo;
@property(retain, nonatomic) NSNumber *filePurseMaxRecCount; // @synthesize filePurseMaxRecCount=_filePurseMaxRecCount;
@property(retain, nonatomic) NSMutableArray *fileTrans; // @synthesize fileTrans=_fileTrans;

@end

