//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IODataQueue {
public: // (access info unavailable from symbols alone)
    IODataQueue(OSMetaClass const*);
    auto enqueue(void*, unsigned int);
    auto sendDataAvailableNotification();
    auto setNotificationPort(ipc_port*);
    ~IODataQueue();
};
