//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class SLAM::TransceiverWrapper {
public: // (access info unavailable from symbols alone)
    Transceive(std::__1::vector<unsigned char, std::__1::allocator<unsigned char>> const&);
    TransceiveAndCheckSW(std::__1::vector<unsigned char, std::__1::allocator<unsigned char>> const&);
    ~TransceiverWrapper();
};
