//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension CoreMedia.CMAttachmentBearerAttachments.Mode {
    init(rawValue: Swift.UInt32) -> Swift.Optional<CoreMedia.CMAttachmentBearerAttachments.Mode>
}
