//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension CoreMedia.CMTaggedDynamicBuffer.tags {
    getter : Swift.Array<CoreMedia.CMTag>
    modify : Swift.Array<CoreMedia.CMTag>
    modify : Swift.Array<CoreMedia.CMTag> with unmangled suffix ".resume.0"
    setter : Swift.Array<CoreMedia.CMTag>
}
