//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension CoreMedia.CMMutableDataBlockBuffer.copyBytes<A where A: Swift.RangeExpression, A.Bound == Swift {
    Int>(to: Swift.UnsafeMutableRawBufferPointer, from: A) -> ()
}
