//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleUSBUserHCIRequest {
public: // (access info unavailable from symbols alone)
    AppleUSBUserHCIRequest();
    AppleUSBUserHCIRequest(OSMetaClass const*);
    auto cancel();
    auto cancel() (.cold.1);
    auto complete();
    auto complete() (.cold.1);
    auto finish(int);
    auto free();
    auto getBuffer() const;
    auto getDeadline();
    auto getFirstTransferStruct();
    auto getLastTransferStruct();
    auto getMetaClass() const;
    auto getNextTransferPointer() const;
    auto getStartFrame();
    auto hasTimedOut();
    auto initWithControllerAndPool(AppleUSBUserHCI*, AppleUSBRequestPool*);
    auto link(AppleUSBUserHCIRequest*);
    auto link(AppleUSBUserHCIRequest*) (.cold.1);
    auto link(AppleUSBUserHCIRequest*)::_os_log_fmt;
    auto prepare(AppleUSBHostRequest*);
    auto prepare(AppleUSBHostRequest*) (.cold.1);
    auto prepare(AppleUSBHostRequest*) (.cold.2);
    auto prepare(AppleUSBHostRequest*)::_os_log_fmt;
    auto setStartFrame(unsigned long long);
    auto update(IOUSBHostCIMessage const*);
    auto update(IOUSBHostCIMessage const*)::_os_log_fmt;
    auto withControllerAndPool(AppleUSBUserHCI*, AppleUSBRequestPool*);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~AppleUSBUserHCIRequest();
};
