//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

// Top-level Swift declarations

(extension in Foundation):Swift.Array._bridgeToObjectiveC() -> __C.NSArray
(extension in WatchKit):__C.WKInterfaceController.presentController(Swift.Array<(name: Swift.String, context: Swift.AnyObject)>) -> ()
(extension in WatchKit):__C.WKInterfaceController.presentController(withNamesAndContexts: Swift.Array<(name: Swift.String, context: Swift.AnyObject)>) -> ()
(extension in WatchKit):__C.WKInterfaceController.reloadRootControllers(Swift.Array<(name: Swift.String, context: Swift.AnyObject)>) -> ()
(extension in WatchKit):__C.WKInterfaceController.reloadRootControllers(withNamesAndContexts: Swift.Array<(name: Swift.String, context: Swift.AnyObject)>) -> ()
demangling cache variable for type metadata for Swift._ContiguousArrayStorage<Any>
demangling cache variable for type metadata for Swift._ContiguousArrayStorage<Swift.String>
function signature specialization <Arg[1] = Dead> of static (extension in WatchKit):__C.WKInterfaceController.reloadRootControllers(withNamesAndContexts: Swift.Array<(name: Swift.String, context: Swift.AnyObject)>) -> ()
generic specialization <Any> of Swift.ContiguousArray._createNewBuffer(bufferIsUnique: Swift.Bool, minimumCapacity: Swift.Int, growForAppend: Swift.Bool) -> ()
generic specialization <Any> of Swift._ContiguousArrayBuffer._consumeAndCreateNew(bufferIsUnique: Swift.Bool, minimumCapacity: Swift.Int, growForAppend: Swift.Bool) -> Swift._ContiguousArrayBuffer<A>
generic specialization <Swift.String> of Swift.ContiguousArray._createNewBuffer(bufferIsUnique: Swift.Bool, minimumCapacity: Swift.Int, growForAppend: Swift.Bool) -> ()
generic specialization <Swift.String> of Swift._ContiguousArrayBuffer._consumeAndCreateNew(bufferIsUnique: Swift.Bool, minimumCapacity: Swift.Int, growForAppend: Swift.Bool) -> Swift._ContiguousArrayBuffer<A>
mangled name ref for type metadata for Swift._ContiguousArrayStorage<Any>
mangled name ref for type metadata for Swift._ContiguousArrayStorage<Swift.String>
nominal type descriptor for Swift._ContiguousArrayStorage
outlined init with take of Any
type metadata for Any
type metadata for Swift.String
