//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOAppleLabelScheme {
public: // (access info unavailable from symbols alone)
    IOAppleLabelScheme();
    IOAppleLabelScheme(OSMetaClass const*);
    auto _RESERVEDIOAppleLabelScheme0();
    auto _RESERVEDIOAppleLabelScheme1();
    auto _RESERVEDIOAppleLabelScheme10();
    auto _RESERVEDIOAppleLabelScheme11();
    auto _RESERVEDIOAppleLabelScheme12();
    auto _RESERVEDIOAppleLabelScheme13();
    auto _RESERVEDIOAppleLabelScheme14();
    auto _RESERVEDIOAppleLabelScheme15();
    auto _RESERVEDIOAppleLabelScheme2();
    auto _RESERVEDIOAppleLabelScheme3();
    auto _RESERVEDIOAppleLabelScheme4();
    auto _RESERVEDIOAppleLabelScheme5();
    auto _RESERVEDIOAppleLabelScheme6();
    auto _RESERVEDIOAppleLabelScheme7();
    auto _RESERVEDIOAppleLabelScheme8();
    auto _RESERVEDIOAppleLabelScheme9();
    auto attachMediaObjectToDeviceTree(IOMedia*);
    auto detachMediaObjectFromDeviceTree(IOMedia*);
    auto free();
    auto getMetaClass() const;
    auto init(OSDictionary*);
    auto instantiateDesiredMediaObject(OSDictionary*);
    auto instantiateMediaObject(OSDictionary*);
    auto isContentCorrupt(OSDictionary*);
    auto isContentInvalid(OSDictionary*);
    auto probe(IOService*, int*);
    auto scan(int*);
    auto start(IOService*);
    auto stop(IOService*);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~IOAppleLabelScheme();
};
