//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOSubMemoryDescriptor {
public: // (access info unavailable from symbols alone)
    IOSubMemoryDescriptor(OSMetaClass const*);
    auto complete(unsigned int);
    auto getPhysicalSegment(unsigned long long, unsigned long long*, unsigned int);
    auto getPreparationID();
    auto initSubRange(IOMemoryDescriptor*, unsigned long long, unsigned long long, unsigned int);
    auto makeMapping(IOMemoryDescriptor*, task*, unsigned long long, unsigned int, unsigned long long, unsigned long long);
    auto prepare(unsigned int);
    auto redirect(task*, bool);
    auto setPurgeable(unsigned int, unsigned int*);
    auto withSubRange(IOMemoryDescriptor*, unsigned long long, unsigned long long, unsigned int);
    ~IOSubMemoryDescriptor();
};
