//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppleTconUARPUpdater/UARPMetaData.h>

@class NSString;

@interface UARPMetaDataPersonalizationFTABSubfileDigestFilename : UARPMetaData
{
    NSString *_filename;
}

- (id);
- (id);
- (id);
- (id);
- (id);
- (id);
- (void);

// Remaining properties
@property(readonly) NSString *filename; // @synthesize filename=_filename;

@end

