//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

// Top-level Swift declarations

(extension in CoreMediaIO):__C.CMIOExtensionDeviceProperties.suspended.getter : Swift.Optional<Swift.Bool>
(extension in CoreMediaIO):__C.CMIOExtensionDeviceProperties.suspended.modify : Swift.Optional<Swift.Bool>
(extension in CoreMediaIO):__C.CMIOExtensionDeviceProperties.suspended.modify : Swift.Optional<Swift.Bool> with unmangled suffix ".resume.0"
(extension in CoreMediaIO):__C.CMIOExtensionDeviceProperties.suspended.setter : Swift.Optional<Swift.Bool>
(extension in CoreMediaIO):__C.CMIOExtensionDeviceProperties.transportType.getter : Swift.Optional<Swift.Int>
(extension in CoreMediaIO):__C.CMIOExtensionDeviceProperties.transportType.modify : Swift.Optional<Swift.Int>
(extension in CoreMediaIO):__C.CMIOExtensionDeviceProperties.transportType.modify : Swift.Optional<Swift.Int> with unmangled suffix ".resume.0"
(extension in CoreMediaIO):__C.CMIOExtensionDeviceProperties.transportType.setter : Swift.Optional<Swift.Int>
(extension in CoreMediaIO):__C.CMIOExtensionStreamFormat.init(formatDescription: __C.CMFormatDescriptionRef, maxFrameDuration: __C.CMTime, minFrameDuration: __C.CMTime, validFrameDurations: Swift.Optional<Swift.Array<__C.CMTime>>) -> __C.CMIOExtensionStreamFormat
(extension in CoreMediaIO):__C.CMIOExtensionStreamFormat.validFrameDurations.getter : Swift.Optional<Swift.Array<__C.CMTime>>
(extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.activeFormatIndex.getter : Swift.Optional<Swift.Int>
(extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.activeFormatIndex.modify : Swift.Optional<Swift.Int>
(extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.activeFormatIndex.modify : Swift.Optional<Swift.Int> with unmangled suffix ".resume.0"
(extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.activeFormatIndex.modify : Swift.Optional<Swift.Int> with unmangled suffix ".resume.0Tm"
(extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.activeFormatIndex.setter : Swift.Optional<Swift.Int>
(extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.frameDuration.getter : Swift.Optional<__C.CMTime>
(extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.frameDuration.modify : Swift.Optional<__C.CMTime>
(extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.frameDuration.modify : Swift.Optional<__C.CMTime> with unmangled suffix ".resume.0"
(extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.frameDuration.modify : Swift.Optional<__C.CMTime> with unmangled suffix ".resume.0Tm"
(extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.frameDuration.setter : Swift.Optional<__C.CMTime>
(extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.maxFrameDuration.getter : Swift.Optional<__C.CMTime>
(extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.maxFrameDuration.modify : Swift.Optional<__C.CMTime>
(extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.maxFrameDuration.modify : Swift.Optional<__C.CMTime> with unmangled suffix ".resume.0"
(extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.maxFrameDuration.setter : Swift.Optional<__C.CMTime>
(extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.sinkBufferQueueSize.getter : Swift.Optional<Swift.Int>
(extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.sinkBufferQueueSize.modify : Swift.Optional<Swift.Int>
(extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.sinkBufferQueueSize.modify : Swift.Optional<Swift.Int> with unmangled suffix ".resume.0"
(extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.sinkBufferQueueSize.setter : Swift.Optional<Swift.Int>
(extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.sinkBufferUnderrunCount.getter : Swift.Optional<Swift.Int>
(extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.sinkBufferUnderrunCount.modify : Swift.Optional<Swift.Int>
(extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.sinkBufferUnderrunCount.modify : Swift.Optional<Swift.Int> with unmangled suffix ".resume.0"
(extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.sinkBufferUnderrunCount.setter : Swift.Optional<Swift.Int>
(extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.sinkBuffersRequiredForStartup.getter : Swift.Optional<Swift.Int>
(extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.sinkBuffersRequiredForStartup.modify : Swift.Optional<Swift.Int>
(extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.sinkBuffersRequiredForStartup.modify : Swift.Optional<Swift.Int> with unmangled suffix ".resume.0"
(extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.sinkBuffersRequiredForStartup.setter : Swift.Optional<Swift.Int>
(extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.sinkEndOfData.getter : Swift.Optional<Swift.Int>
(extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.sinkEndOfData.modify : Swift.Optional<Swift.Int>
(extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.sinkEndOfData.modify : Swift.Optional<Swift.Int> with unmangled suffix ".resume.0"
(extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.sinkEndOfData.setter : Swift.Optional<Swift.Int>
(extension in Foundation):Swift.Array._bridgeToObjectiveC() -> __C.NSArray
(extension in Foundation):Swift.Array._unconditionallyBridgeFromObjectiveC(Swift.Optional<__C.NSArray>) -> Swift.Array<A>
(extension in Foundation):Swift.Dictionary._bridgeToObjectiveC() -> __C.NSDictionary
(extension in Foundation):Swift.Dictionary._forceBridgeFromObjectiveC(_: __C.NSDictionary, result: inout Swift.Optional<Swift.Dictionary<A, B>>) -> ()
(extension in Foundation):Swift.Dictionary._unconditionallyBridgeFromObjectiveC(Swift.Optional<__C.NSDictionary>) -> Swift.Dictionary<A, B>
demangling cache variable for type metadata for Swift.Dictionary<Swift.AnyHashable, Any>
demangling cache variable for type metadata for Swift._ContiguousArrayStorage<Swift.Dictionary<Swift.AnyHashable, Any>>
demangling cache variable for type metadata for Swift._ContiguousArrayStorage<__C.CMTime>
full type metadata for __C.CMTime
full type metadata for __C.CMTimeFlags
generic specialization <Swift.Dictionary<Swift.AnyHashable, Any>> of Swift.ContiguousArray._createNewBuffer(bufferIsUnique: Swift.Bool, minimumCapacity: Swift.Int, growForAppend: Swift.Bool) -> ()
generic specialization <Swift.Dictionary<Swift.AnyHashable, Any>> of Swift._ContiguousArrayBuffer._consumeAndCreateNew(bufferIsUnique: Swift.Bool, minimumCapacity: Swift.Int, growForAppend: Swift.Bool) -> Swift._ContiguousArrayBuffer<A>
generic specialization <__C.CMTime> of Swift.ContiguousArray._createNewBuffer(bufferIsUnique: Swift.Bool, minimumCapacity: Swift.Int, growForAppend: Swift.Bool) -> ()
generic specialization <__C.CMTime> of Swift._ContiguousArrayBuffer._consumeAndCreateNew(bufferIsUnique: Swift.Bool, minimumCapacity: Swift.Int, growForAppend: Swift.Bool) -> Swift._ContiguousArrayBuffer<A>
getEnumTagSinglePayload value witness for __C.CMTime
key path getter for (extension in CoreMediaIO):__C.CMIOExtensionDeviceProperties.suspended : Swift.Optional<Swift.Bool> : __C.CMIOExtensionDeviceProperties
key path getter for (extension in CoreMediaIO):__C.CMIOExtensionDeviceProperties.transportType : Swift.Optional<Swift.Int> : __C.CMIOExtensionDeviceProperties
key path setter for (extension in CoreMediaIO):__C.CMIOExtensionDeviceProperties.suspended : Swift.Optional<Swift.Bool> : __C.CMIOExtensionDeviceProperties
key path setter for (extension in CoreMediaIO):__C.CMIOExtensionDeviceProperties.transportType : Swift.Optional<Swift.Int> : __C.CMIOExtensionDeviceProperties
lazy cache variable for type metadata for __C.CMTime
lazy cache variable for type metadata for __C.CMTimeFlags
mangled name ref for type metadata for Swift.Dictionary<Swift.AnyHashable, Any>
mangled name ref for type metadata for Swift._ContiguousArrayStorage<Swift.Dictionary<Swift.AnyHashable, Any>>
mangled name ref for type metadata for Swift._ContiguousArrayStorage<__C.CMTime>
merged (extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.activeFormatIndex.getter : Swift.Optional<Swift.Int>
merged (extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.activeFormatIndex.setter : Swift.Optional<Swift.Int>
merged (extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.frameDuration.getter : Swift.Optional<__C.CMTime>
merged (extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.frameDuration.setter : Swift.Optional<__C.CMTime>
merged key path getter for (extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.activeFormatIndex : Swift.Optional<Swift.Int> : __C.CMIOExtensionStreamProperties
merged key path getter for (extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.frameDuration : Swift.Optional<__C.CMTime> : __C.CMIOExtensionStreamProperties
merged key path setter for (extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.activeFormatIndex : Swift.Optional<Swift.Int> : __C.CMIOExtensionStreamProperties
merged type metadata accessor for __C.CMTime
module descriptor __C
nominal type descriptor for Swift.AnyHashable
nominal type descriptor for Swift.Int32
nominal type descriptor for Swift.Int64
nominal type descriptor for Swift.UInt32
nominal type descriptor for Swift._ContiguousArrayStorage
nominal type descriptor for __C.CMTime
nominal type descriptor for __C.CMTimeFlags
property descriptor for (extension in CoreMediaIO):__C.CMIOExtensionDeviceProperties.suspended : Swift.Optional<Swift.Bool>
property descriptor for (extension in CoreMediaIO):__C.CMIOExtensionDeviceProperties.transportType : Swift.Optional<Swift.Int>
property descriptor for (extension in CoreMediaIO):__C.CMIOExtensionStreamFormat.validFrameDurations : Swift.Optional<Swift.Array<__C.CMTime>>
property descriptor for (extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.activeFormatIndex : Swift.Optional<Swift.Int>
property descriptor for (extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.frameDuration : Swift.Optional<__C.CMTime>
property descriptor for (extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.maxFrameDuration : Swift.Optional<__C.CMTime>
property descriptor for (extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.sinkBufferQueueSize : Swift.Optional<Swift.Int>
property descriptor for (extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.sinkBufferUnderrunCount : Swift.Optional<Swift.Int>
property descriptor for (extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.sinkBuffersRequiredForStartup : Swift.Optional<Swift.Int>
property descriptor for (extension in CoreMediaIO):__C.CMIOExtensionStreamProperties.sinkEndOfData : Swift.Optional<Swift.Int>
protocol witness table for Swift.AnyHashable : Swift.Hashable in Swift
reflection metadata builtin descriptor __C.CMTime
reflection metadata builtin descriptor __C.CMTimeFlags
reflection metadata field descriptor __C.CMTime
reflection metadata field descriptor __C.CMTimeFlags
storeEnumTagSinglePayload value witness for __C.CMTime
type metadata accessor for __C.CMTime
type metadata accessor for __C.CMTimeFlags
type metadata for Any
type metadata for Swift.AnyHashable
value witness table for Builtin.Int32
value witness table for __C.CMTime
