//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOTimeSyncSyncUserClient {
public: // (access info unavailable from symbols alone)
    IOTimeSyncSyncUserClient(OSMetaClass const*);
    auto _RESERVEDIOTimeSyncSyncUserClient0();
    auto _RESERVEDIOTimeSyncSyncUserClient1();
    auto _RESERVEDIOTimeSyncSyncUserClient10();
    auto _RESERVEDIOTimeSyncSyncUserClient11();
    auto _RESERVEDIOTimeSyncSyncUserClient12();
    auto _RESERVEDIOTimeSyncSyncUserClient13();
    auto _RESERVEDIOTimeSyncSyncUserClient14();
    auto _RESERVEDIOTimeSyncSyncUserClient15();
    auto _RESERVEDIOTimeSyncSyncUserClient2();
    auto _RESERVEDIOTimeSyncSyncUserClient3();
    auto _RESERVEDIOTimeSyncSyncUserClient4();
    auto _RESERVEDIOTimeSyncSyncUserClient5();
    auto _RESERVEDIOTimeSyncSyncUserClient6();
    auto _RESERVEDIOTimeSyncSyncUserClient7();
    auto _RESERVEDIOTimeSyncSyncUserClient8();
    auto _RESERVEDIOTimeSyncSyncUserClient9();
    auto clientClose();
    auto externalMethod(unsigned int, IOExternalMethodArguments*, IOExternalMethodDispatch*, OSObject*, void*);
    auto free();
    auto start(IOService*);
    auto stop(IOService*);
    ~IOTimeSyncSyncUserClient();
};
