//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOTimeSyncLuckyFilter {
public: // (access info unavailable from symbols alone)
    IOTimeSyncLuckyFilter();
    auto S0_InitCeilingFloor(long long);
    auto S1_RunLuckyFilter(long long);
    auto adjustCeilingByStep(IOTimeSyncLuckyFilter&);
    auto adjustCeilingByWindow(IOTimeSyncLuckyFilter&);
    auto filter(long long);
    auto timeStamp(long long);
};
