// -*- mode: ObjC -*-

//  This file is part of class-dump, a utility for examining the Objective-C segment of Mach-O files.
//  Copyright (C) 1997-2019 Steve Nygard.

#import "CDSwiftDumper.h"

#import "CDMachOFile.h"
#import "CDLCSymbolTable.h"
#import "CDSymbol.h"
#import "CDSwiftDemangler.h"

@implementation CDSwiftDumper

// Split a demangled Swift symbol like
//   "Foundation.NSString.lengthOfBytesUsingEncoding(UInt) -> Int"
//   "(extension in Swift):Foundation.NSData.foo() -> ()"
//   "static Foundation.NSURL.absoluteString(self: Foundation.NSURL) -> String"
//   "Foundation.NSURL.__deallocating_deinit"
// into (parent-scope, member-signature). Free functions / module-level
// declarations land under "(top-level)".
static void CDSplitSwiftDemangled(NSString *demangled, NSString **outScope, NSString **outRest)
{
    if (demangled == nil) { *outScope = nil; *outRest = nil; return; }

    // Strip leading qualifiers like "static ", "mutating ", etc.
    NSString *s = demangled;
    static NSArray *prefixes = nil;
    if (prefixes == nil) prefixes = @[@"static ", @"mutating ", @"final ", @"public ", @"open ",
                                       @"internal ", @"fileprivate ", @"private "];
    BOOL stripped = YES;
    while (stripped) {
        stripped = NO;
        for (NSString *p in prefixes) {
            if ([s hasPrefix:p]) { s = [s substringFromIndex:[p length]]; stripped = YES; break; }
        }
    }

    // Find the boundary between scope and member name. The qualified name is
    // the prefix up to the first `(` (function), `:` (witness), `.getter`,
    // `.setter`, `.modify`, `.read`, `.init`, `.deinit`, or end.
    NSUInteger nameEnd = [s length];
    NSUInteger angle = 0; // <…> nesting
    NSUInteger paren = 0; // (…) nesting
    for (NSUInteger i = 0; i < [s length]; i++) {
        unichar c = [s characterAtIndex:i];
        if (c == '<') angle++;
        else if (c == '>' && angle) angle--;
        else if (c == '(' && angle == 0) { nameEnd = i; break; }
        else if (c == ' ' && angle == 0 && paren == 0) { nameEnd = i; break; }
    }

    NSString *qualified = [s substringToIndex:nameEnd];
    NSString *signature = [s substringFromIndex:nameEnd];

    NSRange lastDot = [qualified rangeOfString:@"." options:NSBackwardsSearch];
    if (lastDot.location == NSNotFound) {
        // No dot: top-level declaration in the implicit module.
        *outScope = @"(top-level)";
        *outRest = [qualified stringByAppendingString:signature];
        return;
    }
    *outScope = [qualified substringToIndex:lastDot.location];
    NSString *member = [qualified substringFromIndex:lastDot.location + 1];
    *outRest = [member stringByAppendingString:signature];
}

+ (NSDictionary<NSString *, NSArray<NSString *> *> *)groupedSymbolsFromMachOFile:(CDMachOFile *)machOFile
{
    NSMutableDictionary<NSString *, NSMutableArray<NSString *> *> *groups = [NSMutableDictionary dictionary];
    CDLCSymbolTable *st = machOFile.symbolTable;
    if (st == nil) return @{};
    [st loadSymbols];

    for (CDSymbol *sym in st.symbols) {
        NSString *raw = sym.name;
        if (raw == nil) continue;
        if (![CDSwiftDemangler isMangledSwiftName:raw]) continue;

        NSString *demangled = [CDSwiftDemangler demangle:raw];
        if (demangled == nil || [demangled isEqualToString:raw]) continue;

        NSString *scope = nil;
        NSString *member = nil;
        CDSplitSwiftDemangled(demangled, &scope, &member);
        if (scope == nil) continue;

        NSMutableArray *arr = groups[scope];
        if (arr == nil) { arr = [NSMutableArray array]; groups[scope] = arr; }
        if (member && ![arr containsObject:member]) [arr addObject:member];
    }

    NSMutableDictionary *out = [NSMutableDictionary dictionaryWithCapacity:[groups count]];
    for (NSString *k in groups) out[k] = [groups[k] copy];
    return out;
}

+ (NSString *)_headerStringForScope:(NSString *)scope members:(NSArray<NSString *> *)members
{
    NSMutableString *s = [NSMutableString string];
    [s appendString:@"//\n//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.\n//\n\n"];

    if ([scope isEqualToString:@"(top-level)"]) {
        [s appendString:@"// Top-level Swift declarations\n\n"];
        for (NSString *m in [members sortedArrayUsingSelector:@selector(compare:)]) {
            [s appendFormat:@"%@\n", m];
        }
        return [s copy];
    }

    NSString *header;
    if ([scope hasPrefix:@"(extension in "]) {
        header = [NSString stringWithFormat:@"// %@", scope];
    } else {
        header = [NSString stringWithFormat:@"extension %@", scope];
    }
    [s appendFormat:@"%@ {\n", header];
    for (NSString *m in [members sortedArrayUsingSelector:@selector(compare:)]) {
        [s appendFormat:@"    %@\n", m];
    }
    [s appendString:@"}\n"];
    return [s copy];
}

+ (NSString *)dumpHeaderForMachOFile:(CDMachOFile *)machOFile
{
    NSDictionary *groups = [self groupedSymbolsFromMachOFile:machOFile];
    NSMutableString *out = [NSMutableString string];
    NSArray *names = [[groups allKeys] sortedArrayUsingSelector:@selector(compare:)];
    for (NSString *name in names) {
        [out appendString:[self _headerStringForScope:name members:groups[name]]];
        [out appendString:@"\n"];
    }
    return [out copy];
}

+ (BOOL)writeHeadersForMachOFile:(CDMachOFile *)machOFile toDirectory:(NSString *)outDir error:(NSError **)error
{
    NSFileManager *fm = [NSFileManager defaultManager];
    if (![fm fileExistsAtPath:outDir]) {
        if (![fm createDirectoryAtPath:outDir withIntermediateDirectories:YES attributes:nil error:error]) return NO;
    }
    NSDictionary *groups = [self groupedSymbolsFromMachOFile:machOFile];
    for (NSString *scope in groups) {
        NSString *body = [self _headerStringForScope:scope members:groups[scope]];

        // Sanitize file name: replace problematic characters with `_`.
        NSCharacterSet *bad = [NSCharacterSet characterSetWithCharactersInString:@"/() :<>"];
        NSString *fileName = [[scope componentsSeparatedByCharactersInSet:bad]
                                       componentsJoinedByString:@"_"];
        if ([fileName length] == 0) fileName = @"toplevel";
        NSString *path = [[outDir stringByAppendingPathComponent:fileName] stringByAppendingPathExtension:@"swift"];
        if (![body writeToFile:path atomically:YES encoding:NSUTF8StringEncoding error:error]) return NO;
    }
    return YES;
}

@end
