//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol OS_dispatch_queue;

@interface FaceTimeNotifictionCenterSupport : NSObject
{
    _Bool _callIsRinging;
    NSObject<OS_dispatch_queue> *_facetimeSerialQueue;
}

+ (id)sharedFaceTimeNotifictionCenterSupport;
- (void).cxx_destruct;
- (void)faceTimeCallRingStop;
- (void)faceTimeCallRingStart;
- (_Bool)callIsRinging;
- (void)powerButtonPressed;
- (void)cancelButtonPressed;
- (void)escapeKeyPressed;
- (void)cancelCall;
- (void)muteCall;
- (id)init;

@end

