//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSNumber, NSString;

@protocol LWDefaultScreenLockUIDelegate
- (void)startUnlockForActiveUser;
- (void)passwordFieldKeyPressed;
- (void)handleUnlockResult:(NSNumber *)arg1;
- (void)checkAuthWithUsername:(NSString *)arg1 password:(NSString *)arg2 completionBlock:(void (^)(_Bool))arg3;
@end

