//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "LUI2UserCollectionViewControllerDelegate-Protocol.h"
#import "LUI2WindowDelegate-Protocol.h"

@class LUI2UIController, LUIUnmanagedSpace, NSString, NSTimer;
@protocol LWDefaultScreenLockUIDelegate;

@interface LWDefaultScreenLockUI : NSObject <LUI2WindowDelegate, LUI2UserCollectionViewControllerDelegate>
{
    id <LWDefaultScreenLockUIDelegate> _screenLockDelegate;
    long long _lockRequest;
    _Bool _observingFirstResponder;
    _Bool _useTimeoutTimer;
    _Bool _windowControllerActionInProgress;
    _Bool _windowRefocused;
    NSTimer *_timeoutTimer;
    NSTimer *_resumeStatusTimer;
    NSTimer *_unlockDelayedTimer;
    NSString *_authPwd;
    long long _numberOfAttempts;
    _Bool _passwordRequired;
    _Bool _passwordRequiredForAccessibility;
    _Bool _timeOutTimerBlocked;
    _Bool _oneTimeShortTimeout;
    LUI2UIController *_screenLockController;
    LUIUnmanagedSpace *_screenLockSpace;
    unsigned long long _screenLockSignpostIntervalID;
    NSTimer *_rateLimitTimer;
    _Bool _passwordEntryBlocked;
    struct {
        _Bool hideLockUI;
        _Bool hideAuthHintTextView;
        _Bool hideBackButton;
        _Bool hideClockViews;
        _Bool hideMessageTextView;
        _Bool hidePasswordTextField;
        _Bool hideProgressIndicator;
        _Bool hideStatusView;
        _Bool hideUserCollectionView;
        _Bool hideUserNameLabel;
        _Bool hideUserNameTextField;
    } _visibility;
    _Bool _continuityEnabled;
    _Bool _adminCanUnlockAdmin;
    NSString *_pinPlaceHolderString;
    NSString *_passwordPlaceHolderString;
}

+ (_Bool)supportsSecureCoding;
- (void).cxx_destruct;
@property(retain) NSString *passwordPlaceHolderString; // @synthesize passwordPlaceHolderString=_passwordPlaceHolderString;
@property(retain) NSString *pinPlaceHolderString; // @synthesize pinPlaceHolderString=_pinPlaceHolderString;
@property _Bool adminCanUnlockAdmin; // @synthesize adminCanUnlockAdmin=_adminCanUnlockAdmin;
@property _Bool oneTimeShortTimeout; // @synthesize oneTimeShortTimeout=_oneTimeShortTimeout;
@property(getter=isContinuityEnabled) _Bool continuityEnabled; // @synthesize continuityEnabled=_continuityEnabled;
- (void)_screenLockSignpostIntervalEnd;
- (void)_screenLockSignpostIntervalBegin;
- (id)visibleAvatarDescriptor;
- (id)avatarAnimator;
- (void)_userAvatarResume;
- (void)_userAvatarPause;
- (_Bool)avatarsCanSleep;
- (_Bool)avatarAllowedForUser:(id)arg1;
- (void)showPasswordChangeError:(id)arg1;
- (void)showPasswordPolicyDetailsForUser:(id)arg1;
- (void)showPasswordChange:(int)arg1;
- (void)resetPasswordPressed:(id)arg1;
- (void)_cancelResetPressed:(id)arg1;
- (void)_updateClockSettings;
- (void)updatePlaceholderString;
- (void)_hideUserAvatarAndNameIfNeeded;
@property(readonly) _Bool _forceHideUserAvatarAndName;
- (void)setUserInLockUI:(id)arg1;
- (unsigned long long)findIndexOfUserWithUID:(unsigned int)arg1;
- (unsigned long long)findIndexOfUserWithUID:(unsigned int)arg1 inList:(id)arg2;
- (id)userNameFromLockUI;
- (void)clickUnlockButton;
- (id)userForCurrentFocusedUser;
- (long long)userCollectionViewControllerLayout;
- (_Bool)_shouldShowSwitchUser;
- (void)_setProgressIndicatorHidden:(_Bool)arg1;
- (void)setPasswordFieldString:(id)arg1;
- (void)setPasswordFieldPlaceholderString:(id)arg1;
- (void)setUserCollectionViewControllerLayout:(long long)arg1;
- (void)_setUserCollectionViewHidden:(_Bool)arg1;
- (void)_setUserNameTextFieldHidden:(_Bool)arg1;
- (void)_setUserNameLabelHidden:(_Bool)arg1;
- (void)setUserNameLabel:(id)arg1;
- (void)_setStatusViewHidden:(_Bool)arg1;
- (void)_setPasswordTextFieldHidden:(_Bool)arg1;
- (void)_setMessageTextViewHidden:(_Bool)arg1;
- (void)_setClockViewsHidden:(_Bool)arg1;
- (void)_setBackButtonHidden:(_Bool)arg1;
- (void)_setAuthHintTextViewHidden:(_Bool)arg1;
- (void)_setMessageText:(id)arg1;
- (void)_setAuthHintText:(id)arg1 subHintText:(id)arg2;
- (void)makeUserNameFieldFirstResponder;
- (void)makePasswordFieldFirstResponder;
- (void)_makeCollectionViewFirstResponder;
- (_Bool)_isPasswordRequired;
- (void)showTextField:(_Bool)arg1 withMessage:(id)arg2 subMessage:(id)arg3 passwordRequired:(_Bool)arg4 showingSpinner:(_Bool)arg5 withDelay:(double)arg6;
- (void)updatePanel;
- (void)updateFocus;
- (id)goodSamaritanMessage;
- (_Bool)fmmEnabled;
- (_Bool)fileVaultEnabled;
- (long long)guestMode;
- (_Bool)guestEnabled;
- (void)_accessibilityDidChange:(id)arg1;
- (void)windowDidResignKey:(id)arg1;
- (void)windowDidBecomeKey:(id)arg1;
- (_Bool)control:(id)arg1 textShouldBeginEditing:(id)arg2;
- (void)recenterWindows;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)closeAuthAfterFUSIfNeeded;
- (void)closeAuthAndReset:(_Bool)arg1;
- (double)getIdleTime;
- (_Bool)fastUserSwitchingEnabled:(_Bool)arg1;
- (void)setUnlockDelayedTimer:(double)arg1;
- (void)freeUnlockDelayedTimer;
- (void)handleTimeOutTimer:(double)arg1;
- (void)setTimeoutTimer:(double)arg1 withDelay:(double)arg2;
- (void)setTimeoutTimer:(double)arg1;
- (void)freeTimeoutTimer;
- (void)clearAuthPwdIfSet;
- (id)_timeFormatter;
- (void)authAccountLocked;
- (void)authRateLimitHitWithBackOffTime:(double)arg1;
- (void)authNewPasswordRequired;
- (void)authSuccess;
- (void)addToUserMenu:(id)arg1 target:(id)arg2 action:(SEL)arg3;
- (void)authBegan;
- (void)handlePasswordChangeError:(int)arg1;
- (void)messageTraceNumberOfAuthAttempts:(long long)arg1;
- (void)sendDesktopLayerToHibernation;
- (id)passwordSupportURL;
- (void)authFailWithMessage:(id)arg1;
- (void)setTimeoutTimerIsBlocked:(_Bool)arg1;
- (void)startTimerForUnlockRequest:(long long)arg1;
- (_Bool)lockUIIsOnScreen;
- (void)refocusAuthOnWakeIfNeeded;
- (void)resetAuthUIOnSleepIfNeeded;
- (void)switchFromPlatformSSOTempUser:(id)arg1;
- (void)restartToSafariPressed:(id)arg1;
- (void)centerAlert:(id)arg1;
- (void)setModalLevel:(id)arg1;
- (_Bool)optionReturnPressed:(id)arg1;
- (_Bool)keyPressed:(id)arg1;
- (_Bool)escapePressed:(id)arg1;
- (void)userOrBackgroundPressed:(id)arg1;
- (void)focusedUserChangedFrom:(id)arg1 to:(id)arg2;
- (void)willChangeFromLayout:(long long)arg1 toLayout:(long long)arg2;
- (void)didChangeFromLayout:(long long)arg1 toLayout:(long long)arg2;
- (void)guestPressed:(id)arg1;
- (void)_guestSelected;
- (void)switchUserPressed:(id)arg1;
- (id)_fusAttributeForUser:(id)arg1;
- (void)cancelPressed:(id)arg1;
- (void)loginPressed:(id)arg1;
- (void)checkAuth;
- (void)defaultScreenLockHandleUnlockResult:(long long)arg1 resetAuthWindowLevel:(_Bool)arg2;
- (void)showScreenLock:(long long)arg1;
- (void)_performanceTestingAutoUnlock;
- (id)_automationLoginDict;
- (void)updateSingleUserLayoutMode;
- (void)updateScreenLockUI;
- (void)addDesktopPictureToAuthUI;
- (void)hidePasswordField;
- (void)showPasswordFieldMakingFirstResponder:(_Bool)arg1;
- (void)showPasswordField;
- (void)stopUnlockDelayedAnimation;
- (void)resetAfterDarkwake;
- (void)startUnlockDelayedAnimation;
- (void)_updateLockUI;
- (void)_raiseLockUI;
- (_Bool)_bigClockHidden;
- (void)_lowerLockUI;
- (void)_setWindowLevel:(long long)arg1;
- (void)_setSecureInput:(_Bool)arg1;
- (void)_setObservingFirstResponder:(_Bool)arg1;
- (void)_screenLockWindowDidShow;
- (void)_load;
- (void)_resetVisibility;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

