//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTextView.h>

@interface NSTextView (No_Context_Menus)
- (id)menuForEvent:(id)arg1;
@end

