//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface TokenRemoval : NSObject
{
    _Bool cssmInitialized;
    struct cssm_subservice_uid mSubserviceUID;
    NSMutableDictionary *tokenMap;
}

+ (id)sharedTokenRemoval;
- (void).cxx_destruct;
- (unsigned char)tokenRemoved:(id)arg1;
- (long long)readTokenRemovalActionPref:(id)arg1;
- (struct cssm_subservice_uid *)subserviceUID;
- (void)endWatch;
- (void)watch:(struct cssm_subservice_uid *)arg1;
- (_Bool)isTokenRegistered:(const char *)arg1;
- (void)registerToken:(struct AuthorizationOpaqueRef *)arg1 forUser:(char *)arg2;
- (id)copyTokenIdFromAuthRef:(struct AuthorizationOpaqueRef *)arg1;
- (void)dealloc;
- (id)init;

@end

