//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class icu::HinduSolarCalendar {
public: // (access info unavailable from symbols alone)
    HinduSolarCalendar(icu::Locale const&, UErrorCode&);
    add(UCalendarDateFields, int, UErrorCode&);
    add(icu::Calendar::EDateFields, int, UErrorCode&);
    clone() const;
    doHandleComputeMonthStart(int, int, UErrorCode&) const;
    getDayTransition(int) const;
    getDynamicClassID() const;
    getHinduCalendarType() const;
    getLookupTable() const;
    getLookupTableBaseYear() const;
    getLookupTableLength() const;
    getStaticClassID();
    getType() const;
    getYearOffset() const;
    handleComputeFields(int, UErrorCode&);
    handleComputeMonthStart(int, int, signed char, UErrorCode&) const;
    handleComputeOrdinalDay(int);
    handleGetLimit(UCalendarDateFields, icu::Calendar::ELimitType) const;
    handleGetMonthLength(int, int, UErrorCode&) const;
    hinduCalendarYear(double) const;
    hinduSolarFromFixed(int) const;
    hinduSolarFromFixedWithLookup(int) const;
    nextMonthStart(double, int) const;
    roll(UCalendarDateFields, int, UErrorCode&);
    siderealYear() const;
    solarLongitude(double) const;
    zodiac(double) const;
    ~HinduSolarCalendar();
};
