//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class icu::DateFormatSymbols {
public: // (access info unavailable from symbols alone)
    DateFormatSymbols(UErrorCode&);
    DateFormatSymbols(char const*, UErrorCode&);
    DateFormatSymbols(icu::DateFormatSymbols const&);
    DateFormatSymbols(icu::Locale const&, UErrorCode&);
    DateFormatSymbols(icu::Locale const&, char const*, UErrorCode&);
    arrayCompare(icu::UnicodeString const*, icu::UnicodeString const*, int);
    assignArray(icu::UnicodeString*&, int&, icu::UnicodeString const*, int);
    copyData(icu::DateFormatSymbols const&);
    createForLocale(icu::Locale const&, UErrorCode&);
    createZoneStrings(icu::UnicodeString const* const*);
    dispose();
    disposeZoneStrings();
    getAmPmStrings(int&) const;
    getAmPmStrings(int&, icu::DateFormatSymbols::DtContextType, icu::DateFormatSymbols::DtWidthType) const;
    getDynamicClassID() const;
    getEraNames(int&) const;
    getEras(int&) const;
    getLeapMonthPatterns(int&) const;
    getLocalPatternChars(icu::UnicodeString&) const;
    getLocale(ULocDataLocaleType, UErrorCode&) const;
    getMonths(int&) const;
    getMonths(int&, icu::DateFormatSymbols::DtContextType, icu::DateFormatSymbols::DtWidthType) const;
    getNarrowEras(int&) const;
    getPatternCharIndex(char16_t);
    getPatternUChars();
    getQuarters(int&, icu::DateFormatSymbols::DtContextType, icu::DateFormatSymbols::DtWidthType) const;
    getShortMonths(int&) const;
    getShortWeekdays(int&) const;
    getStaticClassID();
    getTimeSeparatorString(icu::UnicodeString&) const;
    getWeekdays(int&) const;
    getWeekdays(int&, icu::DateFormatSymbols::DtContextType, icu::DateFormatSymbols::DtWidthType) const;
    getYearNames(int&, icu::DateFormatSymbols::DtContextType, icu::DateFormatSymbols::DtWidthType) const;
    getZodiacNames(int&, icu::DateFormatSymbols::DtContextType, icu::DateFormatSymbols::DtWidthType) const;
    getZoneStrings(int&, int&) const;
    initZoneStringsArray();
    initializeData(icu::Locale const&, char const*, UErrorCode&, signed char);
    isNumericField(UDateFormatField, int);
    isNumericPatternChar(char16_t, int);
    operator=(icu::DateFormatSymbols const&);
    operator==(icu::DateFormatSymbols const&) const;
    setAmPmStrings(icu::UnicodeString const*, int);
    setAmPmStrings(icu::UnicodeString const*, int, icu::DateFormatSymbols::DtContextType, icu::DateFormatSymbols::DtWidthType);
    setEraNames(icu::UnicodeString const*, int);
    setEras(icu::UnicodeString const*, int);
    setLocalPatternChars(icu::UnicodeString const&);
    setMonths(icu::UnicodeString const*, int);
    setMonths(icu::UnicodeString const*, int, icu::DateFormatSymbols::DtContextType, icu::DateFormatSymbols::DtWidthType);
    setNarrowEras(icu::UnicodeString const*, int);
    setQuarters(icu::UnicodeString const*, int, icu::DateFormatSymbols::DtContextType, icu::DateFormatSymbols::DtWidthType);
    setShortMonths(icu::UnicodeString const*, int);
    setShortWeekdays(icu::UnicodeString const*, int);
    setTimeSeparatorString(icu::UnicodeString const&);
    setWeekdays(icu::UnicodeString const*, int);
    setWeekdays(icu::UnicodeString const*, int, icu::DateFormatSymbols::DtContextType, icu::DateFormatSymbols::DtWidthType);
    setYearNames(icu::UnicodeString const*, int, icu::DateFormatSymbols::DtContextType, icu::DateFormatSymbols::DtWidthType);
    setZodiacNames(icu::UnicodeString const*, int, icu::DateFormatSymbols::DtContextType, icu::DateFormatSymbols::DtWidthType);
    setZoneStrings(icu::UnicodeString const* const*, int, int);
    ~DateFormatSymbols();
};
