//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class icu::StringPiece {
public: // (access info unavailable from symbols alone)
    StringPiece(char const*);
    StringPiece(icu::StringPiece const&, int);
    StringPiece(icu::StringPiece const&, int, int);
    compare(icu::StringPiece);
    find(icu::StringPiece, int);
    set(char const*);
};
