//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class icu::HinduLunisolarVikramCalendar {
public: // (access info unavailable from symbols alone)
    HinduLunisolarVikramCalendar(icu::Locale const&, UErrorCode&);
    clone() const;
    getDynamicClassID() const;
    getHinduCalendarType() const;
    getStaticClassID();
    getType() const;
    getYearOffset() const;
    handleComputeMonthStart(int, int, signed char, UErrorCode&) const;
    ~HinduLunisolarVikramCalendar();
};
