//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOMemoryDescriptor {
public: // (access info unavailable from symbols alone)
    createMappingInTask(task*, unsigned long long, unsigned int, unsigned long long, unsigned long long);
    getDMAMapLength(unsigned long long*);
    getDescriptorID();
    getPageCounts(unsigned long long*, unsigned long long*, unsigned long long*);
    ktraceEmitPhysicalSegments();
    setContext(OSObject*);
    setOwnership(task*, int, unsigned int);
    withAddressRange(unsigned long long, unsigned long long, unsigned int, task*);
};
