//
//     Generated by class-dump 3.5 (64 bit) — Swift symbol-derived view.
//

extension Observation.Observations.State.dirty {
    getter : Swift.Bool
    modify : Swift.Bool
    modify : Swift.Bool with unmangled suffix ".resume.0"
    setter : Swift.Bool
}
