//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class marisa::grimoire::io::Mapper::map<marisa::grimoire::vector {
public: // (access info unavailable from symbols alone)
    RankIndex>(marisa::grimoire::vector::RankIndex const**, unsigned long);
};
