//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleUSBEthernetControllerAX88178 {
public: // (access info unavailable from symbols alone)
    AppleUSBEthernetControllerAX88178();
    AppleUSBEthernetControllerAX88178(OSMetaClass const*);
    bulkReadCompleteGated(void*, int, unsigned int);
    bulkWriteCompleteGated(void*, int, unsigned int);
    createMediumDictionary();
    disable(IONetworkInterface*);
    enable(IONetworkInterface*);
    enableExtPhyAgere4();
    enableExtPhyMarvell();
    enableExtPhyRealtek();
    enableExtPhyVitesse();
    findAutoNegotiateMedium(unsigned short, unsigned short, unsigned short, unsigned short, unsigned short);
    free();
    getHardwareAddress(IOEthernetAddress*);
    getMetaClass() const;
    getMsrForMediumType(unsigned int, unsigned short*);
    getPacketFilters(OSSymbol const*, unsigned int*) const;
    getRxBufferSize();
    getTxBufferSize();
    handleSelectMediumGated(IONetworkMedium const*);
    init(OSDictionary*);
    interruptReadComplete(void*, int, unsigned int);
    linkChangeThreadCall(void*, void*);
    linkChangeThreadCallGated();
    lockPhyRegisterGated();
    outputStart(IONetworkInterface*, unsigned int);
    outputStart(IONetworkInterface*, unsigned int) (.cold.1);
    outputTimerExpired(IOTimerEventSource*);
    powerStateWillChangeToGated(unsigned long, unsigned long, IOService*);
    prepareExtPhy();
    prepareHwForNormalStop();
    prepareHwForWakeOnLan();
    probe(IOService*, int*);
    probeExtPhy();
    processInterruptTransfer(unsigned char*, unsigned int);
    readBulkPipe();
    readBulkPipeGated();
    readInterruptPipe();
    readInterruptPipeGated();
    readPhyRegister(unsigned char, unsigned short*);
    readPhyRegisterGated(unsigned char, unsigned short*);
    readPhyRegisterInternal(unsigned char, unsigned short*);
    readSROM(unsigned short*, unsigned short, unsigned short);
    readSROMGated(unsigned short*, unsigned short, unsigned short);
    selectMedium(IONetworkMedium const*);
    setHardwareAddress(IOEthernetAddress const*);
    setMulticastList(IOEthernetAddress*, unsigned int);
    setMulticastMode(bool);
    setPromiscuousMode(bool);
    setWakeOnMagicPacket(bool);
    start(IOService*);
    stop(IOService*);
    teardownExtPhy();
    unlockPhyRegisterGated();
    willTerminate(IOService*, unsigned int);
    writePhyRegister(unsigned char, unsigned short);
    writePhyRegisterGated(unsigned char, unsigned short);
    writePhyRegisterInternal(unsigned char, unsigned short);
    writeSROM(unsigned short*, unsigned short, unsigned short);
    writeSROMGated(unsigned short*, unsigned short, unsigned short);
    ~AppleUSBEthernetControllerAX88178();
};
