//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleUSBEthernetController {
public: // (access info unavailable from symbols alone)
    AppleUSBEthernetController(OSMetaClass const*);
    configureInterface(IONetworkInterface*);
    free();
    getMetaClass() const;
    getNetworkStats();
    init(OSDictionary*);
    newModelString() const;
    powerStateDidChangeTo(unsigned long, unsigned long, IOService*);
    powerStateDidChangeToGated(unsigned long, unsigned long, IOService*);
    powerStateWillChangeTo(unsigned long, unsigned long, IOService*);
    powerStateWillChangeToGated(unsigned long, unsigned long, IOService*);
    registerWithPolicyMaker(IOService*);
    registerWithPolicyMaker(IOService*)::powerStates;
    setMulticastMode(bool);
    setPowerState(unsigned long, IOService*);
    setPromiscuousMode(bool);
    start(IOService*);
    stop(IOService*);
    willTerminate(IOService*, unsigned int);
    ~AppleUSBEthernetController();
};
