//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AMDRadeonX4000_AMDAccelShared {
public: // (access info unavailable from symbols alone)
    AMDRadeonX4000_AMDAccelShared();
    AMDRadeonX4000_AMDAccelShared(OSMetaClass const*);
    AndXorByteFlag(unsigned short, unsigned char, unsigned char);
    AndXorByteFlagNoWrite(unsigned short, unsigned char, unsigned char) const;
    EnableVcePowerManagement(bool);
    GetVceSessionId(sVideoContextCreateInfo*, sVideoContextReturnInfo*);
    RemoveVceContext(unsigned int);
    SetPPLibPowerState();
    SurfaceCopy(unsigned int*, unsigned long long, IOAccelEvent*);
    free();
    getMetaClass() const;
    init(IOGraphicsAccelerator2*, task*);
    ~AMDRadeonX4000_AMDAccelShared();
};
