//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AMDRadeonX4000_AMDAccelDisplayMachine {
public: // (access info unavailable from symbols alone)
    AMDRadeonX4000_AMDAccelDisplayMachine();
    AMDRadeonX4000_AMDAccelDisplayMachine(OSMetaClass const*);
    auto describeDriverAllocations(IOAccelAllocationInfo*);
    auto displayModeDidChange();
    auto displayModeWillChange();
    auto getMetaClass() const;
    auto init(IOGraphicsAccelerator2*);
    auto isWindowServerActiveAttribSupported();
    auto resetTempBuffersAndVblankFlips();
    auto setWindowServerActiveState(_eAMDWindowServerActiveAttributeState);
    auto set_display_mode_and_vram();
    auto stop();
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~AMDRadeonX4000_AMDAccelDisplayMachine();
};
