//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AMDRadeonX4000_AMDCISAMURBIRing {
public: // (access info unavailable from symbols alone)
    AMDRadeonX4000_AMDCISAMURBIRing();
    AMDRadeonX4000_AMDCISAMURBIRing(OSMetaClass const*);
    align();
    disableReadPointerWriteBack();
    enableReadPointerWriteBack();
    free();
    getHead();
    getMetaClass() const;
    getReadPointer();
    getWritePointer();
    init(AMDRadeonX4000_IAMDHWInterface*, int, _eAMD_HW_ENGINE_TYPE, unsigned int, void const*);
    programReadAndWritePointers(unsigned int);
    registerLocation();
    reset();
    writeTail();
    ~AMDRadeonX4000_AMDCISAMURBIRing();
};
