//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AMDRadeonX4000_AMDVIHWMemory {
public: // (access info unavailable from symbols alone)
    AMDRadeonX4000_AMDVIHWMemory();
    AMDRadeonX4000_AMDVIHWMemory(OSMetaClass const*);
    complete(AMDRadeonX4000_AMDAccelResource*);
    getHWMemoryApertureSize();
    getHWMemorySize();
    getMetaClass() const;
    prepare(AMDRadeonX4000_AMDAccelResource*, unsigned long long, unsigned long long, unsigned long long*);
    programOrClearHDPRegisters(unsigned char, unsigned long long, unsigned long long, unsigned long long, bool);
    ~AMDRadeonX4000_AMDVIHWMemory();
};
