//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AMDRadeonX4000_AMDVIsDMAEngine {
public: // (access info unavailable from symbols alone)
    AMDRadeonX4000_AMDVIsDMAEngine();
    AMDRadeonX4000_AMDVIsDMAEngine(OSMetaClass const*);
    auto allocateHWChannels();
    auto allocateHWRings();
    auto dumpEngineHangState(bool);
    auto getMetaClass() const;
    auto init(AMDRadeonX4000_IAMDHWInterface*, _eAMD_HW_ENGINE_TYPE);
    auto isIdle();
    auto start();
    auto stop();
    auto validateCommandBuffer(unsigned int*, unsigned int, unsigned int*);
    auto writeDiagnosisReport(char*&, unsigned int&);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~AMDRadeonX4000_AMDVIsDMAEngine();
};
