//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AMDRadeonX4000_AMDDecAppInterface {
public: // (access info unavailable from symbols alone)
    AMDRadeonX4000_AMDDecAppInterface(OSMetaClass const*);
    configureBuffers();
    free();
    getMetaClass() const;
    init(AMDRadeonX4000_AMDGraphicsAccelerator*, AMDRadeonX4000_IAMDHWInterface*, unsigned int, unsigned int);
    ~AMDRadeonX4000_AMDDecAppInterface();
};
