//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AMDRadeonX4000_AMDBaffinAlignManager {
public: // (access info unavailable from symbols alone)
    AMDRadeonX4000_AMDBaffinAlignManager();
    AMDRadeonX4000_AMDBaffinAlignManager(OSMetaClass const*);
    getAddrFormat(unsigned int);
    getAddrTileMode(unsigned int);
    getArrayMode(_AddrTileMode);
    getFormat(_AddrFormat);
    getMetaClass() const;
    ~AMDRadeonX4000_AMDBaffinAlignManager();
};
