//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AMDRadeonX4000_AMDPM4CommandsUtility {
public: // (access info unavailable from symbols alone)
    AMDRadeonX4000_AMDPM4CommandsUtility();
    AMDRadeonX4000_AMDPM4CommandsUtility(OSMetaClass const*);
    buildContextControlCommand(unsigned int*, unsigned int, unsigned int);
    buildEventWriteCommand(unsigned int*, unsigned int, unsigned int);
    buildEventWriteEOPCommand(unsigned int*, unsigned int, unsigned long long, unsigned long long, unsigned int, bool, unsigned int, unsigned int);
    buildIndirectBufferCommand(unsigned int*, unsigned long long, unsigned int, _eAMD_INDIRECT_BUFFER_TYPE, unsigned int, bool, unsigned int);
    buildMemWriteCommand(unsigned int*, unsigned long long, unsigned int, unsigned int);
    buildPFPSyncMECommand(unsigned int*);
    buildPM4Type0Cmd(unsigned int*, unsigned int, unsigned int);
    buildSetDataCommand(unsigned int*, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int);
    buildSurfaceSyncCommand(unsigned int*, unsigned int, unsigned int);
    buildWaitRegMemCommand(unsigned int*, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int);
    buildWriteDataCommand(unsigned int*, unsigned long long, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int const*, unsigned int, unsigned int);
    getMetaClass() const;
    writePM4Type0CmdToRing(AMDRadeonX4000_IAMDHWRing*, unsigned int, unsigned int);
    writeSurfaceSyncCommandToRing(AMDRadeonX4000_IAMDHWRing*, unsigned int, unsigned int);
    writeWriteDataCommandToRing(AMDRadeonX4000_IAMDHWRing*, unsigned long long, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int const*, unsigned int, unsigned int);
    ~AMDRadeonX4000_AMDPM4CommandsUtility();
};
