//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AMDRadeonX4000_AMDCISAMURBIChannel {
public: // (access info unavailable from symbols alone)
    AMDRadeonX4000_AMDCISAMURBIChannel();
    AMDRadeonX4000_AMDCISAMURBIChannel(OSMetaClass const*);
    allocateMemoryResources();
    commitIndirectCommandBuffer(AMD_SUBMIT_COMMAND_BUFFER_INFO*);
    free();
    getMetaClass() const;
    init(int, AMDRadeonX4000_IAMDHWInterface*, AMDRadeonX4000_IAMDHWEngine*, AMDRadeonX4000_IAMDHWRing*, char const*);
    timeStampInterruptCallbackRBI(OSObject*, void*);
    ~AMDRadeonX4000_AMDCISAMURBIChannel();
};
