//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AMDRadeonX4000_AMDAccelSAMUContext {
public: // (access info unavailable from symbols alone)
    AMDRadeonX4000_AMDAccelSAMUContext();
    AMDRadeonX4000_AMDAccelSAMUContext(OSMetaClass const*);
    auto AMDRadeonX4000_setPC(bool);
    auto cleanCPThreadPending();
    auto createAppInf(unsigned int, unsigned int*, AMDRadeonX4000_AMDCPAppInterface**);
    auto describeDriverAllocations(IOAccelAllocationInfo*);
    auto free();
    auto getAppMemoryOffset(unsigned int, unsigned int);
    auto getGPCOMCommandBuffer();
    auto getMetaClass() const;
    auto getRBICommandBuffer();
    auto getSubmitStamp(unsigned int);
    auto init(AMDRadeonX4000_AMDGraphicsAccelerator*, AMDRadeonX4000_IAMDHWInterface*);
    auto isAppInfSupport(unsigned int);
    auto loadApp(AMDRadeonX4000_AMDCPAppInterface*);
    auto loadAppCode(unsigned int, unsigned long long, unsigned int);
    auto processCPThreadTimer();
    auto processFPResume();
    auto reset();
    auto resume();
    auto sendDisplayInfo(unsigned int*);
    auto setMemoryAllocationsEnabled(bool);
    auto setMemoryAllocationsEnabledLegacy(bool);
    auto setMemoryState(bool, bool);
    auto setSuspendResumeState(bool);
    auto setSuspendResumeStateLegacy(bool);
    auto start();
    auto stop(bool);
    auto submitAppMsg(AMDRadeonX4000_AMDCPAppInterface*, AMDRadeonX4000_AMDSMLCPMsg*);
    auto submitGPCOMCommandBuffer(_SAMUCmdBuffers*);
    auto submitRBICommandBuffer(_SAMUCmdBuffers*);
    auto suspend();
    auto unloadApp(AMDRadeonX4000_AMDCPAppInterface*);
    auto waitForAppEvent(unsigned int);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~AMDRadeonX4000_AMDAccelSAMUContext();
};
