//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AMDRadeonX4000_AMDSPUHWEngine {
public: // (access info unavailable from symbols alone)
    AMDRadeonX4000_AMDSPUHWEngine(OSMetaClass const*);
    auto allocateSPUMemory();
    auto disableTimestampInterrupt();
    auto dumpEngineHangState(bool);
    auto enableTimestampInterrupt();
    auto free();
    auto getFixedMemory(unsigned int, bool);
    auto getMetaClass() const;
    auto getSupsendResumeState();
    auto init(AMDRadeonX4000_IAMDHWInterface*, _eAMD_HW_ENGINE_TYPE);
    auto initSPUBootControl();
    auto initSPUMemory();
    auto loadSPUKernel();
    auto pageSPUReservedArea(bool, unsigned int);
    auto releaseSPUMemory();
    auto releaseSPUReservedArea();
    auto reset(_eAMD_HW_RING_TYPE, unsigned int*);
    auto setKernelMemoryCail();
    auto setMemoryAllocations(bool);
    auto setMemoryAllocationsEnabled(bool);
    auto setPowerPauseState(bool);
    auto setPowerRegistrationState(bool);
    auto setSuspendResumeState(bool);
    auto setVirtualSpaceReady(bool);
    auto setupSPUReservedArea();
    auto start();
    auto stop();
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~AMDRadeonX4000_AMDSPUHWEngine();
};
