//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class IOAccelDisplayPipePostCSCGammaVID {
public: // (access info unavailable from symbols alone)
    auto getConfigurationID() const;
    auto getData() const;
    auto getFormat() const;
    auto getMaximumValue() const;
    auto getMinimumValue() const;
    auto getPlane() const;
    auto getSize() const;
    auto getType() const;
};
