//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class TSNCITimeSyncCapture {
public: // (access info unavailable from symbols alone)
    TSNCITimeSyncCapture();
    TSNCITimeSyncCapture(OSMetaClass const*);
    auto free();
    auto getMetaClass() const;
    auto init(OSDictionary*);
    auto init(OSDictionary*)::_os_log_fmt;
    auto macAddressForIPv4Address(unsigned int, unsigned int, unsigned int, unsigned char*, TSNCITimeSyncCaptureUserClient*);
    auto macAddressForIPv4Address(unsigned int, unsigned int, unsigned int, unsigned char*, TSNCITimeSyncCaptureUserClient*)::_os_log_fmt;
    auto macAddressForIPv6Address(unsigned char const*, unsigned char*, TSNCITimeSyncCaptureUserClient*);
    auto macAddressForIPv6Address(unsigned char const*, unsigned char*, TSNCITimeSyncCaptureUserClient*)::_os_log_fmt;
    auto myIPv4Address(unsigned int*, unsigned int*, TSNCITimeSyncCaptureUserClient*);
    auto myIPv4Address(unsigned int*, unsigned int*, TSNCITimeSyncCaptureUserClient*)::_os_log_fmt;
    auto myIPv4AddressForAddress(unsigned int, unsigned int*, unsigned int*, TSNCITimeSyncCaptureUserClient*);
    auto myIPv4AddressForAddress(unsigned int, unsigned int*, unsigned int*, TSNCITimeSyncCaptureUserClient*)::_os_log_fmt;
    auto myIPv6Address(unsigned char*, TSNCITimeSyncCaptureUserClient*);
    auto myIPv6Address(unsigned char*, TSNCITimeSyncCaptureUserClient*)::_os_log_fmt;
    auto myIPv6AddressForAddress(unsigned char const*, unsigned char*, TSNCITimeSyncCaptureUserClient*);
    auto myIPv6AddressForAddress(unsigned char const*, unsigned char*, TSNCITimeSyncCaptureUserClient*)::_os_log_fmt;
    auto nextAvailableTimeSyncPacket(TSNCITimeSyncCaptureUserClient*);
    auto nextAvailableTimeSyncPacket(TSNCITimeSyncCaptureUserClient*)::_os_log_fmt;
    auto setUserClient(TSNCITimeSyncCaptureUserClient*);
    auto start(IOService*);
    auto start(IOService*)::_os_log_fmt;
    auto stop(IOService*);
    auto timeSyncReceiveCallback(TSNPacket*);
    auto timeSyncTransmitCallback(TSNPacket*);
    auto transmitTimeSyncPacket(TSNPacket*, unsigned long long, TSNCITimeSyncCaptureUserClient*);
    auto transmitTimeSyncPacket(TSNPacket*, unsigned long long, TSNCITimeSyncCaptureUserClient*)::_os_log_fmt;
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~TSNCITimeSyncCapture();
};
