//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class TSNCIStreamCapture {
public: // (access info unavailable from symbols alone)
    TSNCIStreamCapture();
    TSNCIStreamCapture(OSMetaClass const*);
    auto free();
    auto getMetaClass() const;
    auto init(unsigned int, OSDictionary*);
    auto init(unsigned int, OSDictionary*)::_os_log_fmt;
    auto setUserClient(TSNCIStreamCaptureUserClient*);
    auto start(IOService*);
    auto start(IOService*)::_os_log_fmt;
    auto stop(IOService*);
    auto streamReceiveCallback(IOEthernetController::IOEthernetAVBPacket*);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~TSNCIStreamCapture();
};
