//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

// Global C++ functions

BTDebugService::gMetaClass;
BTDebugService::metaClass;
BTDebugService::superClass;
BTDebugService_ktv;
IOService::gMetaClass;
vtable for BTDebugService;
vtable for BTDebugService::MetaClass;
vtable for IOService;
