//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class MEICompletion {
public: // (access info unavailable from symbols alone)
    MEICompletion();
    MEICompletion(OSMetaClass const*);
    block();
    complete(MEIEventSource::MEI_CLIENT_EVENT_TYPE, MEIEventSource::MEI_CLIENT_EVENT_REASON, void*, unsigned int, unsigned int);
    completion(IOCommandGate*);
    completion(OSObject*, void (*)(OSObject*, MEIEventSource::MEI_CLIENT_EVENT_TYPE, MEIEventSource::MEI_CLIENT_EVENT_REASON, void*, unsigned int, unsigned int));
    getBlockError();
    getBuffer();
    getBufferSize();
    getBufferUsed();
    getCompletionType();
    getMetaClass() const;
    getReason();
    init(IOCommandGate*);
    init(OSObject*, void (*)(OSObject*, MEIEventSource::MEI_CLIENT_EVENT_TYPE, MEIEventSource::MEI_CLIENT_EVENT_REASON, void*, unsigned int, unsigned int));
    sleepAction(void*, void*, void*, void*);
    ~MEICompletion();
};
