//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleSSEUserClient {
public: // (access info unavailable from symbols alone)
    AppleSSEUserClient();
    AppleSSEUserClient(OSMetaClass const*);
    clientClose();
    extPerform(AppleSSE*, void*, IOExternalMethodArguments*);
    externalMethod(unsigned int, IOExternalMethodArguments*, IOExternalMethodDispatch*, OSObject*, void*);
    free();
    getMetaClass() const;
    initWithTask(task*, void*, unsigned int, OSDictionary*);
    start(IOService*);
    stop(IOService*);
    ~AppleSSEUserClient();
};
