//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class UDFAllocZone {
public: // (access info unavailable from symbols alone)
    UDFAllocZone(unsigned long, bool, int, int, int);
    auto AddChunkToFreeList(UDFChunkInfo const&);
    auto Alloc();
    auto DebugCheck();
    auto DebugCheckPointerRange(void*);
    auto Free(void*);
    auto GrowZone(unsigned long);
    auto GuaranteeSpace(unsigned long);
    ~UDFAllocZone();
};
