//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class UDFBitmap {
public: // (access info unavailable from symbols alone)
    AllocExtent(long long, unsigned int, unsigned int*, unsigned int*, int*, bool, unsigned int);
    DiskBlkNumToBitmapFileOffsets(unsigned int, unsigned int*, unsigned int*, unsigned int*);
    FindFirstBit(unsigned int, unsigned int, bool);
    FreeExtent(unsigned int, unsigned int, int*);
    GetBitmapGrowInfo(unsigned int, unsigned int*, unsigned int*);
    GetNumBlks();
    Grow(unsigned short, unsigned int, unsigned int);
    MarkBitmap(unsigned int, unsigned int, bool);
    MarkBitmapWord(unsigned int, bool, unsigned int, unsigned int*, UDFBlock*);
    ReleaseSysFileVnode();
    SearchBitmapRange(unsigned int, unsigned int, unsigned int, bool*, unsigned int*, unsigned int*, unsigned int*, unsigned int);
    Sync(int);
    UDFBitmap(UDFMount*, unsigned short, unsigned int, unsigned int, unsigned short);
    VerifyBitRange(unsigned int*, unsigned int*, unsigned int, bool, bool*, unsigned int*, UDFBlock*, unsigned int);
    VerifyBitmapWord(unsigned int, bool, unsigned int, unsigned int, unsigned int, bool*, unsigned int*, unsigned int*, UDFBlock*);
    ~UDFBitmap();
};
