//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class ACIPCNullDevice {
public: // (access info unavailable from symbols alone)
    ACIPCNullDevice();
    deviceAlive();
    deviceDead();
    deviceRunning();
    deviceWakeAsync();
    enterDead(acipcErrorType, void*, void*);
    enterLowPower();
    exitLowPower();
    getName() const;
    isChipInaccessible();
    isQuiesced();
    linkDown(acipcLinkState);
    linkUp(unsigned long long, unsigned long long, unsigned int, unsigned int);
    msiInterrupt(unsigned char);
    prepareForMMIOCoredump();
    quiesce();
    sendTimesyncMessage();
    setChipInaccessible(bool);
    setDARBasedTrap(bool);
    unquiesce();
    ~ACIPCNullDevice();
};
