//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class ACIPCChip {
public: // (access info unavailable from symbols alone)
    auto bar0Window0Mapping();
    auto bar0Window1Mapping();
    auto bar0Window4Mapping();
    auto bar0Window5Mapping();
    auto bar1Mapping();
    auto computeDoorbellOffset(unsigned int);
    auto computeDoorbellOffset(unsigned int) (.cold.1);
    auto disableMMIOCoredumpOnError(acipcErrorType);
    auto getBar0RegisterAddress(acipcPeripheralRegister, unsigned int);
    auto getBar0RegisterAddress(acipcPeripheralRegister, unsigned int) (.cold.1);
    auto getBar0RegisterOffset(acipcPeripheralRegister, unsigned int);
    auto getBar0RegisterOffset(unsigned int);
    auto getBar0RegisterOffset(unsigned int) (.cold.1);
    auto getBar0RegisterOffset(unsigned int) (.cold.2);
    auto getBar0WindowMapBaseAddr(unsigned int);
    auto getBar1RegisterOffset(acipcPeripheralRegister, unsigned int);
    auto getBar1RegisterOffset(acipcPeripheralRegister, unsigned int) (.cold.1);
    auto getChipRevisionID();
    auto getDartLimit();
    auto getNumDoorbell();
    auto getOTPInfo() const;
    auto hasMNIInterface();
    auto initBar0MapWindows(writeExtendedConfigSpaceCall const&);
    auto initBar0MapWindows(writeExtendedConfigSpaceCall const&) (.cold.1);
    auto isM2MResetOnSSResetDisabled();
    auto isSplitArchitecture();
    auto lpmPCIePortOffDisabled();
    auto mapBar0RegAddressToOffset(unsigned int);
    auto mapBar0RegAddressToOffset(unsigned int) (.cold.1);
    auto mapBar0RegAddressToOffset(unsigned int) (.cold.2);
    auto requireASPMWorkaround();
    auto requireIntMaskWorkaround();
    auto requireQuiesce();
    auto requireResetAllowCheck();
    ~ACIPCChip();
};
