//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class ACIPCChip4388 {
public: // (access info unavailable from symbols alone)
    disableMMIOCoredumpOnError(acipcErrorType);
    getBar1RegisterOffset(acipcPeripheralRegister, unsigned int);
    getBar1RegisterOffset(acipcPeripheralRegister, unsigned int) (.cold.1);
    getName() const;
    getNumDoorbell();
    initWithRevisionID(unsigned char, writeExtendedConfigSpaceCall const&);
    withRevisionID(unsigned char, writeExtendedConfigSpaceCall const&);
    ~ACIPCChip4388();
};
