//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleConvergedIPCMemoryCommandPool {
public: // (access info unavailable from symbols alone)
    AppleConvergedIPCMemoryCommandPool();
    AppleConvergedIPCMemoryCommandPool(OSMetaClass const*);
    allocateReturnCommand();
    free();
    gatedReturnCommand(IOCommand*);
    getCmdSize() const;
    getMetaClass() const;
    getName() const;
    initWithInfo(IOWorkLoop*, unsigned long long, AppleConvergedIPCMemoryPolicyInfo*);
    withInfo(IOWorkLoop*, unsigned long long, AppleConvergedIPCMemoryPolicyInfo*);
    ~AppleConvergedIPCMemoryCommandPool();
};
