//
//     Generated by class-dump 3.5 (64 bit) — C++ symbol-derived view.
//

class AppleOLYHALPlatformFunctionMacAMFM {
public: // (access info unavailable from symbols alone)
    AppleOLYHALPlatformFunctionMacAMFM();
    AppleOLYHALPlatformFunctionMacAMFM(OSMetaClass const*);
    auto copyRWCV(OSData*&);
    auto free();
    auto getACPIPropVal(OSString*, OSObject*&);
    auto getMetaClass() const;
    auto init(IOService*, CCLogStream*);
    auto isSystemWokenByWiFi(char*, char const*, unsigned long);
    auto setLowPowerDetected(bool);
    auto setPowerEnable(bool);
    auto smcNotifierHandler(void*, IOService*, IONotifier*);
    void * operator new(unsigned long);
    void operator delete(void*, unsigned long);
    ~AppleOLYHALPlatformFunctionMacAMFM();
};
