//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSButtonCell.h>

@class IFDTarget, NSAttributedString, NSImage;

@interface IATargetDomainCell : NSButtonCell
{
    NSAttributedString *_title[3];
    NSImage *_selectionImage;
    NSImage *_selectionImageDeactive;
    int _domain;
    IFDTarget *_referencedTarget;
    _Bool _enabledInDistribution;
}

- (id)target;
- (int)domain;
- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)setupToolTip;
- (void)setEnabled:(_Bool)arg1;
- (void)setEnabledInDistribution:(_Bool)arg1;
- (_Bool)enabledInDistribution;
- (void)_updateToolTip;
- (void)dealloc;
- (id)init;
- (void)setDomainName:(id)arg1 image:(id)arg2 domain:(int)arg3 target:(id)arg4;

@end

